### ISSUE TITLE
Replicacount > 1

### ISSUE THREAD

**Issue by kwaazaar** [Azure/application-gateway-kubernetes-ingress#1000]
Replicas is set to 1 for the AGIC deployment. This is dangerous in case of node outage or other catastrophies.

Please set it to at least 2 and make it configurable in the helm chart values file.

**Comment by akshaysngupta** [comment]
@kwaazaar this will be addressed after we add leader election to AGIC.

**Comment by akshaysngupta** [comment]
Duplicate https://github.com/Azure/application-gateway-kubernetes-ingress/issues/1043. Closing this one.
