### ISSUE TITLE
More than 100 Listener rules

### ISSUE THREAD

**Issue by pradeepbohra** [Azure/application-gateway-kubernetes-ingress#1002]
Hi,
App gw has limits as described here 

https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#application-gateway-limits

When I deploy a ingress e.g. - 

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-wildcard-host
  annotations:
       kubernetes.io/ingress.class: azure/application-gateway
       appgw.ingress.kubernetes.io/appgw-ssl-certificate: "abc-cert"
       appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: "mydomain.com"
    http:
      paths:
      - path: "/"
        backend:
          serviceName: azure-vote-front
          servicePort: 80

It is creating one Listener and one backend pool.
So I need clarification on the below and if my assumptions are false please provide details what I am missing. 

1. Does it means one app gw can only have 100 k8s service support or Am I missing something ?

2. What if the number of services we need exceeds 100 per cluster. What is the solution in that case ?

I understand one way to solve it is go for another app gw but that means we need to maintain multiple app gw as the number of services increases on the cluster.

**Comment by 3quanfeng** [comment]
Hi @pradeepbohra , yes, you can only have 100 active listeners per appgw, however, you could use wildcard hostname which allows you to config up to 5 hostname per listener
https://docs.microsoft.com/en-us/azure/application-gateway/multiple-site-overview

**Comment by pradeepbohra** [comment]
Thank you. Closing the request as the query is answered.
