### ISSUE TITLE
Question 1.18.8 Supported ?

### ISSUE THREAD

**Issue by niteenkole** [Azure/application-gateway-kubernetes-ingress#1005]
Question

we planning to upgrade AKS from 1.17.9 to 1.18.8

we have ingress-azure-1.2.0  running on our 1.17 cluster.Is this supported/tested on 1.18? anything we need to do before we upgrade?

**To Reproduce**

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
* Output of `kubectl logs <ingress controller>. 
* Any Azure support tickets associated with this issue.

**Comment by davejhahn** [comment]
@niteenkole I updated my cluster in Azure to 1.18.8 and didn't run into any issues.

**Comment by niteenkole** [comment]
Awesome thanks.

**Comment by akshaysngupta** [comment]
thanks @davejhahn
