### ISSUE TITLE
Support URL Re-Write

### ISSUE THREAD

**Issue by burn2delete** [Azure/application-gateway-kubernetes-ingress#1019]
Url rewriting is now possible with App Gateway, please implement!

https://docs.microsoft.com/en-us/azure/application-gateway/rewrite-url-portal

**Comment by pbalexlear** [comment]
pretty sure this is possible by using the backend path prefix 

https://azure.github.io/application-gateway-kubernetes-ingress/annotations/#backend-path-prefix

**Comment by praveenpattisapu** [comment]
Hi,I am trying to implement this solution ,my requirement is to configure http response headers like below, I tried via Azure portal and it works if I create a rewrite rule set but can you suggest what annotations to use to rewrite the headers responses?

header_name = "HTTP-Strict-Transport-Security"
        header_value = "max-age=31536000 includeSubdomains always"

header_name = "X-Xss-Protection"
        header_value = "1; mode=block always;"

**Comment by flyboarder** [comment]
backend path prefix is not the same as url rewrites
