### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by vishwa-vijay-by** [Azure/application-gateway-kubernetes-ingress#1020]
**Describe the bug**
I have insatalled version 1.2.0. and using  service principle configuration. Configuration  seems fine. But  whille hitting  service i am getting 502 error. I  checked all setting for backned pool and that is correct. Also i allowed port 65200-65535 in NSG. But still getting 502 error. Nothing coming in log

**To Reproduce**

**Ingress Controller details**
Name:         ingress-azure-5c7c8c6c4c-m4j9f
Namespace:    xxx
Priority:     0
Node:         aks-ldsdev01-xxx
Start Time:   Sat, 10 Oct 2020 19:22:58 +0530
Labels:       app=ingress-azure
              pod-template-hash=5c7c8c6c4c
              release=ingress-azure
Annotations:  checksum/config: 7a10ef4c9ff896254e2011d9333b3f42e57e54c59bc966587019554552efa3db
              prometheus.io/port: 8123
              prometheus.io/scrape: true
Status:       Running
IP:           172.17.133.26
IPs:
  IP:           172.17.133.26
Controlled By:  ReplicaSet/ingress-azure-5c7c8c6c4c
Containers:
  ingress-azure:
    Container ID:   docker://fa31a5c89abe7582bf529ae0a297882a87bf146985f7607ce578da28badeb239
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.2.0
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:de458f962eab0cd2de19d23dfeb9a0e4bc2565a38f8c45cc98a74f3cda8b940c
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Sat, 10 Oct 2020 19:23:00 +0530
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_CLOUD_PROVIDER_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:                  ingress-azure-5c7c8c6c4c-m4j9f (v1:metadata.name)
      AGIC_POD_NAMESPACE:             xxx (v1:metadata.namespace)
      AZURE_AUTH_LOCATION:            /etc/Azure/Networking-AppGW/auth/armAuth.json
    Mounts:
      /etc/Azure/Networking-AppGW/auth from networking-appgw-k8s-azure-service-principal-mount (ro)
      /etc/appgw/azure.json from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-azure-token-qs869 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  networking-appgw-k8s-azure-service-principal-mount:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  networking-appgw-k8s-azure-service-principal
    Optional:    false
  ingress-azure-token-qs869:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-azure-token-qs869
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
 
I1010 14:09:14.654588       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I1010 14:09:44.962724       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I1010 14:09:44.962755       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I1010 14:09:44.963436       1 mutate_app_gateway.go:204] END AppGateway deployment
I1010 14:09:44.963456       1 controller.go:151] Completed last event loop run in: 30.371758164s
I1010 14:09:46.003186       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I1010 14:11:16.351382       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I1010 14:11:16.351424       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I1010 14:11:16.351933       1 mutate_app_gateway.go:204] END AppGateway deployment
I1010 14:11:16.351951       1 controller.go:151] Completed last event loop run in: 1m30.388295649s
I1010 14:11:17.397094       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I1010 14:11:17.397118       1 controller.go:151] Completed last event loop run in: 45.133649ms
I1010 14:11:20.001286       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I1010 14:11:20.001310       1 controller.go:151] Completed last event loop run in: 38.352196ms
I1010 14:16:13.606571       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I1010 14:16:13.606663       1 controller.go:151] Completed last event loop run in: 104.875966ms
I1010 14:16:31.203677       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I1010 14:16:31.203704       1 controller.go:151] Completed last event loop run in: 46.53914ms
I1010 14:19:40.012338       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I1010 14:19:40.012362       1 controller.go:151] Completed last event loop run in: 71.644411ms
I1010 14:32:18.579670       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I1010 14:32:18.579694       1 controller.go:151] Completed last event loop run in: 105.063721ms
I1010 14:33:12.499342       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I1010 14:33:12.499383       1 controller.go:151] Completed last event loop run in: 49.323538ms
I1010 14:33:27.527305       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I1010 14:33:27.527332       1 controller.go:151] Completed last event loop run in: 37.224355ms
I1010 14:33:28.571593       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I1010 14:33:59.094815       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I1010 14:33:59.094838       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I1010 14:33:59.095567       1 mutate_app_gateway.go:204] END AppGateway deployment
I1010 14:33:59.095588       1 controller.go:151] Completed last event loop run in: 30.567912912s
I1010 14:34:00.142962       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I1010 14:34:30.468662       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I1010 14:34:30.468687       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I1010 14:34:30.469461       1 mutate_app_gateway.go:204] END AppGateway deployment
I1010 14:34:30.469481       1 controller.go:151] Completed last event loop run in: 30.373744859s
I1010 14:36:04.779115       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I1010 14:36:04.779142       1 controller.go:151] Completed last event loop run in: 114.724783ms
I1010 14:36:05.826791       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I1010 14:36:36.324838       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I1010 14:36:36.324862       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I1010 14:36:36.325777       1 mutate_app_gateway.go:204] END AppGateway deployment
I1010 14:36:36.325803       1 controller.go:151] Completed last event loop run in: 30.546447514s
I1010 14:36:37.368559       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I1010 14:37:07.724198       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I1010 14:37:07.724221       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I1010 14:37:07.725011       1 mutate_app_gateway.go:204] END AppGateway deployment
I1010 14:37:07.725034       1 controller.go:151] Completed last event loop run in: 30.399041217s
I1010 14:39:09.877167       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I1010 14:39:40.202529       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I1010 14:39:40.202570       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I1010 14:39:40.203165       1 mutate_app_gateway.go:204] END AppGateway deployment
I1010 14:39:40.203234       1 controller.go:151] Completed last event loop run in: 30.402245469s
I1010 14:39:41.248824       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I1010 14:39:41.248865       1 controller.go:151] Completed last event loop run in: 45.395409ms
I1010 14:40:24.665118       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I1010 14:40:24.665150       1 controller.go:151] Completed last event loop run in: 38.654563ms
I1010 14:42:08.499565       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I1010 14:42:08.499605       1 controller.go:151] Completed last event loop run in: 111.816761ms
I1010 14:42:09.858996       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I1010 14:42:40.219463       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I1010 14:42:40.219510       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I1010 14:42:40.220371       1 mutate_app_gateway.go:204] END AppGateway deployment
I1010 14:42:40.220393       1 controller.go:151] Completed last event loop run in: 30.404010066s
I1010 14:42:41.272072       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I1010 14:43:11.623860       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I1010 14:43:11.623906       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I1010 14:43:11.624718       1 mutate_app_gateway.go:204] END AppGateway deployment
I1010 14:43:11.624738       1 controller.go:151] Completed last event loop run in: 30.404045321s
I1010 14:43:12.671748       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I1010 14:43:12.671774       1 controller.go:151] Completed last event loop run in: 46.846519ms
* Any Azure support tickets associated with this issue.

**Comment by akshaysngupta** [comment]
@vishwa-vijay-by Please check AppGW's backend health status. You can use portal or CLI to view the backend health.

You would usually see a 502 when all of your pods for a ingress rule are reported as unhealthy.
1. They could either be unreachable due to a network configuration issue.
2. Health probes are not configured correctly. For example: Incorrect Port or path in the readiness probe or liveness probe.
3. they are returning an unhealthy status code (> 399) to the health probe.

**Comment by akshaysngupta** [comment]
@vishwa-vijay-by any updates?

**Comment by balakrishna222111** [comment]
@akshaysngupta  
Even am also facing same problem from past 1 week . Could u please help me 
https://github.com/Azure/application-gateway-kubernetes-ingress/issues/1196
