### ISSUE TITLE
setting custom health probe via portal gets reset automatically after some time

### ISSUE THREAD

**Issue by dipakyadav** [Azure/application-gateway-kubernetes-ingress#1024]
**Describe the bug**
I have deployed Elasticsearch in AKS using the link https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-quickstart.html,
and exposed (public ip / domain) using ingress app gateway.
Using ingress health probe is automatically created for elasticsearch, but since elasticsearch is by default protected with basic auth it returns 401 status code, which causes backend health to fail.
To resolve this, I tried manually editing the health probe from portal and set it as `200-399,401`, which resolves the issue for sometime (it gets reset to `200-399` automatically after some time.)

**Comment by vishal8k** [comment]
@dipakyadav  By default AGIC assumes full control of the appgw. Hence any manual changes done by you in the application gateway shall be revoked by AGIC whenever any of these actions happen (New Pod launch, New ingress rule addition, Removal of ingress rules etc..). You have two options here, One is defining a ProhibitedTarget (you have to launch AGIC in shared mode for this). Another is editing the health check of the elasticsearch deployment (Editing the existing liveness/readiness probe).

Reference link for Azure Ingress Prohibited target
https://github.com/Azure/application-gateway-kubernetes-ingress/tree/master/crds

This issue shall be closed.

**Comment by dipakyadav** [comment]
Thanks @vishal8k , will check
