### ISSUE TITLE
How to support multiple AppGws with a single AKS cluster and single AGIC?

### ISSUE THREAD

**Issue by michaelsiuda** [Azure/application-gateway-kubernetes-ingress#1025]
I'm in the process of transitioning our application from ASE to AKS on Azure. In the current setup, we have two application gateways with mirrored configuration, running in active-active mode and we load balance between them at DNS. We've found that this redundant setup has helped to keep our application available numerous times over the last few months and therefore it is required that we keep this once we transition to AKS.

I've been trying to find out whether a setup with a single ingress controller and backend pool could work with multiple application gateways. From what I can see, this is not currently possible. https://github.com/Azure/application-gateway-kubernetes-ingress/issues/732 and https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-overview#helm-deployed-agic-single-aks-cluster suggest that if I wanted to run with multiple app gateways, that would require setting up a dedicated AGIC for each of them and furthermore, each AGIC would only be able to watch resources in a specified namespace. Therefore, the setup would have to look like this:
AppGw1 --> AGIC1 --> Namespace1 --> [App1-1, App1-2, ...]
AppGw2 --> AGIC2 --> Namespace2 --> [App2-1, App2-2, ...]

As a result, in case of a failure of one of the app gateways we also lose all the associated backend resources.

What would work better, would be either:
AppGw1 --> AGIC1 --> [App1-1, App1-2, App2-1, App2-2, ...]
AppGw2 --> AGIC2 --> [App1-1, App1-2, App2-1, App2-2, ...]

or even better:
AppGw1 --> AGIC --> [App1-1, App1-2, App2-1, App2-2, ...]
AppGw2 --> AGIC --> [App1-1, App1-2, App2-1, App2-2, ...]

in which the entire backend pool is shared across app gateways.

Can you please clarify whether such setup is currently possible or not? If not ready yet, do you know when it may be coming - https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-overview#helm-deployed-agic-single-aks-cluster suggests that this feature is in the backlog.

**Comment by 3quanfeng** [comment]
Hi @michaelsiuda , currently, one AGIC can be mapped to only one AppGw.
However, there is a feature(which is Beta, feel free to report any defect) to support to run different AGICs for resources within same namespace, check the [feature ](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/proposals/multiple-gateways-single-cluster.md)out. 
The feature allows you to configure ingress to be used by a specific ingress controller. which I guess it's the 2nd use case you pointed out.

**Comment by michaelsiuda** [comment]
Hi @3quanfeng,

Thank you for your reply. Apologies, I think I didn't clearly describe the use case I have in mind and the feature you've linked doesn't meet my requirements.

What I'm thinking about is more like mirroring of configuration by one AGIC instance across multiple application gateways, rather running multiple AGIC instances, each of them with their own set of backend pods.

The main reason behind it is handling application gateway failures:
- with mirrored configuration, backend pool is shared across app gateways, and therefore failure of an app gateway does not affect the capability of the backend to handle user load
- with separate AGIC instances, the backend pool is split between gateways and therefore app gateway's failure effectively removes x% of backend capability to handle user load

I hope I've made the use case clearer. Please let me know your thoughts.

**Comment by isaacdan** [comment]
If i create additional agic in the different name space it throws an error 
Error: rendered manifests contain a resource that already exists. Unable to continue with install: IngressClass "azure-application-gateway" in namespace "" exists and cannot be imported into the current release.

**Comment by thomasmu7** [comment]
Hello @isaacdan, you need to override the default values using the following:
```
kubernetes:
    ingressClassResource:
        name: application-gateway-foobar
        controllerValue: "azure/application-gateway-foobar"
```
Took me a while to figure this out until I downloaded the chart using `helm pull ingress-agic/ingress-azure` and browsed the `values.yaml` file.
Note: you may want to set a value for `kubernetes.watchNamespace` for both AGICs.
