### ISSUE TITLE
is application-gateway-kubernetes-ingress support regex annoation like nginx

### ISSUE THREAD

**Issue by vishwa-vijay-by** [Azure/application-gateway-kubernetes-ingress#1028]
**Is your feature request related to a problem? Please describe.**
In path based routing i want to send traffic based on regex. Like if any thing not matches, this send request to specific service.
**Describe the solution you'd like**
nginx.ingress.kubernetes.io/use-regex: "true"
same for AGIC 
appgw.ingress.kubernetes.io/use-regex: "true"

**Comment by vishwa-vijay-by** [comment]
Let I explain my requirent in details. Below are my ingress configuration.
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: myldstest
    appgw.ingress.kubernetes.io/use-regex: "true" NOT SURE THIS WILL USE FOR appgw.ingress.kubernetes.io CLASS
    kubernetes.io/ingress.class: azure/application-gateway
    meta.helm.sh/release-name: file
    meta.helm.sh/release-namespace: mytest
  creationTimestamp: "2020-10-21T15:55:53Z"
  generation: 24
  labels:
    app.kubernetes.io/instance: file-management
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: file
    app.kubernetes.io/version: 65-SNAPSHOT
    helm.sh/chart: file-management-65-SNAPSHOT
  name: file-management
  namespace: xxxxx
  resourceVersion: "1731849"
  selfLink: /apis/extensions/v1beta1/namespaces/xxxx/ingresses/file
  uid: aeebffd2-c2ac-4fd4-a6cd-dc836c80ee00
spec:
  rules:
  - host: xxxx
    http:
      paths:
      - backend:
          serviceName: file
          servicePort: 3002
        path: /files
      - backend:
          serviceName: file
          servicePort: 3002
        path: /files/
      - backend:
          serviceName: file
          servicePort: 3002
        path: /files/*
      - backend:
          serviceName: file
          servicePort: 3002
        path: /metadata
      - backend:
          serviceName: file
          servicePort: 3002
        path: /metadata/
      - backend:
          serviceName: file
          servicePort: 3002
        path: /metadata/*
      - backend:
          serviceName: file
          servicePort: 3002
        path: /search
      - backend:
          serviceName: file
          servicePort: 3002
        path: /search/
      - backend:
          serviceName: file
          servicePort: 3002
        path: /search/*
      - backend:
          serviceName: file
          servicePort: 3002
        path: /share/
      - backend:
          serviceName: file
          servicePort: 3002
        path: /share/*
      - backend:
          serviceName: message-tracker
          servicePort: 3004
        path: /show
      - backend:
          serviceName: message-tracker
          servicePort: 3004
        path: /show/
      - backend:
          serviceName: message-tracker
          servicePort: 3004
        path: /show/*
      - backend:
          serviceName: file
          servicePort: 3002
        path: /[^((?!file|show)).*]  **I WANT TO WRITE HERE iFANY OF ABOVE PATH DON"T MATCH FORWARD REQUEST TO FILE SERVICE, I MEAN DEFAULT. I TRIED KIND OF THIS REGEX ^((?!file|show)).***
status:
  loadBalancer:
    ingress:
    - ip: xxxx

PLEASE DO HELP ME. THIS IS KIND OF BLOCKER FOR US.

**Comment by akshaysngupta** [comment]
@vishwa-vijay-by Currently, AppGW only support `*` at the end of the path.

**Comment by bongi23** [comment]
+1
