### ISSUE TITLE
Support AzureIngressAllowdTargets to handle several agics managing a shared agw

### ISSUE THREAD

**Issue by JorTurFer** [Azure/application-gateway-kubernetes-ingress#1029]
**Is your feature request related to a problem? Please describe.**
I deployed several cluster during the last months and usualy I use agic with shared agw. We found problems because the clusters handles prohibited target but the humans from one team may buy new domain and add to the agw and they must notify to the another teams that a new domain have to be added to the prohibited target list.

**Describe the solution you'd like**
It will be great if the cluster use a method based in allowed target because only the cluster have to know what domains manages and is not necesary that the other cluster know it.

I have some free time and I think that I can add support to allowed targets if this feature is usefull. I am no sure if this feature should replace the prohibited target in the future but I think that both could work together.

What do you feel about this?

**Comment by andrejbrummelhuis** [comment]
How is this not implemented yet? Impossible to work with multiple clusters and teams without this..

**Comment by JorTurFer** [comment]
I will start this feature ASAP
