### ISSUE TITLE
Question: When will the next version be released ? 

### ISSUE THREAD

**Issue by JorTurFer** [Azure/application-gateway-kubernetes-ingress#1030]
I am looking the git history and I found that the latest release (1.2.1) only contains 1 commit more than the previous version (c6389bc7198e85eb105d293d4a4b82f435451fc9).
![image](https://user-images.githubusercontent.com/36899226/96926233-98324700-14b5-11eb-88ca-e349049349ec.png)

Since the version 1.2.0 there are more changes that would be great be able to use.
I don't know if this is intentionaly or an error. For example, the helm chart is still using the image tag 1.2.0

**Comment by akshaysngupta** [comment]
@JorTurFer Please try the latest release `1.3.0-rc1`. Here is the [changelog](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/CHANGELOG/CHANGELOG-1.3.md).
