### ISSUE TITLE
Configure health probe status code from YAML file

### ISSUE THREAD

**Issue by motim6026** [Azure/application-gateway-kubernetes-ingress#1032]
Please add the ability when using `kubernetes.io/ingress.class: azure/application-gateway` to configure the health probe status code match directly from the YAML.

**Comment by akshaysngupta** [comment]
Code change to support this has been merged.
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/annotations.md#health-probe-status-codes

This change has been released officially.

**Comment by motim6026** [comment]
Thank you for the update.
