### ISSUE TITLE
Update Health probes matching conditions from Yaml file for AGIC

### ISSUE THREAD

**Issue by trivedirince3** [Azure/application-gateway-kubernetes-ingress#1034]
I have deployed one microservice POD in AKS and using AGIC (Application Gateway Ingress Controller), default health probe matching conditions are setups to 200 - 399 and on basic auth code is 401 and show unhealthy and the page does not work.

is it possible to set up matching conditions with some annotations or some other way that we do not need every time to adjust that by hand.

**Comment by Vishal2696** [comment]
You can setup your custom readiness probes for the pod and the same will be reflected in appgw healthchecks. IF you have your readiness probes set as 401 then same will be replicated in appgw.

**Comment by akshaysngupta** [comment]
@trivedirince3 This has been merged although not yet released officially. You can try this using the `nightly` build.
here is the [documentation](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/annotations.md#health-probe-status-codes).

**Comment by akshaysngupta** [comment]
Please check the new annotations released as part of `1.4.0-rc1`.
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/annotations.md#list-of-supported-annotations
