### ISSUE TITLE
No dates in logs!

### ISSUE THREAD

**Issue by howardjones** [Azure/application-gateway-kubernetes-ingress#1036]
**Describe the bug**

When faultfinding the ingress controller, it's impossible to tell what day an error started ocurring.

**To Reproduce**

    kubectl logs ingress-azure-77cf644d76

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
* Output of `kubectl logs <ingress controller>. 
* Any Azure support tickets associated with this issue.

    E1023 06:23:56.786943       1 worker.go:62] Error processing event.unable to get specified AppGateway (CTRL001)
               ^^^^^^^^^^^^^^^^^ which day?

I am using 1.2.0rc1, but I don't see any mention of changes in the changelog relating to logs.

**Comment by aelmanaa** [comment]
@howardjones  what about if you run your command with "--timestamps". for instance:

`kubectl logs ingress-azure-77cf644d76 --timestamps`

**Comment by howardjones** [comment]
Haha. Thanks! I learned something new today.
