### ISSUE TITLE
AKS : AGIC addon vs helm. which mode will be supported in GA on the long term

### ISSUE THREAD

**Issue by aelmanaa** [Azure/application-gateway-kubernetes-ingress#1038]
Hello,

I've been testing both mode of deployments (addon & helm chart). When reading AKS documentation, it seems like addon mode is still on preview.
what is the roadmap of AGIC : Is it to support both mode of deployment (once addon is GA) ? OR are you going to support only addon deployment ?

I'm asking this as we are currently using Nginx+ (which includes a WAF and is supported by F5) to expose our services. However, we would like to migrate to Azure app gateway and hence we would like to choose a deployment method which will be covered by MS support

thanks

**Comment by sabareeshkkanan** [comment]
Any update on this ? Is there a timeline when AGIC Add on will generally available ?

**Comment by nickvanwegen** [comment]
Any update on this?
A timeline would be much appreciated.

**Comment by sbkg0002** [comment]
We are also wondering.
