### ISSUE TITLE
How to enable multiple namespaces on linux AKS with AGIC without using helm chart ?

### ISSUE THREAD

**Issue by ronak319** [Azure/application-gateway-kubernetes-ingress#1047]
Problem 
I have a single kubernetes cluster with 2 node pools and 2 namespaces (A,B) and 2 applications(C,D). I want to use a single Azure app gateway for both of the application's traffic. How can I configure on existing AGIC for  routing traffic to services running on multiple namespaces ?

**Comment by santiagobando** [comment]
This is exactly my current requirement. Is it possible to accomplish the stated question?
