### ISSUE TITLE
Affinities, taints and liveness/readiness configuration with Helm

### ISSUE THREAD

**Issue by arodriguezdlc** [Azure/application-gateway-kubernetes-ingress#1055]
We would like to configure some deployment attributes via values on Helm:
- Affinities
- Node taints
- Liveness/Readiness timeouts

Currently, this is not possible because values are hardcoded. In the case of Liveness/Readiness timeouts, it could be enough if you increase these values because the defaults are so demanding for AKS. For example, we think values used in this other Azure project (https://github.com/Azure/aad-pod-identity/blob/master/charts/aad-pod-identity/templates/mic-deployment.yaml) are better.

**Comment by JorTurFer** [comment]
Hi @arodriguezdlc ,
I am in point with you about the support for Affinities and Node taints, but I disagree with you about the probes. The interval that you are proposing is more exigent for the cluster (5 seconds instead 10/20). 
In my personal opinion, the development team of a software is whose has to determine things like the interval of the probes.
In the afternoon I am going to create a PR that supports the configuration of Affinities and Node taints during the chart installation.
Do @3quanfeng and @akshaysngupta think that the probes configuration during the chart deployment should be supported also?
