### ISSUE TITLE
download limitation over AppGW, when backend is AKS 

### ISSUE THREAD

**Issue by ammarqq** [Azure/application-gateway-kubernetes-ingress#1057]
not able to download any file which is more than 1GB. This seems with scenario when AppGW Ingress controller is used

Not be able to download more than 1 GB by the application that's behind AGIC

![image](https://user-images.githubusercontent.com/18486257/98910160-7c75fb80-24cb-11eb-8a57-509b5ecfadf0.png)

there is a way to download a file with 2GB from the backend? or there is a limitation using AGIC.

**Comment by akshaysngupta** [comment]
Please open a support ticket on AppGW through portal.

**Comment by akshaysngupta** [comment]
Closing issue from GitHub.
