### ISSUE TITLE
Rewrite rule set and association to request routing rule

### ISSUE THREAD

**Issue by praveenpattisapu** [Azure/application-gateway-kubernetes-ingress#1058]
**Describe the bug**
We have a requirement to rewrite HTTP response headers like Strict transport security, CSP etc to some defined values.
We are using terraform to build infrastructure but not for the below sections in Application gateway as there are managed by AGIC.
      backend_address_pool, 
      backend_http_settings,
      frontend_port,
      http_listener,
      probe,
      redirect_configuration,
      request_routing_rule,
      ssl_certificate,
      url_path_map,

I am able to create rewrite sets/rewrite rules using Terraform/Powershell but I am not able to associate these rules to any request routing rules as that is being managed by AGIC.
Even I create the rules manually and associate, AGIC will remove those changes as that is in full charge of App Gateway

How to resolve this issue using AGIC?
Can we create rules using AGIC?
Can we associate rewrite sets to routing rules using AGIC?

**To Reproduce**
Yes I can easily reproduce

**Ingress Controller details**
kubectl describe pod ingress-azure-7d895b7bdf-cnghm -n appgw-ingress
Name:         ingress-azure-7d895b7bdf-cnghm
Namespace:    appgw-ingress
Priority:     0
Node:         aks-default-29987748-vmss000007/10.186.83.175
Start Time:   Thu, 12 Nov 2020 03:01:30 +0000
Labels:       aadpodidbinding=ingress-azure
              app=ingress-azure
              linkerd.io/control-plane-ns=linkerd
              linkerd.io/proxy-deployment=ingress-azure
              linkerd.io/workload-ns=appgw-ingress
              pod-template-hash=7d895b7bdf
              release=ingress-azure
Annotations:  checksum/config: 7876bf2f7d1e2df021a144f177369217ff32cf2c6934563078f7b77136901666
              kubectl.kubernetes.io/restartedAt: 2020-11-12T03:01:29Z
              linkerd.io/created-by: linkerd/proxy-injector stable-2.9.0
              linkerd.io/identity-mode: default
              linkerd.io/proxy-version: stable-2.9.0
              prometheus.io/port: 8123
              prometheus.io/scrape: true
Status:       Running
IP:           10.186.83.197
IPs:
  IP:           10.186.83.197
Controlled By:  ReplicaSet/ingress-azure-7d895b7bdf
Init Containers:
  linkerd-init:
    Container ID:  docker://d777a349e9102ddddb25316c2c42d098375a1654acb205a183041ea19a7b0144
    Image:         ghcr.io/linkerd/proxy-init:v1.3.6
    Image ID:      docker-pullable://ghcr.io/linkerd/proxy-init@sha256:591d4f578a8c4431fc6343c8f2703338888865440f02f4cb44862a87c5557859
    Port:          <none>
    Host Port:     <none>
    Args:
      --incoming-proxy-port
      4143
      --outgoing-proxy-port
      4140
      --proxy-uid
      2102
      --inbound-ports-to-ignore
      4190,4191,25,443,587,3306,11211
      --outbound-ports-to-ignore
      25,443,587,3306,11211
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 12 Nov 2020 03:01:32 +0000
      Finished:     Thu, 12 Nov 2020 03:01:32 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:        10m
      memory:     10Mi
    Environment:  <none>
    Mounts:
      /run from linkerd-proxy-init-xtables-lock (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-azure-token-jvmr6 (ro)
Containers:
  ingress-azure:
    Container ID:   docker://4833c33e9ccb9abf2ccb2cb0bdfd764b517725d246e76c4e110fc623b8137136
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.2.0
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:de458f962eab0cd2de19d23dfeb9a0e4bc2565a38f8c45cc98a74f3cda8b940c
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 12 Nov 2020 03:01:46 +0000
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_CLOUD_PROVIDER_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:                  ingress-azure-7d895b7bdf-cnghm (v1:metadata.name)
      AGIC_POD_NAMESPACE:             appgw-ingress (v1:metadata.namespace)
    Mounts:
      /etc/appgw/azure.json from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-azure-token-jvmr6 (ro)
  linkerd-proxy:
    Container ID:   docker://eda4dbc044aaa8ebfc6259c5a44f19cd477a2de4d370e7ca941073c7558efbb7
    Image:          ghcr.io/linkerd/proxy:stable-2.9.0
    Image ID:       docker-pullable://ghcr.io/linkerd/proxy@sha256:a7166c06fc4a4bf3ef88110e666b35de228df62f23304351ba97a6d81d611f99
    Ports:          4143/TCP, 4191/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Thu, 12 Nov 2020 03:01:47 +0000
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:4191/live delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:4191/ready delay=2s timeout=1s period=10s #success=1 #failure=3
    Environment:
      LINKERD2_PROXY_LOG:                           warn,linkerd=info
      LINKERD2_PROXY_LOG_FORMAT:                    plain
      LINKERD2_PROXY_DESTINATION_SVC_ADDR:          linkerd-dst-headless.linkerd.svc.cluster.local:8086
      LINKERD2_PROXY_DESTINATION_PROFILE_NETWORKS:  10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16
      LINKERD2_PROXY_INBOUND_CONNECT_TIMEOUT:       100ms
      LINKERD2_PROXY_OUTBOUND_CONNECT_TIMEOUT:      1000ms
      LINKERD2_PROXY_CONTROL_LISTEN_ADDR:           0.0.0.0:4190
      LINKERD2_PROXY_ADMIN_LISTEN_ADDR:             0.0.0.0:4191
      LINKERD2_PROXY_OUTBOUND_LISTEN_ADDR:          127.0.0.1:4140
      LINKERD2_PROXY_INBOUND_LISTEN_ADDR:           0.0.0.0:4143
      LINKERD2_PROXY_DESTINATION_PROFILE_SUFFIXES:  svc.cluster.local.
      LINKERD2_PROXY_INBOUND_ACCEPT_KEEPALIVE:      10000ms
      LINKERD2_PROXY_OUTBOUND_CONNECT_KEEPALIVE:    10000ms
      _pod_ns:                                      appgw-ingress (v1:metadata.namespace)
      _pod_nodeName:                                 (v1:spec.nodeName)
      LINKERD2_PROXY_DESTINATION_CONTEXT:           {"ns":"$(_pod_ns)", "nodeName":"$(_pod_nodeName)"}

      LINKERD2_PROXY_IDENTITY_DIR:                  /var/run/linkerd/identity/end-entity
      LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS:        -----BEGIN CERTIFICATE-----
                                                    MIIBzDCCAXKgAwIBAgIRANYoR23CyEkWhQCTvjO8UNEwCgYIKoZIzj0EAwIwOzEQ
                                                    MA4GA1UEChMHbGlua2VyZDEnMCUGA1UEAxMeaWRlbnRpdHkubGlua2VyZC5jbHVz
                                                    dGVyLmxvY2FsMB4XDTIwMDcwMjE0MjQ1M1oXDTIzMDcwMjE0MjQ1M1owOzEQMA4G
                                                    A1UEChMHbGlua2VyZDEnMCUGA1UEAxMeaWRlbnRpdHkubGlua2VyZC5jbHVzdGVy
                                                    LmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAES7Bf6wdyzRhgLaoNDqr/
                                                    LCSn7t8gcmSq5pPYAkzLwh3AvG6zqe3Q6MeG+lKQ71te6313Jgenw04qRQDXc0ee
                                                    EKNXMFUwDgYDVR0PAQH/BAQDAgKkMBMGA1UdJQQMMAoGCCsGAQUFBwMBMA8GA1Ud
                                                    EwEB/wQFMAMBAf8wHQYDVR0OBBYEFItn5K1rHQ7BO3/eiirTmp54D5+zMAoGCCqG
                                                    SM49BAMCA0gAMEUCIQDoeL/lwjcw5twx2gJH8mQsLCc7hOTEyT0rJ7dZtzagwwIg
                                                    Zs6Db0VKkdNzajNxH/vnseJqY9usMddkHU3zZjP8yAY=
                                                    -----END CERTIFICATE-----

      LINKERD2_PROXY_IDENTITY_TOKEN_FILE:           /var/run/secrets/kubernetes.io/serviceaccount/token
      LINKERD2_PROXY_IDENTITY_SVC_ADDR:             linkerd-identity-headless.linkerd.svc.cluster.local:8080
      _pod_sa:                                       (v1:spec.serviceAccountName)
      _l5d_ns:                                      linkerd
      _l5d_trustdomain:                             cluster.local
      LINKERD2_PROXY_IDENTITY_LOCAL_NAME:           $(_pod_sa).$(_pod_ns).serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdomain)
      LINKERD2_PROXY_IDENTITY_SVC_NAME:             linkerd-identity.$(_l5d_ns).serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdomain)
      LINKERD2_PROXY_DESTINATION_SVC_NAME:          linkerd-destination.$(_l5d_ns).serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdomain)
      LINKERD2_PROXY_TAP_SVC_NAME:                  linkerd-tap.$(_l5d_ns).serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdomain)
    Mounts:
      /var/run/linkerd/identity/end-entity from linkerd-identity-end-entity (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-azure-token-jvmr6 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  ingress-azure-token-jvmr6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-azure-token-jvmr6
    Optional:    false
  linkerd-proxy-init-xtables-lock:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  linkerd-identity-end-entity:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      Memory
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:          <none>

* Output of `kubectl logs <ingress controller>. 
api-tst-nsj-80--5bb3b910c394380ccf2c032f06b9ceac
I1112 09:26:23.372055       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I1112 09:26:54.164575       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I1112 09:26:54.164617       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I1112 09:26:54.172198       1 mutate_app_gateway.go:204] END AppGateway deployment
I1112 09:26:54.172221       1 controller.go:151] Completed last event loop run in: 36.818948255s
I1112 09:27:12.592163       1 internaltypes.go:100] Prop name pb-dev-nsj-ms-workflow-rulegenerator-dev-nsj-80-ms-workflow-rulegenerator-dev-nsj with length 81 is longer than 80 characters; Transformed to pb-dev-nsj-ms-workflow-rulegenerator-dev-nsj-80-1b67db44e3fd1be83c9279dff73c1c64
I1112 09:27:12.608237       1 internaltypes.go:100] Prop name bp-dev-nsj-ms-nsj-ipinformation-api-dev-nsj-80-80-ms-nsj-ipinformation-api-dev-nsj with length 82 is longer than 80 characters; Transformed to bp-dev-nsj-ms-nsj-ipinformation-api-dev-nsj-80--a45653f28f81846c8def4a39786408b2
I1112 09:27:12.608478       1 internaltypes.go:100] Prop name bp-dev-nsj-ms-workflow-rulegenerator-dev-nsj-80-80-ms-workflow-rulegenerator-dev-nsj with length 84 is longer than 80 characters; Transformed to bp-dev-nsj-ms-workflow-rulegenerator-dev-nsj-80-7e60ebf38a36e96ec31585f19c2db759
I1112 09:27:12.608552       1 internaltypes.go:100] Prop name bp-tst-nsj-ms-nsj-ipinformation-api-tst-nsj-80-80-ms-nsj-ipinformation-api-tst-nsj with length 82 is longer than 80 characters; Transformed to bp-tst-nsj-ms-nsj-ipinformation-api-tst-nsj-80--5bb3b910c394380ccf2c032f06b9ceac
I1112 09:27:12.608591       1 internaltypes.go:100] Prop name bp-tst-sej-ms-sej-compatibility-api-tst-sej-80-80-ms-sej-compatibility-api-tst-sej with length 82 is longer than 80 characters; Transformed to bp-tst-sej-ms-sej-compatibility-api-tst-sej-80--b73e27d858402eb185b67e206c866e98
I1112 09:27:12.608748       1 internaltypes.go:100] Prop name bp-dev-sej-ms-sej-compatibility-api-dev-sej-80-80-ms-sej-compatibility-api-dev-sej with length 82 is longer than 80 characters; Transformed to bp-dev-sej-ms-sej-compatibility-api-dev-sej-80--c34f8b1afef19894857d7079750414bf
I1112 09:27:12.695264       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I1112 09:27:43.421747       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I1112 09:27:43.421814       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I1112 09:27:43.434602       1 mutate_app_gateway.go:204] END AppGateway deployment
I1112 09:27:43.434624       1 controller.go:151] Completed last event loop run in: 36.807201595s
* Any Azure support tickets associated with this issue.
120111025000888 :Issues with power shell script/not associating to rules
120100925001941 :Issues with AGIC pods commmunicating with App gateway,in the same request asked if this is possible to add rewrite rules.

Thanks in advance and any help here is appreciated.

**Comment by MarcelT-NL** [comment]
_I am able to create rewrite sets/rewrite rules using Terraform/Powershell but I am not able to associate these rules to any request routing rules as that is being managed by AGIC. Even I create the rules manually and associate, AGIC will remove those changes as that is in full charge of App Gateway_

+1
Have exactly the same issue.

**Comment by JonesChi** [comment]
+1
Have same issue here, does anyone have solution to keep rewrite rules?

**Comment by ShaunBresnahan** [comment]
> +1
> Have same issue here, does anyone have solution to keep rewrite rules?

Would love to know if there's a solution to this?

**Comment by chaitanyabhalerao1** [comment]
+1 we want to write rewrite rules whicb should persist even after AGIC updates appgateway during Recreation of PODs...awaiting fix for this 

Appreciate if we get any ETA so we can decide wheather tk move to NGINX+ or some other ingress controllers...

**Comment by adamcarter81** [comment]
+1 for deploying the rewrites via Terraform or az cli and not having agic remove them! Or agic to have the ability to reference the ruleset for each rule
