### ISSUE TITLE
resources in kube-system and kube-public are being ignored

### ISSUE THREAD

**Issue by polasekr** [Azure/application-gateway-kubernetes-ingress#1060]
**Describe the bug**
In a case that ingress resource and its corresponding secret with SSL certificate are deployed into namespace kube-system or kube-public, they are ignore.

This is caused by code in `pkg/k8scontext/context.go`

```
var namespacesToIgnore = map[string]interface{}{
        //      "kube-system": nil,
        //      "kube-public": nil,
        "do-not-ingnore-any-ns": nil,
}
```

I am wondering what is the reason for setting ignore flag on those namespaces.

**Comment by polasekr** [comment]
I was checking and I cannot see a reason why some arbitrary namespaces should be ignored. 

Would be considered an acceptable alternative keeping those two ignored namespaces as default setting, but introducing and environment variable `KUBERNETES_IGNORED_NAMESPACES` that could override the setting? The variable could be either empty, resulting in no namespace being ignored, or comma separated list of namespaces.

If so, I am happy to create PR for it.

**Comment by akshaysngupta** [comment]
@polasekr This was done to avoid the churn in events that happen in these namespaces.

**Comment by akshaysngupta** [comment]
Sure, it should be okay to make this as a flag.
How does `kubernetes.allowSystemNamespaces: true` sound ?

**Comment by polasekr** [comment]
PR https://github.com/Azure/application-gateway-kubernetes-ingress/pull/1088 submitted for the same. Thank you for supporting the motion.
