### ISSUE TITLE
Add ingress annotation 'appgw.ingress.kubernetes.io/rewrites' to assign rewrite sets to listeners created/updated by AGIC

### ISSUE THREAD

**Issue by MarcelT-NL** [Azure/application-gateway-kubernetes-ingress#1066]
### Issue
Currently it is impossible to use the rewrite sets in the App GW, because AGIC keeps overwriting the associations with the listeners. We need the rewrite sets to add security headers, remove unwanted headers, and redirect requests. AGIC is preventing us from using this functionality, and this is also causing red flags on every security scan and compliance pentest.

### Proposed solution
Add `appgw.ingress.kubernetes.io/rewrites-http` and `appgw.ingress.kubernetes.io/rewrites-https` annotations to ingress controllers, with one or more rewrite sets that should be associated with the listener in App GW. Please use the **name** of the rewrite set (not an URL or ID). Otherwise it is impossible to provision them from Terraform  and assign them to a listener from AGIC. 

The `appgw.ingress.kubernetes.io/rewrites-https` should be applied to the HTTPS listener that is automatically created. It may use different rewrite sets (e.g. adding HSTS headers).

### Proposed example code snippet:

```
appgw.ingress.kubernetes.io/rewrites-http:
                              my_rewrites_for_all_http_listeners
                              my_rewrites_for_site1
appgw.ingress.kubernetes.io/rewrites-https:
                              my_rewrites_for_all_https_listeners
                              my_rewrites_for_site1
                              my_rewrites_for_whatever

```

**Comment by andrejbrummelhuis** [comment]
+1

**Comment by jullianoacqio** [comment]
+1

**Comment by scryer-David** [comment]
+1

**Comment by rprashad** [comment]
For context this is impacting the ability to remove ports from the apgw xff header.
