### ISSUE TITLE
Support AG listener wildcard hostnames (currently in preview)

### ISSUE THREAD

**Issue by zorg-the-blue** [Azure/application-gateway-kubernetes-ingress#1069]
Application Gateway support for listener hostname wildcard configurations is currently in preview.
(reference: https://docs.microsoft.com/en-us/azure/application-gateway/multiple-site-overview#wildcard-host-names-in-listener-preview)

Supporting this feature though ingress configuration would be extremely helpful when hosting different multi-tenant sites.

Currently, when trying to apply a host rule including a wildcard configuration, for example:

    spec:
      rules:
      - host: '*foo.bar.com'
        http:  
          paths:
          - path: /
              serviceName: backend
              servicePort: 80

Results in an error (appears to be core Kubernetes Ingress validation so the solution may have to be done with annotations somehow or convince the K8 team there are certain areas of the spec that should leave validation up to the implementing system?):

_The Ingress "foobar-ingress" is invalid: spec.rules[0].host: Invalid value: "*foo.bar.com": a wildcard DNS-1123 subdomain must start with '*.', followed by a valid DNS subdomain, which must consist of lower case alphanumeric characters, '-' or '.' and end with an alphanumeric character (e.g. '*.example.com', regex used for validation is '\*\.[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')_

Thank you in advance for your consideration of this feature as well as your time, and effort supporting this project.

**Comment by akshaysngupta** [comment]
Use `appgw.ingress.kubernetes.io/hostname-extension` annotation to provide a wildcard hostname. This is supported on AGIC but not yet documented.
