### ISSUE TITLE
[Feature] ingressClassName for AGIC

### ISSUE THREAD

**Issue by ayoubeddafali** [Azure/application-gateway-kubernetes-ingress#1071]
Right now, Is it possible to use the ingressClassName when working with AGIC as a controller ? 

Thanks

**Comment by p3tric** [comment]
I am wondering the same thing. How the ingress class name can be set when installing it using helm? 

Furthermore, can approach "[Multiple Gateways Single Cluster](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/proposals/multiple-gateways-single-cluster.md)"  be used for deploying internal (using Private IP for internal routing) and external(for external traffic) ingress controllers instances to the same cluster?

Thanks.

**Comment by maelvls** [comment]
Does AGIC support the field `ingressClassName`? The PR #1076 did not make any mention to that field. @akshaysngupta
