### ISSUE TITLE
AGIC AKS Addon Update Frequency

### ISSUE THREAD

**Issue by johnsonr1994** [Azure/application-gateway-kubernetes-ingress#1085]
Hello,

I am using the AGIC aks addon for a preproduction cluster for my company, and it appears that the version of AGIC currently on our cluster is 1.2.1. One of the benefits of the aks addon deployment is the auto upgrades to the AGIC, but that doesn't appear to have happened (yet at least). Release 1.3 has been available for around a week now and we really want to utilize the new port override annotation that has been merged in with that release. I was wondering what is the time threshold on these automatic updates when a new stable release is available? Or to see if I can throw in a CLI parameter on the addon to use a specific version?

I have disabled and reenabled the addon for our cluster to see if I could force the upgrade, but I was unsuccessful. Any help would be greatly appreciated. Thanks!

**Comment by johnsonr1994** [comment]
Any update on this? I still see that my ingress controller version is 1.2.1 and it has been a long time now since version 1.3 was released

**Comment by YannickG1** [comment]
I'm in the same boat. I need the new configuration parameters but the addon still has 1.2.1 version. I guess it's better to disable it and go the helm route so that we can decide ourselves what version we run. I loved the auto-update feature of the addon, but if it never updates it's quite useless :)

**Comment by akshaysngupta** [comment]
Sorry for the delay in this. We will soon roll out 1.4.0 on the addon.

**Comment by picardsrcd** [comment]
@akshaysngupta  Could you advise of the rough timeline? I have an environment i need to deliver next week with the ability to do public and private ip services. If the timelines can align, I will avoid the hassle of deploying Pod Identity + AGIC :)

**Comment by Julieeeen** [comment]
Any update when the Addon will be roll out ?

**Comment by akshaysngupta** [comment]
We expect the roll out to start this coming week and finish in 1-2 weeks in all regions.

**Comment by javiermarasco** [comment]
I can confirm the add-on now is 1.4.0, deployed in West Europe and got that version out of the box. Thanks @akshaysngupta !

**Comment by johnsonr1994** [comment]
I can confirm that our add-on was updated to v1.4.0 without a redeploy in East US. Thank you @akshaysngupta
