### ISSUE TITLE
AG Backend Pool IP's not getting removed when re-deploying or updating pods

### ISSUE THREAD

**Issue by prateekchawla** [Azure/application-gateway-kubernetes-ingress#1092]
**Describe the bug**
When deploying pods, the backend pool is not picking up the latest IP's of the pod. It still has the old IP's of pod which are terminated

**To Reproduce**
kubectl set image deployment/(new image version from repo)
or
kubectl apply -f $pod_file 

**Ingress Controller details**
auto-web-dev@Azure:~$ kubectl describe pod ingress-azure
Name:         ingress-azure-cd9759846-m2bw6
Namespace:    default
Priority:     0
Node:         aks-agentpool-30824605-2/10.0.0.4
Start Time:   Wed, 16 Dec 2020 13:19:10 +0000
Labels:       aadpodidbinding=ingress-azure
              app=ingress-azure
              pod-template-hash=cd9759846
              release=ingress-azure
Annotations:  checksum/config: 50f1e75d9e29610f160b8e62c1dca0e447d8ed693f7bd6cf1d757a265bb8af1b
              prometheus.io/port: 8123
              prometheus.io/scrape: true
Status:       Running
IP:           10.0.0.15
IPs:
  IP:           10.0.0.15
Controlled By:  ReplicaSet/ingress-azure-cd9759846
Containers:
  ingress-azure:
    Container ID:   docker://9881ce1c8e541fdc29ce945a7d95f6d7cf06da6f57f022c9a164b40dead24a2e
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.2.1
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:cf1df9645ded72127967c99bbf88b758b5b19b698ba18a9ed74c3a7ebf016ef1
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 16 Dec 2020 13:19:21 +0000
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_CLOUD_PROVIDER_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:                  ingress-azure-cd9759846-m2bw6 (v1:metadata.name)
      AGIC_POD_NAMESPACE:             default (v1:metadata.namespace)
    Mounts:
      /etc/appgw/azure.json from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-azure-token-f5d9m (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  ingress-azure-token-f5d9m:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-azure-token-f5d9m
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                     Age                      From                       Message
  ----     ------                     ----                     ----                       -------
  Warning  FailedApplyingAppGwConfig  80s (x13979 over 5d23h)  azure/application-gateway  network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client '<CleintId>' with object id '<objectid>' has permission to perform action 'Microsoft.Network/applicationGateways/write' on scope '/subscriptions/<x>/resourceGroups/aks-rtb-dev/providers/Microsoft.Network/applicationGateways/applicationgateway20bd'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/<x>/resourcegroups/aks-rtb-dev/providers/Microsoft.ManagedIdentity/userAssignedIdentities/appgwContrIdentity20bd' or the linked scope(s) are invalid."
  
**Backend Ingress details**
Name:             backend-ingress
Namespace:        default
Address:          40.88.250.127
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host        Path  Backends
  ----        ----  --------
  *
              /ms-quotewizardbid/*   ms-quotewizardbid-service:8080 ()
              /ms-mediaalphabid/*    ms-mediaalphabid-service:8080 (10.0.0.57:4000,10.0.0.83:4000)
              /ms-everquotebid/*     ms-everquotebid-service:8080 (10.0.0.49:4000,10.0.0.92:4000)
              /ms-quinstreetbid/*    ms-quinstreetbid-service:8080 ()
Annotations:  appgw.ingress.kubernetes.io/backend-path-prefix: /
              appgw.ingress.kubernetes.io/connection-draining: true
              appgw.ingress.kubernetes.io/connection-draining-timeout: 30
              kubernetes.io/ingress.class: azure/application-gateway
Events:       <none>

**Comment by akshaysngupta** [comment]
@prateekchawla You can fix this by giving AGIC identity "contributor" access to Application Gateway's User assigned identity.
```bash
az role assignment create --scope "/subscriptions//resourcegroups/aks-rtb-dev/providers/Microsoft.ManagedIdentity/userAssignedIdentities/appgwContrIdentity20bd" --role "Managed Identity Operator" --assignee "<AGIC-Identity-Client-ID>"
```

**Comment by prateekchawla** [comment]
Thanks! @akshaysngupta
