### ISSUE TITLE
Unable to deploy application

### ISSUE THREAD

**Issue by jp4u** [Azure/application-gateway-kubernetes-ingress#1094]
Hello,

I created a new cluster, created an application gateway and then installed AGIC per the tutorial. I then configured the ingress controller with the following config:

/# This file contains the essential configs for the ingress controller helm chart

/# Verbosity level of the App Gateway Ingress Controller
verbosityLevel: 3

################################################################################
/# Specify which application gateway the ingress controller will manage
/#
appgw:
    subscriptionId: <<subscriptionid>>
    resourceGroup: experimental-cluster-rg
    name: experimental-cluster-ag
    usePrivateIP: false

    # Setting appgw.shared to "true" will create an AzureIngressProhibitedTarget CRD.
    # This prohibits AGIC from applying config for any host/path.
    # Use "kubectl get AzureIngressProhibitedTargets" to view and change this.
    shared: false

################################################################################
/# Specify which kubernetes namespace the ingress controller will watch
/# Default value is "default"
/# Leaving this variable out or setting it to blank or empty string would
/# result in Ingress Controller observing all acessible namespaces.
/#
/# kubernetes:
/#   watchNamespace: <namespace>

################################################################################
/# Specify the authentication with Azure Resource Manager
/#
/# Two authentication methods are available:
/# - Option 1: AAD-Pod-Identity (https://github.com/Azure/aad-pod-identity)
/# armAuth:
/#     type: aadPodIdentity
/#     identityResourceID: <identityResourceId>
/##     identityClientID:  <identityClientId>

/## Alternatively you can use Service Principal credentials
armAuth:
    type: servicePrincipal
    secretJSON: <<hash>>

################################################################################
/# Specify if the cluster is RBAC enabled or not
rbac:
    enabled: true

When I deploy the application and check the gateway, it appears to be updating the gateway through the ingress controller by creating its own settings. The problem seems to be that the application never gets exposed. I checked the health probe and it stated it was unhealthy due to 404 status. I was unable to access the application directly by IP. I get a 404 or 502 depending on how I try to access the application.

I tried deploying both an nginx and agic ingress and the nginx seems to work fine:

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aks-seed-ingress-main
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    # appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
      - agic-cluster.company.com
      - frontend.<ip0>.nip.io
      secretName: zigzypfxtls
  rules:
  - host: agic-cluster.company.com
    http:
      paths:
      - backend:
          serviceName: aks-seed
          servicePort: 80
        path: /
  - host: frontend.<ip0>.nip.io
    http:
      paths:
      - backend:
          serviceName: aks-seed
          servicePort: 80
        path: /
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: aks-seed-ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
      - frontend.<ip>.nip.io
  rules:
  - host: frontend.<ip>.nip.io
    http:
      paths:
      - backend:
          serviceName: aks-seed # Modify
          servicePort: 80
        path: /

I am unsure what I am missing. I followed the tutorials as best I could and the agic controller and application gateway appear to be communicating. However the application is inaccessible on the agic controller but accessible on the nginx controller. I only installed the nginx controller afterwards to ensure there was no issue with the application itself.

**Comment by 3quanfeng** [comment]
Hi @jp4u , did you set your header in your request, e.g. --header 'Host: agic-cluster.company.com'?

**Comment by Jonatthu** [comment]
@3quanfeng Could you be more specific? Where is this request coming from or where should I set up this?

**Comment by jp4u** [comment]
@3quanfeng Hi could you please elaborate where I would include this?

Also, I would like to ask about the documentation-
Under Azure Resource Manager Authentication in Brownfield Deployment it mentions Set up AAD Pod Identity and also Using a Service Principal. I am using a service principal so do I have to do all the steps mentioned above it?

https://azure.github.io/application-gateway-kubernetes-ingress/setup/install-existing/

Also, when I run: az ad sp create-for-rbac --sdk-auth | base64 -w0
Is it possible to get the clientId from this afterwards?

**Comment by jp4u** [comment]
I am getting the following on my backend probe

Received invalid status code: 404 in the backend server’s HTTP response. As per the health probe configuration, 200-399 is the acceptable status code. Either modify probe configuration or resolve backend issues. To learn more visit - https://aka.ms/StatusCodeMismatch.
--

**Comment by 3quanfeng** [comment]
Hi @jp4u , what I meant above is to specify hostname in your request to backend via application gateway given multi-site hosting is configured in your ingress manifest above.
404 basically means your backend endpoint is not set up correctly, one step you could verify is to set up a vm in the same subnet of application gateway and probe manually the same endpoint for your backend.

**Comment by jp4u** [comment]
@3quanfeng You mean use the actual url? I have targeted each specific url and the public ip directly with no success. I have also removed all the hosts so that it appears as * and tried to directly access the public ip.

For your second comment, are you asking me to set up a VM in the same subnet of the application gateway then try to access the internal ip of my gateway backend pool or the clusterip of my service?

**Comment by 3quanfeng** [comment]
@jp4u , an example by using curl is: curl -H "Host: example.com" http://localhost/
Yes, same subnet and try to hit the same path you configure for healthy probe

**Comment by jp4u** [comment]
@3quanfeng I'm not sure if this may be something to consider, but it looks like my vent has two subnets default (10.240.0.0/16) and appgwsubnet (10.241.0.0.24) but it looks like on my backend health tab, the ip addresses for my backend pool is 10.240.0.100

Also, could you please clarify exactly which endpoint in my backend that I am trying to internally access?

**Comment by jp4u** [comment]
My output when I describe the ingress:

kubectl describe ingress aks-seed-general-ingress
Name:             aks-seed-general-ingress
Namespace:        default
Address:          104.42.194.124
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
  pfxtls terminates
Rules:
  Host        Path  Backends
  ----        ----  --------
  *
                 aks-seed:80 (10.240.0.100:80)
Annotations:  kubernetes.io/ingress.class: azure/application-gateway
Events:       <none>

**Comment by 3quanfeng** [comment]
Hi @jp4u , could you also share the updated ingress manifest you have? I think the output you shared above is cut off, you could put shared file content in the code block.

**Comment by jp4u** [comment]
@3quanfeng 

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aks-seed-general-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  tls:
    - secretName: zigzypfxtls
  rules:
  - http:
      paths:
      - backend:
          serviceName: aks-seed
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aks-seed-ingress-main
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    # appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
      - aks-agic-cluster.company.com
      - frontend.104.42.194.124.nip.io
      secretName: pfxtls
  rules:
  - host: aks-agic-cluster.company.com
    http:
      paths:
      - backend:
          serviceName: aks-seed
          servicePort: 80
        path: /
  - host: frontend.104.42.194.124.nip.io
    http:
      paths:
      - backend:
          serviceName: aks-seed
          servicePort: 80
        path: /

**Comment by jp4u** [comment]
I also saw this on another thread:

$ingressappid = az aks show --name $kubernetesClusterName -g $resourceGroupNameAKS --query addonProfiles.ingressApplicationGateway.identity.clientId -o tsv $rgid = az group show --name $resourceGroupNameAKS -o tsv --query "id" az role assignment create --role Reader --scope $rgid --assignee $ingressappid az role assignment create --role Contributor --scope $appgwId --assignee $ingressappid

But I was unable to get the ingressappid, I am wondering if because I am using a service principal for authentication instead of identity may be an issue.

**Comment by jp4u** [comment]
`
Name:             aks-seed-general-ingress
Namespace:        default
Address:          104.42.194.124
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
  zigzypfxtls terminates
Rules:
  Host        Path  Backends
  ----        ----  --------
  *
                 aks-seed:80 (10.240.0.100:80)
Annotations:  kubernetes.io/ingress.class: azure/application-gateway
Events:       <none>
`

**Comment by jp4u** [comment]
@3quanfeng Also, according to https://github.com/MicrosoftDocs/azure-docs/issues/65334, I tried:

kubectl get pods -n kube-system

I don't see an appgw pod:

james@Azure:~$ kubectl get pods -n kube-system
NAME                                    READY   STATUS    RESTARTS   AGE
azure-cni-networkmonitor-f44h7          1/1     Running   0          47h
azure-ip-masq-agent-cmnzt               1/1     Running   0          47h
azure-npm-pbq2p                         1/1     Running   0          47h
azure-policy-6b5fd86b74-vpcbd           1/1     Running   0          47h
azure-policy-webhook-75b4fffd8c-vhdqj   1/1     Running   0          47h
coredns-748cdb7bf4-8mkl9                1/1     Running   0          47h
coredns-748cdb7bf4-h8vfh                1/1     Running   0          47h
coredns-autoscaler-868b684fd4-5gkvn     1/1     Running   0          47h
kube-proxy-ztv9h                        1/1     Running   0          47h
metrics-server-58fdc875d5-9jq98         1/1     Running   0          47h
omsagent-2fzqw                          1/1     Running   0          47h
omsagent-rs-55949445b7-8jclq            1/1     Running   0          47h
tunnelfront-7b6787b4ff-tddjh            1/1     Running   0          27h

**Comment by 3quanfeng** [comment]
Hi @jp4u , if you use agic with add-on, then you should be able to locate agic pod from kube-system, otherwise if will be default if you didn't specify any namespace when you use helm install.
Did you use ssl-redirect or not, I see that annotation is commented, in addition, did you get any error log from agic pod? you can get the full log by "kubectl logs pod -n yournamespace"(it's recommended to share your log at verbosity 5), also what's the agic version you have been using?

**Comment by jp4u** [comment]
@3quanfeng I am not sure how to change the verbosity level, do I have to redeploy the pod with the config set to 5? Here is my current logs for the pod named ingress-azure:

james@Azure:~$ kubectl logs ingress-azure-7778c494f9-wmpts
ERROR: logging before flag.Parse: I0112 23:21:00.993045       1 utils.go:115] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0112 23:21:01.026860       1 environment.go:246] KUBERNETES_WATCHNAMESPACE is not set. Watching all available namespaces.
I0112 23:21:01.026964       1 main.go:128] Appication Gateway Details: Subscription="b13d11b3-9583-4815-be4c-a7fddee16992" Resource Group="aks-exp-rg" Name="aks-exp-ag"
I0112 23:21:01.026982       1 auth.go:37] Creating authorizer from file referenced by environment variable: /etc/Azure/Networking-AppGW/auth/armAuth.json
I0112 23:21:01.027012       1 httpserver.go:57] Starting API Server on :8123
I0112 23:21:01.528486       1 main.go:175] Ingress Controller will observe all namespaces.
I0112 23:21:01.765441       1 context.go:138] k8s context run started
I0112 23:21:01.765469       1 context.go:188] Waiting for initial cache sync
I0112 23:21:01.866253       1 context.go:201] Initial cache sync done
I0112 23:21:01.866274       1 context.go:202] k8s context run finished
I0112 23:21:01.866351       1 worker.go:39] Worker started
I0112 23:21:02.001251       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0112 23:21:32.894728       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0112 23:21:32.894763       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0112 23:21:32.895270       1 mutate_app_gateway.go:204] END AppGateway deployment
I0112 23:21:32.895288       1 controller.go:151] Completed last event loop run in: 31.028921997s
I0113 00:15:12.708537       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I0113 00:15:12.708564       1 controller.go:151] Completed last event loop run in: 241.015084ms
I0113 00:15:13.757546       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 00:16:45.064381       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 00:16:45.064410       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 00:16:45.065657       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 00:16:45.065714       1 controller.go:151] Completed last event loop run in: 1m31.35701167s
I0113 00:16:46.137041       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 00:17:16.727272       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 00:17:16.727291       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 00:17:16.728384       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 00:17:16.728402       1 controller.go:151] Completed last event loop run in: 30.662461341s
I0113 00:43:35.952782       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 00:45:06.814872       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 00:45:06.814894       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 00:45:06.815467       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 00:45:06.815483       1 controller.go:151] Completed last event loop run in: 1m31.041032329s
I0113 00:49:10.862876       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 00:50:41.707032       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 00:50:41.707065       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 00:50:41.708698       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 00:50:41.708729       1 controller.go:151] Completed last event loop run in: 1m31.063001487s
I0113 00:50:42.762598       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 00:51:13.250560       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 00:51:13.250582       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 00:51:13.251498       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 00:51:13.251517       1 controller.go:151] Completed last event loop run in: 30.54262874s
I0113 01:00:24.426813       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 01:01:15.161061       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 01:01:15.161082       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 01:01:15.161939       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 01:01:15.161959       1 controller.go:151] Completed last event loop run in: 50.934271698s
I0113 17:22:57.706366       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 17:24:28.662486       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 17:24:28.662510       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 17:24:28.663730       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 17:24:28.663757       1 controller.go:151] Completed last event loop run in: 1m31.428523473s
I0113 17:24:29.712785       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 17:25:00.194125       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 17:25:00.194158       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 17:25:00.195787       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 17:25:00.195815       1 controller.go:151] Completed last event loop run in: 30.531941564s
I0113 17:25:36.874627       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I0113 17:25:36.874653       1 controller.go:151] Completed last event loop run in: 49.19318ms
I0113 17:25:48.502110       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 17:26:18.982926       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 17:26:18.982948       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 17:26:18.984280       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 17:26:18.984312       1 controller.go:151] Completed last event loop run in: 30.559303359s
I0113 17:26:20.044825       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 17:26:50.636149       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 17:26:50.636182       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 17:26:50.637558       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 17:26:50.637585       1 controller.go:151] Completed last event loop run in: 30.653133557s
I0113 17:26:51.684152       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I0113 17:26:51.684176       1 controller.go:151] Completed last event loop run in: 46.464115ms
I0113 17:31:08.070167       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 17:31:39.039444       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 17:31:39.039471       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 17:31:39.040641       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 17:31:39.040664       1 controller.go:151] Completed last event loop run in: 31.17421311s
I0113 17:31:40.119125       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 17:32:10.710463       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 17:32:10.710484       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 17:32:10.711590       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 17:32:10.711611       1 controller.go:151] Completed last event loop run in: 30.670829186s
I0113 17:32:11.761810       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 17:32:42.205248       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 17:32:42.205270       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 17:32:42.206132       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 17:32:42.206150       1 controller.go:151] Completed last event loop run in: 30.494409888s
I0113 17:33:01.670317       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I0113 17:33:01.670339       1 controller.go:151] Completed last event loop run in: 65.382865ms
I0113 17:33:02.715468       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I0113 17:33:02.715495       1 controller.go:151] Completed last event loop run in: 44.906823ms
I0113 17:33:08.351616       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 17:33:38.799234       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 17:33:38.799313       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 17:33:38.800260       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 17:33:38.800279       1 controller.go:151] Completed last event loop run in: 30.494745908s
I0113 17:33:39.874478       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 17:34:10.354874       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 17:34:10.354898       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 17:34:10.356177       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 17:34:10.356202       1 controller.go:151] Completed last event loop run in: 30.555721306s
I0113 17:38:20.065925       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 17:38:50.954852       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 17:38:50.954873       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 17:38:50.956200       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 17:38:50.956229       1 controller.go:151] Completed last event loop run in: 31.043859005s
I0113 17:38:52.005121       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 17:39:22.460028       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 17:39:22.460053       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 17:39:22.460917       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 17:39:22.460935       1 controller.go:151] Completed last event loop run in: 30.5044971s
I0113 17:39:23.507008       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 17:39:54.093997       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 17:39:54.094048       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 17:39:54.095099       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 17:39:54.095118       1 controller.go:151] Completed last event loop run in: 30.633953549s
I0113 17:43:03.049875       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I0113 17:43:03.049898       1 controller.go:151] Completed last event loop run in: 122.639037ms
I0113 17:43:04.104076       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I0113 17:43:04.104100       1 controller.go:151] Completed last event loop run in: 54.058678ms
I0113 17:43:06.582385       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 17:43:37.438276       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 17:43:37.438301       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 17:43:37.439641       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 17:43:37.439670       1 controller.go:151] Completed last event loop run in: 30.926498988s
I0113 17:43:38.510627       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 17:44:09.123037       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 17:44:09.123059       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 17:44:09.123958       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 17:44:09.123976       1 controller.go:151] Completed last event loop run in: 30.684197796s
I0113 18:24:02.670039       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 18:24:33.522608       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 18:24:33.522631       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 18:24:33.524063       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 18:24:33.524087       1 controller.go:151] Completed last event loop run in: 31.450031344s
I0113 18:24:34.595596       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0113 18:25:05.152103       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0113 18:25:05.152124       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0113 18:25:05.153227       1 mutate_app_gateway.go:204] END AppGateway deployment
I0113 18:25:05.153240       1 controller.go:151] Completed last event loop run in: 30.628901452s

**Comment by jp4u** [comment]
I am not currently using the ssl redirect, I am just trying to establish a connection via directly the ip. My application pod has the following logs as well:

james@Azure:~$ kubectl logs aks-seed-6cfd99c88f-qjgr2
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {b82d795e-16cf-4d5c-83f4-a53413a11ddd} may be persisted to storage in unencrypted form.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.

**Comment by jp4u** [comment]
There doesn't seem to be any internal errors but I still cannot access my application. I created an entirely new AKS server from the ground up and it still does not work

**Comment by jp4u** [comment]
@3quanfeng Any suggestions?

**Comment by 3quanfeng** [comment]
> @3quanfeng I'm not sure if this may be something to consider, but it looks like my vnet has two subnets default (10.240.0.0/16) and appgwsubnet (10.241.0.0.24) but it looks like on my backend health tab, the ip addresses for my backend pool is 10.240.0.100 (its in the default subnet not the appgw?)
> 
> Also, could you please clarify exactly which endpoint in my backend that I am trying to internally access?

Hi @jp4u , sorry for late response.
As I noted before:
1.  to verify the connection b/w appgw subnet and your backend, you could create an instance in appgw subnet and test the connection to your backend subnet, the endpoint could be any endpoint you want to expose to test the connection
2.  Are you testing end 2 end ssl encryption scenario? is your backend an https endpoint? if yes, you will need to use another annotation called backend hostname, e.g. https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/tutorials/tutorial.e2e-ssl.md
3. Although I doubt about using security principal could cause the issue, if you don't see any issues for the above two, I would recommend you to test with user assigned identity
4. Yes, in order to get logging vebosity=5, you will need to update it in the helm values yaml and do redeployment
