### ISSUE TITLE
custom probe path is invalid

### ISSUE THREAD

**Issue by tarrantro** [Azure/application-gateway-kubernetes-ingress#1096]
I create an ingress with custom probe path, but it doesn't reflect on the application gateway.

My ingress yaml:
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-server-ingress-bkprefix
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/health-probe-path: "/probe/test"
    appgw.ingress.kubernetes.io/health-probe-hostname: "localhost"
    appgw.ingress.kubernetes.io/health-probe-port: "80"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: aspnetapp
          servicePort: 80

My application gateway probe:
![image](https://user-images.githubusercontent.com/19900542/103259092-f3f7df80-49d2-11eb-8fc5-c1bc0a9bc287.png)

**Comment by pascal08** [comment]
I'm having the same problem. Just to be sure, does this annotation work with the managed AGIC addon?

**Comment by vinshetty** [comment]
Here we are also facing the same issue 

#1095

**Comment by 3quanfeng** [comment]
1.3 doesn't have the feature, a new release is planned in Jan which will have the new annotations available
