### ISSUE TITLE
Error when update existed via ARM: Changing property 'servicePrincipalProfile.secret' is not allowed

### ISSUE THREAD

**Issue by tonystz** [Azure/application-gateway-kubernetes-ingress#1098]
**Describe the bug**
Could not update AKS, and report error `Changing property 'servicePrincipalProfile.secret' is not allowed.`

**To Reproduce**
1. create follow "Greenfield Deployment' steps
2. Update the created AKS via same steps

Report error:
**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
* Output of `kubectl logs <ingress controller>. 
* Any Azure support tickets associated with this issue.

Could any workaround or solution to fix this issue?

**Comment by 3quanfeng** [comment]
Hi @tonystz, can you please help provide the full log(or may be a log snippet)?

**Comment by akshaysngupta** [comment]
@tonystz When re-running the steps, are you also creating the service principal again ?

**Comment by tonystz** [comment]
sorry, I fix the issue
