### ISSUE TITLE
Application gateway misconfigured without service object

### ISSUE THREAD

**Issue by hp598** [Azure/application-gateway-kubernetes-ingress#1112]
Hi, 

We had an issue where the application gateway was misconfigured and all our listeners were returning 502 when we had an ingress configured and ready pods, but no kubernetes service object (or anything else that might return an endpoints object). 

We are using application gateway ingress controller v1.3.0.

F.e. an ingress with the following rules: 

    rules:
    - host: my.example-host.com
      http:
        paths:
        - backend:
            serviceName: example-service-name
            servicePort: 8080
          path: /example/*

 
would cause problems if there was no "example-service-name" service object within the same namespace (most of the application gateway listeners would then return 502, even if they worked fine previously)

**Comment by akshaysngupta** [comment]
@hp598
1. Can you please share AGIC logs ?
2. Are the remaining ingresses using the same service as a target ?

**Comment by hp598** [comment]
Hi, 

The remaining ingresses are not in the same namespace / do not share the same target. AGIC error log look roughly like this: 

I0119 14:25:41.077408       1 context.go:560] IP 20.56.195.84 already set on Ingress base-example/base-example
I0119 14:25:41.077429       1 mutate_aks.go:72] [mutate_aks] Updated Ingress base-example/base-example IP to 30.56.224.74
I0119 14:25:41.109448       1 ingress_rules.go:152] Found backend:base-example/base-example-http
E0119 14:25:41.110019       1 ingress_rules.go:163] Ingress base-example/base-example references non existent Service base-example/base-example-http. Please correct the Service section of your Kubernetes YAML
I0119 14:25:41.110520       1 health_probes.go:70] Created probe defaultprobe-Http for ingress base-example/base-example at service base-example/base-example-http
E0119 14:25:41.112205       1 backendhttpsettings.go:89] Unable to get the service [base-example/base-example-http]
I0119 14:25:41.113339       1 backendhttpsettings.go:204] Created backend http settings bp-base-example-base-example-http-http-0-base-example for ingress base-example/base-example and service base-example/base-example-http
E0119 14:25:41.114142       1 context.go:304] Code="ErrorFetchingEnpdoints" Message="Endpoint not found for base-example/base-example-http"
E0119 14:25:41.114210       1 backendaddresspools.go:103] Code="ErrorFetchingEnpdoints" Message="Endpoint not found for base-example/base-example-http"
I0119 14:25:41.112933       1 event.go:278] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"base-example", Name:"base-example", UID:"2b02fc99-287b-434a-ba23-375322d61b7c", APIVersion:"extensions/v1beta1", ResourceVersion:"20428107", FieldPath:""}): type: 'Warning' reason: 'ServiceNotFound' Unable to get the service [base-example/base-example-http]
I0119 14:25:41.115786       1 event.go:278] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"base-example", Name:"base-example", UID:"2b02fc99-287b-434a-ba23-375322d61b7c", APIVersion:"extensions/v1beta1", ResourceVersion:"20428107", FieldPath:""}): type: 'Warning' reason: 'EndpointsEmpty' Code="ErrorFetchingEnpdoints" Message="Endpoint not found for base-example/base-example-http"
I0119 14:25:41.116410       1 frontend_listeners.go:121] Processing Rules for Ingress: base-example/base-example
I0119 14:25:41.116524       1 ingress_rules.go:81] Found annotation appgw-ssl-certificate: my.example.com in ingress base-example/base-example
I0119 14:25:41.120189       1 ingress_rules.go:81] Found annotation appgw-ssl-certificate: my.example.com in ingress base-example/base-example
E0119 14:25:41.120763       1 context.go:304] Code="ErrorFetchingEnpdoints" Message="Endpoint not found for base-example/base-example-http"
E0119 14:25:41.120864       1 backendaddresspools.go:103] Code="ErrorFetchingEnpdoints" Message="Endpoint not found for base-example/base-example-http"
E0119 14:25:41.121059       1 context.go:304] Code="ErrorFetchingEnpdoints" Message="Endpoint not found for base-example/base-example-http"
E0119 14:25:41.121247       1 backendaddresspools.go:103] Code="ErrorFetchingEnpdoints" Message="Endpoint not found for base-example/base-example-http"
I0119 14:25:41.121200       1 event.go:278] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"base-example", Name:"base-example", UID:"2b02fc99-287b-434a-ba23-375322d61b7c", APIVersion:"extensions/v1beta1", ResourceVersion:"20428107", FieldPath:""}): type: 'Warning' reason: 'EndpointsEmpty' Code="ErrorFetchingEnpdoints" Message="Endpoint not found for base-example/base-example-http"
I0119 14:25:41.121746       1 requestroutingrules.go:348] Attached pool defaultaddresspool and http setting bp-base-example-base-example-http-http-0-base-example to path rule: pr-base-example-base-example-rule-0-path-0
I0119 14:25:41.121869       1 event.go:278] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"base-example", Name:"base-example", UID:"2b02fc99-287b-434a-ba23-375322d61b7c", APIVersion:"extensions/v1beta1", ResourceVersion:"20428107", FieldPath:""}): type: 'Warning' reason: 'EndpointsEmpty' Code="ErrorFetchingEnpdoints" Message="Endpoint not found for base-example/base-example-http"
I0119 14:25:41.121925       1 requestroutingrules.go:254] Attached default redirection 
E0119 14:25:41.122202       1 context.go:304] Code="ErrorFetchingEnpdoints" Message="Endpoint not found for base-example/base-example-http"
E0119 14:25:41.122291       1 backendaddresspools.go:103] Code="ErrorFetchingEnpdoints" Message="Endpoint not found for base-example/base-example-http"
I0119 14:25:41.122420       1 requestroutingrules.go:331] Attached redirection /subscriptions/<subscription>/resourceGroups/weu-agw-prod-rg/providers/Microsoft.Network/applicationGateways/weu-vnet-prod-agw/redirectConfigurations/sslr-fl-ae1c7796f85e755fdce326c511076d1d to path rule: pr-base-example-base-example-rule-0-path-0
I0119 14:25:41.122520       1 event.go:278] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"base-example", Name:"base-example", UID:"2b02fc99-287b-434a-ba23-375322d61b7c", APIVersion:"extensions/v1beta1", ResourceVersion:"20428107", FieldPath:""}): type: 'Warning' reason: 'EndpointsEmpty' Code="ErrorFetchingEnpdoints" Message="Endpoint not found for base-example/base-example-http"


E0119 14:25:41.148830       1 context.go:304] Code="ErrorFetchingEnpdoints" Message="Endpoint not found for base-example/base-example-http"
E0119 14:25:41.148842       1 backendaddresspools.go:103] Code="ErrorFetchingEnpdoints" Message="Endpoint not found for base-example/base-example-http"

I0119 14:25:41.149974       1 event.go:278] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"base-example", Name:"base-example", UID:"2b02fc99-287b-434a-ba23-375322d61b7c", APIVersion:"extensions/v1beta1", ResourceVersion:"20428107", FieldPath:""}): type: 'Warning' reason: 'EndpointsEmpty' Code="ErrorFetchingEnpdoints" Message="Endpoint not found for base-example/base-example-http"
-- App Gwy config --                "id": "/subscriptions/<subscription>/resourceGroups/weu-agw-prod-rg/providers/Microsoft.Network/applicationGateways/weu-vnet-prod-agw/backendHttpSettingsCollection/bp-base-example-base-example-http-http-0-base-example",
-- App Gwy config --                "name": "bp-base-example-base-example-http-http-0-base-example",
-- App Gwy config --                            "id": "/subscriptions/<subscription>/resourceGroups/weu-agw-prod-rg/providers/Microsoft.Network/applicationGateways/weu-vnet-prod-agw/urlPathMaps/url-447d285f283022e0a6dff2a4def1b770/pathRules/pr-base-example-base-example-rule-0-path-0",
-- App Gwy config --                            "name": "pr-base-example-base-example-rule-0-path-0",
-- App Gwy config --                            "id": "/subscriptions/<subscription>/resourceGroups/weu-agw-prod-rg/providers/Microsoft.Network/applicationGateways/weu-vnet-prod-agw/urlPathMaps/url-ae1c7796f85e755fdce326c511076d1d/pathRules/pr-base-example-base-example-rule-0-path-0",
-- App Gwy config --                            "name": "pr-base-example-base-example-rule-0-path-0",
-- App Gwy config --                                    "id": "/subscriptions/<subscription>/resourceGroups/weu-agw-prod-rg/providers/Microsoft.Network/applicationGateways/weu-vnet-prod-agw/backendHttpSettingsCollection/bp-base-example-base-example-http-http-0-base-example"

**Comment by akshaysngupta** [comment]
@hp598 I don't see other ingresses being processed in the AGIC log.
1. Did you set watchNamespace parameter in the config ?
2. Can you share any other ingress manifest deployed in the cluster ?

**Comment by akshaysngupta** [comment]
@hp598 any updates?
