### ISSUE TITLE
Support exposing external name service (along with native pods)

### ISSUE THREAD

**Issue by vinay-chaudhari** [Azure/application-gateway-kubernetes-ingress#1119]
Currently, AGIC doesn't support K8S external name services. Conversely, it is not possible to route any application via same app gateway along with other applications that are present on AKS. We are facing the same issue - multiple applications (APIs and UI) that needs to be hosted on same domain (as they are part of same eco-system); except some of them are containerized and some of them are yet to be containerized. External name service on K8S offer elegant solution to bring this apps on K8S so that other services may use them in same way except AGIC cannot expose them externally.

Considering that application gateway supports any FQDN/IP as backend, translating external name service on K8S to appropriate FQDN/IP should be technically feasible and perhaps apparently with less efforts.

**Comment by audunsolemdal** [comment]
Second this.

I was trying to create multiple oauth2 proxies from a central namespace by creating an ExternalName service 

Together with deploying this in a for_each loop for every tenant namespace in need.:
https://github.com/Azure/application-gateway-kubernetes-ingress/issues/860#issuecomment-1277377728

I keep stumbling into this limitation though `EndpointsEmpty - Code="ErrorFetchingEndpoints" Message="Endpoint not found for ... `

**Comment by akshaysngupta** [comment]
Tracked here #1567
