### ISSUE TITLE
Allow users to define an AG ingress prefix per AKS cluster.

### ISSUE THREAD

**Issue by asridharan** [Azure/application-gateway-kubernetes-ingress#112]
Currently the ingress controller uses a default prefix when adding sub-resources to the AG config.  The ingress controller will use this prefix to keep track of the sub-resources it added in order to not modify resources it had not added. 

However, the use of a default prefix allows an AG to be associated with only one AKS cluster. If we allow users to set a prefix per-cluster and automate the selection of the cluster prefix to make unique across different AKS clusters it will allow the same AG to be associated with different AKS clusters.

**Comment by draychev** [comment]
We are not planning on working on multi-cluster support in the near future. Closing this. (We do have env var `APPGW_CONFIG_NAME_PREFIX` supporting a custom prefix)
