### ISSUE TITLE
AGIC issues with invalid configs

### ISSUE THREAD

**Issue by pad-pad-pad** [Azure/application-gateway-kubernetes-ingress#1142]
# AGIC Issue Report

## Description

If the AGIC cannot create a valid config for an Ingress, it might also not deploy the other Ingresses or even delete existing Ingresses by overwriting the current APP GW config with an incomplete config, because the pathRules of the other Ingresses might be missing. The AGIC aborts the creation of the pathRules, if it encounters an invalid Ingress and only deploys the rules, which have been created so far.

## Cause of error

This happens, if a port cannot be resolved, which can happen in the following situations:

* Ingress/Service: Service port inside the Ingress is a "name" instead of a number, but the corresponding Service does not exist, which results in an unresolvable port. This does not happen, if the port inside the Ingress is given as a number!
* Ingress/Service: The service port inside the Ingress does not match a port inside the Service.
* Service/Pod: Target port inside the Service is a "name" instead of a number, but the corresponding Pod does not exist (e.g. because the creation of the Pod is denied by admission control), which results in an unresolvable port. This does not happen, if the port is given as a number! It seems, that the AGIC can tolerate 1 unresolvable port, if there is no Pod, but a Deployment/StatefulSet/DaemonSet/ReplicaSet. If there is more than 1 port definition inside the Service (and at least 1 of them is unresolvable), it still breaks, even if there is a Deployment/StatefulSet/DaemonSet/ReplicaSet.
* Service/Pod: The target port inside the Service does not match the port inside the Pod.

## Proposed Actions

The AGIC seems to iterate over all Ingresses during the creation of the pathRules and aborts the creation of further pathRules, if it encounters an invalid Ingress/unresolable port. Instead of a complete abortion, the AGIC should just skip the invalid Ingress and then continue with the other Ingresses!

Microsoft Support Ticket: 2102170050000264

**Comment by bbreijer** [comment]
We are experiencing the same issue. But in our case the AGIC seems to cycle recreation as long as the helm deploy is active.
(also part of Microsoft Support Ticket: 2103220050000970)

**Comment by bbreijer** [comment]
According to the support ticket, the issue should be fixed in release 1.4.0 of the AGIC plugin (er are running 1.2.1).

If you have installed the plugin using helm, you should be able to upgrade: https://docs.microsoft.com/bs-latn-ba/azure/application-gateway/ingress-controller-update-ingress-controller

If you have installed the plugin using ARM (like us), you have to wait for it to be updated: https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-overview#difference-between-helm-deployment-and-aks-add-on
The expectation is within two weeks.

**Comment by bbreijer** [comment]
Microsoft just informed me that they updated the ARM deployed gateway's to AGIC version 1.4.0. This should solve this issue, i hope to test this in the next week.
