### ISSUE TITLE
Version 1.4.0-rc1 cannot be found in the helm repo

### ISSUE THREAD

**Issue by chunliu** [Azure/application-gateway-kubernetes-ingress#1148]
**Describe the bug**
`helm search repo -l application-gateway-kubernetes-ingress` doesn't show version 1.4.0-rc1. Using `helm upgrade` could not upgrade the deployment to 1.4.0-rc1. 

**To Reproduce**
```
helm repo update
helm search repo -l application-gateway-kubernetes-ingress
helm upgrade \
  <release-name> \
  application-gateway-kubernetes-ingress/ingress-azure \
  --reuse-values \
  --version 1.4.0-rc1
```

**Comment by akshaysngupta** [comment]
@chunliu You need to add `--devel` flag since rc1 is a dev release.
`helm search repo -l application-gateway-kubernetes-ingress --devel`

![image](https://user-images.githubusercontent.com/5294363/109018113-b0d18a00-766c-11eb-9915-2873cfb21773.png)

**Comment by chunliu** [comment]
@akshaysngupta thanks. But even when I run `helm upgrade` with `--devel` to upgrade the agic to 1.4.0-rc1, the deployment and the pod in aks still points to 1.3.0 image. Do I miss anything?
