### ISSUE TITLE
One AGIC for Public and Private Ingresses

### ISSUE THREAD

**Issue by SirNeo** [Azure/application-gateway-kubernetes-ingress#1152]
**Is your feature request related to a problem? Please describe.**
I have 1 AGIC and 1 AKS cluster. In cluster, I have some public exposed applications. Also, In Azure DNS Zone, I have a register "A" for each application to access to them using DNS.

Azure DNS Zone:
app1.mydomain.com -> Public IP App Gateway
app2.mydomain.com -> Public IP App Gateway

Now, I want to have one private application, only accesible from internal network. I will connect to application using a VPN. I want to access to this application using a DNS. Currently, I'm able to access using the private IP.

Azure DNS Zone:
app-private.mydomain.com -> Private IP

I have annotated the Service for private application with this:
service.beta.kubernetes.io/azure-load-balancer-internal: 'true'

I have annotated the ingress for private application with this:
appgw.ingress.kubernetes.io/use-private-ip: "true"

Also, I have configured the private frontend IP in Application Gateway.

I checked that the when ingress is deployed, I can see the rule:
https://app-private.mydomain.com -> app-private:port with an IP in LoadBalancer that is the private IP of App Gateway.

Also, In Application Gateway, a listener is created as private and is associated to the Frontend IP configuration. 

But, I'm not able to access to my private application using the dns.

Does AGIC support Private and Public Ingresses in the same time?

**Describe the solution you'd like**
I would like to access to private/public applications using the DNS and only one AGIC.

**Comment by kamekazemaster** [comment]
Did you find any solution to your problem?

**Comment by kamekazemaster** [comment]
@akshaysngupta Its just sad that this issue was closed without a link to te real issue which I found in the mean time [https://github.com/Azure/application-gateway-kubernetes-ingress/issues/948](https://github.com/Azure/application-gateway-kubernetes-ingress/issues/948). The real problem ist that AGIC currently does not support private AND public ingresses (IPs) on the same time on the same port (80/HTTP and/or 443/HTTPS).
