### ISSUE TITLE
5xx error with high traffic to pods 

### ISSUE THREAD

**Issue by mazen423** [Azure/application-gateway-kubernetes-ingress#1165]
**Describe the bug**
I have deployed AGIC together with APP gateway in AKS cluster. The application pod can handle high traffic and it's already tested with Nginx controller. Sending just 200 requests/sec for 5 minutes without any scaling to the application pods and just 10% from required cpu and 30% from required memory we get back 500 errors on APP gateway logs and it's around 1.5 to 3 % from total responses.
I have also gave the APP gateway 3 instances which more than enough as it shows in the logs it's using maximum 2 to 3 capacity units during the peak time.

**To Reproduce**
No clear method to reproduce it.
My main question is if the APP gateway deployed with Agic limits traffic going to a pods or what is the reason of these 5xx responses. What I'm sure about that these errors are not coming back from application side.
**Ingress Controller details**
* here is the ingress values
* ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "azure/application-gateway"
    #appgw.ingress.kubernetes.io/connection-draining: "true"
    cert-manager.io/acme-challenge-type: "http01"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

**Comment by akshaysngupta** [comment]
@mazen423 In the access logs, do you see `serverStatus` as `500` ?

**Comment by mazen423** [comment]
@akshaysngupta yes I'm getting serverstatus 500. I also have tested the same environment with Http routing enabled and ignoring the APP gateway and i didn't get any 500 responses while doing the test. Same also with Nginx ingress without any errors
