### ISSUE TITLE
Manage certs in App Gateway in a Kubernetes Native way

### ISSUE THREAD

**Issue by seenu433** [Azure/application-gateway-kubernetes-ingress#1166]
Currently the cert management has to be done on the application gateway directly. Though this approach works, it would be convenient to be able to mange the certs related to ingress and backend CA in a Kubernetes native way by specifying a secret.

In scenarios like GitOps where all the manifests are persisted in Git, this feature will facilitate it.

Ability to sync the secrets mention under the spec  or a new annotation with watch on those objects for updates

spec:
  tls:
  - hosts:
      - https-example.foo.com
    secretName: testsecret-tls

**Comment by akshaysngupta** [comment]
Kubernetes `secrets` are already supported on AGIC. You can create a new secret and give the secret name under `secretName` field in Ingress.

**Comment by seenu433** [comment]
@akshaysngupta - Thanks for the oversight. Is there something similar to managed the backend root CA too
