### ISSUE TITLE
Unable to get specified ApplicationGateway

### ISSUE THREAD

**Issue by rnkhouse** [Azure/application-gateway-kubernetes-ingress#117]
Running Brownfield Deployment on existing Kubernetes cluster.

Getting below error in ingress pod:

>E0318 20:27:15.462952       1 main.go:83] unable to get specified ApplicationGateway [aks-dev-gateway], error=[azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/xxxx-xxxx-xxxx-xxxx/resourceGroups/aks-dev-gateway/providers/Microsoft.Network/applicationGateways/aks-dev-gateway?api-version=2018-06-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}]
I0318 20:27:15.463055       1 main.go:86] Retrying in 10s

**helm-config.yaml**

    appgw:
        subscriptionId: xxxx-xxxx-xxxx-xxxx
        resourceGroup: aks-dev-gateway
        name: aks-dev-gateway
    
    armAuth:
        type: aadPodIdentity
        identityResourceID: "/subscriptions/xxxx-xxxx-xxxx-xxxx/resourceGroups/MC_aks-dev_aks-dev_canadacentral/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-dev-identity"
        identityClientID:  aaaa-aaaa-aaaa-aaaa
    
    rbac:
        enabled: true
    
    aksClusterConfiguration:
        apiServerAddress: 172.31.1.10:443

An application gateway exists in the mentioned resource group. What am I missing?

**Comment by akshaysngupta** [comment]
Looking at the error, you missed the step to create the identity in the `MC_aks-dev_mts-aks-dev_canadacentral` resource group. Can you check this resource group to make sure the identity exists ?

**Comment by rnkhouse** [comment]
@akshaysngupta Yes. Identity exists.

**Comment by akshaysngupta** [comment]
Also, check your `identityClientID`. Make sure that it matches the `Client ID` of  `userAssignedIdentities/aks-dev-identity` on portal or use `az identity show -g MC_aks-dev_aks-dev_canadacentral -n aks-dev-identity`

**Comment by rnkhouse** [comment]
@akshaysngupta It's exactly the same. Again, it looks like the error is with app-gateway and not the identity.

**Comment by MarkDNL** [comment]
@akshaysngupta At one of our customers we are experiencing the same issue.

**Comment by asridharan** [comment]
@rnkhouse does the identity have contributor rights to the application gateway resource group?

**Comment by rnkhouse** [comment]
@asridharan It worked after I added contributor rights to Identity. I think it's good if it's part of helm config.

**Comment by asridharan** [comment]
@rnkhouse not sure what it means to add this to the helm config? This is an ARM configuration.

> @asridharan It worked after I added contributor rights to Identity. I think it's good if it's part of helm config.

**Comment by asridharan** [comment]
Closing this out, since the issue seem to be resolved and for brown field deployments we can't modify the identity from the helm config.
