### ISSUE TITLE
health-probe-path - wont work

### ISSUE THREAD

**Issue by dariuszbz** [Azure/application-gateway-kubernetes-ingress#1171]
I run ingress deployment (yaml file) with the following annotations:

    appgw.ingress.kubernetes.io/health-probe-hostname: "localhost"
    appgw.ingress.kubernetes.io/health-probe-port: "80"
    appgw.ingress.kubernetes.io/health-probe-path: "/robots.txt"

but after deployment the app gateway doesn't contain the value:  "/robots.txt".

I need to update app gateway manually from the azure portal. But the change is reverted once i delete the ingress-appgw pod.

**Comment by dariuszbz** [comment]
any help, please?

**Comment by dariuszbz** [comment]
knock knock

**Comment by akshaysngupta** [comment]
@dariuszbz These annotations are supported on version `1.4.0` of the ingress controller. If you are running image <1.4.0, then you can using by the [upgrade steps](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/how-tos/helm-upgrade.md).

**Comment by dariuszbz** [comment]
Thank You.
Let me put it that way: I didn't use helm :).
Any road map for the upgrade?

**Comment by dariuszbz** [comment]
Any timeline for new release?

**Comment by dariuszbz** [comment]
Hello. When can we get an update, please?

**Comment by akshaysngupta** [comment]
AGIC 1.4.0 rollout should start this coming week and reach all regions by EOW hopefully.

**Comment by dariuszbz** [comment]
Thank you.

**Comment by dariuszbz** [comment]
Hi. Any update about the rollout, please?

**Comment by sebhaub** [comment]
in the AKS release notes (https://github.com/Azure/AKS/releases/tag/20201-05-06) it is mentioned that agic 1.4.0 should be available already. Anyways, another quick try today (even with a freshly allocated AKS cluster in West Europe) was still deploying agic 1.2.1.
