### ISSUE TITLE
Windows not supported (documentation vs. Helm Chart)

### ISSUE THREAD

**Issue by morsik** [Azure/application-gateway-kubernetes-ingress#1176]
**Describe the bug**
I'm using [this](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress#install-ingress-controller-helm-chart) documentation to create AGIC. And it failed because I have Windows node in my cluster and pod from `agic-ingress-azure` started on Windows node.

**To Reproduce**
1. Create Kubernetes cluster with Windows node group
1. Deploy AGIC
1. Have bad luck so pod will be created on Windows node instead of Linux
1. You will see in `kubectl describe <agic-pod>`:
   ```
   Name:           agic-ingress-azure-bbd6c69c-vcxhl
   Node:           akswin000000/10.1.10.249
   ...
   Events:
     Type     Reason       Age                    From               Message
     ----     ------       ----                   ----               -------
     Normal   Scheduled    13m                    default-scheduler  Successfully assigned ingress-controller/agic-ingress-azure-b964f875-s5x5k to akswin000000
     Warning  FailedMount  6m44s (x3 over 11m)    kubelet            Unable to attach or mount volumes: unmounted volumes=[azure], unattached volumes=[azure agic-sa-ingress-azure-token-t5zv2]: timed out waiting for the condition
     Warning  FailedMount  2m15s (x2 over 4m30s)  kubelet            Unable to attach or mount volumes: unmounted volumes=[azure], unattached volumes=[agic-sa-ingress-azure-token-t5zv2 azure]: timed out waiting for the condition
     Warning  FailedMount  61s (x14 over 13m)     kubelet            MountVolume.SetUp failed for volume "azure" : hostPath type check failed: /etc/kubernetes/ is not a directory

   ```

Fun fact: it actually pulled image without any issue, so someone built Windows image for this software!

But Helm has Deployment configuration only for Linux hosts so it should contain:
```yaml
      nodeSelector:
        kubernetes.io/os: linux
```

**Comment by akshaysngupta** [comment]
This makes sense. We will add the annotation directly in the chart.
