### ISSUE TITLE
The change to the routing rule names has broken the rule ordering

### ISSUE THREAD

**Issue by robs** [Azure/application-gateway-kubernetes-ingress#1177]
**Describe the bug**
In this file:
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/pkg/appgw/requestroutingrules.go
Line 57

The sort is on the rule names which were changed to Guids/hashes fairly recently.

App Gateway selects routes based on their order in the list.

I did raise an issue #1159 about being able to set the priority but I think that's only an issue because of the naming change.

If the rules went back to having the path to match in the name then they'd get ordered by that, which would make the most specific rules highest in the list wouldn't it?

**Comment by akshaysngupta** [comment]
Rule priority is a more deterministic way of providing the ordering. How should this annotation look given an ingress can multiple rules.

**Comment by robs** [comment]
It looks like the main issue is that AGIC is still sorting the rules based on their name even though the names don't mean anything now.
The effect this has is that it's impossible to even do a hacky ordering by holding back a deployment to make it last in the list.

I guess you'd do the annotation the same as the SSL cert:
appgw.ingress.kubernetes.io/appgw-ssl-certificate: "wildcard-whatever"
appgw.ingress.kubernetes.io/appgw-rule-priority: 100

I know that's going to mean all rules for a given ingress will have the same priority but if they're all going to the same ingress it doesn't really matter does it?

**Comment by thisispaulsmith** [comment]
Is this why two ingress rules

*.sub.domain.com
service1.sub.domain.com

can't co-exist?

**Comment by robs** [comment]
@thisispaulsmith 

There is no workaround - we're going to have to switch to the nginx ingress which is a shame.

**Comment by thisispaulsmith** [comment]
> @thisispaulsmith
> 
> There is no workaround - we're going to have to switch to the nginx ingress which is a shame.

Which version were the names changed?

Not being able to route based on specificity is a pretty big ommision :-(

**Comment by robs** [comment]
Heh, looks like it was in the change to support wildcard hostnames in the first place, lots of info at the bottom of #962
