### ISSUE TITLE
Many anotations not working

### ISSUE THREAD

**Issue by Catskan** [Azure/application-gateway-kubernetes-ingress#1178]
**Describe the bug**
I'm trying to use many anotations "override-frontend-port" & "health-probe-status-codes" but it doesn't applied in AGIC.

It seems Kubernetes validate this option and is ok with that, but not applied.

**To Reproduce**
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/health-probe-status-codes: "200-399, 401"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: dev-ongsx-com

Added in the ingress.yml

**Ingress Controller details**
```
Name:             gizmo
Namespace:        aurelien
Address:          51.124.3.171
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host        Path  Backends
  ----        ----  --------
  *
              /api/v1/robotapp   service-gizmo:8080 (10.240.0.65:8080)
              /                  service-gizmo:80 (10.240.0.65:80)
Annotations:  appgw.ingress.kubernetes.io/appgw-ssl-certificate: dev-ongsx-com
              appgw.ingress.kubernetes.io/health-probe-status-codes: 200-399, 401
              kubernetes.io/ingress.class: azure/application-gateway
Events:       <none>
```

* Output of `kubectl logs <ingress controller>.  : I can't see the logs. Kubectl told me that Ingress is not a pod.

**Comment by akshaysngupta** [comment]
All these annotations are supported in `AGIC 1.4.0`.
AGIC 1.4.0 release will start next week.

**Comment by kekovski** [comment]
@akshaysngupta Where can we find the release dates of the version for AGIC?

Currently we are running on 1.2 on our cluster that uses AGIC through the Add-On.

**Comment by nitin-jci** [comment]
@akshaysngupta it's working.

**Comment by Catskan** [comment]
Thanks, it's working fine now.
