### ISSUE TITLE
"StorageProfiles" ManagedDisks ony creating standard HDD not SSD

### ISSUE THREAD

**Issue by danieniemand** [Azure/application-gateway-kubernetes-ingress#1180]
Hi,

In the template.json file that is used to create the deployment section for Microsoft.ContainerService/managedCluster in the agent pool section creates a standard HDD in the virtual machine nodes. Is there any way that this can be changed to also allow you to select SSD standard and premium? I'm using the "Standard Ds2_V2" size for the nodes?

            "type": "Microsoft.ContainerService/managedClusters",
            "name": "[variables('aksClusterName')]",
            "apiVersion": "2018-03-31",
            "location": "[resourceGroup().location]",
            "properties": {
                "kubernetesVersion": "[parameters('kubernetesVersion')]",
                "enableRBAC": "[parameters('aksEnableRBAC')]",
                "dnsPrefix": "[parameters('aksDnsPrefix')]",
                "agentPoolProfiles": [
                    {
                        "name": "agentpool",
                        "osDiskSizeGB": "[parameters('aksAgentOsDiskSizeGB')]",
                        "count": "[parameters('aksAgentCount')]",
                        "vmSize": "[parameters('aksAgentVMSize')]",
                        "osType": "Linux",
                        "storageProfile": "ManagedDisks",
                        "vnetSubnetID": "[variables('kubernetesSubnetId')]",
                        "dnsPrefix": "agents"
                    }
                ],
                "servicePrincipalProfile": {
                    "clientId": "[parameters('aksServicePrincipalAppId')]",
                    "secret": "[parameters('aksServicePrincipalClientSecret')]"
                },
                "networkProfile": {
                    "networkPlugin": "azure",
                    "serviceCidr": "[parameters('aksServiceCIDR')]",
                    "dnsServiceIP": "[parameters('aksDnsServiceIP')]",
                    "dockerBridgeCidr": "[parameters('aksDockerBridgeCIDR')]"
                }
            },
            "dependsOn": [
                "[concat('Microsoft.Network/virtualNetworks/', variables('vnetName'))]",
                "[concat('Microsoft.Resources/deployments/', 'RoleAssignmentDeploymentForKubenetesSp')]"
            ]
        }

**Comment by akshaysngupta** [comment]
@danieniemand please feel free to create a pull request providing this as a choice. 😄
