### ISSUE TITLE
Question: Azure Active Directory pod-managed identities (Preview) support

### ISSUE THREAD

**Issue by MarcelMichau** [Azure/application-gateway-kubernetes-ingress#1189]
**Is your feature request related to a problem? Please describe.**

More of a question than a feature request, but does AGIC (either Add-On or Helm) support integration with the new Azure Active Directory pod-managed identities in Azure Kubernetes Service (Preview) feature? 

https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity

**Describe the solution you'd like**

An example of how this scenario is configured if it's supported.

Thanks heaps!

**Comment by akshaysngupta** [comment]
For AGIC addon, AAD Pod identity should not be needed.

For AGIC helm, you should be able to use the AAD PI addon instead installing it through YAML. AGIC creates an `AzureIdentity` CRD which should be interpreted by both ways of deploying AAD PI.
