### ISSUE TITLE
Question: What's the right way to configure this with Log Analytics?

### ISSUE THREAD

**Issue by NeverOddOrEven** [Azure/application-gateway-kubernetes-ingress#1190]
I am running into a problem with my IaC scripts. 

It seems the AGIC assumes responsibility for provisioning Application Gateway, and deploys to the `MC_` resource group. All efforts to provision my AKS cluster with a pre-existing application gateway have failed -- it always provisions a new instance. I would like to provide my own Application Gateway so that I may declaratively configure the Diagnostic Settings from IaC scripts.

**Is it possible to provide an Application Gateway instance at creation time?**
If so, any snippets or gists you can share?

**If not, how do I configure the diagnostic settings for managed resources?** 
Annotations?

Any feedback or tips are appreciated. Thanks!

**Comment by akshaysngupta** [comment]
I assume that you are deploying using the `addon` since all examples that use helm start with an existing app gateway.
For the addon, you can use the `--appgw-id` parameter to specify an existing app gateway.

**Comment by NeverOddOrEven** [comment]
Oops, I actually meant to close this. I decided to retry from a clean slate and it worked. Classic pebkac.
