### ISSUE TITLE
E2E SSl with singed Certifcate not working as expected 

### ISSUE THREAD

**Issue by vinshetty** [Azure/application-gateway-kubernetes-ingress#1191]
**Describe the bug**
I followed the steps defined in this doc https://azure.github.io/application-gateway-kubernetes-ingress/tutorials/tutorial.e2e-ssl/ Only Change I made is I Used a signed Certificate for *frontend-tls* but its not working as expected 
**To Reproduce**
Follow the steps defined in this doc and use singed Certificate 
And Apply the below spec and see ingress logs 
apiVersion: v1
kind: Pod
metadata:
  name: aspnetapp
  labels:
    app: aspnetapp
spec:
  containers:
  - image: "mcr.microsoft.com/dotnet/core/samples:aspnetapp"
    name: aspnetapp-image
    ports:
    - containerPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: aspnetapp
spec:
  selector:
    app: aspnetapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aspnetapp
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/backend-protocol: "https"
    appgw.ingress.kubernetes.io/backend-hostname: "backend"
    appgw.ingress.kubernetes.io/appgw-trusted-root-certificate: "backend-tls"
spec:
  tls:
    - secretName: frontend-tls
      hosts:
        - vinshetty.com
  rules:
  - host: vinshetty.com
    http:
      paths:
      - path: /
        backend:
          serviceName: aspnetapp
          servicePort: 80

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
* Output of `kubectl logs <ingress controller>. E0527 04:23:19.230214       1 controller.go:141] network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayPortNotValidForProtocol" Message="Port 80 is not validfor protocol Https in backendHttpSettingsCollection /subscriptions/xxxxx/resourceGroups/rg-xxxxweeu/providers/Microsoft.Network/applicationGateways/agw-xxxx-01/backendHttpSettingsCollection/bp-prodsoap-aspnetapp-80-80-aspnetapp." Details=[]
* Any Azure support tickets associated with this issue. 2105140060001814

**Comment by akshaysngupta** [comment]
```
80 is not validfor protocol Https in backendHttpSettingsCollection /subscriptions/xxxxx/resourceGroups/rg-xxxxweeu/providers/Microsoft.Network/applicationGateways/agw-xxxx-01/backendHttpSettingsCollection/bp-prodsoap-aspnetapp-80-80-aspnetapp
```

`aspnetapp` will not work with the tutorial as it doesn't support HTTPS and runs on `80`.

Try using the nginx backend used in the sample.
