### ISSUE TITLE
InvalidTemplateDeployment

### ISSUE THREAD

**Issue by alurujawahar** [Azure/application-gateway-kubernetes-ingress#1193]
I have tried to deploy 'Hyperledger Fabric on Azure Kubernetes Service' I'm getting the below error from Template:

{"code":"InvalidTemplateDeployment","details":[{"code":"AgentPoolK8sVersionNotSupported","message":"Provisioning of resource(s) for container service fbtest-HLF-AKS in resource group Fabric-dealer failed. Message: {\n \"code\": \"AgentPoolK8sVersionNotSupported\",\n \"message\": \"Version 1.18.14 is not supported in this region. Please use [az aks get-versions] command to get the supported version list in this region. For more information, please check https://aka.ms/supported-version-list\"\n }. Details: "}],"message":"The template deployment 'microsoft-azure-blockchain.azure-blockchain-hyper-20210607103318' is not valid according to the validation procedure. The tracking id is 'd71e1e5b-53d4-46b9-a70a-b77eb7aa69ef'. See inner errors for details."}

![azure](https://user-images.githubusercontent.com/42169254/120966275-a2bef980-c783-11eb-842d-bcc0eabb1556.png)

The supporting versions are not provided on the Azure GUI. Please refer to the attachment.

**Comment by akshaysngupta** [comment]
@alurujawahar is this issue related to AGIC in anyway ?
