### ISSUE TITLE
Application Gateway PowerShell  New-AzApplicationGatewaySku module error for sku and tier WAF_v2

### ISSUE THREAD

**Issue by saswatmohanty01** [Azure/application-gateway-kubernetes-ingress#1194]
**Describe the bug**
Application gateway deployment using certificate ( .pfx) file and .cer file not working for sku  WAF_v2 and tier WAF_v2. Though it works for New-AzApplicationGatewaySku -Name WAF_Medium -Tier WAF -Capacity 2. 
**To Reproduce**
deploy new application gateway using PowerShell 
$sku = New-AzApplicationGatewaySku -Name WAF_v2 -Tier WAF_v2 -Capacity 2  
As per Microsoft document sku and tier can be WAF_v2 but it is not working when executing from PowerShell. https://docs.microsoft.com/en-us/powershell/module/az.network/new-azapplicationgatewaysku?view=azps-6.0.0

deployed region : East US

Error :  
does not support AuthenticationCertificates for the
     | selected SKU tier WAF_v2. Supported SKU tiers are Standard,WAF.
![image](https://user-images.githubusercontent.com/68620741/121097746-7d9dab80-c7c2-11eb-937d-2a6de14f42f0.png)

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
* Output of `kubectl logs <ingress controller>. 
* Any Azure support tickets associated with this issue.

**Comment by akshaysngupta** [comment]
Yes, V2 support `TrustedRootCertificates` instead of `AuthenticationCertificates`.
When using `TrustedRootCertificates`, specify the `root.crt` file which was used to sign the backend certificates. And also make sure to use the `backend-hostname` annotation to specify the subject name / host name of the backend.

**Comment by saswatmohanty01** [comment]
@akshaysngupta  Thanks for your response.  Do you have any example PowerShell or az -cli . I do not see this information in Microsoft documentation for Application Gateway.

**Comment by saswatmohanty01** [comment]
It is not required. We found the way to deploy.
