### ISSUE TITLE
Can't create multiple listeners for multiple hosts

### ISSUE THREAD

**Issue by beaverdevtools** [Azure/application-gateway-kubernetes-ingress#1200]
Hello,

I'm using Agic for AKS. It's working great on one host.
I created a second namespace with another application and decided to publish it through the app gateway. 

I used the same yaml file as my 1st app, changing host/service/namespace.
It worked but my 1st app was not available anymore and all traffic were redirected to my 2nd app.
How can I use my appgw to create 2 sets of backend/listener/rule and so on... ?

Here is my yaml file : 
`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: mynamespace
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: mycert
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/request-timeout: "180"
spec:
  rules:
  - host: my.host.com
  - http:
      paths:
      - path: /
        pathType: 
        backend:
          serviceName: myservice
          servicePort: myserviceport`

In the app gw configuration I can see that I have 2 backend pools, but no rules associated with my first app:
![image](https://user-images.githubusercontent.com/54035020/123436888-65ee6180-d5cf-11eb-9771-f64aacd3a888.png)

So I only have a set of 2 rules and 2 listeners (80 and 443 ports) 
![image](https://user-images.githubusercontent.com/54035020/123437037-88807a80-d5cf-11eb-9858-4593e2b07061.png)

But no hostname configured so no multisite capabilities : 
![image](https://user-images.githubusercontent.com/54035020/123437113-9fbf6800-d5cf-11eb-8a13-b9a176866217.png)

How can I resolve my issues ?
Best ,

**Comment by beaverdevtools** [comment]
Hello community,

I resolve my problem by manually create a new listener, modify the listener types to multi site , create a rule to bind backend to listener and then it works.

Is there a way to manage this configuration through K8S yaml files ?

Best,

**Comment by akshaysngupta** [comment]
@beaverdevtools can you share both Ingress YAMLs ?

**Comment by beaverdevtools** [comment]
Hello,

sure :

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress-A
  namespace: namespaceA
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: myWildcardCert
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/request-timeout: "180"
spec:
  rules:
  - host: hostA.mydomain.com
  - http:
      paths:
      - path: /
        pathType: 
        backend:
          serviceName: my-service
          servicePort: 8080
		  
----		  
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress-B
  namespace: namespaceB
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: myWildcardCert
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/request-timeout: "180"
spec:
  rules:
  - host: hostB.mydomain.com
  - http:
      paths:
      - path: /
        pathType: 
        backend:
          serviceName: my-service
          servicePort: 8080

**Comment by akshaysngupta** [comment]
remove `-` from in front on `http` from both ingress. `-` is making `host` and `http` to be evaluated as separate rules.

**Comment by beaverdevtools** [comment]
Alright! Thanks, I learned something! I'll give it 24h before closing the issue :) Thanks again!
