### ISSUE TITLE
 Code="ErrorMissingResourceGroup" - it's not a bug it is an aks feature

### ISSUE THREAD

**Issue by dariuszbz** [Azure/application-gateway-kubernetes-ingress#1202]
I have found below in logs from app gateway pod:
"
_1 azure.go:87] Code="ErrorMissingResourceGroup" Message="infrastructure resource group name: yyyy-xxx-rg-northeurope-nodes is expected to be of format MC_ResourceGroup_ResourceName_Location"
I0705 15:53:07.076352       1 configbuilder.go:256] Error while parsing cluster resource ID for tagging: Code="ErrorMissingResourceGroup" Message="infrastructure resource group name: yyyy-xxx-rg-northeurope-nodes is expected to be of format MC_ResourceGroup_ResourceName_Location"_
"

I deploy aks cluster and for the aks infrastructure resource group I use my own name convention. So it is not an error!
Az cli allows it by:
az aks create --node-resource-group yyyy-xxx-RG-NorthEurope-Nodes

Do not report that as an error. Instead, get the current aks infrastructure resource group from the aks cluster properties.

az aks show -n yyyy-xxx-northeurope -g  yyyy-xxx-rg-northeurope

and see:
"nodeResourceGroup": "yyyy-xxx-RG-NorthEurope-Nodes",

Thank You!

**Comment by jachin84** [comment]
I also encountered this one today and spent quite a lot of time digging into it. As far as I can see everything is working as expected to I am guessing the error isn't actually an error?

As mentioned above I have also changed the node pool resource group which is support via az cli, arm template, etc.

**Comment by akshaysngupta** [comment]
This error can be safely ignored. This will not impact functioning of AGIC.

Here AGIC trier to parse the node resource group and derive the cluster resource group. Couldn't find a better way back then. This information was used to tag the gateway with the cluster resource group.

Sorry for the confusion.

**Comment by craigforr** [comment]
@akshaysngupta: This is still an issue, and mislead us for significant amount of time when attempting to troubleshoot an AGIC issue.  Is there anyway it can be removed from the code if it is no longer necessary and/or "safely ignored"?

**Comment by diepes** [comment]
Also just got tripped up by this, glad to read, i can ignore the Error.
`
I0819 00:54:51.071754       1 azure.go:87] Code="ErrorMissingResourceGroup" Message="infrastructure resource group name: dev-aks-k8s-nodes is expected to be of format MC_ResourceGroup_ResourceName_Location"
I0819 00:54:51.071779       1 configbuilder.go:257] Error while parsing cluster resource ID for tagging:
...
...
`

**Comment by galvesribeiro** [comment]
2+ years later and I got bitten by this as well...

**Comment by mayur2281** [comment]
3+ years and still going strong. Faced this issue today via terraform deployment of aigc to existing application gateway

**Comment by petermajn** [comment]
+1

**Comment by amritpalnagrame** [comment]
It's totally misleading not just by message but by essence that error messages are to be ignored.

**Comment by p9139010** [comment]
+1

**Comment by justinmchase** [comment]
This is still blocking peoples deployments today, can you post the terraform solution?

**Comment by arpanD93** [comment]
+1

Still getting affected by this issue while enabling AGIC for AKS

**Comment by moiseitrosingh** [comment]
+1 fun
