### ISSUE TITLE
Azure Frontend Ip Configuration can not communicate with istio backend pool

### ISSUE THREAD

**Issue by cheklyn** [Azure/application-gateway-kubernetes-ingress#1208]
My project is on building an Integration between Azure App Gateway and Istio.

I have set up Istio in the Backend pool of Azure App Gateway with Listeners, and backend targets configured.

I had already set up the Frontend Ip Configuration and path based routing for Azure Application gateway.

The idea is this, if the Frontend Ip of Azure App Gateway is : 20.100.12.20. I want to browse a page 20.100.12.20/productpage where 20.100.12.20/productpage is from the Istio backend pool

VirtualService metadata: name: bookinfo spec: hosts:

20.84.35.146 gateways:
bookinfo-gateway http:
match:
uri: exact: /productpage

uri: prefix: /static

uri: exact: /login

uri: exact: /logout

uri: prefix: /api/v1/products route:

destination: host: productpage port: number: 9080

Please someone what am i missing. I need help

**Comment by forumsheth15** [comment]
I am facing the same issue...@cheklyn did you find any solution around it?
