### ISSUE TITLE
custom rewrite rules in ingress

### ISSUE THREAD

**Issue by Yiyito11** [Azure/application-gateway-kubernetes-ingress#1240]
**Describe the bug**
Rewrite rules gets erased by AGIC

**To Reproduce**

If user is **_not_** logged in app, then accessing link https://app.com/foo/bar.do  **_should take them_** to https://app.com/foo/service/ssosaml/ link.  (login page)

If user **_is already logged_** into : https://app.com/foo/bar.do , then accesing same link: https://app.com/foo/bar.do, **_should not take them_** again to:  https://app.com/foo/service/ssosaml/ link. 

This was achieve in Appgateway with some rules but were erased by AGIC automation. Is there a way to implement it using ingress rules?

* Any Azure support tickets associated with this issue:
TrackingID#2107290060002383

Thank you.

**Comment by yylai** [comment]
I believe this is addressed by Microsoft in https://github.com/Azure/application-gateway-kubernetes-ingress/issues/462. Personally, I am following that issue for updates from Microsoft.

Also, it seems couple of other similar issues raised 
https://github.com/Azure/application-gateway-kubernetes-ingress/issues/1066
