### ISSUE TITLE
Unable to assign an IP address to Gateway even though plenty should be available in the subnet

### ISSUE THREAD

**Issue by frachel** [Azure/application-gateway-kubernetes-ingress#1247]
After the Gateway is created we go and assign it a private IP address. We have a gateway subnet of size /27, so 32 IP's minus the 5 reserved by Azure leaves us with 27 usable IP's.

After the creation of the 1st gateway, it becomes a guessing game to find an IP that works for the subsequent ones. If the first gateway worked with a "x.x.x.3", if we try "x.x.x.4" for the next gateway it usually says that address is "being used or cleaned up". Then we try 5.. it may or may not work. We'll eventually find one, but it's a pain.

At this point we have 16 devices in the subnet (looking at the vnet/connected devices screen), and we can't add anymore gateways, even though we should have 9 IP's left.. I've tried every "free" address, but they all fail.

Are extra IP's being used behind the scenes by gateways (whether gateway's themselves or somethign with the AGIC service)?

**Comment by dewhurstwill** [comment]
App Gateway requires its own subnet. https://docs.microsoft.com/en-us/azure/application-gateway/configuration-infrastructure
