### ISSUE TITLE
I was just wondering the same thing.  I'm not sure if I want a single application gateway for my entire aks cluster.  At least, the way I'm reading it is that the agic can only take a single app gateway as an argument.  So it's a one to one mapping.

### ISSUE THREAD

**Issue by Rashee04** [Azure/application-gateway-kubernetes-ingress#1255]
I was just wondering the same thing.  I'm not sure if I want a single application gateway for my entire aks cluster.  At least, the way I'm reading it is that the agic can only take a single app gateway as an argument.  So it's a one to one mapping.

So if I have multiple applications in my cluster and I want them each to have separate application gateways, (Perhaps I want them separate for configuration reasons such as WAF rules or just separation of concerns.) how would I go about doing that?

Can I create multiple app-gateway-kub-ingress controllers that each attach to a different app gateway?  

It seems like it might be allowed based on this [page](https://docs.microsoft.com/bs-latn-ba/azure/application-gateway/ingress-controller-multiple-namespace-support), but it's not clearly spelled out.  It does say that caution would be needed to make sure multiple ingresses are not watching the same namespaces.

_Originally posted by @BarnumD in https://github.com/Azure/application-gateway-kubernetes-ingress/issues/831#issuecomment-621270594_

**Comment by fatpowaranga** [comment]
Unless I am misunderstanding current documentation, it is not possible to have multiple gateways per cluster. The docs page you linked references the fact that App gateway ingress controller can handle multiple namespaces, I believe at one point it could only monitor one namespace. But multiple gateways and/or multiple instances of AGIC in the same cluster is not currently supported from what I've seen.
