### ISSUE TITLE
Multi-cluster Shared app-gateway AGIC configuration missmatch

### ISSUE THREAD

**Issue by mmillard0** [Azure/application-gateway-kubernetes-ingress#1258]
**Describe the bug**
We are using one app-gateway for 3 AKS clusters. We have common namespaces on 2 clusters. Cluster 1 configuration overwrite cluster 3 configuration (we have the  same servicename, namespace, portnumber). We have setup AzureIngressProhibitedTarget on each cluster to avoid configuration overriding. How is it possible to have 1 App-gateway shared for 3 AKS clusters (with same serviceName, namespaces and portNumber but different hostname) ?

**To Reproduce**
Create one app-gateway shared for 3 AKS clusters.
Install AGIC on each clusters.
Deploy same services and deployment on each clusters (lab, dev-tst and acc). Services have same name, namespaces and port number. Hostname differs domain-lab.com, domain-dev-tst, domain-acc.com).
Add AzureIngressProhibitedTarget on each cluster to avoid configuration missmatch.
Create Ingress resources on each cluster.
App-gateway configuration is overwritten. 

**Ingress Controller details**
kubernetes-ingress:1.4.0

**App-gateway details**
HTTP settings are composed of bp-{namespace}-{service name}-port-port-{ingress name}
namespaces, service name, ingress name are identical on each cluster.

If I use a different namespace for my lab cluster, everything works fine. Is this the only way to solve my issue ?

**Comment by ansmcimerma** [comment]
even with unique `appgw.subResourceNamePrefix` defined, the backend pools still get destroyed. the prefix is visible in the name of the pool though!
