### ISSUE TITLE
Use Application Gateway multiple site hosting to reduce listeners created by AGIC

### ISSUE THREAD

**Issue by arodriguezdlc** [Azure/application-gateway-kubernetes-ingress#1263]
**Is your feature request related to a problem? Please describe.**
We are using AGIC and application gateway in a multitenant platform solution that provides access to the same backend from different DNS names. For example api.tenant1.example.com and api.tenant2.example.com. 

AGIC supports this by creating a Listener, a Backend HTTP setting and an HTTP load balancing rule per ingress entry, although the backend is exactly the same. The problem here is the limit of these resources that can be created on a single application gateway, that is 100, or 40 if WAF is enabled (See [Application Gateway limits](https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/application-gateway-limits.md)). This is a very low number of ingress for our use case. 

**Describe the solution you'd like**
To increase this limit, a possible solution is to use the multiple site hosting feature of Application gateway, so using the same listener we could create until 5 ingresses that share the same configuration (same backend for example). This behavior could be implemented in the case that an ingress resource defines various rules with the same backend configuration.

Potentially, we could multiply by 5 the number of ingress (and tenants) that our platform could support, saving a lot of costs and making the use of Application Gateway viable for us. 

I could achieve the development of this feature by making a Pull Request, but I would like to know if you think this could be an interesting feature for the project. Thanks!

**Comment by akshaysngupta** [comment]
@arodriguezdlc AppGW supports wildcard hostnames. You can try using a hostname like `api.*.example.com`

https://docs.microsoft.com/en-us/azure/application-gateway/multiple-site-overview#conditions-for-using-wildcard-characters-and-multiple-host-names-in-a-listener

**Comment by arodriguezdlc** [comment]
@akshaysngupta Thanks for your response, but Kubernetes ingress doesn't support wildcards that are not prefix: https://github.com/kubernetes/kubernetes/issues/41881. So is not valid for AGIC...

**Comment by akshaysngupta** [comment]
You can try using following annotation (not documented yet). It can take up-to 5 hostnames (wildcard or exact)
```
appgw.ingress.kubernetes.io/hostname-extension : "hostname1, hostname2"
```

**Comment by arodriguezdlc** [comment]
Thank you @akshaysngupta, this is exactly the feature I was asking for. I would be easier if it is documented 😛
