### ISSUE TITLE
Authorization Repeatedly following full cluster startup

### ISSUE THREAD

**Issue by dan-jackson-github** [Azure/application-gateway-kubernetes-ingress#127]
**Describe the bug**
Our cluster stops and starts each day to save costs (7 node AKS cluster) on development and test systems. Some mornings the ingress control plane reports the following error in its logs following startup

ERROR: logging before flag.Parse: E0416 07:25:37.548159       1 main.go:83] unable to get specified ApplicationGateway [******-devtest-az-app-gateway], error=[network.ApplicationGatewaysClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '*******************************' with object id '************************************' does not have authorization to perform action 'Microsoft.Network/applicationGateways/read' over scope '/subscriptions/******************************************/resourceGroups/******-devtest-az-app-gateway-rg/providers/Microsoft.Network/applicationGateways/******-devtest-az-app-gateway'."]

The problem is rectified by restarting the ingress pod. Our setup uses Managed Service Identities and aad-pod-identity to authenticate with the application gateway. Following deletion and re-creation of the pod, the following is reported (there is an initial error, but the retry succeeds):

ERROR: logging before flag.Parse: I0416 07:30:45.872106       1 main.go:60] Creating authorizer from MSI
ERROR: logging before flag.Parse: E0416 07:30:46.184145       1 main.go:83] unable to get specified ApplicationGateway ******-devtest-az-app-gateway], error=[azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/****************************************/resourceGroups/******-devtest-az-app-gateway-rg/providers/Microsoft.Network/applicationGateways/******-devtest-az-app-gateway?api-version=2018-12-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}
]
ERROR: logging before flag.Parse: I0416 07:30:46.184167       1 main.go:86] Retrying in 10s
ERROR: logging before flag.Parse: I0416 07:30:57.868035       1 context.go:287] k8s context run started
ERROR: logging before flag.Parse: I0416 07:30:57.868101       1 context.go:374] start waiting for initial cache sync

**To Reproduce**
Full shutdown and startup of the AKS cluster nodes. The issue occurs after startup.

**Ingress Controller details**
Log entries are posted above 
Pod Describe :

Name:               devtest-ingress-azure-*********-*********
Namespace:          ingress
Priority:           0
PriorityClassName:  <none>
Node:               aks-devtestap-47004632-7/10.0.2.47
Start Time:         Tue, 16 Apr 2019 08:30:31 +0100
Labels:             aadpodidbinding=*********-ingress-azure
                    app=ingress-azure
                    pod-template-hash=5c568444dd
                    release=devtest
Annotations:        kubernetes.io/limit-ranger:
                      LimitRanger plugin set: cpu, memory request for container ingress-azure; cpu, memory limit for container ingress-azure
Status:             Running
IP:                 10.0.2.51
Controlled By:      ReplicaSet/devtest-ingress-azure-5c568444dd
Containers:
  ingress-azure:
    Container ID:   *******
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.3.0
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:c110f441f81fc53060d4a88367ca9430c681e9a513cc978d55bed8c9025e9121
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 16 Apr 2019 08:30:45 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  128Mi
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment Variables from:
      devtest-cm-ingress-azure  ConfigMap  Optional: false
    Environment:
      KUBERNETES_PORT_443_TCP_ADDR:  *********.hcp.ukwest.azmk8s.io
      KUBERNETES_PORT:               tcp://*********.hcp.ukwest.azmk8s.io:443
      KUBERNETES_PORT_443_TCP:       tcp://*********.hcp.ukwest.azmk8s.io:443
      KUBERNETES_SERVICE_HOST:       *********.hcp.ukwest.azmk8s.io
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from ********* (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  devtest-sa-ingress-azure-token-*********:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  devtest-sa-ingress-azure-token-*********
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age    From                               Message
  ----    ------     ----   ----                               -------
  Normal  Scheduled  6m38s  default-scheduler                  Successfully assigned ingress/devtest-ingress-azure-*********-********* to aks-devtestap-*********-*********
  Normal  Pulling    6m36s  kubelet, aks-devtestap-*********-*********  pulling image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.3.0"
  Normal  Pulled     6m32s  kubelet, aks-devtestap-*********-7  Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.3.0"
  Normal  Created    6m24s  kubelet, aks-devtestap-*********-7  Created container
  Normal  Started    6m24s  kubelet, aks-devtestap-*********-7  Started container

**Comment by asridharan** [comment]
@dan-jackson-github does the issue keep occuring after startup? My initial guess is there is a race condition between the aad-pod-identity and ingress-controller pods coming up. 

We do have checks in our code to keep waiting for the authorizer to come up, but there could be a bug in this code:
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/cmd/appgw-ingress/main.go#L77

**Comment by dan-jackson-github** [comment]
Hi @asridharan, the issue is consistently occurring every morning straight after node startup

**Comment by akshaysngupta** [comment]
@dan-jackson-github Is the issue still happening ?

**Comment by delqn** [comment]
@dan-jackson-github I believe we have root cause for this issue, which as @asridharan said is most likely a delay in the AAD Pod Identity module.  We did indeed find a bug in the [retry mechanism](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/dfce74a2549f91fd911273ecf8abd64249bd63d7/cmd/appgw-ingress/main.go#L204-L242) and fixed it.

The latest version of AGIC is 0.8.0.  Please upgrade your Ingress Controller and do report back!
