### ISSUE TITLE
Override frontend port doesn't work for https

### ISSUE THREAD

**Issue by micgruber** [Azure/application-gateway-kubernetes-ingress#1281]
**Describe the bug**
I use a application gateway with a public and private ip. I want to make services available for both ips. Now I read about the following limitation in the docs:

> Note 1) App Gateway doesn't support multiple IPs on the same port (example: 80/443). Ingress with annotation appgw.ingress.kubernetes.io/use-private-ip: "false" and another with appgw.ingress.kubernetes.io/use-private-ip: "true" on HTTP will cause AGIC to fail in updating the App Gateway. 2) For App Gateway that doesn't have a private IP, Ingresses with appgw.ingress.kubernetes.io/use-private-ip: "true" will be ignored. This will reflected in the controller logs and ingress events for those ingresses with NoPrivateIP warning.

https://azure.github.io/application-gateway-kubernetes-ingress/annotations/#use-private-ip

Therefore I tried to override the port for the private ip with the annotation: appgw.ingress.kubernetes.io/override-frontend-port: "8080". The override works but creates only a http listener and no https listener. When I remove the port annotation the a http/https listener will be created. Is there a bug in the current implementation or is this by design?

I use the helm application-gateway-kubernetes-ingress/ingress-azure in version 1.4.0.

**To Reproduce**

This is the yaml file which I used:

apiVersion: v1
kind: Pod
metadata:
  name: aspnetapp11
  labels:
    app: aspnetapp11
spec:
  containers:
    - image: "mcr.microsoft.com/dotnet/core/samples:aspnetapp"
      name: aspnetapp11-image
      ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: aspnetapp11
spec:
  selector:
    app: aspnetapp11
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---              
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aspnetapp11
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: letsencrypt-staging
    cert-manager.io/acme-challenge-type: dns01
    cert-manager.io/tls-acme: "true"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/override-frontend-port: "8080"
    appgw.ingress.kubernetes.io/use-private-ip: "true"
spec:
  tls:
    - hosts:
      - dev.test.company.com
      secretName: aspnetapp11-cert
  rules:
  - host: dev.test.company.com
    http:
      paths:
      - path: /
        backend:
          serviceName: aspnetapp11
          servicePort: 80

**Comment by akshaysngupta** [comment]
@micgruber Thanks for reporting!

I was able to reproduce the bug with your YAMLs. AGIC generates incorrect config when using `appgw.ingress.kubernetes.io/ssl-redirect: "true"` along with override frontend port. If you remove the annotation, port 8080 is created correctly on HTTPS.

**Comment by micgruber** [comment]
@akshaysngupta thanks for the quick reply. With the bug fix it will also possible to provide a ssl redirect?

**Comment by akshaysngupta** [comment]
like 80 -> 8080 ?

**Comment by prash6dtech** [comment]
HI Azure team,

We have a query regarding the Azure Api gateway ingress .
If we are not using this flag **appgw.ingress.kubernetes.io/ssl-redirect: "true"** for https ingress with port-overriding.
Ingress is working, if we use the flag , it is not working.
Our query is, once you fix the bug, If we donot specify the flag 'appgw.ingress.kubernetes.io/ssl-redirect: "false" ',
Will it affect our production workflow ??
please confirm.

**Comment by prash6dtech** [comment]
HI @akshaysngupta,

We have a query regarding the Azure Api gateway ingress .
If we are not using this flag appgw.ingress.kubernetes.io/ssl-redirect: "true" for https ingress with port-overriding.
Ingress is working fine for us, 
**If we use the flag , it is not working**.

Our query is, once you fix the bug, If we don't specify the flag 'appgw.ingress.kubernetes.io/ssl-redirect: "true" ',
Will it affect our currently running production workloads??
Also please confirm when will be the bug fixed?
