### ISSUE TITLE
AzureAssignedIdentity not found

### ISSUE THREAD

**Issue by g0pinath** [Azure/application-gateway-kubernetes-ingress#129]
**Describe the bug**
This worked well the first time(http and https) but after I tried to add URIs using / format using 
 - host: azk8.site
    http:
      paths:
      - path: /
        backend:
          serviceName: simple-web-pod-service
          servicePort: 80
it broke, and it responds via IP but not via hostname.
 RG -- RG-TRG01-LAB01-GOPI
subscription id -- 79af804c-1b4f-4d83-975f-5ebbeaf2c422

**To Reproduce**
Try to set the URI method -- I am hoping that I must have broken this, I will start from the beginning and confirm the behaviour. Since appgw takes eons to update settings, I am wondering if applying the yaml files multiple times in a short time frame has messed this. Unless this works flawlessly like NGinx, I dont think customers will be confident to use this service. I must say that this much better than using layer 4 LB, but the APpGw slowness, like restarts taking 15 minutes etc is really the downsides

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
Name:               wandering-magpie-ingress-azure-5dfc74f4d-m2jkq
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               aks-agentpool-35064155-0/10.0.0.4
Start Time:         Fri, 19 Apr 2019 20:21:19 -0400
Labels:             aadpodidbinding=wandering-magpie-ingress-azure
                    app=ingress-azure
                    pod-template-hash=5dfc74f4d
                    release=wandering-magpie
Annotations:        <none>
Status:             Running
IP:                 10.0.0.15
Controlled By:      ReplicaSet/wandering-magpie-ingress-azure-5dfc74f4d
Containers:
  ingress-azure:
    Container ID:   docker://bcbbcc4ed967301cf8c768b5754bb492f5976b00b9a3d1d7618310cda80daded
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.3.0
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:c110f441f81fc53060d4a88367ca9430c681e9a513cc978d55bed8c9025e9121
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Fri, 19 Apr 2019 20:21:23 -0400
    Ready:          True
    Restart Count:  0
    Environment Variables from:
      wandering-magpie-cm-ingress-azure  ConfigMap  Optional: false
    Environment:
      KUBERNETES_PORT_443_TCP_ADDR:  aks-e7e482a9.hcp.eastus.azmk8s.io
      KUBERNETES_PORT:               tcp://aks-e7e482a9.hcp.eastus.azmk8s.io:443
      KUBERNETES_PORT_443_TCP:       tcp://aks-e7e482a9.hcp.eastus.azmk8s.io:443
      KUBERNETES_SERVICE_HOST:       aks-e7e482a9.hcp.eastus.azmk8s.io
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from wandering-magpie-sa-ingress-azure-token-vpfz9 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  wandering-magpie-sa-ingress-azure-token-vpfz9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  wandering-magpie-sa-ingress-azure-token-vpfz9
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                               Message
  ----    ------     ----  ----                               -------
  Normal  Scheduled  2m    default-scheduler                  Successfully assigned default/wandering-magpie-ingress-azure-5dfc74f4d-m2jkq to aks-agentpool-35064155-0
  Normal  Pulling    2m    kubelet, aks-agentpool-35064155-0  pulling image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.3.0"
  Normal  Pulled     2m    kubelet, aks-agentpool-35064155-0  Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.3.0"
  Normal  Created    2m    kubelet, aks-agentpool-35064155-0  Created container
  Normal  Started    2m    kubelet, aks-agentpool-35064155-0  Started container
* Output of `kubectl logs <ingress controller>. 
ERROR: logging before flag.Parse: I0420 00:22:45.015670       1 main.go:86] Retrying in 10s
ERROR: logging before flag.Parse: E0420 00:22:55.037566       1 main.go:83] unable to get specified ApplicationGateway [applicationgatewayffa8], error=[azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/79af804c-1b4f-4d83-975f-5ebbeaf2c422/resourceGroups/RG-TRG01-LAB01-GOPI/providers/Microsoft.Network/applicationGateways/applicationgatewayffa8?api-version=2018-12-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: no AzureAssignedIdentity found for pod:default/wandering-magpie-ingress-azure-5dfc74f4d-m2jkq
]
ERROR: logging before flag.Parse: I0420 00:22:55.037586       1 main.go:86] Retrying in 10s
ERROR: logging before flag.Parse: E0420 00:23:05.049957       1 main.go:83] unable to get specified ApplicationGateway [applicationgatewayffa8], error=[azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/79af804c-1b4f-4d83-975f-5ebbeaf2c422/resourceGroups/RG-TRG01-LAB01-GOPI/providers/Microsoft.Network/applicationGateways/applicationgatewayffa8?api-version=2018-12-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: no AzureAssignedIdentity found for pod:default/wandering-magpie-ingress-azure-5dfc74f4d-m2jkq
]
ERROR: logging before flag.Parse: I0420 00:23:05.049977       1 main.go:86] Retrying in 10s
* Any Azure support tickets associated with this issue.

**Comment by g0pinath** [comment]
This worked on the second try, I put the IDs incorrectly. Couple of challenges while trying to deploy this from Azure Devops pipeline, helm repo isnt available in the pipeline tasks but I can work around this by putting the commands inside a cli or ps task.

This is good work by MS and I wish this is listed in the AKS documentation(https://docs.microsoft.com/en-us/azure/aks/), this option of Ingress controller using AppGW isnt even available in AKS section but is present in some other section.
Also, similar to AWS AKS  MS could name this to something fancy.

I wasnt even aware that MS had this offering similar to AWS AKS until I read about this in some forum so putting this in https://docs.microsoft.com/en-us/azure/aks/ would certainly help.

THanks
Gopinath T

**Comment by asridharan** [comment]
@g0pinath  thanks for your comments. Currently the ingress controller is in preview and we are getting a feel of how this integration is progressing. We are working towards GA in the next few months as we add more resources to this project. Due its preview nature its not highlighted in all the AKS and AG websites.

That said have informed the product groups of this lapse and they are looking at ways to better highlight ingress controller in the Application Gateway and AKS documentation. As we add more features and move towards GA, hopefully we will be able to fix these issues and make the project a lot more visible and accessible.

Thanks again for trying it out. Please keep the issues coming, and we will try to make the experience better based on your feedback.
