### ISSUE TITLE
apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+;

### ISSUE THREAD

**Issue by CrazyTuna** [Azure/application-gateway-kubernetes-ingress#1292]
**Describe the bug**
I'm currently using application-gateway-kubernetes-ingress (AGKI) v1.40. I've just updated to AKS version 1.21.2 and seeing this warning:
apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+;

I've also created a fresh aks cluster using 1.22.2 and wasn't able to install AGKI on it.

**To Reproduce**
Create a cluster with AKS v.1.21.2 and install AGKI v1.4.0 => warning
Create a cluster with AKS v.1.22.2 and try to install AGKI v1.4.0 => error

**Comment by vladmm** [comment]
https://github.com/Azure/application-gateway-kubernetes-ingress/pull/1253

Looks like there's already a PR open for this for some time. 
I wander what's taking so long, this is a blocker for v1.22+

**Comment by CJJ69** [comment]
**Do not do this!**

I've just upgraded an existing AKS cluster to version 1.22.2 (very foolish)
now AGIC is broken; adding an Ingress does nothing. Listeners, rules etc. are no longer created in App GW

I can see that AGIC has upgraded, it was 1.4:
mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.5.0-rc1                 app=ingress-appgw


I have tried many things...

  annotations:
    # deprecated as of 1.22
    #kubernetes.io/ingress.class: azure/application-gateway

changed	Ingress to add spec.ingressClassName

spec:
  ingressClassName: azure-application-gateway



 fixing the yaml (removed beta.)

nodeSelector:
    ~~beta.~~kubernetes.io/os:
	


And on discovering this error message: ingresses.networking.k8s.io is forbidden: cannot list resource "ingresses" in API group "networking.k8s.io" at the cluster scope.

I found that networking.k8s.io is missing from ClusterRole!

  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses

**Comment by akshaysngupta** [comment]
@CJJ69 Thank for sharing! Will straight away get to fixing this.

**Comment by sunmsieben** [comment]
Any update on this? I've updated our Pre-Prod clusters to 1.22 and had adjust AGIC to use 1.5.0rc1 to make this work.
But for now we're waiting to roll out the new version until this is solved.

**Comment by Lord-RedShirt** [comment]
Hi @akshaysngupta. Has this this issue been resolved or targeted to a release?
