### ISSUE TITLE
Change namespace of agic installation

### ISSUE THREAD

**Issue by assaf-grth** [Azure/application-gateway-kubernetes-ingress#1298]
**Is your feature request related to a problem? Please describe.**
I need to change the namespace where the pods are running from default to a more dedicated namespace

**Describe the solution you'd like**
Is there a procedure describing how such activity should be done without affecting existing ingresses?

**Comment by spr0ut** [comment]
Simple enough - specify the namespace and --create-namespace option with helm install, e.g. 
`helm install -n ingress agw-ingress <helm-config> application-gateway-kubernetes-ingress/ingress-azure  --create-namespace`

**Comment by assaf-grth** [comment]
Isn't this relevant for new installations?
How about existing installations?
