### ISSUE TITLE
Add egress traffic support with static public IP

### ISSUE THREAD

**Issue by g0pinath** [Azure/application-gateway-kubernetes-ingress#130]
**Is your feature request related to a problem? Please describe.**
Per this article https://docs.microsoft.com/en-us/azure/aks/egress the outbound Public IP of the cluster can be defined with a static PIP and Azure load balancer. I have a cluster that is exposed via app gw and it is accessing via https endpoint. I dont have any AKS service of type load balancer and following the artice https://docs.microsoft.com/en-us/azure/aks/egress should bind AKS outbound traffic to the PIP I created. Based on the documentation AKS service of type load balancer is mandatory for this feature to work.

**Describe the solution you'd like**
after apply the steps in https://docs.microsoft.com/en-us/azure/aks/egress, the outbound IP should refer the static PIP with AppGW ingress controller and without any AKS service of type loadbalancer.

**Comment by asridharan** [comment]
@g0pinath do you want all traffic egressing out of AKS, not necessarily responses going to AG, to have the same PIP as the public IP of the Application Gateway? I am not sure if that is possible. Reason being that there is a layer 4 load-balancer sitting in front of AKS and AG, and these could be different. Hence, the VIPs associated with these load-balancers would be different as well.

Could you clarify your question a bit based on my comments above?

**Comment by g0pinath** [comment]
Hi Asridharan

Let us take 2 examples, aks-webtier that is exposed to the internet and having 50+ urls, with AppGW having 50 rules and then translating them into AKS ingress controller, I just need to define the URL mapping in the AKS service file and all the magic happens behind the scenes.  The response from this cluster to a partner can be bound to a specific PIP is my understanding as per https://docs.microsoft.com/en-us/azure/aks/egress However, for this to happen it seems that I need to expose those services via layer 4 LB. For example, consider an integration where there is a website running called partnerout.conso.com that calls a bank via URL, the bank needs to know the source IP to whitelist it. In this scenario I just need to have aks lb service type and assign it a public IP, all the traffic leaving this cluster will have this PIP - is this correct?

Second scenario is aks-midtier, which I wouldnt expose anything to internet and have an internal APPGW, if I want to talk to on premise then what are my options. Today Azure ASE V2 has a specific static outbound IP assigned although we use PAAS websties. Another option is to integrate this VNET with on premise network via a site to site VPN ??.

**Comment by asridharan** [comment]
@

> Hi Asridharan
> 
> Let us take 2 examples, aks-webtier that is exposed to the internet and having 50+ urls, with AppGW having 50 rules and then translating them into AKS ingress controller, I just need to define the URL mapping in the AKS service file and all the magic happens behind the scenes. The response from this cluster to a partner can be bound to a specific PIP is my understanding as per https://docs.microsoft.com/en-us/azure/aks/egress However, for this to happen it seems that I need to expose those services via layer 4 LB. For example, consider an integration where there is a website running called partnerout.conso.com that calls a bank via URL, the bank needs to know the source IP to whitelist it. In this scenario I just need to have aks lb service type and assign it a public IP, all the traffic leaving this cluster will have this PIP - is this correct?
> 
> Second scenario is aks-midtier, which I wouldnt expose anything to internet and have an internal APPGW, if I want to talk to on premise then what are my options. Today Azure ASE V2 has a specific static outbound IP assigned although we use PAAS websties. Another option is to integrate this VNET with on premise network via a site to site VPN ??.

@g0pinath  for the first scenario (`aks-webtier`) won't all responses go through AG? In which case the PIP in the responses would the AG PIP.

For scenario 2 (`aks-midtier`) you can connect your Azure virtual network to your on-prem using Azure VPN or Azure ER. You would still front all your traffic using AG which works with Azure ER and Azure VPN.

**Comment by xxthegonzxx** [comment]
@g0pinath Did you ever get this resolved? I also need an Egress Static IP setup for a few of my K8's services.

**Comment by g0pinath-metricon** [comment]
Avinash

This is quite old and I cant seem to remember the exact requirement at the time I posted this. At a high level, the VMs in Azure behind a public LB will use that LB's PIP for outbound internet connections and the same concept is extended for AKS nodes.

So the question is an AKS that is not exposed to internet(not behind public LB), can it send out traffic to a partner on a static public IP. So an AKS cluster that is not behind a public LB, if it hosts a pod that sends a POST to say bofa.com what is the Public IP as seen by BOFA - can this be made static? 
One way would be, say the BOFA's endpoint is gatewayinfromcontoso.bofa.com, if we host the DNS record for this record and point to APPGW, and let APPGW send the traffic to the actual BOFA, then we can dictate the public IP "seen" by bofa - is there another way to do this.

Thanks
Gopinath T

**Comment by xxthegonzxx** [comment]
@g0pinath-metricon If I understand @asridharan correctly, If you're using AGIC (Application Gateway Ingress Controller) that has an attached Static Public IP, the Ingress and Egress IP will not be the same. I have validated this by checking the IP from within one of my Pods on the K8's cluster and got back a Microsoft based IP address. I have seen some suggest that setting up a NAT gateway for egress of traffic seems to work but have not found any good documentation if this will work anywhere.
