### ISSUE TITLE
Support CRD's in K8s 1.22+

### ISSUE THREAD

**Issue by rjminchuk** [Azure/application-gateway-kubernetes-ingress#1302]
CRD's no longer in beta1 as of 1.22+
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122

feature flag crd azureingressprohibitedtargets.appgw.ingress.k8s.io to use `apiextensions.k8s.io/v1` when k8s >= version 1.22

**Comment by dwenpark** [comment]
And Please update helm chart, too.
(Latest chart version : 1.4.0)

![스크린샷 2022-01-14 오후 12 19 31](https://user-images.githubusercontent.com/80210205/149445910-787f8ace-f3c3-404b-9025-f6acc78b157a.png)

**Comment by WitoldSlawko** [comment]
Hello.

As @rjminchuk & @dwenpark said, this is still and issue... Here I tried with terraform `helm_release` resource, yet same outcome 
![image](https://user-images.githubusercontent.com/20817587/173428454-42a2bfb9-1900-4b9d-a88b-a754292abe61.png)

can you please corect this in release `1.5.0` ?
