### ISSUE TITLE
ETA for 1.5.0 (k8s 1.22 already released by AKS)

### ISSUE THREAD

**Issue by arodriguezdlc** [Azure/application-gateway-kubernetes-ingress#1317]
Hello, k8s 1.22 is already officially released, so is mandatory to have the 1.5.0 of AGIC to work with ingress v1 API. Is there any ETA to have this release? Thank you.

**Comment by ferronsw** [comment]
I submitted a support request for this problem in November. Microsoft said AGIC 1.5.0 would be released prior to 1.22 GA. That's not what happened, so I just send a mail to the person in question again.

**Comment by cmendible** [comment]
Hi Team,

any news on this one? k8s 1.22 is already in the wild and we need the 1.5.0 released.

Thank in advance.

**Comment by davidkarlsen** [comment]
What is the link between 1.22 and the 1.5.0 controller? Is it a must or a nice-to-have?

**Comment by ferronsw** [comment]
Must have. You can't upgrade to 1.22 without.

**Comment by cwiederspan** [comment]
There is a 1.5.0-rc1 that you can use, but that's definitely not ideal. This is what AKS uses if you use the AGIC add-on when creating a cluster of 1.22+.

**Comment by chreichert** [comment]
@cwiederspan This does not help, if you are not using the add-on, but installed AGIC via Helm. It is simply not understandable, why nothing happens to this project anymore. AKS 1.22 is released and depends on AGIC release, but AGIC release is still pending.

**Comment by chreichert** [comment]
I am not willing to use a RC version in Production,  especially when it has known bugs: #1318 for example.

**Comment by cwiederspan** [comment]
I'm in total agreement - I'm a consumer of AGIC and stuck in the same limbo as you. Would love to hear from the AGIC team what's going on with the new release train.

**Comment by arodriguezdlc** [comment]
The unbelievable thing is that a GA release of AKS is using a release candidate (but officially supported) addon. What kind of guarantee is that? If you have problems in production they will say that AGIC is not ready for production use? In its GA service?

**Comment by mscatyao** [comment]
1.5.0 has now been released: https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/1.5.0 which should resolve issues with k8s 1.22+. Closing thread as the release is now out.
