### ISSUE TITLE
AGIC-1.5.0 rc1 - Rewrite rules still being removed even after annotations for rewrite rules are in place 

### ISSUE THREAD

**Issue by m-matharu** [Azure/application-gateway-kubernetes-ingress#1327]
Hi Team, 

Rewrite rules should work now with the required annotations as per the below link - 
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/annotations.md#rewrite-rule-set

After upgrading AGIC to 1.5.0 rc1 and latest version of AKS, the rewrite rules are still getting disabled when a pod crashes / deployment is scaled etc. 

Some application need to have port information removed and the only way is to use rewrite rules.  This is a show stopper as it is delaying rollout of a critical application in production.  Any help to resolve the issue will be highly appreciated. 

Thanks, 
Mandeep

**Comment by m-matharu** [comment]
Strange enough, here's MS support response for the issue - 
_"I reached out to our engineering group to get clarification on the rewrite ruleset annotation feature. Apparently, it was not incorporated into AGIC release 1.5.0rc1 as documented, but will be in a later release. At this point, I don't have a timeline on when that will happen. ."_

**Comment by sgerace** [comment]
This is a high-priority issue for us as well. We are in the process of migrating from our current Azure infrastructure to one  based on AKS, and the rewrite rules are a part of the security profile.
