### ISSUE TITLE
AGIC doesn't support path prefix based wildcard routing. 

### ISSUE THREAD

**Issue by karyatech-github** [Azure/application-gateway-kubernetes-ingress#1335]
**Describe the bug**
We are porting a NGINX ingress definition to APPGW and found the wildcard routing not supported that even with the path prefix annotation. 

**To Reproduce**
(1) This below is the yaml.  
(2) when I deploy, both prefix - v1.sample.net/backend and v1.sample.net/index.html gives 502. this perfectly works in NGINX
(application gateway specific YAML) 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  tls:
    - hosts:
      - v1.sample.net
      secretName: letsencrypt-ca
  rules:
  - host: v1.sample.net
    http:
      paths:
      - path: /backend/(.*) 
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 80
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80

(old NGINX based YAML) 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - xxx
      secretName: letsencrypt-ca
  rules:
  - host: xxxx
    http:
      paths:
      - path: /backend/(.*) 
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 80
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80

**Comment by akshaysngupta** [comment]
Try using `/*` instead of `/(*)`.

Application Gateway only supports simple wildcard paths.
