### ISSUE TITLE
1.22 clusters uses the 1.5.0-rc1 version instead of the final 1.5.0

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/application-gateway-kubernetes-ingress#1336]
**Describe the bug**
It seems strange to run RCs instead of final versions.

**To Reproduce**
Install a v 1.21.7 cluster, then upgrade to 1.22.4
Observe that the ingress controller is upgraded from 1.4 to 1.5.0-rc1

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
```
ode-Selectors:              <none>
Tolerations:                 :NoExecute op=Exists
                             :NoSchedule op=Exists
                             CriticalAddonsOnly op=Exists
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  27s   default-scheduler  Successfully assigned kube-system/ingress-appgw-deployment-69b856df-kq279 to aks-nodepool-35694215-vmss000000
  Normal  Pulled     27s   kubelet            Container image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.5.0-rc1" already present on machine
  Normal  Created    27s   kubelet            Created container ingress-appgw-container
  Normal  Started    27s   kubelet            Started container ingress-appgw-container
vmadmin@nic-dts-dev-kigx-vm-0:~$ 
```

**Comment by davidkarlsen** [comment]
yes, it works. we have the appgw in another vnet than the cluster, so it only works when running azure-cni, not with kubenet. But that's not related to the version.

**Comment by jan-delaet** [comment]
Is this issue getting any attention?

Upgraded a cluster and facing the exact same issue described by avbanks. Manually changing the image from 1.5.0-rc to 1.5.1 now results in the same 'forbidden' error for the appgw service account. Editing the cluster role to include get/list/watch for ingressclasses under the api group networking.k8s.io fixes the issue entirely and restores the health of the backends on the app gateway.

Problem is that this config is automatically being reconciled/overwritten on a schedule/trigger. We are using the native AGIC integration for AKS and are not deploying the helm charts. Looking at the helm charts it looks like this is fied in 1.5.1, but the native AGIC integration is not using this version yet...
