### ISSUE TITLE
AGIC AKS Addon v1.5.0 Update 

### ISSUE THREAD

**Issue by danivisma** [Azure/application-gateway-kubernetes-ingress#1341]
Hello,

I'm using AKS AGIC in the company I'm working for and we were waiting for the appgw.ingress.kubernetes.io/rewrite-rule-set annotation feature that was recently released in the version 1.5.0.

We are using the AKS AGIC addon and we were hoping to have the 1.5.0 version already updated in our AKS "but" we still have the version 1.4.0:

Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.4.0

Do we need to execute any action in our side to get the version 1.5.0 updated in our AKS? 
Is it updated automatically? If so then  when it is going to be updated?

Thanks in advance.

**Comment by benc-uk** [comment]
We hit issues using the add-on way to install AGIC, as it deploys an older (and buggier) version, and you have no control over it.

The only answer is to self install using Helm

**Comment by Gordonby** [comment]
This is related, from the AKS repo.
https://github.com/Azure/AKS/issues/2801

**Comment by sehgalnamit** [comment]
Do we have any update on the fix?

Thanks

**Comment by danivisma** [comment]
Hello, 

The AGIC pod is already updated in the AKS clusters. It is using the container image: mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.5.1.

Thanks,
