### ISSUE TITLE
AGIC silently bypassed the networking failure during the pod initialization  

### ISSUE THREAD

**Issue by Shuanglu** [Azure/application-gateway-kubernetes-ingress#1342]
**Describe the bug**
In v1.22 cluster, when the pod v1.5.0-rc starts to discover server version, if there is networking issue like failed to connect to the apiserver, AGIC silently bypass it instead of raising exception. This may result the cache sync failed because the pod keeps looking for 'v1beta1.Ingress'
eg. https://github.com/Azure/application-gateway-kubernetes-ingress/blob/1.5.0-rc1/pkg/k8scontext/supported_apiversion.go#L41   
**To Reproduce**
1. deploy AGIC 
2. block the connection to apiserver from the AGIC pod via iptables
3. restart the container of AGIC
4. checking the logs we could find message like below. It should not use 'v1beta1' any more in v1.22. 
I0211 09:39:48.815944       1 reflector.go:255] Listing and watching ***v1beta1.Ingress** from pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
* Output of `kubectl logs <ingress controller>. 
* Any Azure support tickets associated with this issue.

**Comment by akshaysngupta** [comment]
@Shuanglu thanks for raising the issue. Will take this issue in the next minor release of AGIC.
If you are comfortable, you are welcome to help with a fix!
