### ISSUE TITLE
AGIC E2E SSL with Letsencrypt

### ISSUE THREAD

**Issue by lhiqvia** [Azure/application-gateway-kubernetes-ingress#1354]
Hi everybody,

From the documentation I couldn't find a way to accomplish E2E with Let's Encrypt, only SSL/TLS termination for AKS cluster.

My question here is:
- Is that possible and if yes can you point me to some documentation that I could follow.

Thank you,
L

**Comment by ashwinpagarkhed** [comment]
Hi @lhiqvia we are facing the same issue.

**Comment by jmp601** [comment]
@lhiqvia Could you provide a sample of your ingress and the HTTP spec of your application? This annotations page is extremely handy for this: https://azure.github.io/application-gateway-kubernetes-ingress/annotations/

**Comment by lhiqvia** [comment]
@jmp601 Thank you for your reply. 
Unfortunately I moved away for Let's Encrypt E2E setup and I implemented E2E with custom CA, thinking that that can't be achieved for the moment with LE E2E. Therefore I don't have any sample to provide.

But I'm still interested to know how this could be achieved with LE E2E AGIC/AGW. 
If you or anybody else have documentation/samples/ideas how we could implement this please share with us, and I would setup a cluster to test this.

Thx,
L
