### ISSUE TITLE
E2E Nightly is failing after Mar 5. Please update the token.

### ISSUE THREAD

**Issue by mazgi** [Azure/application-gateway-kubernetes-ingress#1368]
**Describe the bug**

The CI `E2E Nightly` is failing after Mar 5.
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/194222/159702195-d1fc41f7-eebd-4790-abbc-e4035254bb50.png">

The reason seems expired token.
https://dev.azure.com/azure/application-gateway-kubernetes-ingress/_build/results?buildId=37969&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86&l=1597

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/194222/159703074-8cb9997d-4d27-4042-a2d7-9b3b5812592d.png">

**To Reproduce**

1. Open https://dev.azure.com/azure/application-gateway-kubernetes-ingress/_build?definitionId=85&_a=summary on your browser.

**Comment by mazgi** [comment]
@akshaysngupta I found your amazing activities in recent pull requests.
Would you happen to know how to update the token?
Or could you update it?

**Comment by akshaysngupta** [comment]
fixed!
