### ISSUE TITLE
Error: rendered manifests in helm install AGIC ,and Multiple Namespace Support for Application Gateway Ingress

### ISSUE THREAD

**Issue by abarqawi** [Azure/application-gateway-kubernetes-ingress#1383]
**Describe the bug**

We have configured our Cluster with Application Gateway as Ingress via the Plugin. Now we want to enable Multiple Namespace Support to let AppGW watch all Namespaces. Helm-Config:
# This file contains the essential configs for the ingress controller helm chart

    # Verbosity level of the App Gateway Ingress Controller
    verbosityLevel: 3
    
    ################################################################################
    # Specify which application gateway the ingress controller will manage
    #
    appgw:
        subscriptionId: b7171e85-72b8-426f-a5b6-d3651ca95e4e
        resourceGroup: rg-aks01-prod-appgw
        name: appgw-eu2-prod-003
    
        # Setting appgw.shared to 'true' will create an AzureIngressProhibitedTarget CRD.
        # This prohibits AGIC from applying config for any host/path.
        # Use 'kubectl get AzureIngressProhibitedTargets' to view and change this.
        shared: false
    
    ################################################################################
    # Specify which kubernetes namespace the ingress controller will watch
    # Default value is 'default'
    # Leaving this variable out or setting it to blank or empty string would
    # result in Ingress Controller observing all acessible namespaces.
    #
    # kubernetes:
    watchNamespace: 
    
    ################################################################################
    # Specify the authentication with Azure Resource Manager
    #
    # Two authentication methods are available:
    # - Option 1: AAD-Pod-Identity (https://github.com/Azure/aad-pod-identity)
    armAuth:
         type: aadPodIdentity
    identityResourceID: <identityResourceId>
    identityClientID:  <identityClientId>
    
################################################################################
    # Specify if the cluster is Kubernetes RBAC enabled or not
    rbac:
        enabled: true # true/false
    
    # Specify aks cluster related information. THIS IS BEING DEPRECATED.
    aksClusterConfiguration:

We did not get this up and running:
dwilsberg@XPS-DWI-001:/mnt/c/Users/dwilsberg/source/repos/K8S$ helm install agic -f apgw-config.yaml application-gateway-kubernetes-ingress/ingress-azure

Error: rendered manifests contain a resource that already exists. Unable to continue with install: IngressClass "azure-application-gateway" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "azure-agic"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"

![image](https://user-images.githubusercontent.com/16225699/165299706-975c639d-2688-404d-8ee1-ecbd24bddde1.png)

We do the following :
1-tried to enable the Add on and disable
2-helm list and not showing any release
3-checked installed pods and not found agic pod
4-there was test service i exposed i deleted it 

i suspect there is some left-overs from AGIC add-on i cannot solve it 

**To Reproduce**

* Any Azure support tickets associated with this issue.  2204200050002724

**Comment by JiayangZhou** [comment]
Your config file is a bit off, it should be kubernetes.watchNamespace, you commented out the kubernetes

**Comment by abarqawi** [comment]
@JiayangZhou  sorry its copy/paste issue but i uncomment it and same issue , also i tried with helm install with parameters and same problem , i suspect there is some left overs affected by the agic add-on

**Comment by kamellemann** [comment]
We also got the error with manual commandline deployment: 
helm install ingress-azure application-gateway-kubernetes-ingress/ingress-azure --namespace default --set appgw.name=appgw-eu2-prod-002 --set appgw.resourceGroup=rg-aks01-prod-appgw --set appgw.subscriptionId=<subid> --set appgw.usePrivateIP=false --set appgw.shared=false --set armAuth.type=aadPodIdentity --set armAuth.identityResourceID=<msi resource id>--set armAuth.identityClientID=<msi client id> --set rbac.enabled=true --set verbosityLevel=5 --set kubernetes.watchNamespace= --set aksClusterConfiguration.apiServerAddress=<api url> --version 1.5.1

**Comment by kamellemann** [comment]
@JiayangZhou, @abarqawi
perhaps this is our problem? Is it safe to delete this CRD without damaging the cluster? This CRD is still there even if no ingress is configured (neither agic nor nginx)

![image003 19](https://user-images.githubusercontent.com/24431844/165464085-1324eb79-a5f7-4ef3-8ceb-297c4e9ded71.png)

https://beta.pkg.go.dev/github.com/Azure/application-gateway-kubernetes-ingress/pkg/crd_client/agic_crd_client/clientset/versioned/typed/azureingressprohibitedtarget/v1

**Comment by kamellemann** [comment]
Cleanup this CRD did not help. No resource left in all namespaces that seems to be related to an AppGW.

**Comment by kamellemann** [comment]
This did the trick: 
kubectl delete ingressclass azure-application-gateway

Then both deployments works fine:
- addon is working as expected
- helm is working as expected

Info: even the addon is watching all namespaces by default. This should be updated in MS Doku. So multiple Namespace Support activation is only required for helm release.

**Comment by abarqawi** [comment]
Thank @kamellemann  Thanks for update i will close
