### ISSUE TITLE
AKS create with App gateway ingress control fails with IngressAppGwAddonConfigInvalidSubnetCIDRNotContainedWithinVirtualNetwork error

### ISSUE THREAD

**Issue by ArunSuryaPrakash** [Azure/application-gateway-kubernetes-ingress#1386]
When i try to create aks using azure cli using the following command :

"az aks create -n myCluster -g myResourceGroup --network-plugin azure --enable-managed-identity -a ingress-appgw --appgw-name myApplicationGateway --appgw-subnet-cidr "10.2.0.0/16" --generate-ssh-keys"

I get the below error.

"(IngressAppGwAddonConfigInvalidSubnetCIDRNotContainedWithinVirtualNetwork) Subnet Prefix '10.2.0.0/16' specified for IngressApplicationGateway addon is not contained within the AKS Agent Pool's Virtual Network address prefixes '[10.224.0.0/12]'. Code: IngressAppGwAddonConfigInvalidSubnetCIDRNotContainedWithinVirtualNetwork Message: Subnet Prefix '10.2.0.0/16' specified for IngressApplicationGateway addon is not contained within the AKS Agent Pool's Virtual Network address prefixes '[10.224.0.0/12]'. Target: AddonProfiles.IngressApplicationGateway"

Any idea why i get this error ? or how to fix it.

This happens only when i enable the ingress.

**Comment by lsl-msft** [comment]
Just met same error.

**Comment by ArunSuryaPrakash** [comment]
> Just met same error.

In AKS [release notes](https://github.com/Azure/AKS/releases/tag/2022-02-24) the default VNET address for managed VNETs changed from 10.0.0/8 to 10.224.0.0/12. The Azure documentation is outdated and causing the above error. 

please use --appgw-subnet-cidr "**10.225.0.0/16**"  instead of "**10.2.0.0/16**". This should fix the issue.
