### ISSUE TITLE
AGIC Wildcard Hostnames - subdomain doesn't start with *

### ISSUE THREAD

**Issue by karloefd95** [Azure/application-gateway-kubernetes-ingress#1398]
**DESCRIBE A PROBLEM**

While reading Azure Application Gateway [documentation](https://docs.microsoft.com/en-us/azure/application-gateway/multiple-site-overview#conditions-for-using-wildcard-characters-and-multiple-host-names-in-a-listener) I got to conclusion that Azure Application Gateway supports wildcards in subdomains. As stated:

> "Asterisk * can be mentioned only once in a component of a domain style name or host name. For example, **component1***.component2*.component3. (\*.contoso-\*.com) is valid."

When I tried to created ingress using AGIC with following wildcard hostname: **ch1\*.playground.domain.com**  I got following error:

> "The Ingress "hub-app" is invalid:
> spec.rules[0].host: Invalid value: "**ch1\*.playground.domain.com**": a wildcard DNS-1123 **subdomain must start with '*.'**, followed by a valid DNS subdomain, which must consist of lower case alphanumeric characters, '-' or '.' and end with an alphanumeric character (e.g. '*.example.com', regex used for validation is ` '\*\.[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'` )
> 

Here is also YAML code used to create it (sorry for bad formatting): 

> apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hub-app
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/request-timeout: "600"
spec:
  tls:
  \- hosts:
    \- ch1-\*.playground.domain.com
    secretName: playground.domain.com
  defaultBackend:
    service:
      name: hub-app
      port:
        number: 80
  rules:
  \- host: ch1-\*.playground.domain.com
    http:
      paths:
      \- pathType: Prefix
        path: /app
        backend:
          service:
            name: hub-app
            port:
              number: 80

This is also stated [here](https://azure.github.io/application-gateway-kubernetes-ingress/ingress-v1/) that AGIC doesn't support subdomains which are not starting with *. Is there a way that regex used for validation is changed to accept subdomain which are not starting with * like in my case? 

This is blocking me from having more web deployments using same ingress/listeners/rules on azure application gateway causing me troubles in having multi web environments setup which use same backend services. 

**SOLUTION**
Change validation regex / enable AGIC to accept and create wildcard hostnames with subdomains which are not starting with *, eg ch1\*.playground.domain.com

**Comment by akshaysngupta** [comment]
@karloefd95 This is an issue with the ingress API as it doesn't allow wildcard in the middle.

To workaround, AGIC supports [appgw.ingress.kubernetes.io/hostname-extension](https://azure.github.io/application-gateway-kubernetes-ingress/annotations/#hostname-extension) which can use to provide the hostname as well.
