### ISSUE TITLE
AGIC deployment in an existing AKS with custom routing tables can't be done using HELM.

### ISSUE THREAD

**Issue by eduardodfmex** [Azure/application-gateway-kubernetes-ingress#1415]
**Describe the bug**

As AKS is configured to use KUBENET as network provider and due to the custom routing table (so the AKS can connect to private Networking), AGIC could not be deployed using HELM. 
HELM requires Manage Identity that does not work with custom routing table.
In such scenario, we needed to use the AKS Add-On deployment.

**To Reproduce**

Sample error message and commands when we try to enable pod Identity and we can use HELM for AGIC Deployment:

Full message:
azureuser@######$ az aks update -g resource-group -n aks-name --enable-pod-identity --enable-pod-identity-with-kubenet
The behavior of this command has been altered by the following extension: aks-preview
--enable-pod-identity can only be specified for cluster enabled managed identity
azureuser@######$ az aks update -g resource-group -n aks-name --enable-managed-identity

The behavior of this command has been altered by the following extension: aks-preview
Your cluster is using service principal, and you are going to update the cluster to use systemassigned managed identity.
After updating, your cluster's control plane and addon pods will switch to use managed identity, but kubelet will KEEP USING SERVICE PRINCIPAL until you upgrade your agentpool.
Are you sure you want to perform this operation? (y/N): y
(CustomRouteTableWithUnsupportedMSIType) Clusters using managed identity type SystemAssigned do not support bringing your own route table. Please see  https://aka.ms/aks/customrt for more information
Code: CustomRouteTableWithUnsupportedMSIType
Message: Clusters using managed identity type SystemAssigned do not support bringing your own route table. Please see  https://aka.ms/aks/customrt for more information
azureuser@######$

**Comment by akshaysngupta** [comment]
@eduardodfmex This is not related to AGIC. Please contact AKS support via a support ticket on AKS.
