### ISSUE TITLE
AGIC: Update WAF Policy Custome rules 

### ISSUE THREAD

**Issue by jawad846** [Azure/application-gateway-kubernetes-ingress#1419]
AGIC had limitations to update WAF policy custom rules.

Once the Application gateway is attached to AKS, we have only to attach the WAF policies to AGIC, there is no option to update the WAF policy custom rules from AKS.

As per Microsoft support, we shouldn't touch the application gateway or WAF policy after attaching it to the AKS.

**Comment by akshaysngupta** [comment]
@jawad846 You can update the WAF policy via Azure Portal for custom rules.

Customizing WAF rules via AGIC/AKS is not on the horizon.
