### ISSUE TITLE
After 1.5.0-rc1 unable to install more than one AGIC per namespace using helm

### ISSUE THREAD

**Issue by tbertenshaw** [Azure/application-gateway-kubernetes-ingress#1420]
**Describe the bug**
Upgrading multiple AGIC Helm Deployments to the same namespace fails when upgrading from 1.5.0-rc1 to  1.5.0 or above.

**To Reproduce**
After upgrading one helm deployment in the same namespace, then try the second and you recieve an error as below 

`Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: IngressClass "azure-application-gateway" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "REDACTED_NAME_OF_SECOND-ingress-azure": current value is "REDACTED_NAME_OF_FIRST-ingress-azure"`

**Ingress Controller details**
After Upgrading/installing the first helm deployment you can see the following ingressClass

```
k get ingressclass -A -oyaml
apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: IngressClass
  metadata:
    annotations:
      meta.helm.sh/release-name: REDACTED_NAME_OF_FIRST-ingress-azure
      meta.helm.sh/release-namespace: ingress-controller
    generation: 1
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/managed-by: Helm
    name: azure-application-gateway
  spec:
    controller: azure/application-gateway
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by akshaysngupta** [comment]
@tbertenshaw This is happening as both AGICs are using the same ingress class.
You can provide a different value for ingress class name by using providing `kubernetes.ingressClassResource.name` parameter in the Helm values.
Remember to use the same name in the `Ingress` resource as well.
