### ISSUE TITLE
Application Gateway Private - Private (100% Private AG) deployment for AGIC.

### ISSUE THREAD

**Issue by eduardodfmex** [Azure/application-gateway-kubernetes-ingress#1423]
**Is your feature request related to a problem? Please describe.**

To use Application gateway Ingress controller AGIC on AKS, you need an application gateway.
Application Gateway has two deployment modes related to endpoints' IPs, which are Private & Public or Public &Public IP configurations. 
For users that require a 100% private AGIC with two private IP´s (instead of having one public IP and one Private IP), the only option is a Public - Private deployment.
The Public - Private Application Gateway deployment demands the creation of Public IP’s and add security risks for users that can mistake configurations and publish services to the public IP instead of publishing services only internally.

**Describe the solution you'd like**

A third option that allows a full private Application Gateway ingress having Private & Private IP configurations would better attend a 100 % private approach and prevent errors during deployments such as adding proper annotations indicating the use of public or private (someone may accidentally set public when they need private for deployment, even when using NSG to secure access to those resources).

Example of the mistaken Ingress setup:

```
ingress:
enabled:true
annotations:
kubernetes.io/ingress.class:azure/application-gateway
appgw.ingress.kubernetes.io/use-private-ip:"false"
```

**Comment by akshaysngupta** [comment]
"Private IP only" Application Gateway is slated for public preview early next year. AGIC should follow after that.
