### ISSUE TITLE
Enable additional HELM Features on AKS add-on or enable deployment through HELM when using custom routing tables

### ISSUE THREAD

**Issue by eduardodfmex** [Azure/application-gateway-kubernetes-ingress#1424]
**Is your feature request related to a problem? Please describe.**

By being restricted to deploy AGIC using AKS add-on only, we also could not use full features available on helm configuration. To mention one example:

- Deploy only one Application Gateway, as mentioned in the AKS Add-on: “Customers can only deploy one AGIC add-on per AKS cluster, and each AGIC add-on currently can only target one Application Gateway.” 

For more information see, [Difference between Helm deployment and AKS Add-On](https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-overview#difference-between-helm-deployment-and-aks-add-on)

**Describe the solution you'd like**
Ask: Enable additional Helm features on AKS add-on (like have more application gateways for one AKS) or enable deployment through Helm for Application Gateway in case custom routing tables are used.

**Comment by akshaysngupta** [comment]
Currently, this is by design. We will consider this as a feature request and prioritize based on our backlog.
