### ISSUE TITLE
Improve AGIC Ingress deployment performance during creation or update to under 5 min

### ISSUE THREAD

**Issue by eduardodfmex** [Azure/application-gateway-kubernetes-ingress#1425]
**Is your feature request related to a problem? Please describe.**

Currently in our scenario, it may take between 5 to 10 min. to create the ingress, every time we create a new ingress or update it (like updating paths).
That delay adds more time to the CI/CD, like time consumption for test and release process. 
Pipelines triggered using Azure DevOps with helm tasks complete, but you need to wait until you manually can verify that the Ingress was deployed.

The delay also affects 0 down time deployment strategies because you can see the ingress configuration deployed on the AKS, but the communication from public Ip to the APP GG and then the AKS can´t be completed.

We already implement the ["Minimizing Downtime During Deployments"](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/how-tos/minimize-downtime-during-deployments.md) list, but the delay persists.

**Describe the solution you'd like**
Improve AGIC Ingress deployment performance during creation or update to under 5 min or even less time.

Language: Java 11.0.2 with Spring Boot 2.5.6
Application Gateway Ingress Controller: version 1.0
Helm: version 2
AKS with Kubenet network
Custom IP routing table

**Comment by akshaysngupta** [comment]
@eduardodfmex Is your Application Gateway up and running or is it being created as part of this? If it is only update, then it seems to be an Application Gateway issue. Can you please create a support ticket via Azure Portal?

**Comment by eduardodfmex** [comment]
Is up and running.
