### ISSUE TITLE
Azure security policy violation for having host path mounted in agic setup

### ISSUE THREAD

**Issue by Uvindu96** [Azure/application-gateway-kubernetes-ingress#1429]
**Describe the bug**
Hi, we have deployed application gateway ingress controller in our AKS cluster and one of the azure polices have detected security policy violation for agic component. This policy is `Usage of pod HostPath volume mounts should be restricted to a known list to restrict node access from compromised containers` Can I know the requirement for having the host path mounted ? Then we can whitelist this component from the policy.

**Comment by jamesbwilkinson** [comment]
We also see the same issue and would welcome more information here.
