### ISSUE TITLE
Each time "name": "defaulthttpsetting" recreating in GW.

### ISSUE THREAD

**Issue by oberdeha** [Azure/application-gateway-kubernetes-ingress#1466]
Hello,

First of all please excuse if there was such question, I didn’t find it.

Each time, when ingress send updates to Azure GW it is recreating list of default settings and use protocol HTTP in the configuration even when I have next annotations in my ingress:

`appgw.ingress.kubernetes.io/backend-protocol: https
  kubernetes.io/ingress.allow-http: false`

One of them are not allowed by local security policy. My question is how I can disable this? Maybe I can use any key:value in ingress annotation.

Log output:
`"name": "defaulthttpsetting",
-- App Gwy config --                "properties": {
-- App Gwy config --                    "cookieBasedAffinity": "Disabled",
-- App Gwy config --                    "pickHostNameFromBackendAddress": false,
-- App Gwy config --                    "port": 80,
-- App Gwy config --                    "probe": {
-- App Gwy config --                        "id": "/subscriptions/******/resourceGroups/rg-name/providers/Microsoft.Network/applicationGateways/ag-name/probes/defaultprobe-Http"
-- App Gwy config --                    },
-- App Gwy config --                    "protocol": "Http",
-- App Gwy config --                    "requestTimeout": 30
-- App Gwy config --                }`

Will be really appreciated if someone can suggest something.

**Comment by sixeyed** [comment]
This is also an issue for us. 

We have a policy to enforce end-to-end SSL which checks all backend settings are configured with protocol HTTPS. The `defaulthttpsetting` is always created with protocol HTTP and port 80 (see [getBackendHttpSettingsMap in backendhttpsettings.go](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/a91b78305bb6496097ce994d17963637a5db49a4/pkg/appgw/backendhttpsettings.go#L76)).

We can update the backend setting manually to force HTTPS but as soon as AGIC syncs, the AppGW setting is reverted back to HTTP. Unless we have a policy exception tag in place, the sync fails.
