### ISSUE TITLE
ApplicationGatewayBackendAddressPoolLimitReached error when more than 100 Ingresses

### ISSUE THREAD

**Issue by rlaveycal** [Azure/application-gateway-kubernetes-ingress#1471]
**Describe the bug**
App Gateway has a limit of 100 backend pools. AGIC creates a pool per ingress which causes failure when the limit is exceeded
`
Error processing event.network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ApplicationGatewayBackendAddressPoolLimitReached" Message="The number of BackendAddressPools exceeds the maximum allowed value. The number of BackendAddressPools is 113 and the maximum allowed is 100." Details=[]
`

**To Reproduce**
- Create 101 Ingresses

**Comment by Felichita** [comment]
I try to explain how i was able to solve this issue. If you have more than 100 ingress is a typical case, and my cluster have too more 100 ingresses. First better way will be add one ingress like as kube-addons (installation from azure). In my case I know exactly that I have a lot of static namespaces  (dev, qa ,bi, ci, elk, release, another-env ...). Command for installation:

`az aks enable-addons -n $aks_name -g $aks_resourse_group -a ingress-appgw --appgw-id /subscriptions/$uid/resourceGroups/$resourseGroupAppGw/providers/Microsoft.Network/applicationGateways/$AppGwName --appgw-watch-namespace bi,ci,default,dev,elk,kube-system,qa,release,velero,ingress-nginx`

Also I have dynamic environments, according limits I should to install another one appgw through helm ([docs](https://learn.microsoft.com/en-us/azure/application-gateway/ingress-controller-install-existing)):
`helm upgrade --install ingress-azure-ext-0  -f helm-config.yaml  application-gateway-kubernetes-ingress/ingress-azure  --namespace default --version 1.3.0 --set kubernetes.watchNamespace="{fnx-2,fnx-3,fnx-1000}"`

I also noticed a feature that if the namespace does not exist, then we get Kubernetes CrashLoopBackOff from the appgw application. Every time when I'd like to add new namespace I'll edit configmap for appgw and append new namespace then restart my appgw.

I'm not sure that it's a really well feature bypass, but it works...
if someone has  another decision, please share!
