### ISSUE TITLE
How to use AGIC when route table needs a quad-zero route

### ISSUE THREAD

**Issue by tdevopsottawa** [Azure/application-gateway-kubernetes-ingress#1484]
According to this page here - https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/how-tos/networking.md#with-kubenet - the AKS route table needs to be associated with the application gateway subnet in order for the app gateway ingress to work. 

But my AKS route table has an outbound firewall rule that directs 0.0.0.0/0 traffic to a virtual appliance (a third party firewall - note - **not** Azure firewall) and when I tried to associate my AKS route table to the application gateway subnet, it threw an error that 0.0.0.0/0 must be directed to Internet for the application gateway subnet.

How do I get around this problem?

**Comment by kamilzzz** [comment]
Recent improvements for Application Gateway v2 allow to have 0.0.0.0/0 route to NVA attached to Application Gateway's subnet. 
At the moment they are in public preview but maybe it is worth checking that.
