### ISSUE TITLE
No support for workload identity

### ISSUE THREAD

**Issue by tsachi-transmit** [Azure/application-gateway-kubernetes-ingress#1492]
**Describe the bug**
As AAD pod is now deprecated https://github.com/Azure/aad-pod-identity, we want to switch to workload identity but there is no support in the chart

**To Reproduce**
Steps to reproduce the behavior: N/A

**Ingress Controller details**
N/A

**Comment by akshaysngupta** [comment]
We are prioritizing this issue and expect this to be in the next release.

**Comment by damnedOperator** [comment]
Is there a roadmap to where the next release is coming? We are forced to migrate to AAD Workload Identity and need AGIC to get letsencrypt certs on our ingress routes. 

Or is there any other way for us to get a prerelease version that somehow works?
