### ISSUE TITLE
Failed to watch *v1beta1.AzureApplicationGatewayRewrite: failed to list *v1beta1.AzureApplicationGatewayRewrite

### ISSUE THREAD

**Issue by angelbulas** [Azure/application-gateway-kubernetes-ingress#1495]
When i upgrade to version 1.6.0 i start getting this errors every minute:

I0124 18:18:52.773456       1 reflector.go:255] Listing and watching *v1beta1.AzureApplicationGatewayRewrite from pkg/mod/k8s.io/client-go@v0.20.0-beta.1/tools/cache/reflector.go:167                                                   │
E0124 18:18:52.776414       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.0-beta.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.AzureApplicationGatewayRewrite: failed to list *v1beta1.AzureApplicationGatewayRewrite: the server could not find the requested resource (get azureapplicationgatewayrewrites.appgw.ingress.azure.io)  

I'm not sure what other info do you need to troubleshoot this?

Thank you

**Comment by mmillard0** [comment]
I'm facing the same logs messages after AGIC upgrade to version 1.6.0 and using and upgraded AKS cluster to 1.23.12.

**Comment by angelbulas** [comment]
I'm using AKS 1.24.6

**Comment by akshaysngupta** [comment]
Looking at the `helm upgrade` command help, It says that custom resource definitions are installed as when `upgrade` is used with `--install`.
Can you try the same upgrade command and add `--install` and check if that helps?

**Comment by angelbulas** [comment]
Looks like you were right, i uninstall the helm chart because I'm deploying through terraform, but in theory when you deploy it again it uses --install, so after that the error went away, maybe someone else can test with the helm upgrade using --install

**Comment by mmillard0** [comment]
Thanks @akshaysngupta, I have generated the missing crd file with --include-crds helm option. I'm using "helm template" to generate the yaml files.

**Comment by akshaysngupta** [comment]
It looks like an unsupported feature in helm: https://github.com/helm/helm/issues/6581

**Comment by relent0r** [comment]
I just hit this issue upgrading from 1.5.2 to 1.6.0.

Thanks for supplying the command on adding the missing CRD.

**Comment by tanvp112** [comment]
```
E0830 16:24:12.045731       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.0-beta.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.AzureApplicationGatewayRewrite: failed to list *v1beta1.AzureApplicationGatewayRewrite: azureapplicationgatewayrewrites.appgw.ingress.azure.io is forbidden: User "system:serviceaccount:kube-system:ingress-appgw-sa" cannot list resource "azureapplicationgatewayrewrites" in API group "appgw.ingress.azure.io" at the cluster scope: Azure does not have opinion for this user.
```

The AKS managed AGIC now lack of `list` permission on the `azureapplicationgatewayrewrites` custom resource. Is there a fix for this or we need to manually add the permission?

**Comment by taulantracajm** [comment]
Same issue here?

**Comment by jlopezv31** [comment]
Hi, 

I have the same error, have you found any correction?

Thank you!

**Comment by josmare** [comment]
Any for when you install the CRD as a AddOn?

**Comment by GersonDias** [comment]
having same issue here when using the managed AGIC :(

**Comment by scorpionfly7** [comment]
Hello, Is there any updates about this issue?

**Comment by rtrigo-opengov** [comment]
Same here

**Comment by kosta-bain** [comment]
Same here, are there any updates on AKS version 1.27.7

**Comment by hemantkathuria** [comment]
Hello @akshaysngupta ,
I have setup AGIC add-on on AKS.
Getting the below error.
I did the steps mentioned by kosta-bain above, but no luck.

E1206 08:55:22.697842       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.0-beta.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.AzureApplicationGatewayRewrite: failed to list *v1beta1.AzureApplicationGatewayRewrite: the server could not find the requested resource (get azureapplicationgatewayrewrites.appgw.ingress.azure.io)
I1206 08:55:24.859776       1 reflector.go:255] Listing and watching *v1beta1.AzureApplicationGatewayRewrite from pkg/mod/k8s.io/client-go@v0.20.0-beta.1/tools/cache/reflector.go:167
E1206 08:55:24.861709       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.0-beta.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.AzureApplicationGatewayRewrite: failed to list *v1beta1.AzureApplicationGatewayRewrite: the server could not find the requested resource (get azureapplicationgatewayrewrites.appgw.ingress.azure.io)
I1206 08:55:30.043667       1 reflector.go:255] Listing and watching *v1beta1.AzureApplicationGatewayRewrite from pkg/mod/k8s.io/client-go@v0.20.0-beta.1/tools/cache/reflector.go:167
E1206 08:55:30.045526       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.0-beta.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.AzureApplicationGatewayRewrite: failed to list *v1beta1.AzureApplicationGatewayRewrite: the server could not find the requested resource (get azureapplicationgatewayrewrites.appgw.ingress.azure.io)
I1206 08:55:36.451807       1 reflector.go:255] Listing and watching *v1beta1.AzureApplicationGatewayRewrite from pkg/mod/k8s.io/client-go@v0.20.0-beta.1/tools/cache/reflecto

**Comment by ruffrey** [comment]
Glad someone posted fixes. My team lost a lot of time troubleshooting this after deploying some AKS-AGIC systems with terraform.

I think MS should know, obscure issues like this are so frequent, we were an hour from completely dumping the AGIC in favor of something stable (traefik, haproxy, or nginx). Surely we are not alone. (We followed microsoft terraform examples from the start, and they were missing a lot of config to make it work.)

This issue has been open for 10 months. That is way too long, especially for the prices people pay in Azure. There are 287 open issues and 10 open PRs to this repo, on a project with only 650 stars and 40 watchers. Is Microsoft still supporting this project?

**Comment by GersonDias** [comment]
@ruffey, go with the HELM template install. It doesn't have that problem and allows you to share the AGW instance with other things. But by far I guess the nginx is a better option since this kind of issue where you have a checkbox in the azure portal that install things in your cluster that doesn't work is very frustrating. Also, since AGW is the responsible to route the requests instead of NGINX pods or similar, if all your app pods dies you will start receiving a 502 error, while nginx can handle that better or respond to changes in the services pods faster. I understand that this difference is because the way AGW works and how changes in the network are propagated... so if you deployment just kills all the pods to replace with a new version, you might want to review that strategy. 

(https://techcommunity.microsoft.com/t5/fasttrack-for-azure/aks-ingress-perf-testing-nginx-vs-appgw-agic/ba-p/3706694).

**Comment by evmimagina** [comment]
Hi @akshaysngupta ,

When is this gonna be fixed for the AKS AGIC add-on? I'm deploying AKS enabling the add-on and I would like to leave it that way and not having to deploy AGIC as a separate deployment.

Many thanks and best regards,

**Comment by antoinemartinoctave** [comment]
The following is the @kosta-bain  fix in terraform:

```terraform
# This file is a fix for the following issue:
# https://github.com/Azure/application-gateway-kubernetes-ingress/issues/1495
provider "kubernetes" {
  host                   = azurerm_kubernetes_cluster.main.kube_admin_config.0.host
  client_certificate     = base64decode(azurerm_kubernetes_cluster.main.kube_admin_config.0.client_certificate)
  client_key             = base64decode(azurerm_kubernetes_cluster.main.kube_admin_config.0.client_key)
  cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.main.kube_admin_config.0.cluster_ca_certificate)
}

resource "kubernetes_cluster_role" "fixrole" {
  metadata {
    name = "fix-agic-role"
  }
  rule {
    api_groups = ["appgw.ingress.azure.io"]
    resources  = ["*"]
    verbs      = ["get", "list", "watch"]
  }
  depends_on = [azurerm_kubernetes_cluster.main]
}

resource "kubernetes_cluster_role_binding" "fixrolebinding" {
  metadata {
    name = "fix-agic-role-binding"
  }
  subject {
    kind      = "ServiceAccount"
    name      = "ingress-appgw-sa"
    namespace = "kube-system"
  }
  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "ClusterRole"
    name      = "fix-agic-role"
  }
  depends_on = [kubernetes_cluster_role.fixrole]
}

data "http" "appgw" {
  url = "https://raw.githubusercontent.com/Azure/application-gateway-kubernetes-ingress/master/helm/ingress-azure/crds/azureapplicationgatewayrewrite.yaml"
}

resource "kubernetes_manifest" "crds" {
  for_each = {
    for value in [
      for yaml in split(
        "\n---\n",
        "\n${replace(data.http.appgw.response_body, "/(?m)^---[[:blank:]]*(#.*)?$/", "---")}\n"
      ) :
      yamldecode(yaml)
      if trimspace(replace(yaml, "/(?m)(^[[:blank:]]*(#.*)?$)+/", "")) != ""
    ] : "${value["kind"]}--${value["metadata"]["name"]}" => value
  }
  manifest   = each.value
  depends_on = [kubernetes_cluster_role_binding.fixrolebinding]
}
```

The `for_each` in `kubernetes_manifest` is useless as the URL only contains one CRD.

**Comment by kaushikd13** [comment]
Still seeing these errors. Any solution for this?

E0109 08:27:56.481514 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.0-beta.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.AzureApplicationGatewayRewrite: failed to list *v1beta1.AzureApplicationGatewayRewrite: azureapplicationgatewayrewrites.appgw.ingress.azure.io is forbidden: User "system:serviceaccount:kube-system:ingress-appgw-sa" cannot list resource "azureapplicationgatewayrewrites" in API group "appgw.ingress.azure.io" at the cluster scope: Azure does not have opinion for this user.

E0109 09:38:27.684411 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.0-beta.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.AzureApplicationGatewayRewrite: failed to list *v1beta1.AzureApplicationGatewayRewrite: the server could not find the requested resource (get azureapplicationgatewayrewrites.appgw.ingress.azure.io)

**Comment by vishu42** [comment]
So I recently got agic working for me and I will break down the problem and solution in this comment. 

There are two ways to install agic, one is via helm chart and other is using the aks add-on. 

If you install agic via add-on, it doesn't install the crds and the required rbac, which results in the current issue. Hack is to obv install the required rbac and crds as mentioned by @kosta-bain. 

Second option is to install the agic via helm chart, which seems more robust way and requires no manual hack. Follow the guide [here](https://learn.microsoft.com/en-us/azure/application-gateway/ingress-controller-install-existing#azure-resource-manager-authentication) to install agic helm chart using workload identity. Keep in mind that to be able to use workload identity you need to enable oidc and workload identity in the cluster. Also, I observed that the guide above is missing one step which was required for agic pod to work and the missing step was to create a federated credential for the managed identity using following command
`az identity federated-credential create --name test-fed-id --identity-name test-identity --resource-group test-rg --issuer <your_oidc_issuer> --subject <service_account_for_agic_pod> --audience api://AzureADTokenExchange`
(you can google how to find oidc issuer for aks)

**Comment by GersonDias** [comment]
It's a simple thing to solve, but the AKS team doesn't fix that... and you
still have a checkbox in the portal that installs components in your
cluster that simply doesn't work. Not asking too much from a paid service.

Em ter., 23 de jan. de 2024 às 14:34, vishal tewatia <
***@***.***> escreveu:
