### ISSUE TITLE
App Gateway + Workload Identity Release Schedule

### ISSUE THREAD

**Issue by damnedOperator** [Azure/application-gateway-kubernetes-ingress#1504]
Hi, I just wanted to ask what your release cadence is for AGIC, or when the new version of the helm chart supporting Workload Identity comes out. If it is not until monday, is there any possibility to get the chart out as a pre-release version? 

Many thanks

**Comment by jbpaux** [comment]
There is a prerelease : https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/CHANGELOG/CHANGELOG-1.7.md
