### ISSUE TITLE
Cannot configure Ingress with support for both HTTP and HTTPS

### ISSUE THREAD

**Issue by philippn** [Azure/application-gateway-kubernetes-ingress#1510]
**Describe the bug**
When an Ingress resource is created with TLS, subsequently the HTTP listener gets removed completely. This observable behaviour does not match the documentation (which was already reported as #540) but it also brings up the question how to configure HTTP and HTTPS at the same time at all.

Please advise how to configure Ingress so that both HTTP and HTTPS are enabled.

Thanks in advance!

**To Reproduce**

- Create Ingress resource pointing to some hostname
- Add TLS section in Ingress resource and configure TLS accordingly (i.e. via cert-manager)
- wait for the 
- Invoke hostname from browser with HTTP protocol and observe a 404 error from AGIC

**Comment by rk9qn3j** [comment]
I experience the same issues. It seems that no listener is being created under Listeners in the Application Gateway.

@philippn Have you found any workaround to this?

**Comment by philippn** [comment]
Yeah, the work-around is to have 2 separate Ingress resources, one with TLS configured and one without. Also make sure not to use the annotation [appgw.ingress.kubernetes.io/ssl-redirect](https://azure.github.io/application-gateway-kubernetes-ingress/annotations/#ssl-redirect).

Hope that helps!

**Comment by rk9qn3j** [comment]
Thanks for the response! I can confirm that this approach now creates both listeners, but when I add `appgw.ingress.kubernetes.io/ssl-redirect: "true"` under annotations for the HTTP ingress, HTTP stops working (as before).

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-http
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: app.test.example.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: app-svc
              port:
                number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-https
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01-staging
spec:
  ingressClassName: azure-application-gateway
  tls:
  - hosts:
      - app.test.example.com
    secretName: app-tls
  rules:
  - host: app.test.example.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: app-svc
              port:
                number: 80
``

**Comment by rk9qn3j** [comment]
I just found out that you need to use the annotation `appgw.ingress.kubernetes.io/ssl-redirect: "true"` in order to achieve HTTP to HTTPS redirection. Otherwise, no HTTP listener will be created, only HTTPS (if a certificate is available). See this guy's [finding](https://github.com/Azure/application-gateway-kubernetes-ingress/issues/540#issue-497098708).

**Comment by philippn** [comment]
I think this issue has been solved to my satisfaction, two separate ingresses work fine. Thanks.
