### ISSUE TITLE
Add documentation for configuring `AzureApplicationGatewayRewrite`

### ISSUE THREAD

**Issue by karlschriek** [Azure/application-gateway-kubernetes-ingress#1544]
**Is your feature request related to a problem? Please describe.**

We are attempting to set up a  `AzureApplicationGatewayRewrite` that needs to rewrite the host from `foo.bar` to `foo.baz`. This is an extremely simple (and maybe even the most common) use case for a rewrite, but I cannot find any docs that describe how to do this.

**Describe the solution you'd like**

I would like to see documentation that explains all of the available options under the `spec` section of `AzureApplicationGatewayRewrite `(apiVersion: `appgw.ingress.azure.io/v1beta1`), as well as some examples how to perform typical use cases.

**Comment by akshaysngupta** [comment]
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/features/rewrite-rule-set-custom-resource.md
