### ISSUE TITLE
AGIC support for HTTPS backend pools

### ISSUE THREAD

**Issue by sarahecraddock** [Azure/application-gateway-kubernetes-ingress#1555]
**Is your feature request related to a problem? Please describe.**
I am unable to use AGIC and encrypt ingress traffic end to end. Specifically, I am looking to implement mTLS via OSM.

**Describe the solution you'd like**
Support for HTTPS backends when using AGIC so that I can implement mTLS via OSM with AGIC.

I have seen that there were some comments about this being on the backlog in 2020 with no ETA, could you advise on the current ETA for this feature?

**Comment by fozturner** [comment]
AGIC does support HTTPS backends, but it does not work with OSM.

It is worth adding that OSM project is being archived - https://github.com/openservicemesh/osm#%EF%B8%8F-the-osm-project-has-been-proposed-for-archive-status-%EF%B8%8F

**Comment by akshaysngupta** [comment]
AGIC doesn't support Backend MTLS.
