### ISSUE TITLE
Is it possible to open a port other than 80/443 for listening?

### ISSUE THREAD

**Issue by chriskinsman** [Azure/application-gateway-kubernetes-ingress#159]
Looking to indicate a new listener port other than 80/443.

**Comment by asridharan** [comment]
@chriskinsman  we will need to add a listener specific annotation for this since ingress resource itself doesn't support this.

**Comment by yamansama** [comment]
Hi, any news on this feature ?

**Comment by DreamRivulet** [comment]
Any update on this ? Could we customize listener port ?

**Comment by olafkfreund** [comment]
Any update on this ?

**Comment by MCKLMT** [comment]
Any news on this issue? My customer requests the same and this issue is opened since one year. Thanks

**Comment by sbkg0002** [comment]
@akshaysngupta any word on this?

**Comment by schlickspringer** [comment]
we require this as well to be able to use public and private ip on different ports as AppGW does not support different IPs on one port.

**Comment by kamilzzz** [comment]
@akshaysngupta Any ideas when this might be merged?
Would be useful to have this so we can expose HTTP/HTTPS workloads using both Public and private IPs (right now when I have HTTPS configured for Public IP then I cannot expose any HTTPS service over Private IP).

**Comment by sbkg0002** [comment]
Any updates on this?

**Comment by mcarlsen** [comment]
Seems to be released in 1.4.0 (annotation appgw.ingress.kubernetes.io/override-frontend-port). 

Can we get an update of the Feature Roadmap so that it reflects current reality?

Thanks!
