### ISSUE TITLE
az cli command from install guide evaluates with empty value

### ISSUE THREAD

**Issue by effelow** [Azure/application-gateway-kubernetes-ingress#1591]
**Describe the bug**
az command [this line](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/a11719a9f0d5e95edad0e67c9d81a6486a3f1d93/docs/setup/install-new.md?plain=1#L49) from the [install.md ](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/setup/install-new.md)
```sh
az aks get-versions --location $location --query "orchestrators[-1].orchestratorVersion" -o tsv
```

**To Reproduce**
1. Go to cloudshell
2. paste the command
    ```sh
    location="westus2"
    kubernetesVersion=$(az aks get-versions --location $location --query "orchestrators[-1].orchestratorVersion" -o tsv)
    echo $kubernetesVersion

    ```
    Notive the variable `$kubernetesVersion` is empty.

**Solution**

Replace `--query`parameter like so **"values[?isDefault==\`true\`].version | [0]"**

```sh
kubernetesVersion=$(az aks get-versions --location $location --query "values[?isDefault==\`true\`].version | [0]" -o tsv)
```

**Comment by akshaysngupta** [comment]
install guide is now updated with new steps.
