### ISSUE TITLE
AAD Pod Identity - archived and is no longer maintained.

### ISSUE THREAD

**Issue by plalnol** [Azure/application-gateway-kubernetes-ingress#1599]
As of Monday 10/02/2023, [AAD Pod Identity repo has been archived](https://github.com/Azure/aad-pod-identity) and is no longer maintained. The repo will be available in read-only mode. There will be no new releases.
Please use [Azure Workload Identity](https://azure.github.io/azure-workload-identity/) instead. 

Any plans to migrate?

**Comment by rowanmoul** [comment]
Pod Identity has be deprecated since October 2022. If the basic documentation still hasn't been updated (something that would take someone probably a day a most to update), it makes me wonder if I should trust this project to continue being supported.

**Comment by akshaysngupta** [comment]
Updated
