### ISSUE TITLE
[Feature] Support `spec.ingressClassName`

### ISSUE THREAD

**Issue by JoeyC-Dev** [Azure/application-gateway-kubernetes-ingress#1637]
**Is your feature request related to a problem? Please describe.**
When deploying with `kubectl`, it is telling me:
`Warning: annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead`.

BTW, `spec.ingressClassName: azure/application-gateway` is not supported as the character `/` is not allowed.

**Describe the solution you'd like**
Support `spec.ingressClassName`.

**Comment by toredash** [comment]
https://azure.github.io/application-gateway-kubernetes-ingress/ingress-v1/#ingressclass-and-ingressclass-name

It's not clear, but it is supported.

**Comment by toredash** [comment]
@JoeyC-Dev  close issue if this resolves your question ?

**Comment by JoeyC-Dev** [comment]
> @JoeyC-Dev close issue if this resolves your question ?

Let me do a test and will get back to you later, cuz I remember before I submit this issue, I already tested with `spec.ingressClassName` and there was an error. 
Gimme sometime.

**Comment by JoeyC-Dev** [comment]
Looks like it is working. Thanks for the answer.
