### ISSUE TITLE
RBAC Support

### ISSUE THREAD

**Issue by GrigorievNick** [Azure/application-gateway-kubernetes-ingress#200]
It will be great to have support of RBAC in ingress spec.
I have a production k8s cluster, with Enabled RBAC and few teams that independently work on it.

I expect that it will be way to specify Service Account for Ingress Controller during deployemnt.
Like in Nginx https://kubernetes.github.io/ingress-nginx/deploy/rbac/.
Or What even better is specify Service Account per Ingress Rule.

Sorry but i'am not familair with k8s internals, so i cant suggest any design idea or add any implementations notes.
I just know that this is very important feature, which supported by every production ready K8s resources.

**Comment by invidian** [comment]
Wasn't it added in #57?

**Comment by akshaysngupta** [comment]
Currently, helm deploys a `clusterrole` which gives ingress controller access to the required resources in all the namespaces.
Are you guys running 1 ingress controller per namespace ? (per team, so you want to restrict access ?)

**Comment by GrigorievNick** [comment]
Yes.
Just no notes about it in documents.


ср, 12 июн. 2019 г., 15:04 Mateusz Gozdek <notifications@github.com>:

**Comment by GrigorievNick** [comment]
Hi, we want use ingress controller per project. What will result like
ingress controller per multiple namespace.
Current situation with 57 is ok.

Previously i cant find in doc how to setup ingress on k8s with rbac
enabled. But after you give me link to 57 ticket, i build template from
helm.
So its ok.

сб, 22 июн. 2019 г., 4:41 Akshay Gupta <notifications@github.com>:

**Comment by akshaysngupta** [comment]
Good new, multiple namespace is already in `0.7.0-rc2`. Please provide us feedback. We will release this soon!
