### ISSUE TITLE
Multiples ingress support

### ISSUE THREAD

**Issue by cristhianbicca** [Azure/application-gateway-kubernetes-ingress#218]
**Describe the bug**
Hello, I'm trying to create multiple ingress features to serve various services
Ingress Examples:

NAME         HOSTS                    ADDRESS   PORTS   AGE
flask-app1   flask-app1.exemple.com             80      60m
flask-app2   flask-app2.example.com             80      54m
flask-app4   flask-app4.example.com             80      53m

My Ingress controller it's configured:
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/install-existing.md

In the Application Gateways interface, only one RULES ASSOCIATED is enable and  all the traffic always falls into that which is associated, should not all the ingress be associated?

![image](https://user-images.githubusercontent.com/7811406/58563231-22af4200-8201-11e9-9e50-6f30744096c0.png)

**Comment by akshaysngupta** [comment]
@cristhianbicca can you please share your `ingress` resource and `ingress controller` pod logs ?

**Comment by akshaysngupta** [comment]
@cristhianbicca  were you able to resolve the issue ?

**Comment by draychev** [comment]
@cristhianbicca AGIC does support multiple ingress definitions and multiple host names.  Closing issue since we have not heard from you. Please reopen if you are still unable to configure multiple ingress resources.
