### ISSUE TITLE
Ingress for Windows nodes not working

### ISSUE THREAD

**Issue by rahulvmarathe** [Azure/application-gateway-kubernetes-ingress#225]
I have a AKS cluster with both Windows & Linux nodes, ingress setup completed successfully. 

Deployed an ASPNET core application to both windows and Linux nodes.
The application gateway is getting configured correctly for both the Windows and Linux hosted applications however the health probe for the Windows hosted app shows up as unhealthy where as the one for Linux app is healthy.

Is there is anything specific i have to configure to get the ingress integrated with Windows nodes?

**Comment by draychev** [comment]
@rahulvmarathe There isn't anything different that you need to configure based on the operating system.  However the health probes may have to be configured differently based on the expectation of the HTTP/S service.  By default responses with status code anywhere between 200 and 399 is considered healthy.
Without much context on what the backend services are - I'd speculate that the health probe URL needs to be corrected or there are perhaps specific headers required that App Gateway is not supplying as part of health checks, or it could be that all endpoints on the Windows hosts require authentication. Another issue could be that the backend responds too slow (this could be changed).

**Comment by akshaysngupta** [comment]
Duplicate: https://github.com/Azure/application-gateway-kubernetes-ingress/issues/535
