### ISSUE TITLE
Documentation: app gw autoscaling requirement

### ISSUE THREAD

**Issue by landro** [Azure/application-gateway-kubernetes-ingress#245]
From what is written on https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/install-existing.md one can get the impression that the ingress controller does not support autoscaling application gateways. Does this apply? I have verified that several ingress controller operations work as expected, even if autoscaling is enabled.

Current doc:

```An existing Azure Application Gateway v2 with manual scaling configured (not set to AutoScale).```

**Comment by draychev** [comment]
@landro Thank you for verifying that Ingress Controller works with Autoscale enabled.

I dug into this as well - we added this line to the documentation https://github.com/Azure/application-gateway-kubernetes-ingress/pull/82 at a time when an older version of the underlying SDK did not yet support Autoscale-enabled Application Gateways.  As you found out - this is no longer the case.

I will update the documentation momentarily.
