### ISSUE TITLE
Any thoughts of having a secure backend?

### ISSUE THREAD

**Issue by solacens** [Azure/application-gateway-kubernetes-ingress#284]
I'm a new comer of Azure with some past experience of Kubernetes and EKS.

I'm just wondering if there will be a secure backend options after the ingress has done SSL termination. For example: [Annotation: Nginx ingress controller](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#backend-protocol)

I would like to get more features in this ingress controller with Azure App Gateway, hopefully more feature will attract more people to use it: Ingress controller base on cloud platform customized CNI is a nice approach to avoid extra hops inside the cluster, hence reduce latency.

Please feel free to reference and close the issue if there's a similar one.

**Comment by akshaysngupta** [comment]
Yes, Backend HTTPS is in the pipeline.

**Comment by akshaysngupta** [comment]
We are working on this but we don't have an ETA yet.

**Comment by draychev** [comment]
Similar issue: https://github.com/Azure/application-gateway-kubernetes-ingress/issues/187

**Comment by kwaazaar** [comment]
Is there a comparison of the Application Gateway featureset and this Ingress Controller featureset? Like what is implemented and what not?
Because [the FAQ says](https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-faq#does-application-gateway-support-reencryption-of-traffic-to-the-backend) Application Gateway already supports this.

**Comment by marrobi** [comment]
@akshaysngupta - any update on this and how to configure? As per https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-faq#does-application-gateway-support-reencryption-of-traffic-to-the-backend . 

I work in environments where all traffic between cloud components must be encrypted so this is an essential feature. Thanks.

**Comment by akshaysngupta** [comment]
If you are using certificate signed well-known CAs. You can reference this document: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/annotations.md#backend-protocol

If you have your own PKI/self-signed certificate, we still some work left on AGIC.

**Comment by StianOvrevage** [comment]
@akshaysngupta Do you have more information on how the communication between AGW and backend service when configured by AGIC is happening?

We have certs signed by LetsEncrypt but of course they are only valid for `mysvc.ourcluster.company.com`. Does AGIC and AGW use `mysvc.ourcluster.company.com` for connection (the example from the annotation docs does not include any hostnames in Ingress definition)? If so, how does it actually determine the hosts etc? And is there any way to verify it in for example Azure Portal? And if it's not configured correctly, where do we go to check for logs or errors?

**Comment by akshaysngupta** [comment]
@StianOvrevage You can now use:
1) [appgw.ingress.kubernetes.io/backend-hostname](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/annotations.md#backend-hostname) to modify the hostname used while talking to the backend.
2) [appgw.ingress.kubernetes.io/appgw-trusted-root-certificate](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/annotations.md#appgw-trusted-root-certificate) can be used to provide the root certificate that will used to verify backend certs.
