### ISSUE TITLE
Doc: clarify regarding AppGW standard (v1)

### ISSUE THREAD

**Issue by tdihp** [Azure/application-gateway-kubernetes-ingress#294]
**Is your feature request related to a problem? Please describe.**
I'm confused if application gateway standard v1 works with this ingress-controller, to what extent.
The installation doc states prerequisite to be v2, however there's no reason explicitly given on why v1 shouldn't be considered.

**Describe the solution you'd like**
Explicitly state if AppGW v1 is supported or not in doc. If not, preferably state why.

Thank you.

**Comment by tdihp** [comment]
I have don a brief test, indicating v1 can work with the tutorial, but haven't done any further testing.

**Comment by mcarlsen** [comment]
We attempted to use appgw v1 and basic networking with this ingress controller with some initial success. However, Microsoft support told me this:

> AppGW v2 will be the only supported version of AppGW when this feature is deemed GA.

and 

> While we would be happy to make a best effort exploration of a workaround for a test environment, one thing I would like to note is that we do not recommend using them [appgw V1] in production environments. The reason being is that we cannot guarantee we will be able to help you find a solution should the workaround break in the future.

**Comment by cwe1ss** [comment]
If AppGw v2 is the only way forward then you really have to do something about the pricing. V2 currently has a ~ 10x increase for the minimum charge, which makes it way too expensive for many dev/test scenarios. 

We would really have liked to test and use this project, but the V2 pricing is a blocker for us.

**Comment by winthrop28** [comment]
Thanks for the comment, we're aware of the ask. It's on our backlog.
