### ISSUE TITLE
Support AKS RBAC enabled clusters

### ISSUE THREAD

**Issue by asridharan** [Azure/application-gateway-kubernetes-ingress#31]
**Is your feature request related to a problem? Please describe.**
We should be able to run the ingress controller on RBAC enabled AKS clusters.

**Describe the solution you'd like**
We need to add templates to the Helm chart to setup a service principal and give the service principal the right permissions to get access to the resources.
https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/deployment-rbac.yaml

**Comment by vramakrishnan** [comment]
Support added in https://github.com/Azure/application-gateway-kubernetes-ingress/pull/57
