### ISSUE TITLE
Logs everywhere

### ISSUE THREAD

**Issue by solacens** [Azure/application-gateway-kubernetes-ingress#310]
**Describe the bug**

Currently I'm testing the release 0.7.0-rc2 with multiple namespaces feature, it works well and smooth. 

However, the output logs are unstoppable when you got so many namespaces (~15). I'm wondering if the log level can be refined. I'm currently have `APPGW_VERBOSITY_LEVEL` = `1` but it doesn't really help.

**Comment by draychev** [comment]
@solacens This is great feedback - thank you for taking the time to come back here and report your experience.

Let's iterate on this - we should be able to tame logging before dropping the `-rc2` from the version.  Will update the issue here when we are ready for you to take a look again.

**Comment by draychev** [comment]
@solacens We released version `0.7.0`. This has https://github.com/Azure/application-gateway-kubernetes-ingress/pull/311, which has 3 verbosity levels for logging and defaults to the most quiet one.

Read about the [streamlined logging levels here](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/ec009ede61626e0153f14331df2a638cad6583a2/docs/troubleshooting.md#logging-levels)

I'm going to close this issue, but please share your experience with the new version!

**Comment by solacens** [comment]
@draychev Thanks, I will test it later today 👍
