### ISSUE TITLE
Can we support using existing certificate in appgw for https listener?

### ISSUE THREAD

**Issue by zhiweiv** [Azure/application-gateway-kubernetes-ingress#316]
We have strict ssl certificate policy, ssl certificate is preconfigured to appgw by IT team, then we use it to configure new https listeners, we are unable to touch the pfx and it's password.

AGIC needs certificate from k8s secret, it is a big gap for us.

**Comment by mschumacher2625** [comment]
Eta on this?

**Comment by zhiweiv** [comment]
Does https://github.com/Azure/application-gateway-kubernetes-ingress/pull/765 fix this?

**Comment by akshaysngupta** [comment]
@zhiweiv Yes, these two PRs fixes this ask.
