### ISSUE TITLE
Add kubernetes e2e test framework to mock Kubernetes API server.

### ISSUE THREAD

**Issue by asridharan** [Azure/application-gateway-kubernetes-ingress#34]
**Is your feature request related to a problem? Please describe.**
We need to figure out a way to perform e2e tests against a kubernetes API server.

**Describe the solution you'd like**
The kubernetes e2e framework allows us to mock the kubernetes API server and allows us to run tests for controllers against this API server.
https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md

**Comment by akshaysngupta** [comment]
Closing as this has been resolved.
