### ISSUE TITLE
Support for both public and private listeners on AGIC

### ISSUE THREAD

**Issue by DeanPH** [Azure/application-gateway-kubernetes-ingress#359]
Currently with the AGIC 0.7.1, is it's not possible to have an HTTPS listener (443) on public and an http listener (80) on the private IP. When enabling `usePrivateIP`, it attaches **both** the ssl listener and the port 80 listener to the private IP which leaves the public with no listeners.

This is the setup we need the AGIC to replicate:

![image](https://user-images.githubusercontent.com/39728249/60747951-04b3ca80-9f81-11e9-8160-5b9e68e35826.png)

I would appreciate it if someone could look into adding this feature.

Thanks!

**Comment by akshaysngupta** [comment]
Thanks for the request. This should be part of the next release.

**Comment by akshaysngupta** [comment]
Here is the release 0.8.0 supporting the private ip annotation.
https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/0.8.0
Closing this issue.
