### ISSUE TITLE
Unclear Service Principal Authentication

### ISSUE THREAD

**Issue by henningploegerzeb** [Azure/application-gateway-kubernetes-ingress#364]
**Describe the bug**

I deployed the ingress controller to aks with principal authentication option. I could not determine how to set up the secrets for the service principal. So I added the Contributor-Role on the application gateway to the AKS-principal and mountet the AKS-principal's credentials into the ingress controller. But that leads to the error shown below. 

Could you please clarify how to set up the ingress controller's service principal and its secretes. 

**Ingress Controller details**

Name:                   azure-ag-ingress-controller
Namespace:              kube-system
CreationTimestamp:      Tue, 09 Jul 2019 16:05:37 +0200
Labels:                 app=azure-ag-ingress-controller
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=azure-ag-ingress-controller
Replicas:               1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=azure-ag-ingress-controller
  Service Account:  azure-ag-ingress-controller
  Containers:
   azure-ag-ingress-controller:
    Image:      mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.7.1
    Port:       <none>
    Host Port:  <none>
    Environment:
      AZURE_AUTH_LOCATION:    /etc/kubernetes/azure.json
      APPGW_SUBSCRIPTION_ID:  xxxxxxxxxxxxxxxxxxxxxxxxxxx
      APPGW_RESOURCE_GROUP:   installtestpublic_interface-rg
      APPGW_NAME:             installtestag-ep
      APPGW_VERBOSITY_LEVEL:  5
    Mounts:
      /etc/kubernetes/azure.json from azure-config (ro)
  Volumes:
   azure-config:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json

ERROR: logging before flag.Parse: I0709 14:06:28.388541       1 main.go:233] Using verbosity level 5 from environment variable APPGW_VERBOSITY_LEVEL
I0709 14:06:28.388667       1 main.go:171] Creating authorizer from file referenced by AZURE_AUTH_LOCATION
F0709 14:06:28.388862       1 main.go:93] Error creating Azure clientauth file missing client and certificate credentials

**Comment by akshaysngupta** [comment]
Following steps explain how to run the controller with a service principal for authentication:

1. Create the service principal, assign the required RBACs and create a k8s Secret

    ```bash
    # Create service principal and store the json output in a file
    az ad sp create-for-rbac --skip-assignment > azureauth.json

    # Assign service principal contributor access to the AppGW
    az role assignment create --role Contributor --assignee <principal ID from the command above> --scope <Resource ID of Application Gateway>

    # Assign service principal reader access to the resource group
    az role assignment create --role Reader --assignee <principal ID from the command above> --scope <Resource ID of Application Gateway Resource Group>

    # Create a secret using the above json file
    kubectl create secret generic controllerSp --from-file=path/to/azureauth.json
    ```

1. Now update the helm config's `armAuth`:

    ```yaml
    armAuth:
        type: servicePrincipal
        secretName: controllerSp
        secretKey: azureauth.json
    ```

I will soon add this in the documentation.

**Comment by henningploegerzeb** [comment]
works like a charm. thx
