### ISSUE TITLE
Pod has no access

### ISSUE THREAD

**Issue by kwaazaar** [Azure/application-gateway-kubernetes-ingress#372]
Straight after a brown field installation:
E0715 14:47:06.227604       1 reflector.go:125] github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:296: Failed to list *v1beta1.Ingress: ingresses.extensions is forbidden: User "system:serviceaccount:default:agic-sa-ingress-azure" cannot list resource "ingresses" in API group "extensions" at the cluster scope

**To Reproduce**
Brown field installation

**Ingress Controller details**
Name:               agic-ingress-azure-749d44576b-l94vf
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               aks-agentpool-71662594-7/10.234.19.142
Start Time:         Mon, 15 Jul 2019 16:31:07 +0200
Labels:             aadpodidbinding=agic-ingress-azure
                    app=ingress-azure
                    pod-template-hash=749d44576b
                    release=agic
Annotations:        <none>
Status:             Running
IP:                 10.234.19.216
Controlled By:      ReplicaSet/agic-ingress-azure-749d44576b
Containers:
  ingress-azure:
    Container ID:   docker://d263ff28a4ba15145fd0e534d6f8e2dfa751af7fabd68a4b1c1eb0264e930b47
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.7.1
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:7474a032ed48a82105b960844e32fef203067a60e9a46a5c7a298b103c38725c
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Mon, 15 Jul 2019 16:31:09 +0200
    Ready:          True
    Restart Count:  0
    Environment Variables from:
      agic-cm-ingress-azure  ConfigMap  Optional: false
    Environment:
      KUBERNETES_PORT_443_TCP_ADDR:  aahnl-kubernetes-ot-78c6386c.hcp.westeurope.azmk8s.io
      KUBERNETES_PORT:               tcp://aahnl-kubernetes-ot-78c6386c.hcp.westeurope.azmk8s.io:443
      KUBERNETES_PORT_443_TCP:       tcp://aahnl-kubernetes-ot-78c6386c.hcp.westeurope.azmk8s.io:443
      KUBERNETES_SERVICE_HOST:       aahnl-kubernetes-ot-78c6386c.hcp.westeurope.azmk8s.io
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from agic-sa-ingress-azure-token-vsqhh (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  agic-sa-ingress-azure-token-vsqhh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  agic-sa-ingress-azure-token-vsqhh
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                               Message
  ----    ------     ----  ----                               -------
  Normal  Scheduled  19m   default-scheduler                  Successfully assigned default/agic-ingress-azure-749d44576b-l94vf to aks-agentpool-71662594-7
  Normal  Pulling    19m   kubelet, aks-agentpool-71662594-7  pulling image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.7.1"
  Normal  Pulled     19m   kubelet, aks-agentpool-71662594-7  Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.7.1"
  Normal  Created    19m   kubelet, aks-agentpool-71662594-7  Created container
  Normal  Started    19m   kubelet, aks-agentpool-71662594-7  Started container

* Output of `kubectl logs <ingress controller>. 
E0715 14:50:36.835413       1 reflector.go:125] github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:296: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:default:agic-sa-ingress-azure" cannot list resource "secrets" in API group "" at the cluster scope
E0715 14:50:36.994211       1 reflector.go:125] github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:296: Failed to list *v1beta1.Ingress: ingresses.extensions is forbidden: User "system:serviceaccount:default:agic-sa-ingress-azure" cannot list resource "ingresses" in API group "extensions" at the cluster scope
E0715 14:50:36.994220       1 reflector.go:125] github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:296: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:default:agic-sa-ingress-azure" cannot list resource "pods" in API group "" at the cluster scope
E0715 14:50:36.994255       1 reflector.go:125] github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:296: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:default:agic-sa-ingress-azure" cannot list resource "endpoints" in API group "" at the cluster scope
E0715 14:50:36.996109       1 reflector.go:125] github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:296: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:default:agic-sa-ingress-azure" cannot list resource "services" in API group "" at the cluster scope
E0715 14:50:37.838553       1 reflector.go:125] github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:296: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:default:agic-sa-ingress-azure" cannot list resource "secrets" in API group "" at the cluster scope
E0715 14:50:38.000190       1 reflector.go:125] github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:296: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:default:agic-sa-ingress-azure" cannot list resource "endpoints" in API group "" at the cluster scope
E0715 14:50:38.000198       1 reflector.go:125] github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:296: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:default:agic-sa-ingress-azure" cannot list resource "pods" in API group "" at the cluster scope
E0715 14:50:38.000922       1 reflector.go:125] github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:296: Failed to list *v1beta1.Ingress: ingresses.extensions is forbidden: User "system:serviceaccount:default:agic-sa-ingress-azure" cannot list resource "ingresses" in API group "extensions" at the cluster scope
E0715 14:50:38.001277       1 reflector.go:125] github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:296: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:default:agic-sa-ingress-azure" cannot list resource "services" in API group "" at the cluster scope

* Any Azure support tickets associated with this issue.
???

**Comment by kwaazaar** [comment]
Is there some trouble shooting guidance somewhere?

**Comment by akshaysngupta** [comment]
@kwaazaar Since, you have an RBACed cluster, you need to install the controller in the RBAC mode by adding the following to the helm config.

```yaml
rbac:
    enabled: true
```

We will add some more instruction on the helm config and trouble shooting this.

**Comment by kwaazaar** [comment]
That changes things. But the result is not much better:

robertka@OT-0038:/mnt/d/src/Infrastructure.aks/AGIC$ kubectl logs -l app=ingress-azure --tail=100 -f
I0716 06:38:06.395881       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.395886       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396687       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396780       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396786       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396792       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396796       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396801       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396805       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396810       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396815       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396820       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396824       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396829       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396833       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396840       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396844       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396849       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396853       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396859       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396863       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396871       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396875       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396880       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396885       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396890       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396895       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396900       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396904       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396912       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396917       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396924       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396929       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396934       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396938       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396944       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396948       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396953       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396957       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396963       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396968       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396973       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396978       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396983       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396987       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396993       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.396997       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.394162       1 secretstore.go:121] converted secret [development/dev-ssl]
I0716 06:38:06.397243       1 eventqueue.go:45] Enqueuing skip(false) item
I0716 06:38:06.445218       1 backendhttpsettings.go:137] resolving port name http-main
E0716 06:38:06.445273       1 backendhttpsettings.go:156] Unable to resolve any backend port for service [development/ssldemo-svc]
E0716 06:38:06.445281       1 configbuilder.go:58] unable to generate backend http settings, error [unable to resolve backend port for some services]
E0716 06:38:06.445297       1 process.go:84] ConfigBuilder Build returned error:unable to generate backend http settings
I0716 06:38:06.445785       1 process.go:97] BEGIN ApplicationGateway deployment
I0716 06:38:06.445810       1 panic.go:522] END ApplicationGateway deployment
E0716 06:38:06.445857       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 57 [running]:
github.com/Azure/application-gateway-kubernetes-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1431ec0, 0x2678420)
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
github.com/Azure/application-gateway-kubernetes-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
panic(0x1431ec0, 0x2678420)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.AppGwIngressController.Process(0x1820a60, 0xc000409590, 0x1822940, 0xc0003c99e0, 0x0, 0x0, 0xdf8475800, 0xd18c2e2800, 0x3, 0x6fc23ac00, ...)
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/process.go:102 +0x1280
github.com/Azure/application-gateway-kubernetes-ingress/pkg/eventqueue.(*EventQueue).worker(0xc000432a20)
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/eventqueue/eventqueue.go:112 +0x22b
github.com/Azure/application-gateway-kubernetes-ingress/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0000607a8)
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
github.com/Azure/application-gateway-kubernetes-ingress/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0009bbfa8, 0x3b9aca00, 0x0, 0x1, 0x0)
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
github.com/Azure/application-gateway-kubernetes-ingress/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
github.com/Azure/application-gateway-kubernetes-ingress/pkg/eventqueue.(*EventQueue).Run(0xc000432a20, 0x3b9aca00, 0x0)
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/eventqueue/eventqueue.go:69 +0x6c
created by github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.(*AppGwIngressController).Start
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/controller.go:58 +0x73
**panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45a5ea]**

goroutine 57 [running]:
github.com/Azure/application-gateway-kubernetes-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1431ec0, 0x2678420)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.AppGwIngressController.Process(0x1820a60, 0xc000409590, 0x1822940, 0xc0003c99e0, 0x0, 0x0, 0xdf8475800, 0xd18c2e2800, 0x3, 0x6fc23ac00, ...)
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/process.go:102 +0x1280
github.com/Azure/application-gateway-kubernetes-ingress/pkg/eventqueue.(*EventQueue).worker(0xc000432a20)
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/eventqueue/eventqueue.go:112 +0x22b
github.com/Azure/application-gateway-kubernetes-ingress/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0000607a8)
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
github.com/Azure/application-gateway-kubernetes-ingress/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0009bbfa8, 0x3b9aca00, 0x0, 0x1, 0x0)
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
github.com/Azure/application-gateway-kubernetes-ingress/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
github.com/Azure/application-gateway-kubernetes-ingress/pkg/eventqueue.(*EventQueue).Run(0xc000432a20, 0x3b9aca00, 0x0)
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/eventqueue/eventqueue.go:69 +0x6c
created by github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.(*AppGwIngressController).Start
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/controller.go:58 +0x73

**Comment by akshaysngupta** [comment]
Few questions:
1. What is the version of Ingress controller are you using? Use
    ```yaml
    helm list
   ```
1. From logs, I see that controller is unable to resolve ports for the service. Can you check if `http-main` port is exposed on the Pod behind the service ?

**Comment by kwaazaar** [comment]
robertka@OT-0038:~$ helm list
NAME                            REVISION        UPDATED                         STATUS          CHART                           APP VERSION     NAMESPACE
agic                            4               Tue Jul 16 08:37:46 2019        DEPLOYED        ingress-azure-0.7.1             0.7.1           default

The service and its port definitely exist:
robertka@OT-0038:~$ kubectl -n development get svc ssldemo-svc -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"ssldemo-svc","namespace":"development"},"spec":{"ports":[{"name":"http-ssldemo","port":80,"targetPort":"http-main"}],"selector":{"app":"ssldemo"},"type":"ClusterIP"}}
  creationTimestamp: "2019-05-13T09:47:06Z"
  name: ssldemo-svc
  namespace: development
  resourceVersion: "5463974"
  selfLink: /api/v1/namespaces/development/services/ssldemo-svc
  uid: 11da7b15-7564-11e9-88f6-fedc648087ef
spec:
  clusterIP: 10.234.7.27
  ports:
  - name: http-ssldemo
    port: 80
    protocol: TCP
    targetPort: http-main
  selector:
    app: ssldemo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

Also, the pods for label 'app:ssldemo' have this port specification:
ports:
      - containerPort: 8080
        name: http-main
        protocol: TCP

After deleting the ingress controller pod and viewing the logs from the new pod directly after startup, I notice this:
robertka@OT-0038:/mnt/d/src/ssl$ kubectl logs agic-ingress-azure-749d44576b-bpvf8 --tail=1000 -f
ERROR: logging before flag.Parse: I0717 07:49:46.160366       1 main.go:233] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0717 07:49:46.160473       1 main.go:168] Creating authorizer from Azure Managed Service Identity
E0717 07:49:46.200235       1 main.go:179] Error getting Application Gatewayag-otazure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/7b520150-0df3-4adb-83b7-5646c7c62fef/resourceGroups/network-ot-rg/providers/Microsoft.Network/applicationGateways/ag-ot?api-version=2018-12-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: **no AzureAssignedIdentity found for pod:default/agic-ingress-azure-749d44576b-bpvf8**
I0717 07:49:46.200261       1 main.go:180] Retrying in 10s
I0717 07:49:56.201593       1 main.go:109] Ingress Controller will observe all namespaces.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x12b89ca]

goroutine 1 [running]:
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.validateFrontendIPConfiguration(0x185e4e0, 0xc00042b800, 0x0, 0xc000048016, 0x24, 0xc000042045, 0xd, 0xc00004600b, 0x5, 0x0, ...)
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/validators.go:119 +0x3a
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.FatalValidateOnExistingConfig(0x185e4e0, 0xc00042b800, 0x0, 0xc000048016, 0x24, 0xc000042045, 0xd, 0xc00004600b, 0x5, 0x0, ...)
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/validators.go:153 +0xc0
main.main()
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/cmd/appgw-ingress/main.go:121 +0x83c
(pod keeps restarting)

I did install aadPodIdentity, but I haven't used it for other solutions. Did I perhaps miss a step to configure it or should the helm installation take care of that?

**Comment by akshaysngupta** [comment]
Thanks for sharing the yamls. I was able to figure out that this is a bug on the controller.
Controller is incorrectly using the `service.port.targetPort` instead of `service.port.Name` to lookup port in the `endpoints` object.

**Comment by littlenetcoder** [comment]
I am also facing same issue with Grafana which is running on port 3000. I tried to change port in Http settings but again that was also superseded !!

**Comment by kwaazaar** [comment]
Is this fix in 0.8.0-rc1? It would be nice if you could label issues (or PR's), so this is clear.

**Comment by delqn** [comment]
@kwaazaar Yes - the [fix](https://github.com/Azure/application-gateway-kubernetes-ingress/pull/393/files) is in 0.8.0-rc1
I see the issue here was closed automatically when we merged the PR.
Typically when we get a non Release Candidate version out (which means we have tested it extensively with large and complex AKS configurations) we go back to the GitHub issues this release fixes and post updates.
Thanks for your patience with this bug.

Could you give us an update - did `0.8.0-rc1` address the error you ran into?

**Comment by delqn** [comment]
@littlenetcoder Would you be so kind to upgrade to `0.8.0-rc1` and update us on whether the big is fixed for you too?
Upgrade instructions are [here](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/879608e63f4b0d59914cfca66033d877d13ff0dc/docs/how-tos/helm-upgrade.md#L22).

**Comment by simhams** [comment]
I am trying out a scenario which includes the following,
1. [Restrict and control cluster egress traffic (preview)](https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic)
2. AAD integrated AKS
3. App Gateway ingress controller

AKS subnet is associated to a route table which routes "0.0.0.0/0" to Azure Firewall private ip. 

Azure firewall is configured with both required and optional addresses and ports specified in [Restrict and control cluster egress traffic (preview)](https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic)

Also, upgraded the application gateway ingress controller to "0.8.0-rc1" as specified in [upgrade instructions](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/879608e63f4b0d59914cfca66033d877d13ff0dc/docs/how-tos/helm-upgrade.md#L22).

But it still fails with "_Error getting Application Gateway config..... Failed to refresh the Token for request to https://management.azure.com/subscriptions/......_"

Azure Firewall logs doesn't show up any denied FQDNs or IPs.

However, application gateway is configured as soon as the route table is dissociated from AKS Subnet and the guestbook web app is accessible from a browser!

[Azure Firewall known issues](https://docs.microsoft.com/en-us/azure/firewall/overview#known-issues) state that "Azure Firewall SNAT/DNAT doesn't work for private IP destinations"

Not sure if the error is, 
1. related to "Azure Firewall known issues" or 
2. if some additional FQDNs/IPs need to be whitelisted in Azure Firewall or 
3. if its related to App Gateway ingress controller

Could you please suggest?
