### ISSUE TITLE
Does the ingress controller support AKS with Kubenet (Simple Networking)?

### ISSUE THREAD

**Issue by Romiko** [Azure/application-gateway-kubernetes-ingress#399]
We have an existing AKS cluster using Kubenet (Simple Networking)

The Brownfields [https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/setup/install-existing.md](tutorial) shows that you need advanced networking.

I would like to use AKS kubenet with an application-gateway-kubernetes-ingress.

Thx

**Comment by akshaysngupta** [comment]
AKS with Kubenet is dependent upon AppGw v2 SKU supporting UDR on the subnet.

**Comment by MiyKh** [comment]
Hello,
Any update for AppGateway + kubenet?
I wonder how the application gateway can ping pod which are in an isolated subnet

**Comment by ChristopheChirat** [comment]
> Hello,
> Any update for AppGateway + kubenet?
> I wonder how the application gateway can ping pod which are in an isolated subnet

@akshaysngupta Is it possible for you to gives us a status on the integration of App Gateway as ingress controller with Kubenet?

**Comment by akshaysngupta** [comment]
Yes, this is now supported. We will update the docs soon on this.

If you want to try this quickly, just associated the AKS route table in node resource group to the subnet used by Application Gateway.
