### ISSUE TITLE
http 504 - gateway timeout error

### ISSUE THREAD

**Issue by vishnujanardhanan** [Azure/application-gateway-kubernetes-ingress#400]
**Describe the bug**
Seeing a http 504 - gateway timeout error after 10 mins of inactivity on app-gateway. We are using 0.7.1 version of ingress controller

 support ticket raised for this issue- 119072323001821

**Comment by akshaysngupta** [comment]
Looking into it.

**Comment by akshaysngupta** [comment]
@vishnujanardhanan Can you please provide an update ?

**Comment by vishnujanardhanan** [comment]
@akshaysngupta will come back on this

**Comment by akshaysngupta** [comment]
@vishnujanardhanan Is this resolved ?

**Comment by vishnujanardhanan** [comment]
@akshaysngupta - it is sorted. Thanks.
