### ISSUE TITLE
Add as Acs-engine plugin

### ISSUE THREAD

**Issue by kkmsft** [Azure/application-gateway-kubernetes-ingress#41]
**Is your feature request related to a problem? Please describe.**
Add as plugin for  acs-engine.

**Describe the solution you'd like**
acs-engine is used by many customers to create clusters on Azure. Add app gw k8s ingress as a plugin to the acs-engine so that customers can get this by default with just a config value set.

**Comment by tonyschollum** [comment]
Hi @kkmsft, 

Is there any progress on this one?

Cheers

**Comment by akshaysngupta** [comment]
Completed https://github.com/Azure/aks-engine/pull/1442
