### ISSUE TITLE
Raised events in addition to logs and point docs to events

### ISSUE THREAD

**Issue by kkmsft** [Azure/application-gateway-kubernetes-ingress#42]
**Is your feature request related to a problem? Please describe.**
Raised events in addition to logs and point docs to events

**Describe the solution you'd like**
Kubernetes events will provide an easy way for customers to debug and track what is going on with the app gw. The docs currently talk about looking at logs. Once this is added we should point it to the events for more streamlined monitoring of the state.

**Comment by akshaysngupta** [comment]
We are now logging to the Ingress Events for the customer to easily able to see the config errors.
We will add more info to the docs in coming PRs!
