### ISSUE TITLE
Occasionally Ingress Controller introduces significant delays in process ingress events

### ISSUE THREAD

**Issue by asridharan** [Azure/application-gateway-kubernetes-ingress#45]
**Describe the bug**
Occasionally, when we modify the Ingress resource it takes to the order tens of minutes to update the Application Gateway configuration through ARM.

**To Reproduce**
Start a Kubernetes service. Expose it through the Application Gateway by creating an Ingress resource. Scale the service up or down, or remove the Ingress resource completely and observe the time it takes to apply this configuration on the Application Gateway. Most of the time the update would go through within a matter of seconds, but occasionally it will take to order tens of minutes to get applied.

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
* Output of `kubectl logs <ingress controller>. 
will add the logs here shortly.
* Any Azure support tickets associated with this issue.

**Comment by asridharan** [comment]
This issue could be related to:
https://github.com/Azure/AKS/issues/522

**Comment by njzhangyifei** [comment]
This is somewhat related to the resync period. It happens when the informer misses events.

**Comment by asridharan** [comment]
> This is somewhat related to the resync period. It happens when the informer misses events.

@njzhangyifei why would the informer miss events?

**Comment by asridharan** [comment]
Looks like the work around mentioned in this issue should resolve this problem till it fixed in AKS itself:
https://github.com/Azure/AKS/issues/676

**Comment by asridharan** [comment]
@akshaysngupta could you take this on? This can be an extension of your helm work for enabling RBAC.
