### ISSUE TITLE
Automation of "Setting up Application Gateway Ingress Controller on AKS"

### ISSUE THREAD

**Issue by yasikmondal** [Azure/application-gateway-kubernetes-ingress#457]
Hi Team,

I am trying to do automation and have deployed application gateway as a ingress controller using ARM template. Now Application gateway , AKS and managed identity is creating properly but how to do this steps which are mention in "[Setting up Application Gateway Ingress Controller on AKS](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/setup/install-new.md#setting-up-application-gateway-ingress-controller-on-aks)" tutorial from VSTS pipeline?

can you please provide any sample pipeline where it has done those steps?

**Comment by akshaysngupta** [comment]
Thanks for asking. Investigating.

**Comment by akshaysngupta** [comment]
Added a [CI/CD document ](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/how-tos/continuous-deployment.md)for AzureDevOps
Closing.
