### ISSUE TITLE
cannot route when using path based

### ISSUE THREAD

**Issue by LirazRom** [Azure/application-gateway-kubernetes-ingress#47]
I have followed all your instructions , and i wanted to test the path base routing
this is my yaml filr

`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /guest
        backend:
          serviceName: frontend
          servicePort: 80
      - backend:
          serviceName: frontend
          servicePort: 80`

however when i navigate to the publicip/guest - i get
![image](https://user-images.githubusercontent.com/15184128/46283464-21981900-c57d-11e8-98f9-a98ab6327a79.png)

those are the rules in the appgw

![image](https://user-images.githubusercontent.com/15184128/46283537-52784e00-c57d-11e8-8e46-31e234ccbb6d.png)

![image](https://user-images.githubusercontent.com/15184128/46283564-67ed7800-c57d-11e8-9d79-939bb4d62e97.png)

**Comment by asridharan** [comment]
A few things to look at. 

I am assuming you are running the `guestbook` app. 

Please verify the following:
* In your Kubernetes dashboard can you make sure that you are running the guestbook app. You can look at the `services` tab or the deployment tab to make sure the `frontend` is actually up and running. 

* Also, can you make sure that the backends that are part of the backend pool are being reflected correctly on the Application Gateway. In Azure portal look at the `k8s-default-frontend-....` that you showed above.

* Finally, make sure that Application Gateway and the AKS cluster are part of the same VNET. The application gateway needs to be able to route to pods running on the AKS cluster.

**Comment by LirazRom** [comment]
All is working fine when I don’t use path base routing- regular rule
Only when I try to add another service , it don’t route to the new service
In this case I used the same frontend

**Comment by njzhangyifei** [comment]
@LirazRom @asridharan Application gateway will not rewrite URL of the request at the moment. I guess the problem here is that the backend service does not respond to a request on `/guest`.

**Comment by asridharan** [comment]
@njzhangyifei thanks !! Good catch. @LirazRom as @njzhangyifei pointed out we don't support re-write. We need to figure out how to support re-write using ingress annotations. Will open a support feature request for this. Currently the application gateway v2 itself doesn't support URL re-writes so we will have to wait for that support to land (sometime early next year).

**Comment by asridharan** [comment]
@LirazRom have opened a feature request #49 . Can we close this out in favor of #49 ?

Thanks!!

**Comment by LirazRom** [comment]
So it means that my service needs to listen on the path?

**Comment by asridharan** [comment]
Closing this out since we captured the feature request in #49 .

**Comment by phillipgibson** [comment]
Do we have an updated yaml that will show how to handle multiple services on the same port but using a different path. I'm unable to get this to work. I have deployed the guestbook app and testing a Nginx service using a /nginx path and it reaches the Nginx site, but the path /nginx is not present and Nginx sends back an error. I even tried using service port 8080 with the path /nginx and it still doesn't work. What is the correct way to host multiple services using the ingress controller?

**Comment by asridharan** [comment]
@phillipgibson as mentioned in the comments above, currently AG (application gateway) does not support URL re-writes. Due to this constraint to make different services work on the same the port using path based routing, the backends for the services need to explicitly support the paths that you are exporting the service on. 

In your case, e.g., the backend application needs to accept a `/nginx` path for you to expose the service associated with the backends on `/nginx` through Kubernetes ingress.

URL re-write is in the works for application gateway, and once it is introduced we will add the corresponding support in the ingress controller as well as part of #49.
