### ISSUE TITLE
Update Health probes matching conditions

### ISSUE THREAD

**Issue by jkljajic** [Azure/application-gateway-kubernetes-ingress#483]
We using httpd (apache 2.4) pods in development with enabled BasicAuth but default status code are setups to 200.399 and on basic auth code is 401 and show unhealthy and the page does not work.
If we change status code range from default to 200-403 all start working.

Mine question is, it is possible to set up matching conditions with some annotations or some other way that we do not need every time to adjust that by hand.

**Comment by delqn** [comment]
Zdravo @jkljajic

It looks like you are health checking an endpoint, which requires authentication.  Then your workaround is to allow for a 401 (error) to be accepted as an indication of a healthy backend. Is my understanding correct?

We don't currently have a way to define a range of status codes accepted. Obviously App Gateway has that config,  I don't see a way to define status code range in the livenessProbe in Kubernetes.  We could add something - first thing that comes to mind is another annotation - but this is not ideal.

Would you be able to create an un-authenticated endpoint on your backend? Something like `/healthz`, which could return 200? (I presume there's no way for you to have an authenticated health probe? You could technically add a custom header to the liveness probe in Kubernetes; If you use token-based auth - that could be the right step forward.)

Another option - you could deploy a side car (or another process within the same container, or another listener within the existing process), which would be on the same pod, but a different port.  Then you could specify the liveness/readiness probe to be on that particular port.  This is a new feature we just merged - https://github.com/Azure/application-gateway-kubernetes-ingress/pull/482 (We'd have to release a new version for this to land in the Helm repository)

Let me know what path you choose. I'll consider the question answered and will close this issue.  If none of these options work for you - re-open the issue and we can dig deeper into finding a solution for this scenario.

**Comment by jkljajic** [comment]
Hi thanks for your swift response and you help a lot, those are all good solutions and I will take one of them for mine issue, only issue I can see is that in any case if some pod is down for some reason and /healtz return 200 clients will also see that problematic page or that pod. It would be nice that we have some option in Ingress that manage and setup that nice feature for matching condition even true annotations.

And one more thanks for clarifying that for now, Appgw ingress do not have that option and maybe will have some day.

BEst Regards
