### ISSUE TITLE
Websocket connections drops at http timeout value

### ISSUE THREAD

**Issue by MarkDNL** [Azure/application-gateway-kubernetes-ingress#491]
We have some issues in successfully implementing our websocket enabled application via AGIC and the AppGW. The websocket connection drops after 30 seconds, which is the default http timeout. When changing the timeout vault, the ws connection drops at the selected value. We submitted a ticket at Azure support, but their suggestion was the following:

> The backend should be available to work on both HTTP and HTTPS. I can see that your app gateway backend pool only has port 80 enabled.

But the [documentation](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/application-gateway/application-gateway-websocket.md) states that the Listeners must be setup correctly:
>You would need both HTTP and HTTPS listeners to support WebSocket and secure WebSocket traffic.

I find it hard to believe that having both HTTP and HTTPS is mandatory for websocket, since this would remove the option to use SSL offloading at the AppGw. The [example in issue 169](https://github.com/Azure/application-gateway-kubernetes-ingress/issues/169#issuecomment-492080890) does not use HTTPS, also your example in the documentation on Websocket does not use HTTPS. I hope you can shed a light on the issue we are experiencing.

We tried the following setup:
```apiVersion: v1
kind: Pod
metadata:
  name: ws
  labels:
    app: ws
spec:
  containers:
    - name: ws
      image: ********.azurecr.io/ws:latest
    - name: nginx
      image: ********.azurecr.io/ws-nginx:latest
      ports:
        - containerPort: 80
        - containerPort: 443
      volumeMounts:
      - name: cert
        mountPath: "/certs"
        readOnly: true
  volumes:
  - name: cert
    secret:
      secretName: cert-1
---
apiVersion: v1
kind: Service
metadata:
  name: ws
spec:
  selector:
    app: ws
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ws
  labels:
    app: ws
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: ws.********.tech
    http:
      paths:
      - backend:
          serviceName: ws
          servicePort: 80
      - backend:
          serviceName: ws
          servicePort: 443
  tls:
  - secretName: cert-1
```
This deploys a small NodeJS application, including Nginx in front, which exposes 80 and 443, and also loads the SSL certificates.

The ws service exposes these two ports. The ingress includes two backend ports: 80 and 443, but this fails at azure-ingress-pod-level:

`Processing event failed:network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 – Original Error: Code="ApplicationGatewayPortNotValidForProtocol" Message="Port 443 is not valid for protocol Http in backendHttpSettingsCollection /subscriptions/********-****-****-****-************/resourceGroups/d-weu-rg-shared-dev/providers/Microsoft.Network/applicationGateways/d-app-ag-dev/backendHttpSettingsCollection/bp-default-ws-443-443-ws." Details=[]`

Removing the backend with port 443 works, but still the WS connection drops after 30 sec.

We tested using `npm i -g ws` and store the following script in a file (e.g. `client.js`):

```
const WebSocket = require('ws');

const ws = new WebSocket('wss://ws.*****.tech', { rejectUnauthorized: false });

ws.on('open', function open() {
  console.log('connected')
});

ws.on('close', function close() {
  console.log('disconnected');
});
```

After running `node client.js` we notice that the connection drops after 30 sec.

Conclusion: Its still unclear whats the issue is, all requirements seem to be fulfilled.

We now ended up using a Keep-Alive ping, which is sent from the server to the client to keep the connection up. But we consider this as a workaround.

**Comment by MarkDNL** [comment]
I noticed in [issue 284](https://github.com/Azure/application-gateway-kubernetes-ingress/issues/284) that backend HTTPS is not supported yet, which explains the error we've encountered.

**Comment by delqn** [comment]
@MarkDNS Could you elaborate on the Keep-Alive ping solution?  I understand that the WebSocket protocol itself sends ping/pong frames.  Is that what you are enabling?

**Comment by awakecoding** [comment]
I think I am facing the same issue with the "regular" Azure Application Gateway (not as an ingress controller for AKS). I get WebSocket disconnections after ~30sec of inactivity, and my WebSocket server default configuration is set to send WebSocket pings every 2 minutes. Is the default idle timeout for the WebSocket connections in the Azure Application Gateway configurable in any way? I'll see if I can lower my 2 minute interval, but 30sec is quite low.

**Comment by Flodu31** [comment]
Hi,
I'm experiencing the same issue, did you find a solution?
Thanks.
Florent

**Comment by juanluelguerre** [comment]
Hi,
Same issue for me. Any solution or workarround?
Thanks too much in advance
Juanlu

**Comment by awakecoding** [comment]
I did manage to figure it out, there is an HTTP request timeout setting which is set to 30 seconds by default. You can increase it by a lot to let's say 3 minutes and it should be good, but this will affect regular HTTP requests as well, not just WebSockets, unfortunately

**Comment by juanluelguerre** [comment]
Good, I've done that and it works for my particular case. 
Thanks a lot

**Comment by juanluelguerre** [comment]
Hi,
Finally to complete successfully my connection through Azure Api Gateway, I developed a Ping & Pong Solution using https://www.npmjs.com/package/reconnecting-websocket.
