### ISSUE TITLE
Support mergeable ingress types

### ISSUE THREAD

**Issue by ducas** [Azure/application-gateway-kubernetes-ingress#50]
**Is your feature request related to a problem? Please describe.**
As a developer I want to control routing rules in each of my applications' repositories so that I don't have to manage many applications from a central ingress.

**Describe the solution you'd like**
NGINX Ingress supports this - https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/mergeable-ingress-types

**Comment by asridharan** [comment]
An interesting feature. Thanks for suggesting this @ducas

**Comment by draychev** [comment]
@ducas We are going to close this issue as we are not planning on implementing mergable ingress. We are however looking into supporting configuration for our default App Gateway listener (see this issue https://github.com/Azure/application-gateway-kubernetes-ingress/issues/77)

**Comment by scottzilla** [comment]
It is not uncommon for multiple components of an application stack to be packaged and deployed together including an ingress to expose those components behind the same hostname (i.e. helm chart, for an app and api component).

Packaging and deploying an ingress definition for each component is quite convenient, and supports DevOps principles suggesting a pipeline per component, etc.
