### ISSUE TITLE
 unable to get service from store, no such service kube-system/kube-controller-manager and kube-scheduler

### ISSUE THREAD

**Issue by Apholisha** [Azure/application-gateway-kubernetes-ingress#505]
Hello,
I've been working on this setup and something odd is happening. 

After a brand new deployment of a cluster and AG, the pod logs are made out of the following entry being generated every 2-3 minutes:
I0903 07:14:20.068704       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 07:14:21.365667       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager

**Note:** Application Gateway works and traffic is redirected as expected. 
It's just the logs are unreadable, as the consist of a mission  identical entries. 
It behaves the same regardless if there is any ingress configuration or not. 

**To Reproduce**
1. Deploy AKS Cluster
2. Deploy pods
3. Deploying the Application Gateway
4. Check pod logs 

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 

Name:               application-gateway-ingress-azure-7b9b56db94-sw5tz
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               aks-nodepool1-11951724-1/10.110.48.35
Start Time:         Tue, 03 Sep 2019 12:11:07 +0200
Labels:             app=ingress-azure
                    pod-template-hash=7b9b56db94
                    release=application-gateway
Annotations:        <none>
Status:             Running
IP:                 10.110.48.57
Controlled By:      ReplicaSet/application-gateway-ingress-azure-7b9b56db94
Containers:
  ingress-azure:
    Container ID:   docker://26cb9cc7a545b05ef146f29b0083a01154a111db7c56bae1c894310972687119
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.8.0
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:9d0e655368098dc64ef00cc93b920df8c959027a167ca82ef7b8408fca45bd3a
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 03 Sep 2019 12:11:09 +0200
    Ready:          True
    Restart Count:  0
    Environment Variables from:
      application-gateway-cm-ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_AUTH_LOCATION:  /etc/Azure/Networking-AppGW/auth/armAuth.json
    Mounts:
      /etc/Azure/Networking-AppGW/auth from networking-appgw-k8s-azure-service-principal-mount (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from application-gateway-sa-ingress-azure-token-xmwfz (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  networking-appgw-k8s-azure-service-principal-mount:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  networking-appgw-k8s-azure-service-principal
    Optional:    false
  application-gateway-sa-ingress-azure-token-xmwfz:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  application-gateway-sa-ingress-azure-token-xmwfz
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                               Message
  ----    ------     ----  ----                               -------
  Normal  Scheduled  117s  default-scheduler                  Successfully assigned default/application-gateway-ingress-azure-7b9b56db94-sw5tz to aks-nodepool1-11951724-1
  Normal  Pulling    116s  kubelet, aks-nodepool1-11951724-1  pulling image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.8.0"
  Normal  Pulled     115s  kubelet, aks-nodepool1-11951724-1  Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.8.0"
  Normal  Created    115s  kubelet, aks-nodepool1-11951724-1  Created container
  Normal  Started    115s  kubelet, aks-nodepool1-11951724-1  Started container

* Output of `kubectl logs <ingress controller>. 

ERROR: logging before flag.Parse: I0903 10:11:09.846629       1 main.go:272] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0903 10:11:09.847981       1 main.go:222] Creating authorizer from file referenced by AZURE_AUTH_LOCATION environment variable: /etc/Azure/Networking-AppGW/auth/armAuth.json
I0903 10:11:10.203167       1 main.go:114] Ingress Controller will observe all namespaces.
I0903 10:11:10.250758       1 context.go:115] k8s context run started
I0903 10:11:10.250795       1 context.go:158] Wait for initial cache sync
I0903 10:11:10.350942       1 context.go:165] initial cache sync done
I0903 10:11:10.350960       1 context.go:117] k8s context run finished
I0903 10:11:10.422748       1 process.go:119] BEGIN AppGateway deployment
I0903 10:11:30.924252       1 process.go:144] Applied App Gateway config in 20.501368853s
I0903 10:11:30.924302       1 process.go:153] cache: Updated with latest applied config.
I0903 10:11:30.924907       1 process.go:156] END AppGateway deployment
I0903 10:11:30.924922       1 worker.go:47] Successfully processed event
I0903 10:11:30.924956       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:30.925000       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:30.981789       1 process.go:119] BEGIN AppGateway deployment
I0903 10:11:31.165134       1 process.go:144] Applied App Gateway config in 183.313571ms
I0903 10:11:31.165163       1 process.go:153] cache: Updated with latest applied config.
I0903 10:11:31.165809       1 process.go:156] END AppGateway deployment
I0903 10:11:31.165825       1 worker.go:47] Successfully processed event
I0903 10:11:31.225359       1 process.go:115] cache: Config has NOT changed! No need to connect to ARM.
I0903 10:11:31.225386       1 worker.go:47] Successfully processed event
I0903 10:11:31.283160       1 process.go:115] cache: Config has NOT changed! No need to connect to ARM.
I0903 10:11:31.283187       1 worker.go:47] Successfully processed event
I0903 10:11:31.339419       1 process.go:115] cache: Config has NOT changed! No need to connect to ARM.
I0903 10:11:31.339445       1 worker.go:47] Successfully processed event
I0903 10:11:31.468135       1 process.go:115] cache: Config has NOT changed! No need to connect to ARM.
I0903 10:11:31.468159       1 worker.go:47] Successfully processed event
I0903 10:11:31.525625       1 process.go:115] cache: Config has NOT changed! No need to connect to ARM.
I0903 10:11:31.525652       1 worker.go:47] Successfully processed event
I0903 10:11:31.577611       1 process.go:115] cache: Config has NOT changed! No need to connect to ARM.
I0903 10:11:31.577638       1 worker.go:47] Successfully processed event
I0903 10:11:31.634827       1 process.go:115] cache: Config has NOT changed! No need to connect to ARM.
I0903 10:11:31.634850       1 worker.go:47] Successfully processed event
I0903 10:11:31.692714       1 process.go:115] cache: Config has NOT changed! No need to connect to ARM.
I0903 10:11:31.692734       1 worker.go:47] Successfully processed event
I0903 10:11:31.746681       1 process.go:115] cache: Config has NOT changed! No need to connect to ARM.
I0903 10:11:31.746703       1 worker.go:47] Successfully processed event
I0903 10:11:31.800999       1 process.go:115] cache: Config has NOT changed! No need to connect to ARM.
I0903 10:11:31.801018       1 worker.go:47] Successfully processed event
I0903 10:11:31.855712       1 process.go:115] cache: Config has NOT changed! No need to connect to ARM.
I0903 10:11:31.855732       1 worker.go:47] Successfully processed event
I0903 10:11:31.910922       1 process.go:115] cache: Config has NOT changed! No need to connect to ARM.
I0903 10:11:31.910943       1 worker.go:47] Successfully processed event
I0903 10:11:31.963846       1 process.go:115] cache: Config has NOT changed! No need to connect to ARM.
I0903 10:11:31.963867       1 worker.go:47] Successfully processed event
I0903 10:11:32.016602       1 process.go:115] cache: Config has NOT changed! No need to connect to ARM.
I0903 10:11:32.016642       1 worker.go:47] Successfully processed event
I0903 10:11:32.071355       1 process.go:115] cache: Config has NOT changed! No need to connect to ARM.
I0903 10:11:32.071383       1 worker.go:47] Successfully processed event
I0903 10:11:32.129812       1 process.go:115] cache: Config has NOT changed! No need to connect to ARM.
I0903 10:11:32.129836       1 worker.go:47] Successfully processed event
I0903 10:11:32.182429       1 process.go:115] cache: Config has NOT changed! No need to connect to ARM.
I0903 10:11:32.182471       1 worker.go:47] Successfully processed event
I0903 10:11:32.182660       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:32.182722       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:32.182735       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:32.182741       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:32.182747       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:32.182751       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:32.182757       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:32.182762       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:32.182784       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:32.182788       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:32.182810       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:32.182821       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:32.182826       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:32.182831       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:32.182837       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:32.182841       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:32.182846       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:32.182851       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:32.182856       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:32.182860       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:32.182865       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:32.182869       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:32.733555       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:34.203819       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:34.756486       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:36.238372       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:36.801149       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:38.277842       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:38.866531       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:40.323738       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:40.892507       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:42.359117       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:42.918367       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:44.391493       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:45.312612       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:46.426187       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:47.302531       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:48.445478       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:49.346340       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:50.486587       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:51.383221       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:52.513040       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:53.415905       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:54.539311       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:55.437821       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:56.566133       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:57.453967       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:11:58.652745       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:11:59.483226       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:12:00.741360       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:12:01.518990       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:12:02.787348       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:12:03.540476       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:12:04.798630       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:12:05.567425       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:12:06.879960       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager
I0903 10:12:07.590422       1 context.go:283] unable to get service from store, no such service kube-system/kube-scheduler
I0903 10:12:08.888886       1 context.go:283] unable to get service from store, no such service kube-system/kube-controller-manager

* Any Azure support tickets associated with this issue.

**Comment by ChristophRichner** [comment]
We face exactly the same issue!

**Comment by ChrisRichner** [comment]
We are facing exactly the same issue.

**Comment by delqn** [comment]
Hi @Apholisha, @ChrisRichner @MartinDoerig 

Even though these log lines are innocuous, they do create a lot of noise.
Here is a PR that will alleviate this issue: https://github.com/Azure/application-gateway-kubernetes-ingress/pull/509
The PR proposes a short-term fix.  I'd like to find a better way to surface similar per-event errors, but with adjustable frequency.

What version of AGIC are you using?  I'm surprised to see these log lines - in the latest version we [deliberately ignore](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/02fabc822df62b4e1e38505c32d1f7e3075cf7a0/pkg/controller/should_process.go#L18) `kube-system` namespace for some events.

**Comment by Apholisha** [comment]
Hi @delqn,
I followed the instructions in the guide and used the 
`helm repo add application-gateway-kubernetes-ingress https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/`

I'm not sure if I'm reading this right but wouldn't the entry be ignored if the pod creating the entry is a kube-system?  So if it's a default namespace pod complaining about no being able to reach a system one wouldn't it still come from the default namespace?

**Comment by delqn** [comment]
Hi @Apholisha, @ChrisRichner @MartinDoerig  we released version [0.9.0-rc2](https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/0.9.0-rc2)

One of the improvements in this release is lowering the log noise (as well as ignoring events from `kube-system`)

Would you be so kind to upgrade to 0.9.0-rc2 and give ups feedback? Instructions on how to upgrade using `helm` are here: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/how-tos/helm-upgrade.md

**Comment by delqn** [comment]
@ChrisRichner @MartinDoerig  @brent-robinson  -- based on @Apholisha's report that v0.9.0-rc2 solves the log noise - I'm going to close this issue.
