### ISSUE TITLE
Is there an ARM Greenfield deployment that supports Windows containers with node pools?

### ISSUE THREAD

**Issue by SteveCurran** [Azure/application-gateway-kubernetes-ingress#508]
Seems that the ARM template being used for greenfield deployment does not support AKS node pools required for Windows containers.

**Comment by delqn** [comment]
@SteveCurran You are indeed right. The deployment template is a quick way to spin-up an environment in which one could try the Ingress Controller.  Were you able to modify it to suite your needs? Would you be able to update the repo with your changes?

Were you able to manually create an AKS cluster supporting Windows containers and install the Ingress Controller in it?

**Comment by akshaysngupta** [comment]
@SteveCurran Please reopen this issue if you need more assistance.
