### ISSUE TITLE
Error while parsing cluster resource ID for tagging

### ISSUE THREAD

**Issue by DeanPH** [Azure/application-gateway-kubernetes-ingress#510]
**Describe the bug**
I've come across the following error in the log file of the Ingress Controller when verbose logging is enabled (level 5). It happens when the Ingress Controller is reconfiguring the Application Gateway.

**To Reproduce**
Deploy AGIC 0.9.0-rc1 and deploy any app that forces AGIC to reconfigure Application Gateway.

**Error Message**
```[prod1-smapps-ingress-azure-694b9fc6c9-pjkwq] I0904 09:18:00.448809       1 configbuilder.go:202] Error while parsing cluster resource ID for tagging: infrastructure resource group name: mc_prod1-stack-smapps_prod1-smapps_westeurope is expected to be of format MC_ResourceGroup_ResourceName_Location```

This is odd because the resource group is prod1-stack-smapps, resource name is prod1-smapps and location is westeurope. I'm not sure where MC comes from and if it's specifically looking for uppercase `MC` and it's seeing a lower case mc, or if the issue is something else.

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . 
```
Name:           prod1-smapps-ingress-azure-694b9fc6c9-pjkwq
Namespace:      ingress-controller
Priority:       0
Node:           aks-smapps-18787795-vmss000000/10.117.69.4
Start Time:     Wed, 04 Sep 2019 10:06:08 +0100
Labels:         aadpodidbinding=prod1-smapps-ingress-azure
                app=ingress-azure
                pod-template-hash=694b9fc6c9
                release=prod1-smapps
Annotations:    <none>
Status:         Running
IP:             10.117.69.31
Controlled By:  ReplicaSet/prod1-smapps-ingress-azure-694b9fc6c9
Containers:
  ingress-azure:
    Container ID:   docker://1930bb16dcc8b03324bdbc8059e769471f9be75be2beafdbc1c8c0b4529f53d9
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.9.0-rc1
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:fe4fd98dd3b45fbf3b9681ba3e76896b315606ef683dfaaafb0763b8719184af
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 04 Sep 2019 10:06:14 +0100
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      prod1-smapps-cm-ingress-azure  ConfigMap  Optional: false
    Environment:                     <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from prod1-smapps-sa-ingress-azure-token-2dqww (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  prod1-smapps-sa-ingress-azure-token-2dqww:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prod1-smapps-sa-ingress-azure-token-2dqww
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                                     Message
  ----    ------     ----  ----                                     -------
  Normal  Scheduled  18m   default-scheduler                        Successfully assigned ingress-controller/prod1-smapps-ingress-azure-694b9fc6c9-pjkwq to aks-smapps-18787795-vmss000000
  Normal  Pulling    18m   kubelet, aks-smapps-18787795-vmss000000  Pulling image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.9.0-rc1"
  Normal  Pulled     18m   kubelet, aks-smapps-18787795-vmss000000  Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.9.0-rc1"
  Normal  Created    18m   kubelet, aks-smapps-18787795-vmss000000  Created container ingress-azure
  Normal  Started    18m   kubelet, aks-smapps-18787795-vmss000000  Started container ingress-azure
```

* Output of `kubectl logs <ingress controller>. 
```
I0904 09:19:04.711919       1 requestroutingrules.go:79] Binding rule rr-443 to listener fl-443
I0904 09:19:04.851972       1 configbuilder.go:202] Error while parsing cluster resource ID for tagging: infrastructure resource group name: mc_prod1-stack-smapps_prod1-smapps_westeurope is expected to be of format MC_ResourceGroup_ResourceName_Location
I0904 09:19:04.853732       1 process.go:126] cache: Config has NOT changed! No need to connect to ARM.
I0904 09:19:04.853754       1 worker.go:37] Successfully processed event
I0904 09:19:04.853778       1 context.go:289] unable to get service from store, no such service default/aad-pod-identity-mic
I0904 09:19:04.853786       1 worker.go:27] Skipping event: Skipping endpoints default/aad-pod-identity-mic as it is not used by any ingress
I0904 09:19:04.853812       1 context.go:289] unable to get service from store, no such service default/aad-pod-identity-mic
I0904 09:19:04.853820       1 worker.go:27] Skipping event: Skipping endpoints default/aad-pod-identity-mic as it is not used by any ingress
```

**Comment by delqn** [comment]
@DeanPH Sorry if the error seems alarming.  It is not.  The error is emitted here: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/9cfd48f80dc3d47bf7211f7449d58b1619911bd9/pkg/azure/azure.go#L45

This is a function which _attempts_ to add a User Tag to the App Gateway in question here. The user tag would have contained the Azure ID of the AKS it is associated with.

The resource group mentioned in the error message, starting with MC, is something AKS creates automatically.  You can read more about this here:  https://docs.microsoft.com/en-us/azure/aks/faq#why-are-two-resource-groups-created-with-aks

Is this negatively affecting the Ingress Controller in your setup?  If not - I'd love to close this issue. (I've opened up a ticket for us to find a better approach vs string matching)

**Comment by DeanPH** [comment]
@delqn Thanks for the additional info. No it doesn't affect configuration of the AppGW just get worried when seeing "Error" as a message.

Looking at the snippet of code you posted it looks like my first guess may have be correct.

`	split := strings.Split(string(resourceGroup), "_")
	if len(split) != 4 || split[0] != "MC" {
		logLine := fmt.Sprintf("infrastructure resource group name: %s is expected to be of format MC_ResourceGroup_ResourceName_Location", string(resourceGroup))
		return "", errors.New(logLine)
	}`

The string compare of `split[0]` != "MC"` but in my case split[0] is "mc", as per log posted on top: mc_prod1-stack-smapps_prod1-smapps_westeurope

**I think line 44 needs of that file to be changed to the following**
`	if len(split) != 4 || strings.ToUpper(split[0]) != "MC" {`

I tested with this:

`package main

import (
	"fmt"
	"strings"
)

func main() {
	resourceGroup := "mc_prod1-stack-smapps_prod1-smapps_westeurope"
	split := strings.Split(string(resourceGroup), "_")
	if len(split) != 4 || strings.ToUpper(split[0]) != "MC" {
		fmt.Println("infrastructure resource group name:", string(resourceGroup),"is expected to be of format MC_ResourceGroup_ResourceName_Location")
	} else {
	  fmt.Println("Matches")
	}
}`

Thanks!

**Comment by delqn** [comment]
@DeanPH - this is fixed on master!  Thank you so much for digging into the code! We'll cut a new release and let you know so you can deploy!

Thanks for reporting this!
