### ISSUE TITLE
Issue using both public and private listener

### ISSUE THREAD

**Issue by DeanPH** [Azure/application-gateway-kubernetes-ingress#511]
**Describe the bug**
Something has changed in the latest version of the AGIC (v0.9.0-rc1) in terms of using both public/private listeners at the same time. v0.8.0 works fine. When you have both public and private listener ingresses setup, the AGIC fails to configure the Application Gateway.

**To Reproduce**
Deploy latest AGIC 0.9.0-rc1
Deploy this sample-app.yaml

```apiVersion: v1
kind: Secret
metadata:
  name: aks-ingress-tls-certs
  namespace: yeti
data:
  tls.crt: "xxxxxxxx"
  tls.key: "xxxxxxxx"
type: kubernetes.io/tls
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kleenex-external
  namespace: yeti
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  tls:
  - secretName: aks-ingress-tls-certs
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: kleenex
          servicePort: 443
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kleenex-internal
  namespace: yeti
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: "true"
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: kleenex
          servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: yeti
spec:
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: microsoft/dotnet-samples:aspnetapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
  replicas: 3
---
apiVersion: v1
kind: Service
metadata:
  name: kleenex
  namespace: yeti
spec:
  selector:
    app: sample-app
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80
```

**Ingress Controller details**
Set logging to level 5 and observe the error:

```E0904 15:49:44.339600       1 worker.go:34] Processing event failed:network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestFormat" Message="Cannot parse the request." Details=[{"code":"DuplicateResourceName","message":"Resource /subscriptions//resourceGroups//providers/Microsoft.Network/applicationGateways/ has two child resources with the same name (rr-80)."}]```

**Comment by delqn** [comment]
@DeanPH We merged a few changes, which we believe addresses the issue you describe here.
We are going to release v 0.9.0-rc2, which will contain these fixes.
The issue here is closed since we referenced it in https://github.com/Azure/application-gateway-kubernetes-ingress/pull/525
I'll update the issue here once v0.9.0-rc2 is out so you can test and give us feedback if possible!

**Comment by DeanPH** [comment]
Thank you @delqn . Release v0.9.0-rc2 works great! It resolved another ingress issue to do with listeners and routing rules that I hadn't logged yet. 

I've done a bit of testing so far and things are looking good with this release 👍
