### ISSUE TITLE
Ingress controller creates backend pool based on pod IP not the service IP.

### ISSUE THREAD

**Issue by SteveCurran** [Azure/application-gateway-kubernetes-ingress#524]
**Describe the bug**
When I create the following ingress, service and deployment, the ingress controller creates a backend pool for the application gateway using the ip address of the pod and not the ip address of the service. The pod ip is not accessible, whereas the internal load balancer ip for the service is. So I have to manually go in and change the ip address on the backend pool. Logs show success setting up gateway configuration. This is an AKS cluster running 1.14.5, with two node pools, one linux another windows. 

**To Reproduce**
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pdpdartapp
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /*
      - backend:
          serviceName: pdpdart
          servicePort: 25000
---
apiVersion: v1
kind: Service
metadata:
  name: pdpdart
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 25000
    targetPort: 25000
  selector:
    app: pdpdartapp
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pdpdart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdpdartapp
  template:
    metadata:
      labels:
        app: pdpdartapp
    spec:
      containers:
      - name: pdpdart
        image: smc908/testpdp:1809
        imagePullPolicy: Always
        ports:
        - containerPort: 25000
      nodeSelector:
         beta.kubernetes.io/os: windows

**Ingress Controller details**
Name:           fantastic-elk-ingress-azure-f8f564d66-cdhvz
Namespace:      default
Priority:       0
Node:           aks-agentpool-35064155-vmss000000/10.0.0.4
Start Time:     Thu, 05 Sep 2019 14:03:01 +0000
Labels:         aadpodidbinding=fantastic-elk-ingress-azure
                app=ingress-azure
                pod-template-hash=f8f564d66
                release=fantastic-elk
Annotations:    <none>
Status:         Running
IP:             10.0.0.14
Controlled By:  ReplicaSet/fantastic-elk-ingress-azure-f8f564d66
Containers:
  ingress-azure:
    Container ID:   docker://310e7ca3c899ff4f49606b790e44435c7874d184895fd2d66ec17563ea8a68ae
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.8.0
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:9d0e655368098dc64ef00cc93b920df8c959027a167ca82ef7b8408fca45bd3a
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 05 Sep 2019 14:03:15 +0000
    Ready:          True
    Restart Count:  0
    Environment Variables from:
      fantastic-elk-cm-ingress-azure  ConfigMap  Optional: false
    Environment:                      <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from fantastic-elk-sa-ingress-azure-token-qq8n7 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  fantastic-elk-sa-ingress-azure-token-qq8n7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  fantastic-elk-sa-ingress-azure-token-qq8n7
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

**Comment by delqn** [comment]
Hi @SteveCurran,

A few questions to understand the problem:
 - Is the App Gateway on the same Virtual Network as AKS
    - You can see what virtual network your App Gateway is from [Azure Portal](https://portal.azure.com/) -- `Application Gateway` -- `Overview` -- `Virtual network/subnet`
    - See what vnet AKS is in -- find one of the `aks-agentpool-...` Virtual Machines that back your AKS and note the `Virtual network/subnet` in the Overview pane.
 
  - Is advanced networking enabled on your AKS? You can find out by navigating to the Kubernetes Service -- Networking pane -- in `Network profile` I'd expect to see `Type (plugin)
Advanced (Azure CNI)`


The idea behind the project here in this repository (Application Gateway Ingress Controller) is indeed to expose the Kubernetes Pods directly to App Gateway, bypassing the internal kubernetes load balancer.

The App Gateway Ingress Controller requires the following:
  -- your [App Gateway](https://azure.microsoft.com/en-us/services/application-gateway/) must be in the same [VNet](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-overview) as your AKS
  -- AKS must have [Advanced Networking(https://docs.microsoft.com/en-us/azure/aks/concepts-network#azure-cni-advanced-networking) enabled  (Azure CNI)

A simplified way to explain how App Gateway Ingress Controller works - fetches the IP addresses of your pods (much like `kubectl get endpoints`) and uses these to configure the backend pools of your App Gateway.  App Gateway then is able to perform load balancing, URL-based routing, cookie based affinity etc. directly to the pods. Without direct access to the pods, where their IPs are listed in the backend pools, App Gateway won't be able to provide most of the L7 load balancing [features it has](https://docs.microsoft.com/en-us/azure/application-gateway/overview). And also since this networking model bypasses the extra hop of going through the internal load balancer - you get lower latency.

Would love to know if this clarifies things and how you choose to configure your AKS!

**Comment by SteveCurran** [comment]
@delqn thanks for the response. I used the greenfield ARM template in the examples but made changes  to enable vm scale sets to support node pools. I checked the configuration and the app gateway and aks cluster are in the same vnet and two different subnets which is expected. Advanced networking Azure CNI is enabled. Unfortunately, when the gateway health probe tries to connect directly to the pod ip there is no response. 
So should I not define a service component at all? 
Change the service to use type "NodePort"?
Could this have something to do with using "vm scale sets" where you are allocated a pool of possible IP addresses rather one for each VM node? Please note RBAC is not enabled.

**Comment by delqn** [comment]
@SteveCurran  So it seems that there is connectivity between App Gateway and the pods.
And just to confirm - here is what I'd expect to see as far as IPs:

```$ kubectl get pods -o wide

NAME                                    READY   STATUS    RESTARTS   AGE   IP            NODE                                NOMINATED NODE   READINESS GATES
ingress-azure-5f6f75c58-lm64w           0/1     Running   0          73s   10.240.0.42   aks-agentpool-13682822-vmss000001   <none>           <none>
mic-55ff8c886-96bhk                     1/1     Running   0          95s   10.240.0.46   aks-agentpool-13682822-vmss000001   <none>           <none>
mic-55ff8c886-wfbcm                     1/1     Running   0          95s   10.240.0.15   aks-agentpool-13682822-vmss000000   <none>           <none>
nmi-dq62x                               1/1     Running   0          96s   10.240.0.66   aks-agentpool-13682822-vmss000002   <none>           <none>
nmi-k9t6g                               1/1     Running   0          96s   10.240.0.35   aks-agentpool-13682822-vmss000001   <none>           <none>
nmi-p75cw                               1/1     Running   0          96s   10.240.0.4    aks-agentpool-13682822-vmss000000   <none>           <none>
websocket-deployment-5cbc7b7c5b-6lk2w   1/1     Running   1          67s   10.240.0.17   aks-agentpool-13682822-vmss000000   <none>           <none>
```
```
$ kubectl get nodes -o wide

NAME                                STATUS   ROLES   AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-agentpool-13682822-vmss000000   Ready    agent   44h   v1.15.3   10.240.0.4    <none>        Ubuntu 16.04.6 LTS   4.15.0-1055-azure   docker://3.0.6
aks-agentpool-13682822-vmss000001   Ready    agent   44h   v1.15.3   10.240.0.35   <none>        Ubuntu 16.04.6 LTS   4.15.0-1055-azure   docker://3.0.6
aks-agentpool-13682822-vmss000002   Ready    agent   44h   v1.15.3   10.240.0.66   <none>        Ubuntu 16.04.6 LTS   4.15.0-1055-azure   docker://3.0.6
```

The Pod that I deployed `websocket-deployment-5cbc7b7c5b-6lk2w` (`10.240.0.17`) is on the same subnet as the actual Nodes (`aks-agentpool-13682822-vmss000000` --> `10.240.0.4`)

I hope you see something similar in your setup.
Do you see these exact same IP addresses in the App Gateway Backend Pools - you could check via [the portal](https://portal.azure.com)?
Now if that good, then the trouble must come from Health Probes.

Could you share a bit about the health probes?  Are these HTTP GET? Do you expect these to return 200 OK?  Is there a requirement for something to be in the header for the backend to return 200 OK?  Are the health probes on port 80?

**Comment by akshaysngupta** [comment]
Please reopen this issue if you need further help.
