### ISSUE TITLE
Improve speed port lookup in backendhttpsettings

### ISSUE THREAD

**Issue by Baklap4** [Azure/application-gateway-kubernetes-ingress#528]
**Describe the bug**
Currently we have 34 ingresses and services defined with each ingress having 2 hosts and 2 path routes.
When we change or add a route to the config it takes over 2 minutes to get the new route live.
We've noticed lots of the same info logs (`I0911 14:12:10.048335       1 backendhttpsettings.go:159] resolving port name stats`) giving us an idea there are [way too many **nested** loops](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/0.8.0/pkg/appgw/istio_settings.go#L23-L26).

Is there a way to enhance this and improve the speed of such a tiny change?
The performance of the gateway is drasticly slow when more routes are added...

**To Reproduce**
* Create a new path-based route
* wait for more than 2 minutes
This timing will be increased the more routes and rules you add.

**Ingress Controller details**
```
Name:           ingress-azure-f66858b6b-zbm45
Namespace:      default
Priority:       0
Node:           aks-agentpool-75099453-0/172.16.11.4
Start Time:     Mon, 02 Sep 2019 16:00:21 +0200
Labels:         aadpodidbinding=ingress-azure
                app=ingress-azure
                pod-template-hash=f66858b6b
                release=ingress-azure
Annotations:    <none>
Status:         Running
IP:             172.16.11.10
Controlled By:  ReplicaSet/ingress-azure-f66858b6b
Containers:
  ingress-azure:
    Container ID:   docker://754e88caf6e7a6227b2a0c6a09b4c2be98cf13fdb21e2308454d172dea681dd3
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.8.0
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:9d0e655368098dc64ef00cc93b920df8c959027a167ca82ef7b8408fca45bd3a
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Mon, 02 Sep 2019 16:00:24 +0200
    Ready:          True
    Restart Count:  0
    Environment Variables from:
      ingress-azure  ConfigMap  Optional: false
    Environment:     <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-azure-token-2fqnv (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  ingress-azure-token-2fqnv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-azure-token-2fqnv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```
* Output of `kubectl logs <ingress controller>.`
[log.txt](https://github.com/Azure/application-gateway-kubernetes-ingress/files/3601498/log.txt)

**Comment by delqn** [comment]
@Baklap4 This is great feedback!
I'm going to take a look at that ASAP.
You pointed me to a function within our experimental Istio controller. Are you actually using this Ingress Controller within an Istio installation?
If not - the relevant code that emits this message is here: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/0.8.0/pkg/appgw/backendhttpsettings.go#L159

Would you be so kind to provide a sanitized version of one of these 34 ingresses?  I'd love to simulate the environment in which you are running this.

**Comment by delqn** [comment]
Hi @Baklap4 
I tested a scenario similar to what you are describing. As you pointed out with version 0.8.0 creating App Gwy config is indeed slower than it could be.
We just released version [0.9.0-rc2](https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/0.9.0-rc2) - this utilizes memoization on functions that are often used and so I noticed significant improvement in time it takes to gen the config.
I do think we can do better in the area of the code you pointed out, and started work on this: https://github.com/Azure/application-gateway-kubernetes-ingress/compare/delqn/http_settings_perf?expand=1

I think 0.9.0-rc2 is already fast.

Would you be able to test 0.9.0-rc2 and report back?

Also regarding this, or any other areas of the codebase that you think could be improved - PRs are more than welcome!

I'll keep this issue open, but would love to close it when you confirm that the latest version is faster for your setup!

**Comment by Baklap4** [comment]
Heey @delqn 
We've tried out v0.9.0-rc2 and it's indeed way faster and a lot less cpu usage. We were hovering around 40-50% cpu usage and are currently with everything deployed around 0-3%.

However due to upgrading to v0.9.0-rc2 we had to update our tls configuration. We have multiple namespaces and defined one tls config in `namespaceA` while ingress in `namespaceB` was also using this tls configuration but was not defined:
IngressA in namespace A
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: azure/application-gateway
  creationTimestamp: "2019-09-04T13:30:38Z"
  generation: 1
  labels:
    app: other-controller
    chart: app-0.2.7
    heritage: Tiller
    release: other-controller
  name: other-controller
  namespace: namespaceA
  resourceVersion: "2799276"
  selfLink: /apis/extensions/v1beta1/namespaces/namespaceA/ingresses/other-controller
  uid: 2ec69625-cf18-11e9-9b54-4e9e722f0d3c
spec:
  rules:
  - host: test.domain.net
    http:
      paths:
      - backend:
          serviceName: other-controller
          servicePort: 5000
        path: /other-path
  tls:
  - hosts:
    - test.domain.net
    secretName: domain-tls
    
status:
  loadBalancer: {}
```

Ingress B in Namespace B
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: azure/application-gateway
  creationTimestamp: "2019-09-04T13:30:38Z"
  generation: 1
  labels:
    app: differ-controller
    chart: app-0.2.7
    heritage: Tiller
    release: differ-controller
  name: differ-controller
  namespace: namespaceB
  resourceVersion: "2799276"
  selfLink: /apis/extensions/v1beta1/namespaces/namespaceB/ingresses/differ-controller
  uid: 2ec69625-cf18-11e9-9b54-4e9e722f0d3c
spec:
  rules:
  - host: test.domain.net
    http:
      paths:
      - backend:
          serviceName: differ-controller
          servicePort: 5000
        path: /differ-path
status:
  loadBalancer: {}
```

The `domain-tls` secret was defined in `namespaceA`.

This was a valid configuration for `v.0.8.0` however when upgrading to `v.0.9.0-rc2` this resulted in a bad gateway with the message: 
```
RedirectWithNoTLS' ignoring Ingress namespaceB/differ-controller as it has an invalid spec. It is annotated with ssl-redirect: true but is missing a TLS secret. Please add a TLS secret or remove ssl-redirect annotation
```

Since secrets can't be shared between namespaces as per kubernetes ingress spec we had to copy our secret to `namespaceB` and configure a tls section.

Copying the secret was done by this command:
```
kubectl get secret domain-tls --namespace=namespaceA --export -o yaml | kubectl apply --namespace=join-data-namespaceB -f -
```

The ingress for Ingress2 looks now like this to make it work:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: azure/application-gateway
  creationTimestamp: "2019-09-04T13:30:38Z"
  generation: 1
  labels:
    app: differ-controller
    chart: app-0.2.7
    heritage: Tiller
    release: differ-controller
  name: differ-controller
  namespace: namespaceB
  resourceVersion: "2799276"
  selfLink: /apis/extensions/v1beta1/namespaces/namespaceB/ingresses/differ-controller
  uid: 2ec69625-cf18-11e9-9b54-4e9e722f0d3c
spec:
  rules:
  - host: test.domain.net
    http:
      paths:
      - backend:
          serviceName: differ-controller
          servicePort: 5000
        path: /differ-path
  tls:
  - hosts:
    - test.domain.net
    secretName: domain-tls
status:
  loadBalancer: {}
```

do you have any suggestions how to do this better or is this is an 'okay-ish' solution? I liked the idea to have one secret which could be used as configuration for other ingresses.. but somehow that seems impossible now..

**Comment by akshaysngupta** [comment]
@Baklap4 You can use the new annotation [`appgw-ssl-certificate`](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/annotations.md#appgw-ssl-certificate) to store the certificate on Application Gateway directly and referencing it in the ingress.
