### ISSUE TITLE
Only 502 responses for a few minutes after backend pod is changed.

### ISSUE THREAD

**Issue by radekba** [Azure/application-gateway-kubernetes-ingress#532]
**Describe the bug**
I'm not sure where the problem is but always after any change in backend ip address I have to wait at least 5 minutes to service become accessible. In that 5 minutes I see only 502 responses. 

**To Reproduce**

**Ingress Controller details**
```
Name:           ingress-azure-64cc679bb-6g9mv
Namespace:      default
Priority:       0
Node:           aks-nodepool1-76381565-2/10.0.0.132
Start Time:     Thu, 12 Sep 2019 11:33:06 +0100
Labels:         app=ingress-azure
                pod-template-hash=64cc679bb
                release=ingress-azure
Annotations:    <none>
Status:         Running
IP:             10.0.0.150
Controlled By:  ReplicaSet/ingress-azure-64cc679bb
Containers:
  ingress-azure:
    Container ID:   docker://bc429c4b3a398c98eb7e35037c8dc3a8629d17d09996b1bae01d6473fe752244
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.7.1
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:7474a032ed48a82105b960844e32fef203067a60e9a46a5c7a298b103c38725c
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 12 Sep 2019 11:33:08 +0100
    Ready:          True
    Restart Count:  0
    Environment Variables from:
      ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_AUTH_LOCATION:  /etc/Azure/Networking-AppGW/auth/armAuth.json
    Mounts:
      /etc/Azure/Networking-AppGW/auth from networking-appgw-k8s-azure-service-principal-mount (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-azure-token-plc9p (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  networking-appgw-k8s-azure-service-principal-mount:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  networking-appgw-k8s-azure-service-principal
    Optional:    false
  ingress-azure-token-plc9p:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-azure-token-plc9p
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                               Message
  ----    ------     ----  ----                               -------
  Normal  Scheduled  18m   default-scheduler                  Successfully assigned default/ingress-azure-64cc679bb-6g9mv to aks-nodepool1-76381565-2
  Normal  Pulling    18m   kubelet, aks-nodepool1-76381565-2  Pulling image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.7.1"
  Normal  Pulled     18m   kubelet, aks-nodepool1-76381565-2  Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.7.1"
  Normal  Created    18m   kubelet, aks-nodepool1-76381565-2  Created container ingress-azure
  Normal  Started    18m   kubelet, aks-nodepool1-76381565-2  Started container ingress-azure

```
* Output of `kubectl logs <ingress controller>. 
* Any Azure support tickets associated with this issue.

**Comment by Baklap4** [comment]
probably linked to #528

**Comment by radekba** [comment]
Thanks! I was trying to upgrade to 0.9.0-rc2 but it looks like I have to upgrade my Application Gateway to V2 first.
I think it's a combination of both issues you mentioned. Sometimes the change in pods is being reflected quicker than 5 minutes in App Gateway change. I have to check backend health, it might be a problem here. Can you recommend what is the best value for periodSeconds, timeoutSeconds and initialDelaySeconds?

**Comment by Baklap4** [comment]
The best values are dependant on your program: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
> * initialDelaySeconds: Number of seconds after the container has started before liveness or readiness probes are initiated.
>* periodSeconds: How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
>* timeoutSeconds: Number of seconds after which the probe times out. Defaults to 1 second. Minimum value is 1.
>* successThreshold: Minimum consecutive successes for the probe to be considered successful after having failed. Defaults to 1. Must be 1 for liveness. Minimum value is 1.
>* failureThreshold: When a Pod starts and the probe fails, Kubernetes will try failureThreshold times before giving up. Giving up in case of liveness probe means restarting the container. In case of readiness probe the Pod will be marked Unready. Defaults to 3. Minimum value is 1.

**Comment by radekba** [comment]
> The best values are dependant on your program

Yeah, I know general rules. But any recommendations when integrating with Application Gateway?

Thanks

**Comment by Baklap4** [comment]
Application gateway reads these values and uses them to test out your probes.
If your application takes long to start and isn't able to serve traffic yet, i'd suggest to set a higher initialDelaySeconds.
As for the `periodSeconds` i'd leave them be (at 10 seconds) unless the whole ready/live-check takes longer than 10 seconds.
The application gateway will timeout after 1 second by default so your healthchecks should return within that timewindow. I'd suggest to increase this if the ready/live-check takes longer than 1 second. But it shouldn't be higher than the period seconds.

As for all of these timings you should play with them to get the correct timings. Try measuring how long it takes for your application to actually start.

As for the gateway, a liveness check checking the website externally needs the config to be applied already to the gateway. Right now on our side with 34 ingresses it takes around 10-20 seconds before an update is applied so our liveness check has an initial delay of 60 seconds.

Also make sure the liveness check initial delay is greater or equal to the time of the initialDelay of the readiness check since else the checks would run in circles... with a failing liveness check causing the application to restart and redo the readiness and liveness check...

**Comment by delqn** [comment]
@radekba It sounds like you are using App Gateway V1? When we are building the Ingress Controller we target specifically V2 and don't support V1, although as you can see App Gwy works for the most port.

I encourage you to upgrade to App Gateway V2!

It takes much longer to apply updates to App Gateway V1.  Most likely most of the slow update issues are going to disappear once you upgrade to App Gwy v2 and AGIC v0.9.0-rc2

The liveness/readiness probe config @Baklap4 is proposing is also great and I agree it should be applied as well.

**Comment by radekba** [comment]
@delqn @Baklap4 Thank you for your help! With V2 system is significantly faster. Changes are applied after few seconds and not minutes. After upgrade AGIC to v0.9.0-rc2 additional small improvement in time is visible.

Thanks
radekba
