### ISSUE TITLE
Documentation issue for HTTP->HTTPS redirect

### ISSUE THREAD

**Issue by Uriil** [Azure/application-gateway-kubernetes-ingress#540]
**Describe the bug**
In the [tutorial](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/tutorial.md#expose-services-over-https) there is statement:

> Now the guestbook application will be available on both HTTP and HTTPS.

And provided Ingress sample is:

    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: guestbook
      annotations:
        kubernetes.io/ingress.class: azure/application-gateway
    spec:
      tls:
        - secretName: <guestbook-secret-name>
      rules:
      - http:
          paths:
          - backend:
              serviceName: frontend
              servicePort: 80

However with this configuration only HTTPS Listener will be created on specified Application Gateway.

In [ingress_rules.go](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/pkg/appgw/ingress_rules.go)  I found comment:

> If a certificate is available we enable only HTTPS; unless ingress is annotated with ssl-redirect - then we enable HTTPS as well as HTTP, and redirect HTTP to HTTPS.

Which means that for provided Ingress controller will listen only to HTTPS port(and that's actual behavior).

So to fix this issue we should either changed above statement or add extra annotation:

    annotations:
        kubernetes.io/ingress.class: azure/application-gateway
        appgw.ingress.kubernetes.io/ssl-redirect: true

**Comment by krishnadce** [comment]
The annotation is not working for me. I added  `appgw.ingress.kubernetes.io/ssl-redirect: true` and the service changed https to http. On the APP GW side, the rules changed from rr-443 to rr-80.

When I attempt the url with https, no response and it is timed out.
When I attempt the url on http, response is 502 Bad gateway
