### ISSUE TITLE
watchNamespace only processes one namespace when multiple are specified

### ISSUE THREAD

**Issue by abenck** [Azure/application-gateway-kubernetes-ingress#560]
**Describe the bug**
Deploying an AGIC to watch multiple namespaces only processes one namespace. Testing each namespace independently does work.

**To Reproduce**
Create WAF V2 Application Gateway with 2 replicas
Configure aaPodIdentity with Reader and Contributor roles in IAM for AG
Create an AGIC with aaPodIdentity, rbac enabled: true, and watchNamespace: test1,test2

**Ingress Controller details**
Tried with AGIC version 0.8.0 & 0.9.0
Azure controller logs show it's recognizing the configuration with this:
'Ingress Controller will observe the following namespaces:test1,test2'

Setting APPGW_VERBOSITY_LEVEL to 5 doesn't mention the other namespace after outputting the observation line above. It continues processing only one namespace and completes successfully.

I'm able to configure the AG with each of the namespaces independently, but not at the same time with multiple namespace. I reviewed the ingress resources and configured them with different domains to rule out conflicts.

**Comment by abenck** [comment]
**Update

I tried again with AGIC 0.10.0 and I'm still unable to get multiple namespace support working. Here's the example and test ingress resources used along with the helm config. Our use case is a staging and production namespaces with the same applications.

[example-ing.txt](https://github.com/Azure/application-gateway-kubernetes-ingress/files/3799654/example-ing.txt)
[test-ing.txt](https://github.com/Azure/application-gateway-kubernetes-ingress/files/3799655/test-ing.txt)
[helm-config-debug-redacted.txt](https://github.com/Azure/application-gateway-kubernetes-ingress/files/3799656/helm-config-debug-redacted.txt)

installed with:
> helm install --name debug-azure-ingress --version 0.10.0 -f helm-config-debug.yaml application-gateway-kubernetes-ingress/ingress-azure

AGIC version
> 0.10.0
> AG with WAF V2

Aks cluster version
> 1.14.6

helm version 
> v2.15.2

**Comment by abenck** [comment]
@draychev 
Setting "KUBERNETES_WATCHNAMESPACE": "" in the AGIC config map successfully watches and process all ingress resources in all namespaces, but setting it to test,example only watches the test namespace.

Is there a known bug for this and is there anything I can use in addition to "APPGW_VERBOSITY_LEVEL" to get to the bottom of this?

**Comment by draychev** [comment]
@abenck Thanks for helping troubleshoot this.
I'm working on this - will have a version for you to test with soon.

**Comment by abenck** [comment]
@draychev Great, thank you! If you need any additional info please let me know.

**Comment by draychev** [comment]
Hi @abenck,
Thanks for your patience with this issue.
We released version `0.10.1-rc1` of AGIC, which we believe addresses the issue you ran into:  https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/0.10.1-rc1

Would you be so kind to upgrade to this release candidate: `0.10.1-rc1`

```bash
helm repo update
helm search -l application-gateway-kubernetes-ingress
helm list
helm upgrade <XYZ> \
    --version 0.10.1-rc1 \
    application-gateway-kubernetes-ingress/ingress-azure \
    --debug
```

Would you be so kind to test the new version and let us know whether it was able to observe the listed namespaces?

**Comment by abenck** [comment]
Hey @draychev, thank you for handling this! I'll deploy a testing environment to try this out later today and get back to you.

**Comment by abenck** [comment]
Looks like the Application Gateway is configured for both namespaces, thanks for fixing this!
