### ISSUE TITLE
docs rendering is wonky

### ISSUE THREAD

**Issue by sblack4** [Azure/application-gateway-kubernetes-ingress#594]
**Describe the bug**
The yaml in bash toward the bottom of this document was being rendered incorrectly on the docs site. I changed the style to be in line with [your websockets page](https://azure.github.io/application-gateway-kubernetes-ingress/how-tos/websockets/) which renders it correctly. 

![image](https://user-images.githubusercontent.com/15880760/66355820-ab1fbb00-e936-11e9-82bf-631c3bd0c903.png)

Also the indentation under [Install AAD Pod Identity](https://azure.github.io/application-gateway-kubernetes-ingress/setup/install-new/#install-aad-pod-identity) had the bulleted list being rendered as a code block. 

![image](https://user-images.githubusercontent.com/15880760/66355904-efab5680-e936-11e9-9ae3-f2be0e83d097.png)
**To Reproduce**
Visit https://azure.github.io/application-gateway-kubernetes-ingress/setup/install-new/

**Ingress Controller details**
NA

**Comment by sblack4** [comment]
It looks like my PR solved the indentation issue but not the `yaml` formatting issue:
![image](https://user-images.githubusercontent.com/15880760/66486938-841dd200-ea79-11e9-800d-752499f00ac0.png)

**Comment by akshaysngupta** [comment]
There was a whitespace before the yaml code block tag.
