### ISSUE TITLE
Health probes provisioning misbehave when same service has different health check probes across namespaces

### ISSUE THREAD

**Issue by aleksmark** [Azure/application-gateway-kubernetes-ingress#604]
**Describe the bug**

I have installed the ingress controller in the default namespace. I also have namespaces: development, staging, and integration. Each namespace has `my-service` deployed and running. Each namespace has its own ingress.yaml which exposes the service for that namespace. The deployment file looks something like this. The file it is the same on all environment.

```apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: my-service
    spec:
      containers:
      - name: my-service
        image: image.url/image:tag
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /my-service/health
            port: 80
            httpHeaders:
              - name: Host
                value: 127.0.0.1
          initialDelaySeconds: 180
          periodSeconds: 60
          failureThreshold: 6
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /my-service/health
            port: 80
            httpHeaders:
              - name: Host
                value: 127.0.0.1
          initialDelaySeconds: 45
          periodSeconds: 60
          failureThreshold: 6
          timeoutSeconds: 30
      restartPolicy: Always
status: {}
```

After ingress controller updates AGW it creates all resources needed and my service is reachable. It creates three health probes with correct paths 

```
                    name                                     path
pb-development-my-service-80-ingress-development      /my-service/health
pb-integration-my-service-80-ingress-integration      /my-service/health
pb-staging-my-service-80-ingress-staging              /my-service/health
```

However, when I update the deployment file on the development environment and change the probes to `/my-service/check/health`, health probes on AGW are not updated accordingly. I tried many times to trigger the update by updating ingress or updating deployment and there is no pattern. Sometimes there is no change at all, sometimes the probes of other environments got updated, etc...

```
                    name                                     path
pb-development-my-service-80-ingress-development      /my-service/check/health
pb-integration-my-service-80-ingress-integration      /my-service/check/health
pb-staging-my-service-80-ingress-staging              /my-service/health
```
or
```
                    name                                     path
pb-development-my-service-80-ingress-development      /my-service/health
pb-integration-my-service-80-ingress-integration      /my-service/health
pb-staging-my-service-80-ingress-staging              /my-service/check/health
```
or
```
                    name                                     path
pb-development-my-service-80-ingress-development      /my-service/health
pb-integration-my-service-80-ingress-integration      /my-service/check/health
pb-staging-my-service-80-ingress-staging              /my-service/check/health
```

I turned on verbose logging on ingress controller and I can see that it sends the wrong configuration to the AGW.

**To Reproduce**
Create multiple namespaces each containing a service with the same deployment file (same name) but with different probe URLs
Check if the AGW health probe are created with correct paths

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
```
Name:               alert-eagle-ingress-azure-7d9cd8957f-qwqxn
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               aks-agentpool-15375443-1/10.0.0.35
Start Time:         Fri, 11 Oct 2019 18:05:25 +0200
Labels:             aadpodidbinding=alert-eagle-ingress-azure
                    app=ingress-azure
                    pod-template-hash=7d9cd8957f
                    release=alert-eagle
Annotations:        <none>
Status:             Running
IP:                 10.0.0.45
Controlled By:      ReplicaSet/alert-eagle-ingress-azure-7d9cd8957f
Containers:
  ingress-azure:
    Container ID:   docker://a8d819d7bff51b6b401cec130bcc12b599faf2957db80ca3cd1690f85489d8a9
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.10.0-rc1
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:874db4938c332920deea399a85d33bade264df240022123fc061b8f483e8c491
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Fri, 11 Oct 2019 18:05:34 +0200
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      alert-eagle-cm-ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_CONTEXT_LOCATION:        /etc/appgw/azure.json
      AGIC_POD_NAME:                 alert-eagle-ingress-azure-7d9cd8957f-qwqxn (v1:metadata.name)
      AGIC_POD_NAMESPACE:            default (v1:metadata.namespace)
      KUBERNETES_PORT_443_TCP_ADDR:  xxxxxx..westeurope.azmk8s.io
      KUBERNETES_PORT:               tcp://xxxxx.westeurope.azmk8s.io:443
      KUBERNETES_PORT_443_TCP:       tcp://xxxxx.westeurope.azmk8s.io:443
      KUBERNETES_SERVICE_HOST:       xxxxxx.westeurope.azmk8s.io
    Mounts:
      /etc/appgw/azure.json from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from alert-eagle-sa-ingress-azure-token-g4zdk (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  alert-eagle-sa-ingress-azure-token-g4zdk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alert-eagle-sa-ingress-azure-token-g4zdk
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                               Message
  ----    ------     ----  ----                               -------
  Normal  Scheduled  59m   default-scheduler                  Successfully assigned default/alert-eagle-ingress-azure-7d9cd8957f-qwqxn to aks-agentpool-15375443-1
  Normal  Pulling    59m   kubelet, aks-agentpool-15375443-1  pulling image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.10.0-rc1"
  Normal  Pulled     59m   kubelet, aks-agentpool-15375443-1  Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.10.0-rc1"
  Normal  Created    59m   kubelet, aks-agentpool-15375443-1  Created container
  Normal  Started    59m   kubelet, aks-agentpool-15375443-1  Started container
```

* Output of `kubectl logs <ingress controller>. 
This is output with log level 3. log level 5 is too big and contains sensitive details
```
I1011 15:52:14.742910       1 process.go:129] BEGIN AppGateway deployment
I1011 15:52:56.393338       1 process.go:152] Applied App Gateway config in 41.65039754s
I1011 15:52:56.393373       1 process.go:163] cache: Updated with latest applied config.
I1011 15:52:56.403922       1 process.go:169] END AppGateway deployment
I1011 15:52:56.666513       1 process.go:129] BEGIN AppGateway deployment
I1011 15:53:38.040629       1 process.go:152] Applied App Gateway config in 41.374085893s
I1011 15:53:38.040657       1 process.go:163] cache: Updated with latest applied config.
I1011 15:53:38.052399       1 process.go:169] END AppGateway deployment
```

* Any Azure support tickets associated with this issue.

**Comment by aleksmark** [comment]
I am trying to build the controller locally and to investigate the issue I am facing. I am following this guide https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/developers/build.md but I when I start the app (./scripts/start.sh), I am getting the error 

`panic: No Auth Provider found for name "azure"`

I am on macOS Mojave.

Can somebody help?

**Comment by draychev** [comment]
Hi @aleksmark - Could you provide more context around the panic on macOS (line numbers, what file it happen in)?  I just built the repo on Mojave (and submitted a few tiny fixes https://github.com/Azure/application-gateway-kubernetes-ingress/pull/618 and https://github.com/Azure/application-gateway-kubernetes-ingress/pull/617)

The panic you ran into seems related to configuration.  Do you have your `$HOME/.azure/azureConfig.json` file?

Also - thank you so much for the PR!  I have a few questions - will continue the conversation there.

**Comment by aleksmark** [comment]
HI, @draychev , sorry I just saw this comment. 

Yes, I have the `HOME/.azure/azureConfig.json` file filled in with correct config values.
I copied .env.example to .env and fill in with my config as well.

when I run ./scripts/start.sh, first, I got an error ```: command not found```. I have an issue with `source .env` from start.sh. I am not sure why. I have the source installed. To bypass this I copied export commands from .env to the start.sh itself.

Next, I got an error `go install: cannot install cross-compiled binaries when GOBIN is set`. This is strange, I don't have it set system-wide, it is set in the start script on line 13. To bypass this I added `unset GOBIN` just before `go install` command. And set it back after the `go install` command, for it might be needed later. 

Then I had an issue with GOOS=linux but that is expected because I run it on macOS. I just removed it.

Then I got an error `chmod: bin: No such file or directory` referring to a line 26, `chmod -R 777 bin`. I did not had `bin` directory, because `go install` installed it in `$HOME/go`, which is the value of $GOPATH env var I have set system-wide. I tried to reset $GOPATH to `$(pwd)/bin` in the start script but when I run start.sh I got an error `$GOPATH/go.mod exists but should not`, which is strange because that file is under version control.

I then let `go install` installs it in `$HOME/go/bin` and update the paths of the app in start.sh (`./bin/appgw-ingress` => `$HOME/go/bin/appgw-ingress`). I also comment out `chmod -R 777 bin` to get rid of the `chmod: bin: No such file or directory` error.

I finally got `Build SUCCEEDED` message. After it the error followed: `unknown flag: --apiserver-host`. To get rid of this error I commented out `--apiserver-host="$AKS_API_SERVER" \`

After that app is started and I got an error `No Auth Provider found for name "azure"`. I bypassed that by importing `azauth "k8s.io/client-go/plugin/pkg/client/auth/azure"` because it has init function to register auth provider.

```
func init() {
	if err := restclient.RegisterAuthProviderPlugin("azure", newAzureAuthProvider); err != nil {
		klog.Fatalf("Failed to register azure auth plugin: %v", err)
	}
}
```

Only after that, I was able to run the application. 

Funny thing is that when I wanted to reproduce all the steps for the sake of this comment, and I left GOOS=linux as it is (did not remove it) I don't get the `No Auth Provider found for name "azure"` error and app starts.

As you can see I had a lot of trouble starting it, probably due to my go installation and lack of experience. Not sure if any of this is useful but If you have any suggestion let me know.

**Comment by draychev** [comment]
Hi @aleksmark 

Version `0.10.0-rc4` is out and in our Helm repo. This includes the fix you added - THANK you so much for fixing the health probe issue!!

Here are the upgrade instructions:  https://github.com/Azure/application-gateway-kubernetes-ingress/blob/e28a1388ddc0cc0fa8efbedc595ae43ac7c91be2/docs/how-tos/helm-upgrade.md#upgrade

Keep us posted on how well 0.10.0-rc4 works with your setup!

On the issues you ran with `./scripts/start.sh` - really sorry to hear that you had so much trouble bootstrapping the project.  Any changes you want to make to the start.sh script (or how this is started) are more than welcome.  I did some refactoring of `start.sh` after your initial feedback, and now will take another look. We need to make the onboarding process to this repo be as easy as possible!

I'll keep the issue here open until you post back on whether health probes are working as expected now with the fix you pushed!

**Comment by aleksmark** [comment]
@draychev great news, I will try tomorrow

**Comment by aleksmark** [comment]
@draychev Problems fixed. Thank you. You can close the issue.
