### ISSUE TITLE
The link for Installation is broken - showing a 404 page.

### ISSUE THREAD

**Issue by monubamb** [Azure/application-gateway-kubernetes-ingress#61]
When I try to go to this link to install. https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/tutorial.md

**Prerequisites**
Installed ingress-azure helm chart. Please refer to **_installation_** instructions to install the Azure Application Gateway Ingress controller on your AKS cluster. If you want to use HTTPS on this application, you will need a x509 certificate and its private key.
 

The link is in Prerequisites section - _installation_

**Comment by asridharan** [comment]
@monubamb this should be fixed by #62 

Thanks for reporting this problem.
