### ISSUE TITLE
Load balancing algorithm used by AGIC

### ISSUE THREAD

**Issue by vishnujanardhanan** [Azure/application-gateway-kubernetes-ingress#614]
**Describe the bug**
May i know what is the Load balancing algorithm used by AGIC? Could not find much details from the docs.

**To Reproduce**

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
* Output of `kubectl logs <ingress controller>. 
* Any Azure support tickets associated with this issue.

**Comment by draychev** [comment]
Hi @vishnujanardhanan - the ingress controller currently relies on App Gateway for round-robin load distribution.  That's the only option at this time.
