### ISSUE TITLE
Inconsistency in values.yaml on Github vs Helm

### ISSUE THREAD

**Issue by DeanPH** [Azure/application-gateway-kubernetes-ingress#626]
**Describe the bug**
In release 0.10.0-rc4 there was a fix for Helm Validations: "9995ce3 fix helm validations (#620)"

In this file from the fix [values.yaml](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/9995ce3c28160f5a8dcde8bfa1c16f22ecada2a6/helm/ingress-azure/values.yaml) , even in the master branch, there 2 new values in there for subnetID and subnetPrefix:
```
 #subnetPrefix: 10.1.0.0/16
 subnetID: sup
```
If I download the helm package and look at the same file values.yaml, those 2 values do not exist.

Any ideas as to what's going on here?

**To Reproduce**
helm fetch \
  --repo https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/ \
  --untar \
  --untardir ./charts \
  --version 0.10.0-rc4 \
    ingress-azure
cat charts/ingress-azure/values.yaml

**Comment by DeanPH** [comment]
This is still an issue in 0.10.0-rc5.

**Comment by akshaysngupta** [comment]
Thanks for reporting @DeanPH 
https://github.com/Azure/application-gateway-kubernetes-ingress/pull/634 will fix the inconsistency with `values.yaml`.
It is generated using this [template](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/helm/ingress-azure/values-template.yaml) in the Azure Devops pipeline.

**Comment by draychev** [comment]
@DeanPH We addressed the inconsistency w/ this PR: https://github.com/Azure/application-gateway-kubernetes-ingress/pull/637
