### ISSUE TITLE
nil pointer dereference in isServiceReferencedByAnyIngress

### ISSUE THREAD

**Issue by draychev** [Azure/application-gateway-kubernetes-ingress#635]
Bug report from @evmimagina (copied from https://github.com/Azure/application-gateway-kubernetes-ingress/issues/629):

-----------

Hi,

I'm think I'm affected by the same bug;

I1026 17:20:54.020027       1 process.go:171] END AppGateway deployment 
panic: runtime error: invalid memory address or nil pointer dereference 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11e3897] 

goroutine 135 [running]: 
github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext.(*Context).isServiceReferencedByAnyIngress(0xc00012b880, 0xc0005881f8, 0xc000312660) 
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:458 +0x107 
github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext.(*Context).IsPodReferencedByAnyIngress(0xc00012b880, 0xc00057c000, 0xc000531c40) 
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:232 +0x85 
github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.AppGwIngressController.ShouldProcess(0x16f5ac0, 0xc00026be70, 0x16f7240, 0xc0002a84e0, 0x0, 0x0, 0xdf8475800, 0xd18c2e2800, 0x3, 0x6fc23ac00, ...) 
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/should_process.go:26 +0x15e 
github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker.(*Worker).Run(0xc0004657a0, 0xc000084fc0, 0xc00008e7e0) 
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker/worker.go:37 +0x17d 
created by github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.(*AppGwIngressController).Start 
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/controller.go:65 +0x1bb

The thing is, the first time I deploy my app on the K8s cluster, everything works fine... once I deploy a new release of the app this error starts to happen. Seems that I can only fix it recreating the Gateway.

How can I install it once it's available?

thanks,

**Comment by draychev** [comment]
@evmimagina You have ran into an interesting edge case it seems - could you please open a new issue (so we can keep track of what you observed separately).

Would you be able to share with the following:
1) what version of the AGIC you are using (`helm list` would tell us this)
2) would you be able to provide a sanitized versions of your Ingress and Service kubernetes resources?

It looks like we are running into a situation where we are making unsafe assumptions about a pod or a service struct existing, but it is hard to tell without the context above. Thanks!

**Comment by evmimagina** [comment]
Hi Draychev,

The thing is, it's not happening anymore. I've recreated everything and it seems to be working now. I guess it was something I did wrong? anyway, we can close the issue.

thanks for looking into that.

Best regards,

**Comment by akshaysngupta** [comment]
@evmimagina closing this issue. Please feel free to reopen it if you encounter it again.
