### ISSUE TITLE
Allow for `kubernetes.io/ingress.class:` specification

### ISSUE THREAD

**Issue by sblack4** [Azure/application-gateway-kubernetes-ingress#636]
**Is your feature request related to a problem? Please describe.**
I want to deploy two App Gateways, one for internal traffic and one for external traffic. Normally you would use an annotation, `kubernetes.io/ingress.class:`, to designate which ingress-controller an ingress should use - otherwise the ingress controllers will fight over the ingress. 

**Describe the solution you'd like**
To be able to specify the name for the `kubernetes.io/ingress.class`. Or if this is an undocumented feature then just some docs on it. 

Thank you! 😄

**Comment by draychev** [comment]
Hi @sblack4 I'd like to understand what you mean by `one for internal traffic and one for external traffic`.

Could you answer these questions: 

- How is the internal traffic going to be different than the external?
- How are the 2 App Gateways be different?
- Are there 2 different domain names?
- Would the backend pools be different or shared between external and internal.

A few ideas we could explore:
 - we could use the [Multi-cluster / Shared App Gateway](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/072626cb4e37f7b7a1b0c4578c38d1eadc3e8701/docs/setup/install-existing.md#multi-cluster--shared-app-gateway)
 - we could also explore using [multiple different namespaces](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/463a87213bbc3106af6fce0f4023477216d2ad78/docs/features/multiple-namespaces.md#enable-multiple-namespace-support)
