### ISSUE TITLE
ssl-redirect not redirecting for default http settings

### ISSUE THREAD

**Issue by abenck** [Azure/application-gateway-kubernetes-ingress#642]
**Describe the bug**
ssl-redirect: "true" doesn't redirect Default HTTP settings for Path-based rule in App Gateway. 

Example:
http://test.contoso.com/example1 -> redirects to https
http://test.contoso.com/ -> does not redirect to https

**To Reproduce**
See example ingress

[test_ing.txt](https://github.com/Azure/application-gateway-kubernetes-ingress/files/3789457/test_ing.txt)

Is this a bug or a feature that requires a workaround?

**Comment by draychev** [comment]
Hi @abenck 
Which version of AGIC did you notice this bug with?
How did you determine that `http://test.contoso.com/ -> does not redirect to https`?

Thank you so much for attaching the ingress resource!

**Comment by abenck** [comment]
We're using AGIC 0.8.0 + App Gateway with WAF V2

From the look of the resulting Path-based rule in the App Gateway the behavior makes sense, the rule test.contoso.com-80 lists all paths with a redirect target except for the root.

I checked with curl after noticing the redirect didn't happen on home pages at the root.
`curl -I http://test.contoso.com/ 
-> 200 OK`
`curl -I http://test.contoso.com/example1
-> 302 FOUND`

**Comment by delqn** [comment]
@abenck would you be so kind to upgrade to the latest version - [released just this week - 0.10.0](https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/0.10.0)

I am certain that it will address the redirect issue you ran into.

Here are the [instructions on upgrading AGIC](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/e28a1388ddc0cc0fa8efbedc595ae43ac7c91be2/docs/how-tos/helm-upgrade.md#upgrade)

**Comment by draychev** [comment]
@abenck would you be so kind to upgrade to the latest version - [released just this week - 0.10.0](https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/0.10.0)

I am certain that it will address the redirect issue you ran into.

Here are the [instructions on upgrading AGIC](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/e28a1388ddc0cc0fa8efbedc595ae43ac7c91be2/docs/how-tos/helm-upgrade.md#upgrade)

**Comment by abenck** [comment]
Sure, I can put in a request to make this change in our next update. I'll report back after that to confirm it's resolved.

Thanks for the help and fast reply!

**Comment by abenck** [comment]
@draychev I got the go ahead to use a testing instance and confirmed that it's fixed in 0.10.0, testing with curl now reports 301 Moved Permanently.
