### ISSUE TITLE
Helm 3 Compatibility

### ISSUE THREAD

**Issue by marc-mueller** [Azure/application-gateway-kubernetes-ingress#664]
**Describe the bug**
Installing the chart with Helm 3 results in an error. Installing it with Helm 2.x works fine. 

**To Reproduce**
`helm.exe install ingress-azure --dry-run --debug --generate-name`

**Ingress Controller details**
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in ConfigMap.data.USE_PRIVATE_IP
helm.go:76: [debug] error validating "": error validating data: unknown object type "nil" in ConfigMap.data.USE_PRIVATE_IP
```

**Comment by akshaysngupta** [comment]
Thanks for reporting!
Would you be willing to take a stab at this ?

**Comment by marc-mueller** [comment]
It looks like the validation changed with Helm 3. The error is caused because we do not have any default value for appgw.usePrivateIP in the values. So setting this value during deployment works. What is the default of this one? false?

This one shows the correct output:
`helm.exe install ingress-azure --dry-run --debug --generate-name --set appgw.usePrivateIP=false``

Should we just update the values file for a default value then?

**Comment by akshaysngupta** [comment]
Correct, default value is `false` and adding it to the `values.yaml` will fix this.

**Comment by stefankip** [comment]
Thanks @marc-mueller, found this issue via Google and the extra `--set` parameter fixed it.

**Comment by hajdukd** [comment]
Im still getting:
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "AzureIngressProhibitedTarget" in version "appgw.ingress.k8s.io/v1"

When tryin to install 1.0.0 chart..
