### ISSUE TITLE
Restricted to AKS?

### ISSUE THREAD

**Issue by janegilring** [Azure/application-gateway-kubernetes-ingress#677]
Is the ingress controller restricted to AKS, or is it also supported with Kubernetes clusters running on IaaS in Azure?
What about OpenShift support?

**Comment by akshaysngupta** [comment]
You should be able to run AGIC on any k8s cluster in Azure so long as it is using `Azure CNI` network plugin. This requirement will be relaxed early next year.

**Comment by warroyo** [comment]
@akshaysngupta any updates on this being available without the Azure CNI?
