### ISSUE TITLE
[question] Support for for multiple AKS clusters behind single App GW

### ISSUE THREAD

**Issue by rhollins** [Azure/application-gateway-kubernetes-ingress#679]
Does AGIC solution support having multiple AKS clusters running same workloads behind single App GW for HA scenarios, or is it 1:1 mapping between AKS and App GW ?

**Comment by akshaysngupta** [comment]
@rhollins Currently, AGIC doesn't support same workloads running behind multiple clusters.

We have plan to support this feature contingent to an upcoming load distribution policies feature on Application Gateway. It will allow AGIC to create 2 Backend pools coming from 2 different clusters and distribute load evenly in a very clean way. But I don't have an ETA yet.

**Comment by SrinuM** [comment]
@akshaysngupta is this feature available now, if yes, could you please share the documentation on how to do it.
Thanks in advance..!!

**Comment by fchavatte** [comment]
@akshaysngupta: This feature is available now??
