### ISSUE TITLE
can't evaluate field apiServerAddress in type interface {}

### ISSUE THREAD

**Issue by AresiusXP** [Azure/application-gateway-kubernetes-ingress#68]
I've created an AKS, followed the instructions for creating a Managed Identity and deploying AAD Identity Pod. When I try to run the helm install, it shows the following error:

`Error: render error in "ingress-azure/templates/deployment.yaml": template: ingress-azure/templates/deployment.yaml:35:93: executing "ingress-azure/templates/deployment.yaml" at <.Values.aksClusterCo...>: can't evaluate field apiServerAddress in type interface {}`

This doesn't happen if I use v0.1.2 downloaded and extracted locally.

**Comment by akshaysngupta** [comment]
@AresiusXP 
Please add following property to your ingress controller helm config:
```yaml
aksClusterConfiguration:
    apiServerAddress: <aks-api-server-address>
```
You can find `<aks-api-server-address>` in proeprties of your AKS cluster.
ex: `prefix.hcp.location.azmk8s.io`

I will push the fix to print a proper error message.

**Comment by AresiusXP** [comment]
I see in the installation guide that the helm yaml file has changed with the last 2 versions. My bad.

Thank you!
