### ISSUE TITLE
LoadBalancer doesn't aquire external IP address

### ISSUE THREAD

**Issue by CCostaT** [Azure/application-gateway-kubernetes-ingress#680]
**Describe the bug**
I have some microservices deployed to a kubernetes cluster using helm charts and Azure Pipelines.

During development, sometimes I need to delete a helm chart manually for a microservice.
After doing this and deploying again (using the pipelines), the Load Balancer service is recreated in the cluster but an external IP address is never assigned to it.

![image](https://user-images.githubusercontent.com/48755988/70138334-f5e45780-1687-11ea-91d8-d400fec2285d.png)

The only solution I've found so far is to change the name of the load balancer service (in the helm chart) everytime this happens:

![image](https://user-images.githubusercontent.com/48755988/70139085-a4d56300-1689-11ea-8215-4e9e1e48b797.png)

How do I get the load balancer to work without having to rename it?

**To Reproduce**
It's hard to reproduce because it doesn't always happen but deleting the service and recreating it is enough to cause the problem.

**Ingress Controller details**
Not using an ingress controller

**Comment by akshaysngupta** [comment]
@CCostaT You can take a reference from this doc: https://docs.microsoft.com/en-us/azure/aks/internal-lb

I am closing the issue as it is unrelated to AGIC.

**Comment by CCostaT** [comment]
Hi @akshaysngupta I can create the load balancer. The problem is that, sometimes, when I try to recreate it (after a `kubectl delete service` for example) it won't aquire an external IP no matter how long I wait. I can't find any errors anywhere that could explain this.

The only solution I've found so far is to deploy the load balancer with a different name.
