### ISSUE TITLE
Probe is not overwritten if multiple containers are defined

### ISSUE THREAD

**Issue by LucaPrete** [Azure/application-gateway-kubernetes-ingress#681]
Hello guys,

Not sure if this is really a feature request, a bug or if it's something due to come other causes, but I have a deployment that defines multiple containers, one of which sets a liveness probe a readiness probe. Both probes are applied correctly in Kubernetes, but the one on the application gateway remains the default one (I can tell it because I've re-defined some of the timers and the path).

Please, note that I'm using HTTPS as backend and that I'm using both scheme HTTPS and the `Host` custom header in the probes definition (which I know are not yet supported). Anyway, the probe wasn't overwritten anyway, even before introducing the scheme and the custom header fields...

This lets me suspect that the real issue is supporting a pod with two or more containers inside (in my case a container with a sidecar container).

Thank you

-Luca

**Comment by draychev** [comment]
@LucaPrete would you be able to share with us a sanitized version of the Deployment/Pod, and SErvice YAMLs?

I'd like to understand which container is backing the given Service, what the side-car is, and which container has the probes.

To obtain the defined health probes and apply them to App Gateway, we walk the Services referenced in the Ingress, then match the Containers by port and get probes. See here: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/pkg/appgw/health_probes.go#L172

I suspect the system you have built differs from the assumptions we are making in the code above.

**Comment by LucaPrete** [comment]
@draychev thanks for the quick reply!

The code is all open source. You can find the code and the related readme [here](https://github.com/teamdigitale/io-infrastructure-post-config/tree/master/pagopa-proxy).

Hope it helps

**Comment by LucaPrete** [comment]
@draychev also, let me give some background on the integration with the Application Gateway.

As you'll understand from the readme, the sidecar container is there to provide TLS authentication/encryption services, in order to safely communicate with another partner.

The sidecar container is an nginx container, which gets the traffic from the "main" container, encrypts it and forwards it over to the partner. The same happens the other way around: traffic coming from the partner needs to be authenticated (based on a trusted certificate), decrypted and sent over to the "main" container.

Since the sidecar container does the ingress auth (which is not -yet- supported by AGIC) we expose port 443 of the sidecar container through the application gateway. The application gateway should simply pass encrypted traffic to it (that's why the backend has been set to HTTPS).

As you can imagine, by default, if someone tries to contact to the public address without a valid certificate the replies that she/he gets would be a 403. This is also true for the default AGW probes. To overcome this issue, I had to create in the nginx sidecar container config a dedicated `/healthz` location (always on port 443, since probe ports can't be different from the ingress ports in use) always replying 200, making the AGW probes work, so making the AGW not returning 502 and letting us reach the endpoint.

Hope it gives you some more useful context...

**Comment by akshaysngupta** [comment]
@LucaPrete given the current logic for probe selection, are you seeing `/ping` in the probe path on AppGW ?

**Comment by LucaPrete** [comment]
Hello @akshaysngupta.

No, I don't. I only see the default probe (path /) that tries to reach my sidecar.
