### ISSUE TITLE
Make use of existing Service Principal Secret

### ISSUE THREAD

**Issue by ChristianGottinger** [Azure/application-gateway-kubernetes-ingress#682]
**Is your feature request related to a problem? Please describe.**
I would  like to scripting my infrastructure including a service principal following the principal of least privilege (POLP). It looks like there is currently no way configuring the existing helm chart to use existing secret instead of applying secret json.

**Describe the solution you'd like**
I would like to add name of existing secret instead of secret json.

**`--set armAuth.secret=<myExistingSecret>`**

**Comment by akshaysngupta** [comment]
Thanks for asking!

Have you considered using `user assigned identity` with AGIC to get around this ?
