### ISSUE TITLE
Failed authenticating with Azure Resource Manager: not found

### ISSUE THREAD

**Issue by mayong43111** [Azure/application-gateway-kubernetes-ingress#685]
**Describe the bug**
In AzureChinaCloud, I manually set AZURE_ENVIRONMENT=AzureChinaCloud, but is error, If I don't set it ,it will get https://management.azure.com/, but china is https://management.chinacloudapi.cn/.

when set AZURE_ENVIRONMENT=AzureChinaCloud 

I1214 05:30:33.122380       1 auth.go:90] Creating authorizer from Azure Managed Service Identity
E1214 05:30:33.926436       1 auth.go:35] Got 404 NOT FOUND status code on getting Application Gateway from ARM.
F1214 05:30:33.926499       1 main.go:164] Failed authenticating with Azure Resource Manager: not found (AZUR005)

ENVIRONMENT:
1. on AzureChinaCloud
2. Kubernetes 1.12.7
3. kubernetes-ingress:1.0.0
4. helm 2.16.1
5. Enabled RBAC
6. aad-pod-identity/mic:1.5.3

**Comment by mayong43111** [comment]
I found /etc/appgw/azure.json, It's 
{
    "cloud":"AzureChinaCloud",
    "tenantId": "...",
    "subscriptionId": "...",
    "aadClientId": "...",
    "aadClientSecret": "...",
    "resourceGroup": "aks-waf_aks161e_chinanorth2",
    "location": "chinanorth2",
    "vmType": "standard",
    "subnetName": "kubesubnet",
    "securityGroupName": "aks-agentpool-35064155-nsg",
    "vnetName": "virtualnetwork161e",
    "vnetResourceGroup": "aks-waf",
    "routeTableName": "aks-agentpool-35064155-routetable",
    "primaryAvailabilitySetName": "agentpool-availabilitySet-35064155",
    "primaryScaleSetName": "",
    "cloudProviderBackoffMode": "v1",
    "cloudProviderBackoff": false,
    "cloudProviderBackoffRetries": 6,
    "cloudProviderBackoffExponent": 1.5,
    "cloudProviderBackoffDuration": 5,
    "cloudProviderBackoffJitter": 1,
    "cloudProviderRatelimit": true,
    "cloudProviderRateLimitQPS": 10,
    "cloudProviderRateLimitBucket": 100,
    "cloudProviderRatelimitQPSWrite": 10,
    "cloudProviderRatelimitBucketWrite": 100,
    "useManagedIdentityExtension": false,
    "userAssignedIdentityID": "",
    "useInstanceMetadata": true,
    "loadBalancerSku": "Basic",
    "excludeMasterFromStandardLB": false,
    "providerVaultName": "",
    "maximumLoadBalancerRuleCount": 250,
    "providerKeyName": "k8s",
    "providerKeyVersion": ""
}

**Comment by akshaysngupta** [comment]
@mayong43111 I think the error message needs an improvement here.
Can you check if the application gateway information is correct ?

**Comment by mayong43111** [comment]
> @mayong43111 I think the error message needs an improvement here.
> Can you check if the application gateway information is correct ?
> 
> Instead add this manually, You can set `environment: AZURECHINACLOUD` to your helm config to set this env variable on the AGIC container.
> https://github.com/Azure/application-gateway-kubernetes-ingress/blob/1098cfd027b2782053e225027a78871fdf03a08f/helm/ingress-azure/values.yaml#L31

I communicated with the Chinese Azure team and finally used the version 1.0.1-rc1.
