### ISSUE TITLE
Ingress creating following the tutorial has no IP Address associated

### ISSUE THREAD

**Issue by nacho-marin** [Azure/application-gateway-kubernetes-ingress#688]
Following the steps in the Tutorials (https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/tutorial.md), I reach section "Expose Services over HTTP" (https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/tutorial.md#expose-services-over-http) and, after executing **kubectl apply -f ing-guestbook.yaml**, the ingress created has no value set for column ADDRESS:

$ **kubectl get ingress**
NAME        HOSTS   ADDRESS   PORTS   AGE
guestbook       *                          80       16m

For more info, I created the AKS cluster with 2 nodes and relevant kubectl command execution shows the following results:

$ **kubectl describe ingress guestbook**
Name:             guestbook
Namespace:        default
Address:
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host  Path  Backends
  ----  ----  --------
  *
           frontend:80 (10.244.0.8:80,10.244.1.5:80,10.244.1.6:80)
Annotations:
  kubectl.kubernetes.io/last-applied-configuration:  {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"azure/application-gateway"},"name":"guestbook","namespace":"default"},"spec":{"rules":[{"http":{"paths":[{"backend":{"serviceName":"frontend","servicePort":80}}]}}]}}

  kubernetes.io/ingress.class:  azure/application-gateway
Events:                         <none>

$ **kubectl get nodes -o wide**
NAME                                STATUS   ROLES   AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-nodepool1-41901855-vmss000000   Ready    agent   6h44m   v1.14.8   10.240.0.4    <none>        Ubuntu 16.04.6 LTS   4.15.0-1061-azure   docker://3.0.7
aks-nodepool1-41901855-vmss000001   Ready    agent   6h44m   v1.14.8   10.240.0.5    <none>        Ubuntu 16.04.6 LTS   4.15.0-1061-azure   docker://3.0.7

$ **kubectl get pods -o wide**
NAME                           READY   STATUS    RESTARTS   AGE   IP           NODE                                NOMINATED NODE   READINESS GATES
frontend-69859f6796-56qf2      1/1     Running   0          61m   10.244.0.8   aks-nodepool1-41901855-vmss000000   <none>           <none>
frontend-69859f6796-65t6w      1/1     Running   0          61m   10.244.1.5   aks-nodepool1-41901855-vmss000001   <none>           <none>
frontend-69859f6796-kbjps      1/1     Running   0          61m   10.244.1.6   aks-nodepool1-41901855-vmss000001   <none>           <none>
redis-master-596696dd4-lwzqt   1/1     Running   0          61m   10.244.1.3   aks-nodepool1-41901855-vmss000001   <none>           <none>
redis-slave-96685cfdb-hgbmc    1/1     Running   0          61m   10.244.0.7   aks-nodepool1-41901855-vmss000000   <none>           <none>
redis-slave-96685cfdb-tprqr    1/1     Running   0          61m   10.244.1.4   aks-nodepool1-41901855-vmss000001   <none>           <none>

From what I understand, the Ingress should have an external IP address assigned automatically when created. Am I right?

Thank you!

Best,

Nacho

**Comment by nacho-marin** [comment]
I had missed a step. Sorry. Please delete this issue.

**Comment by mindstormz** [comment]
Hi @nacho-marin , would you kindly share what the missed step was?

**Comment by mindstormz** [comment]
ok, so, for me, the problem was as follows:

after sample app deployment, there was no ingress-pod deployed. It appeared, that my Helm installation was faulty and therefore the chart was not correctly installed.
Following did the job for me:

>helm reset --force

Then, redeploy according to the Tutorial. Make sure you deploy all the settings according to if you are using RBAC-enabled Cluster or not.

**Comment by nacho-marin** [comment]
Sorry. I forgot the notification from mindstormz asking me to talk about the missing step back in the day when he post it.

And it was quite a huge error. I followed the tutorial without executing the preliminary Greenfield Deployment steps (https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/setup/install-new.md). Huge error on my side.

**Comment by nacho-marin** [comment]
@mindstormz , it has worked for me perfectly, with only one change and a decision... if you follow the steps as they are in the tutorial, you go to Helm's website and get the latest version, which is v3... and all the steps are for v2... if you go for Helm v3, you do not need to execute the following commands when doing the Install Helm steps in the Greenfield Deployment process:

- If you use RBAC:
-- You do not need the two kubectl create command and the subsequent helm init
- If you do not use RBAC:
-- You do not need the helm init command

Never needed to execute the helm reset --force

By the way, I have only tried deploying RBAC-based clusters so far.
 
  -
