### ISSUE TITLE
Can I use this ingress controller with only Windows nodes?

### ISSUE THREAD

**Issue by adamcarter81** [Azure/application-gateway-kubernetes-ingress#694]
I have a requirement to deploy a Windows node only AKS cluster - I realise this is still in preview, but we expect GA early next year and I was hoping to deploy this AGIC, but does it require linux nodes, thus requiring me to deploy say 2 x linux nodes just to run the ingress controller?

Thanks

**Comment by akshaysngupta** [comment]
Afaik, deploying a linux node pool is mandatory in AKS. Given that you can have AGIC run in the linux pool while pods can reside in the windows node pool.
