### ISSUE TITLE
AgentPoolK8sVersionNotSupported

### ISSUE THREAD

**Issue by Jonathan1Wade** [Azure/application-gateway-kubernetes-ingress#696]
![aks issues](https://user-images.githubusercontent.com/22188658/71572778-bccec400-2b1b-11ea-8a3f-d0523b9057df.jpg)

**Describe the bug**
Azure Error: InvalidTemplateDeployment
Message: The template deployment 'ingress-appgw' is not valid according to the validation procedure.

**To Reproduce**
Follow procedure

Message: The template deployment 'ingress-appgw' is not valid according to the validation procedure. The tracking id is 'a57a510f-c973-4a8c-ab08-d21796b87763'. See inner errors for details.
Exception Details:
        Error Code: AgentPoolK8sVersionNotSupported
        Message: Provisioning of resource(s) for container service aks0a57 in resource group rg-aks-wp2 failed. Message: {
  "code": "AgentPoolK8sVersionNotSupported",
  "message": "Version 1.12.7 is not supported in this region. Please use [az aks get-versions] command to get the supported version list in this region. For more information, please check https://aka.ms/supported-version-list"
 }. Details:

**Comment by draychev** [comment]
@Jonathan1Wade Thank you for creating this issue and bringing this up to our attention.
Indeed it seems that the version we have hard-coded in the Azure deployment template is now obsoleted in the region you are deploying.

This is referenced in the following file within the repository:  https://github.com/Azure/application-gateway-kubernetes-ingress/blob/b9c661ab165d6d58d1b271135a141295bb515170/deploy/azuredeploy.json#L284

That file is the ARM template creating an AKS cluster as part of our [Greenfield Deployment](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/cd166d64fc4922c60d2c9de1f2e3531210f6a694/docs/setup/install-new.md#deploy-components)

I am going to fix this, but it would require another release, so it won't be immediate.  If you are blocked on this you can use this workaround:

When you follow the [Greenfield Deployment instructions](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/cd166d64fc4922c60d2c9de1f2e3531210f6a694/docs/setup/install-new.md#deploy-components), after you execute `wget https://raw.githubusercontent.com/Azure/application-gateway-kubernetes-ingress/master/deploy/azuredeploy.json -O template.json` -- go ahead and edit the newly created `template.json` file:
  1. use `az aks get-versions` to get the possible Kubernetes versions -- for example to get the possible versions in US West 2: `az aks get-versions --location westus | jq '.orchestrators[].orchestratorVersion'`
  2. open to edit `template.json`
  3. find the `kubernetesVersion` key and change `"defaultValue": "1.12.7",` to be one shown by the `az aks get-versions` command above
  4. save `template.json` and proceed to Greenfield Deploy instructions
