### ISSUE TITLE
Helm 3 helm init --tiller-namespace

### ISSUE THREAD

**Issue by Jonathan1Wade** [Azure/application-gateway-kubernetes-ingress#697]
**Describe the bug**
Error: unknown flag: --tiller-namespace

**To Reproduce**
helm init --tiller-namespace kube-system --service-account tiller-sa

Is this needed / supported in Helm 3? 

![tiller name space](https://user-images.githubusercontent.com/22188658/71605882-72932480-2ba7-11ea-9250-043e81c3410f.jpg)

**Comment by akshaysngupta** [comment]
helm 3 did away with tiller. Now you don't need to execute this step. I will update the documentation soon.

**Comment by Buchatech** [comment]
Hello, 

FYi... the documentation is still not updated. https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-install-new

**Comment by saostad** [comment]
doc is still outdated!

**Comment by janodutoit** [comment]
So it seems the document is still outdated @akshaysngupta?
