### ISSUE TITLE
Helm install --generate-name 

### ISSUE THREAD

**Issue by Jonathan1Wade** [Azure/application-gateway-kubernetes-ingress#698]
**Describe the bug**
Error: must either provide a name or specify --generate-name

When --generate-name is used the following error is recorded. 

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in ConfigMap.data.USE_PRIVATE_IP

**To Reproduce**
![generate name](https://user-images.githubusercontent.com/22188658/71605949-fcdb8880-2ba7-11ea-843d-e306bcabf1c5.jpg)

**Comment by akshaysngupta** [comment]
Thanks for reporting. 
Here is PR fixing it: https://github.com/Azure/application-gateway-kubernetes-ingress/pull/722

We will soon do a release carrying this fix.
