### ISSUE TITLE
allow configuration of ingress annotation

### ISSUE THREAD

**Issue by Morriz** [Azure/application-gateway-kubernetes-ingress#699]
The current annotation
```yaml
kubernetes.io/ingress.class: azure/application-gateway
```
does not play well with external-dns as it does not accept the label value (because of the slash in it). It should be possible to configure the label this controller listens to so we can make it valid:
```yaml
kubernetes.io/ingress.class: azure-application-gateway
```
Could you please make it so?

**Comment by akshaysngupta** [comment]
@Morriz Interesting.
Would you be willing to take a stab at this ?

**Comment by akshaysngupta** [comment]
Closing as it is covered by https://github.com/Azure/application-gateway-kubernetes-ingress/issues/732
