### ISSUE TITLE
Allow to configure two different certs for public access and internal service

### ISSUE THREAD

**Issue by evmimagina** [Azure/application-gateway-kubernetes-ingress#700]
Hi,

This is a feature request.

After opening a support case and being followed by one colleague of yours, seems that is not posible to use two different certificates; one for the public URL accessed on WAF and the other one used by the pods, 
What I want to achieve is to have SSL channel between WAF and the pods, there's an article that points that is only necessary that the certificate is valid, but that's not accurate, after discussing the problem seems that it's a requirement to use the same hostname on public host as on the internal host… or have the public certificate to include names for the internal services.

E.G. 

CONFIG THAT WOULD WORK BUT NOT DESIRED:
"
spec:
 tls:
  - hosts:
    - $DNS_APP_FQDN_SVC
    secretName: $AKS_PUBLIC_CERT_NAME
 rules:
 - host: $DNS_APP_FQDN_SVC
   http:
    paths:
    - backend:
       serviceName: $APP_SVC
       servicePort: 443
"
The not desired config is because we don't want that internal cert used by the pods to match the public name.

DESIRED CONFIG THAT WON´T WORK:

"
spec:
 tls:
  - hosts:
    - $DNS_APP_FQDN_SVC
    secretName: $AKS_PUBLIC_CERT_NAME
 rules:
 - host: $DNS_APP_K8S_SVC
   http:
    paths:
    - backend:
       serviceName: $APP_SVC
       servicePort: 443
"
The public host name to be different from the healthprove for internal hosts. Please note that configuring WAF manually it would work (already tested).

If the explanation is a bit confusing I will be glad to contact any one that looks into this to give further details and explanations.

Thanks and kind regards,

**Comment by akshaysngupta** [comment]
@evmimagina I have created a PR which adds an annotation `appgw.ingress.kubernetes.io/backend-hostname`. Using this annotation, you can specify the `hostname(SNI)` that Application Gateway should use while talking to the Pods.

**Comment by evmimagina** [comment]
Hi Akshay,

Thanks for looking into this, how can I test that setting? should I install any specific versión to test it?

Regards,
