### ISSUE TITLE
Update Helm install steps for new version of Helm

### ISSUE THREAD

**Issue by Phydeauxman** [Azure/application-gateway-kubernetes-ingress#702]
This repo is a great How-To to learn more about k8s, App Gateway, and Helm but the Helm install steps are no longer accurate. Helm v3 removed Tiller. Being someone that has zero experience with Helm, (let alone limited experience with k8s) I do not know how to use this How-To guide with Helm version 3. I wound up going back and leveraging the last v2 release.

**Comment by akshaysngupta** [comment]
@Phydeauxman With helm 3, there is no tiller component that you need to deploy to the k8s cluster. This means that we can avoid the part of instructions that are needed to setup tiller.
Following are the commands we will skip.
```bash
kubectl create serviceaccount --namespace kube-system tiller-sa
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller-sa
helm init --tiller-namespace kube-system --service-account tiller-sa
```

But still need to add the repo for AGIC to helm and perform the installation.
```bash
helm init
helm repo add application-gateway-kubernetes-ingress https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/
helm repo update
```

And then proceed with installing the ingress controller in AGIC setup instructions.

**Comment by nsaud-skysync** [comment]
I'm getting tripped up at adding the AGIC repo. I get the following:

```
$ helm repo add application-gateway-kubernetes-ingress https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/
Error: Looks like "https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/" is not a valid chart repository or cannot be reached: open /home/sandman/.helm/repository/cache/application-gateway-kubernetes-ingress-index.yaml: permission denied
```

**Comment by akshaysngupta** [comment]
@nsaud-skysync Looking at the error message:
```
open /home/sandman/.helm/repository/cache/application-gateway-kubernetes-ingress-index.yaml: permission denied
```
Can you see if fixing the permission issue solves the problem ?
