### ISSUE TITLE
Only configure pod IP addresses in the AG back-end pool.

### ISSUE THREAD

**Issue by askew** [Azure/application-gateway-kubernetes-ingress#706]
Many organisations want to manage ingress routes, SSL etc. separately from the application deployments. It would be ideal if the Application Gateway Ingress Controller had a simple mode whereby the only configuration changes it makes are managing the pod IP addresses in the back-end pool of the Application Gateway. The config would simply need to reference the name of the back-end pool. All other settings would have to be managed directly in the Application Gateway.

This also solves several other issues such as getting SSL certificates directly from KeyVault.

**Comment by jakedenyer** [comment]
Anyone looking at this?

**Comment by 3quanfeng** [comment]
Regarding the ssl certificate, there is a new annotation called appgw-ssl-certificate which you could use to refer the ssl certificate pre-installed in appgw.

**Comment by askew** [comment]
> Regarding the ssl certificate, there is a new annotation called appgw-ssl-certificate which you could use to refer the ssl certificate pre-installed in appgw.

This does work nicely and solves the main issue of getting certs from KeyVault and not putting them in K8s secrets. However there are still some orgs that want to manage the routing separately as well. A similar annotation that references the back-end pool would be great.

**Comment by 3quanfeng** [comment]
Hi @askew, if I understand correctly, what you would like to see is AGIC could only handle backend event for IP change?

**Comment by askew** [comment]
@3quanfeng, Yes that's right. In a scenario where the Application Gateway is shared and used for multiple services, it would be cleaner to manage the routing separately. In the example I am working on now, we have two AKS clusters, a VM Scale-set and also a set of VMs all which have services that sit behind the AppGw. We are deploying the App Gw using ARM, and this creates the back-end pools and routes for the VM Scale-set and VMs. The VMSS and VMs register their IPs to the backend pools via the network their configuration. For the two AKSs each running AGIC, we have to have a complex set of `AzureIngressProhibitedTarget` CRDs to ensure they don't try to remove the config from other services. Also re-running the ARM deployment means a 502 error until the AGICs reconcile. It would be far cleaner if all the routes were created in the ARM template and AGIC would just add the pod IPs to the pre-created backend pools, just like the VMSS and VMs do.
