### ISSUE TITLE
[error]client.go:401: Replaced "agic-cm-ingress-azure"

### ISSUE THREAD

**Issue by nezoic** [Azure/application-gateway-kubernetes-ingress#709]
**Describe the bug**
Attempted to change to version 1.0.1-rc2 in order to avoid issue [(#674)](https://github.com/Azure/application-gateway-kubernetes-ingress/pull/674)

**To Reproduce**
Switch from 1.0.0 to1.0.1-rc2

**Ingress Controller details**
Name:           agic-ingress-azure-79cc6d9f47-pq6cx
Namespace:      default
Priority:       0
Node:           aks-agentpool-35064155-vmss000002/15.1.0.66
Start Time:     Thu, 16 Jan 2020 19:10:55 +0000
Labels:         aadpodidbinding=agic-ingress-azure
                app=ingress-azure
                pod-template-hash=79cc6d9f47
                release=agic
Annotations:    prometheus.io/port: 8123
                prometheus.io/scrape: true
Status:         Running
IP:             15.1.0.72
IPs:            <none>
Controlled By:  ReplicaSet/agic-ingress-azure-79cc6d9f47
Containers:
  ingress-azure:
    Container ID:   docker://583b54406cb23a5c6ad3e4d8e26469ad5257876d1e1784bb947261c84321f748
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.0.0
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:c295f99ae66443c5a392fd894620fcd1fc313b9efdec96d13f166fefb29780a9
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 16 Jan 2020 21:24:19 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Thu, 16 Jan 2020 21:14:06 +0000
      Finished:     Thu, 16 Jan 2020 21:24:18 +0000
    Ready:          True
    Restart Count:  13
    Environment Variables from:
      agic-cm-ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_CONTEXT_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:           agic-ingress-azure-79cc6d9f47-pq6cx (v1:metadata.name)
      AGIC_POD_NAMESPACE:      default (v1:metadata.namespace)
    Mounts:
      /etc/appgw/azure.json from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from agic-sa-ingress-azure-token-8srjz (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  agic-sa-ingress-azure-token-8srjz:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  agic-sa-ingress-azure-token-8srjz
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s

* Output of `kubectl logs <ingress controller>. 
`ERROR: logging before flag.Parse: I0116 21:24:19.884838       1 main.go:302] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0116 21:24:19.931825       1 environment.go:168] KUBERNETES_WATCHNAMESPACE is not set. Watching all available namespaces.
I0116 21:24:19.931865       1 main.go:132] App Gateway Details: Subscription: REDACTED, Resource Group:REDACTED, Name: appgw-clientportal
I0116 21:24:19.931872       1 auth.go:90] Creating authorizer from Azure Managed Service Identity`

I think that particular error is related to something else wrong in the configuration but I have yet to look at it in much detail.

**Comment by akshaysngupta** [comment]
@nezoic Were you able to get past this issue ?

**Comment by akshaysngupta** [comment]
Closing the issue. Please re-open if issue still exists.
