### ISSUE TITLE
Add support for using custom nodeResourceGroup instead of MC_ResourceGroup_ResourceName_Location

### ISSUE THREAD

**Issue by mcambal** [Azure/application-gateway-kubernetes-ingress#710]
**Is your feature request related to a problem? Please describe.**
ARM template currently supports using nodeResourceGroup for customizing the nodes resource group name. AGIC currently supports only MC_ResourceGroup_ResourceName_Location. It is a bit misleading if AKS supports it

**Describe the solution you'd like**
I expect that AGIC will work with any resource group name

**Comment by akshaysngupta** [comment]
@mcambal AGIC functionally doesn't require `nodeResourceGroup` to be of `MC_ResourceGroup_ResourceName_Location` format. If you are referring to the error, it is harmless.

Tagging the app gateway with the AKS cluster is definitely useful. I am still looking for a better way of arriving at the cluster name/id.

**Comment by mcambal** [comment]
@akshaysngupta I got a warning from AGIC if I use different node resource group than MC_.  And this is the code from azure.go file

`func ConvertToClusterResourceGroup(subscriptionID SubscriptionID, resourceGroup ResourceGroup, err error) (string, error) {
	if err != nil {
		return "", err
	}

	split := strings.Split(string(resourceGroup), "_")
	if len(split) != 4 || strings.ToUpper(split[0]) != "MC" {
		logLine := fmt.Sprintf("infrastructure resource group name: %s is expected to be of format MC_ResourceGroup_ResourceName_Location", string(resourceGroup))
		glog.Warning(logLine)
		return "", ErrMissingResourceGroup
	}

	return fmt.Sprintf("/subscriptions/%s/resourcegroups/%s/providers/Microsoft.ContainerService/managedClusters/%s", subscriptionID, split[1], split[2]), nil
}`
