### ISSUE TITLE
Documentation > invalid? request to keep identity in the same RG as the AKS nodes

### ISSUE THREAD

**Issue by mcambal** [Azure/application-gateway-kubernetes-ingress#711]
**Describe the bug**
There is a requirement in the Brownfield deployment to keep AAD Pod Identity in the same resource group as the AKS nodes. This requirement is not mentioned in the Greenfield Deployment. 

What is the difference between Brownfield and Greenfield deployments that only Brownfield deployment requires it? Is it still valid?

This is the text from documentation (https://azure.github.io/application-gateway-kubernetes-ingress/setup/install-existing/)
1. Create an Azure identity in the same resource group as the AKS nodes. Picking the correct resource group is important. The resource group required in the command below is not the one referenced on the AKS portal pane. This is the resource group of the aks-agentpool virtual machines. Typically that resource group starts with MC_ and contains the name of your AKS. For instance: MC_resourceGroup_aksABCD_westus

**Comment by akshaysngupta** [comment]
@mcambal In greenfield, `template` deployment part takes care of deploying the identity. Then, it is just about referencing it in the helm-config.
In brownfield, user assigned identity is created by manually running `az cli` commands.

As such, there is no restriction on where the identity is present as long as the user has `managed identity operator` rights over the identity.

I am working on aligning the document for greenfield and brownfield.
