### ISSUE TITLE
getting error on worker.go:62 when setting parameter shared=true in helm-config.yaml

### ISSUE THREAD

**Issue by mohamedmzid** [Azure/application-gateway-kubernetes-ingress#712]
**Describe the bug**

error when trying to set two differents targets (/app1 and /app2) from two different AKS clusters to the same appgw (waf v2)

**To Reproduce**

- install AGIC on AKS1 and AKS2 with parametre (shared=true)
- create two AzureIngressProhibitedTarget with /app1/* and /app2/* in two clusters
- ingress deploymenet for app1 work correctly but when creating ingress for app2 i got the error code.

** Error code**

error: network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidResourceReference" Message="Resource /subscriptions/—-/providers/Microsoft.Network/applicationGateways/—-/urlPathMaps/url-(hostname)-80 referenced by resource /—/resourceGroups/—/providers/Microsoft.Network/applicationGateways/—/requestRoutingRules/rr-(hostname)-80 was not found. Please make sure that the referenced resource exists, and that both resources are in the same region." Details=[]
I0116 16:24:01.752640       1 mutate_app_gateway.go:174] END AppGateway deployment
E0116 16:24:01.752664       1 worker.go:62] Error mutating App Gateway config from k8s event. network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidResourceReference" Message="Resource /—/resourceGroups/—/providers/Microsoft.Network/applicationGateways/—/requestRoutingRules/rr-(hostname)-80 referenced by resource /—/resourceGroups/—/providers/Microsoft.Network/applicationGateways/—/requestRoutingRules/rr-(hostname)-80 was not found. Please make sure that the referenced resource exists, and that both resources are in the same region." Details=[]

**Comment by mxrss2** [comment]
Some insight would be appreciated on this, cause we are hitting the same issue where first one wins. Our config was kubnet cluster with CNI cluster as the second cluster. Is there a supported config that Multi Cluster and Brownfield works?
