### ISSUE TITLE
error: Future#WaitForCompletion: context has been cancelled: StatusCode=200 

### ISSUE THREAD

**Issue by mschumacher2625** [Azure/application-gateway-kubernetes-ingress#715]
**Describe the bug**
error: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
I0121 07:05:24.811176       1 mutate_app_gateway.go:174] END AppGateway deployment

**To Reproduce**
We have a deployment with ~35 sites.. and setup http redirect.. so ends up with ~70 listeners.. This is initial deployment, plan on having more towards ~200 sites. Any new deployment that makes a change to the app gateway, times out and then it appears to go into a endless loop of trying to update it. 

initially starting occurring on version 1.0.0.. tried the 1.0.1 rc-2 same results

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 

ame:           ingress-azure-7f7fc8cb-6bhlp
Namespace:      default
Priority:       0
Node:           aks-nodepool1-14687019-vmss000000/10.0.0.4
Start Time:     Tue, 21 Jan 2020 06:49:56 +0000
Labels:         app=ingress-azure
                pod-template-hash=7f7fc8cb
                release=ingress-azure
Annotations:    prometheus.io/port: 8123
                prometheus.io/scrape: true
Status:         Running
IP:             10.0.0.144
IPs:            <none>
Controlled By:  ReplicaSet/ingress-azure-7f7fc8cb
Containers:
  ingress-azure:
    Container ID:  docker://2757311949c55f45d6d84a92402a69f36cf0a1edd7d82f8403429276c9c85c5a
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.0.1-rc2
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:1543bf5f9b............965a
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 21 Jan 2020 06:50:12 +0000
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_CONTEXT_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:           ingress-azure-7f7fc8cb-6bhlp (v1:metadata.name)
      AGIC_POD_NAMESPACE:      default (v1:metadata.namespace)
      AZURE_AUTH_LOCATION:     /etc/Azure/Networking-AppGW/auth/armAuth.json
    Mounts:
      /etc/Azure/Networking-AppGW/auth from networking-appgw-k8s-azure-service-principal-mount (ro)
      /etc/appgw/azure.json from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-azure-token-mmwtp (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  networking-appgw-k8s-azure-service-principal-mount:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  networking-appgw-k8s-azure-service-principal
    Optional:    false
  ingress-azure-token-mmwtp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-azure-token-mmwtp
 Optional:    false
QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                     Age    From                                                     Message
  ----     ------                     ----   ----                                                     -------
  Normal   Scheduled                  22m    default-scheduler                                        Successfully assigned default/ingress-azure-7f7fc8cb-6bhlp to aks-nodepool1-14687019-vmss000000
  Normal   Pulling                    22m    kubelet, aks-nodepool1-14687019-vmss000000               Pulling image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.0.1-rc2"
  Normal   Pulled                     22m    kubelet, aks-nodepool1-14687019-vmss000000               Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.0.1-rc2"
  Normal   Created                    22m    kubelet, aks-nodepool1-14687019-vmss000000               Created container ingress-azure
  Normal   Started                    22m    kubelet, aks-nodepool1-14687019-vmss000000               Started container ingress-azure
  Warning  FailedApplyingAppGwConfig  6m57s  azure/application-gateway, ingress-azure-7f7fc8cb-6bhlp  Failed applying App Gwy configuration:
{
-- App Gwy config --    "id": "/subscriptions/b9.....3/resourceGroups/aks-scus-prod-01-rg/providers/Microsoft.Network/applicationGateways/aks-scus-prod-01-ag",
-- App Gwy config --    "location": "southcentralus",
-- App Gwy config --    "id": "/subscriptions/b9...3/resourceGroups/aks-scus-prod-01-rg/providers/Microsoft.Network/applicationGateways/aks-scus-prod-01-ag",
-- App Gwy config --    "location": "southcentralus",
-- App Gwy config --    "properties": {
-- App Gwy config --        "autoscaleConfiguration": {
-- App Gwy config --            "maxCapacity": 3,
-- App Gwy config --            "minCapacity": 2
-- App Gwy config --        },
-- App Gwy config --        "backendAddressPools": [
-- App Gwy config --            {
-- App Gwy config --                "id": "/subscriptions/b9......3/resourceGroups/aks-scus-prod-01-rg/providers/Microsoft.Network/applicationGateways/aks-scus-prod-01-ag/backendAddressPools/defaultaddresspoo
l",
-- App Gwy config --                "name": "defaultaddresspool",
-- App Gwy config --                "properties": {
-- App Gwy config --                    "backendAddresses": []
-- App Gwy config --      
.........
....lots more likes like the ones above with the "App Gwy config"
.....
....
-- App Gwy config --        "webApplicationFirewallConfiguration": {
-- App Gwy config --            "disabledRuleGroups": [],
-- App Gwy config --            "enabled": true,
-- App Gwy config --            "exclusions": [],
-- App Gwy config --            "fileUploadLimitInMb": 100,
-- App Gwy config --            "firewallMode": "Detection",
-- App Gwy config --            "maxRequestBodySizeInKb": 128,
-- App Gwy config --            "requestBodyCheck": true,
-- App Gwy config --            "ruleSetType": "OWASP",
-- App Gwy config --            "ruleSetVersion": "3.0"
-- App Gwy config --        }
-- App Gwy config --    },
-- App Gwy config --    "tags": {
-- App Gwy config --        "ingress-for-aks-cluster-id": "/subscriptions/b9...3/resourcegroups/aks-scus-prod-01-rg/providers/Microsoft.ContainerService/managedClusters/aks-scus-prod-01-cl",
-- App Gwy config --        "last-updated-by-k8s-ingress": "2020-01-21 06:50:19.514982449 +0000 UTC m=+7.103336064",
-- App Gwy config --        "managed-by-k8s-ingress": "1.0.1-rc2/2105e9e7/2019-12-10-07:01T+0000"
-- App Gwy config --    }
-- App Gwy config --}

error: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded

* Output of `kubectl logs <ingress controller>. 
 -- see above

* Any Azure support tickets associated with this issue.
120012021001411

**Comment by mschumacher2625** [comment]
I believe this https://github.com/Azure/application-gateway-kubernetes-ingress/issues/316 would help.. to not have to have different certs for each deployment

**Comment by akshaysngupta** [comment]
@mschumacher2625 Thanks for reporting. I will take a look shortly.

For #316, yes, currently, you need to provide certificate for each namespace, we are planning to make this easier by having a Key Vault integration. I don't have an ETA yet.

**Comment by NiklasArbin** [comment]
We're currently experiencing this in our production environment too. No traffic is coming through to newly created pods since the ingress cannot update the appgw.
We only use 1 certificate.

**Comment by iamNoah1** [comment]
any news on this one, since we are experiencing the same behavior. The longest time range I have experienced the AppGw being in Updating state and rejecting any traffic on the respective routes was about 10 hours.

**Comment by prateekchawla** [comment]
@iamNoah1 Did you get hold on the error? I have the same problem. AppGW is in updating state & the logs are not very useful

**Comment by iamNoah1** [comment]
@prateekchawla to be honest we decided to not use AGIC anymore and now use Traefik Ingress Controller for that specific customer project
