### ISSUE TITLE
Application Gateway with AKS fails with muliple backend pods app with Azure AAD authentication

### ISSUE THREAD

**Issue by mtuppad** [Azure/application-gateway-kubernetes-ingress#72]
I am using Application Gateway as ingress controller on my AKS cluster https://github.com/Azure/application-gateway-kubernetes-ingress.
1.	Developed a ASP.net Core application with Azure AAD application.
2.	Deployed to AKS cluster
3.	Created Application Gateway ingress controller to access this application via App Gateway URL
4.	All works fine when there is only one pod of application running in AKS.
5.	Things break when scale the AKS application to 2 or more pods, which is a requirement in production case. (for high Availability)
6.	The same app works when Accessed form public IP exposed by AKS (Load Balancer type service)
An unhandled exception occurred while processing the request.
Exception: Correlation failed.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+d__12.MoveNext()
Stack Query Cookies Headers
Exception: Correlation failed.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Session.SessionMiddleware+d__9.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Session.SessionMiddleware+d__9.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+d__7.MoveNext()
Show raw exception details
System.Exception: Correlation failed.
at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler1.<HandleRequestAsync>d__12.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Session.SessionMiddleware.d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.AspNetCore.Session.SessionMiddleware.d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.d__7.MoveNext()

**Comment by mtuppad** [comment]
I am using Application Gateway as ingress controller on my AKS cluster https://github.com/Azure/application-gateway-kubernetes-ingress. 

1. Developed a ASP.net Core application with Azure AAD application. 
2. Deployed to AKS cluster 
3. Created Application Gateway ingress controller to access this application via App Gateway URL
4. All works fine when there is only one pod of application running in AKS. 
5. Things break when scale the AKS application to 2 or more pods, which is a requirement in production case. (for high Availability) 
6. The same app works fine with multiple pods when accessed from public IP exposed as AKS load balancer. 

An unhandled exception occurred while processing the request.
Exception: Correlation failed.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()
Stack Query Cookies Headers 
Exception: Correlation failed.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Session.SessionMiddleware+<Invoke>d__9.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Session.SessionMiddleware+<Invoke>d__9.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

Show raw exception details 
System.Exception: Correlation failed.
at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

**Comment by asridharan** [comment]
@mtuppad why do you thing this is problem with the load-balancer? The exception being thrown seem to be coming from the application pod. It seems to work when only a single instance of the pod is running but seems to fail when the traffic is spread across multiple pods. Also, it would work when you are accessing it from the public IP because the traffic again hits only a single pod.

Could you describe what your application is trying to do? Explaining the architecture and the workflow of the requests would be helpful as well.

**Comment by asridharan** [comment]
Based on offline discussion looks like this is resolved.

**Comment by mtuppad** [comment]
@asridharan thanks for closing. Just to clarify, it did work with public ip address (load balancer) when there are more than 2 pods. Its used to fail only when accessed via app gateway. 

I am posting solution for others benefit. 

Turns out to be dotnet core new api issues. The authentication flow uses data protection API for encryption and decryption of some data (not sure which).  I wasn’t using any shared location to store the keys for the data protection keys. Hence in multi-pod deployment when originating request lands in another pod, issue came. Here is what I did. 

-	Created new storage account in resources group where AKS is deployed. (which is usually Start MC_).  I did try storage account outside of resources group and region, AKS nodes didn’t had access to these storage accounts. SO make sure it’s in same resource group as AKS. Not sure its right thing to as its MC_ 
-	Add below code to startup class ConfigureServices method. (sorry couldn't get all code in code block)

-------

`
try
            {
                string AppStorageAccountConnectionString = Configuration.GetSection("keystore").GetValue<string>("AppStorageAccountConnectionString");
                // create a blob storage container to use as the central, cross-node DataProtection key holder
                CloudStorageAccount storageAccount = CloudStorageAccount.Parse(AppStorageAccountConnectionString);
                CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();
                CloudBlobContainer blobContainer = blobClient.GetContainerReference("tupblobsea");
                blobContainer.CreateIfNotExistsAsync().GetAwaiter().GetResult();

                // TODO: keys in keys.xml are not encrypted at rest, by default
                // we need to add an encryption cert here so they will be, via .ProtectKeysWithCertificate("certthumbprint")
                services.AddDataProtection(options =>
                {
                    options.ApplicationDiscriminator = "todolistwebapp";
                })
                .PersistKeysToAzureBlobStorage(blobContainer, "keys.xml");
            }
            catch (System.Exception ex)
            {

                Console.WriteLine("Error in dataprotection-" + ex.Message);
            }
`
-	Scaled the app to 4 pods and seems like issue is gone. 
-	Other option is to use volumes to store keys. 
https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv
-	Haven’t tried the file share option, but looks like it should work as all pods will mount same file share. 
-	
Some references I used are 
https://github.com/IdentityServer/IdentityServer4/issues/720
https://www.kevindockx.com/solving-correlation-failed-state-property-not-found-errors-openid-connect-middleware-asp-net-core/
https://github.com/aspnet/Security/issues/1755#issuecomment-392803709
