### ISSUE TITLE
Configuring Shared AGIC after deployment fails

### ISSUE THREAD

**Issue by samrobillard** [Azure/application-gateway-kubernetes-ingress#720]
Deploying the Helm chart with the option "shared: true" in helm-config.yaml throws the following error:

**manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "AzureIngressProhibitedTarget" in version "appgw.ingress.k8s.io/v1"**

Following the documentation and applying the following manifest:

**apiVersion: "appgw.ingress.k8s.io/v1"
kind: AzureIngressProhibitedTarget
metadata:
  name: somedns.com
spec:
  hostname: somedns.com**

Throws the following error:

**error: unable to recognize "prohibited-agic.yaml": no matches for kind "AzureIngressProhibitedTarget" in version "appgw.ingress.k8s.io/v1"**

Helm chart version is ingress-azure-1.0.0

**Comment by BzSpi** [comment]
It seems that the Helm chart does not deploy the required CRD https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/crds/AzureIngressProhibitedTarget.yaml.

It should.

**Comment by akshaysngupta** [comment]
This seems to be related to helm 3 not supporting `crd-install`hook.

**Comment by samrobillard** [comment]
Any updates on this issue? More people at my work are getting this exact error. Helm 3 doesn't support the crd-install hook. Were their recommendations applied to AGIC?
https://v3.helm.sh/docs/topics/charts_hooks/

**Comment by samrobillard** [comment]
I'll open a new issue with the new error.
