### ISSUE TITLE
App GW with Let's Encrypt not working

### ISSUE THREAD

**Issue by samrobillard** [Azure/application-gateway-kubernetes-ingress#721]
Following the documentation provided in this repo to configure Cert-Manager with App GW and the ingress controller does not create any https listener, backend pool or anything but I see the following in the logs:

I0127 16:30:58.327137       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment
I0127 16:31:18.869181       1 mutate_app_gateway.go:182] Applied App Gateway config in 20.542019492s
I0127 16:31:18.869210       1 mutate_app_gateway.go:198] cache: Updated with latest applied config.
I0127 16:31:18.869975       1 mutate_app_gateway.go:203] END AppGateway deployment

Here's my manifest for the ingress:

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ing
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
      - somedns.com
      secretName: lets-encrypt-secret
  rules:
  - host: somedns.com
    http:
      paths:
      - backend:
          serviceName: svc
          servicePort: 80
        path: /

Cert-Manager version is 0.13 (latest). It works with a NGINX Ingress controller by the way.

**Comment by akshaysngupta** [comment]
@samrobillard You should try the following
1) Look at the logs by setting [log verbosity](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/troubleshooting.md#logging-levels) to 5.
2) Look at the k8s events by see if you see any event associated to the ingress created by AGIC.

**Comment by samrobillard** [comment]
@akshaysngupta 

Thanks for getting back to me. Setting the logging level 5 showed that with a TLS config in the Ingress manifest, nothing besides the default pool, listener, etc get created. If my manifest contains only the HTTP portion, everything gets created as it should. Let me know if I can provide more information.

**Comment by samrobillard** [comment]
I figured out the issue. There were some changes in the API version and annotations since version 0.8 that is explained in the documentation. For the ClusterIssuer is now "cert-manager.io/v1alpha2" with the http01 section now being:

solvers:
  - http01:
    ingress:
      class: azure/application-gateway

The annotation for the Ingress manifest is now: "cert-manager.io/cluster-issuer:"
