### ISSUE TITLE
Unable to get AGIC to work with AKS backed by VMSS

### ISSUE THREAD

**Issue by AlexanderViken** [Azure/application-gateway-kubernetes-ingress#730]
**Describe the bug**
.I've tried to get AGIC to work with both brownfield and greenfield eployment with an AKS service backed by VMSS. For some reason it will not work.

**To Reproduce**
Modify greenfield sample template to use VMSS instead of AvailabilitySet.

If it is a know issue I think it would be wise to put a notice about it.

**Comment by akshaysngupta** [comment]
@AlexanderViken You should try the following
1) Look at the logs by setting [log verbosity](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/troubleshooting.md#logging-levels) to 5.
2) Look at the k8s events by see if you see any event associated to the ingress created by AGIC.

**Comment by AlexanderViken** [comment]
for some reason it has suddenly started to work but I have noe idea of why because I've run this deployment script a 100 times. I'll just close this.
