### ISSUE TITLE
Does application-gateway support Helm 3

### ISSUE THREAD

**Issue by pratham98k** [Azure/application-gateway-kubernetes-ingress#731]
Does application-gateway support Helm 3, I am using continuous deployment.
https://azure.github.io/application-gateway-kubernetes-ingress/how-tos/continuous-deployment/

soon planning to use aks(k8s)1.17 for CD will this work ?

**Comment by ericgoode** [comment]
I was able to follow the directions, skip the tiller install and use Helm 3 to install the gateway.

**Comment by akshaysngupta** [comment]
Yes, it supports helm 3. As mentioned by @ericgoode, just skip the `helm init`

**Comment by joelharkes** [comment]
@akshaysngupta does it work on AKS version 1.17 as well? (this question wasnt answered)

**Comment by sebader** [comment]
@joelharkes nope, it does not :( see here https://github.com/Azure/application-gateway-kubernetes-ingress/issues/767

**Comment by joelharkes** [comment]
@sebader i got it working on our AKS. Small helm issue but that was all.
