### ISSUE TITLE
Greenfield docs do not specify Azure CNI as a prerequisite

### ISSUE THREAD

**Issue by AdamSharif-MSFT** [Azure/application-gateway-kubernetes-ingress#739]
**Describe the bug**

Documentation here missing the prerequisite for Azure CNI rather than Kubenet

**To Reproduce**
N/A - documentation needs clarification

--

On the official setup docs, we see a note for Azure CNI being a prerequisite for brownfield deployment:

_Prerequisites
This documents assumes you already have the following tools and infrastructure installed: - AKS with **Advanced Networking enabled** - App Gateway v2 in the same virtual network as AKS - AAD Pod Identity installed on your AKS cluster - Cloud Shell is the Azure shell environment, which has az CLI, kubectl, and helm installed. These tools are required for the commands below._

REF: https://azure.github.io/application-gateway-kubernetes-ingress/setup/install-existing/#prerequisites

However, the same statement is not mentioned for greenfield:

https://azure.github.io/application-gateway-kubernetes-ingress/setup/install-new/

---

Is this correct/is it possible to deploy greenfield with kubenet?

**Comment by akshaysngupta** [comment]
@AdamSharif-MSFT You can now use AKS with kubenet with AGIC. Just make sure that you associate the route table of AKS with Application Gateway's subnet. I will update the docs soon.

**Comment by AdamSharif-MSFT** [comment]
That's great news! Does this support AppGw V2 also, or just V1 for now?

Sent from Nine<http://www.9folders.com/>
________________________________
