### ISSUE TITLE
cloud environment variable problem

### ISSUE THREAD

**Issue by bg2s0r** [Azure/application-gateway-kubernetes-ingress#740]
**Describe the bug**
I set the cloud environment variable to AzureChinaCloud, but it still request the wrong api endpoint.
**To Reproduce**
snippet of helm-config.yml
`
appgw:
    environment: AZURECHINACLOUD
    subscriptionId: dc6f24f5-ff36-4029-b603-ddb144490348
    resourceGroup: testResourceGroup1
    name: ApplicationGateway1
    usePrivateIP: false
`

**Ingress Controller details**
* Output of `kubectl logs <ingress controller>. 

`
ERROR: logging before flag.Parse: I0220 16:49:40.191714       1 main.go:302] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0220 16:49:40.222557       1 environment.go:168] KUBERNETES_WATCHNAMESPACE is not set. Watching all available namespaces.
I0220 16:49:40.222632       1 main.go:132] App Gateway Details: Subscription: dc6f24f5-ff36-4029-b603-ddb144490348, Resource Group: testResourceGroup1, Name: ApplicationGateway1
I0220 16:49:40.222647       1 auth.go:90] Creating authorizer from Azure Managed Service Identity
E0220 16:49:40.330818       1 auth.go:28] Possible reasons: AKS Service Principal requires 'Managed Identity Operator' access on Controller Identity; 'identityResourceID' and/or 'identityClientID' are incorrect in the Helm config; AGIC Identity requires 'Contributor' access on Application Gateway and 'Reader' access on Application Gateway's Resource Group;
E0220 16:49:40.330839       1 auth.go:41] Unexpected ARM status code on GET existing App Gateway config: 403
E0220 16:49:40.330845       1 auth.go:49] Failed fetching config for App Gateway instance. Will retry in 10s. Error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/dc6f24f5-ff36-4029-b603-ddb144490348/resourceGroups/testResourceGroup1/providers/Microsoft.Network/applicationGateways/ApplicationGateway1?api-version=2019-09-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://management.azure.com/ was not found in the tenant named 2cbcf857-5096-4909-a7a9-37fcc567abab. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: 3ee0adcc-3604-4bb6-ada5-a52b84115c00\r\nCorrelation ID: 3585698e-632b-4559-9e95-c8ea1880ff0b\r\nTimestamp: 2020-02-20 16:49:40Z","error_codes":[500011],"timestamp":"2020-02-20 16:49:40Z","trace_id":"3ee0adcc-3604-4bb6-ada5-a52b84115c00","correlation_id":"3585698e-632b-4559-9e95-c8ea1880ff0b","error_uri":"https://login.chinacloudapi.cn/error?code=500011"}
E0220 16:49:50.424261       1 auth.go:28] Possible reasons: AKS Service Principal requires 'Managed Identity Operator' access on Controller Identity; 'identityResourceID' and/or 'identityClientID' are incorrect in the Helm config; AGIC Identity requires 'Contributor' access on Application Gateway and 'Reader' access on Application Gateway's Resource Group;
`

**Comment by akshaysngupta** [comment]
Closing this in favor of https://github.com/Azure/application-gateway-kubernetes-ingress/issues/735
