### ISSUE TITLE
Does it support Gateway Tier standard (not v2)?

### ISSUE THREAD

**Issue by joelharkes** [Azure/application-gateway-kubernetes-ingress#745]
The docs mention you must have a V2 gateway: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/setup/install-existing.md#prerequisites

Doest it also work with v1? because v2 isnt supported on all locations:
![image](https://user-images.githubusercontent.com/2960938/75259366-33203780-57e8-11ea-95e4-97d2d11c452e.png)

Sadly its also not possible to host k8s service in other region as to host the gateways since they have to be connected with the same VNet?

**Comment by mscatyao** [comment]
Hey @joelharkes - v0.9.0 is the last version of AGIC to support AppGW v1 [(release notes)](https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/0.9.0). AppGW v2 is tentatively set to be in Germany West Central by 3/15. We will let you know if that date gets pushed back.
