### ISSUE TITLE
Reverse proxy to an external service

### ISSUE THREAD

**Issue by bpinter** [Azure/application-gateway-kubernetes-ingress#749]
I would like to configure the application gateway with the ingress controller to do two jobs:
- drive the traffic into my AKS cluster (this works as expected)
- adding a /proxy/* path based reverse proxy rule which should drive the traffic to another application gateway. 

I have currently two ingresses in my helm chart. Both of them uses the same hostname. So ingress controller configured the application gateway properly like it created path-based rules. But the health probe fails for the reverse proxy backend pool. 

Would you have any advice on how to debug this or any description, tutorial which could help me?

**Comment by Wema** [comment]
I have also have a similar request where I would like to drive traffic to an azure function, or an api management instance.
