### ISSUE TITLE
Parameters.json file is missing

### ISSUE THREAD

**Issue by dereksonthejob** [Azure/application-gateway-kubernetes-ingress#757]
**Describe the bug**

**To Reproduce**

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
* Output of `kubectl logs <ingress controller>. 
* Any Azure support tickets associated with this issue.

**Comment by akshaysngupta** [comment]
@dereksonthejob Please refer the greenfield document to see how the parameter file is generated.
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/setup/install-new.md#create-an-identity

**Comment by dereksonthejob** [comment]
Thanks
