### ISSUE TITLE
Using multi Applicaiton gateway ingress controller for single cluster

### ISSUE THREAD

**Issue by dewanymca** [Azure/application-gateway-kubernetes-ingress#764]
Hi All

We have been using App Gateway as ingress controller and everything is working as expected. We want to have 3 different ingress controller connected to same cluster. reason of having different controller is to allow different team not to get into overriding each other route in Application Gateway and breaking stuff. Is this possible? Please provide some recommendation.

Thanks

**Comment by akshaysngupta** [comment]
Yes, you can run multiple AGICs targeting different app gateways. You can use the https://github.com/Azure/application-gateway-kubernetes-ingress/blob/8e33f25befbcecb56e038fd3212c62453236b1de/helm/ingress-azure/values.yaml#L20
to provide different namespaces for each ingress controller to watch.
