### ISSUE TITLE
Please update repository for K8s v1.16x

### ISSUE THREAD

**Issue by mindstormz** [Azure/application-gateway-kubernetes-ingress#767]
Hi there,

I'm afraid this is neither an issue nor a feature request, but I noticed the Charts available in the [official Repository](https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/) are not compatible for use with Kubernetes Versions v1.16.x.

This is because the Deployment.yaml on the blob is still using API v1beta2 - which was deprecated with the introduction of K8s v1.16.

Is it possible to update the Chart on the Blob?

**Comment by sebader** [comment]
I'm having the same issue - just with K8s 1.17.0 :(

**Comment by sebader** [comment]
Looks like this was already fixed here: https://github.com/Azure/application-gateway-kubernetes-ingress/pull/713

@akshaysngupta when will there be a new release with this PR included? thanks!

**Comment by erjosito** [comment]
Yepp, I have verified that cloning this repo and deploying from the local chart (instead of deploying from the helm repo) works just fine on a 1.16 cluster. Using helm3 BTW.

**Comment by rdtechie** [comment]
Having the same issue. Just downloading the chart and modifying deployment.yaml to use the correct API version works for me also. But best is to get the repo up to date. Checking the pipeline, I see that there's a new release going running, but still need to be approved. Hope that this will happen soon!

**Comment by kylefender** [comment]
If you do clone the repo locally, make sure to switch to the 1.0.0 tag before updating the deployment.yaml file because there are some configuration changes (ex. AZURE_CONTEXT_LOCATION renamed to AZURE_CLOUD_PROVIDER_LOCATION) that aren't in the image yet.

**Comment by SychevIgor** [comment]
https://github.com/Azure/application-gateway-kubernetes-ingress/issues/781

**Comment by akshaysngupta** [comment]
Closing in favour of #788
