### ISSUE TITLE
504 error using Application gatewat ingress controller

### ISSUE THREAD

**Issue by dewanymca** [Azure/application-gateway-kubernetes-ingress#770]
Hi Team

We have been using Application Gateway ingress controller and we are seeing different behavior. If we try to load test, then all request starts failing with 504.
 Below is message flow:

AGIC->POD->(dotnet core).

checking logs on Application gateway this is what is see:

httpStatus_d | 504
  | httpVersion_s | HTTP/1.1
  | receivedBytes_d | 5264
  | sentBytes_d | 376
  | timeTaken_d | 30.211
  | serverStatus_s | 504

Bakend shows all request gets processed with 200 response.

Not sure what is the issue.

Thanks
Deepak Sanghi

**Comment by vishnujanardhanan** [comment]
@dewanymca  504 indicates a timeout.  If your backend takes time then the request timeout can be set via this annotation

appgw.ingress.kubernetes.io/request-timeout: "60"

**Comment by dewanymca** [comment]
I am seeing 504 even for request finishing in 30 sec.

**Comment by vishnujanardhanan** [comment]
@dewanymca can you increase the timeout to 35 secs and validate pls? timetaken seems to be 30 secs, which is almost the time appgw closes the connection
