### ISSUE TITLE
502 error in AGIC

### ISSUE THREAD

**Issue by dewanymca** [Azure/application-gateway-kubernetes-ingress#771]
Hi Team

We are using AGIC to route the traffic to POD(in backend), we are experiencing 502 error under load and traffic is going to default route not to the API path define in the AG. Not sure why under load something is going into default route. below are logs from AG for success and fail scenario

502 error:

listenerName_s | fl-80
  | ruleName_s | rr-80
  | backendPoolName_s | defaultaddresspool
  | backendSettingName_s | defaulthttpsetting

success 200:

listenerName_s | fl-80
  | ruleName_s | rr-80
  | backendPoolName_s | pool-default-tradeproformaapi-service-80-bp-80
  | backendSettingName_s | bp-default-tradeproformaapi-service-80-80-tradeproformaapi-ingress

Once it's stop working, there is no way i can make it work. it keep on giving 502 error and i need to fully redeploy the yaml files.

**Comment by akshaysngupta** [comment]
@dewanymca Once you start seeing 502s, Can you check the following:
1) if there are any errors in the AGIC Pod logs
2) if the routing rules are as expected on the app gateway
3) if scaling up your application pods helps with the 502s.

**Comment by dewanymca** [comment]
Please see responses below:
#1. I don't see error in AGIC pod logs. As per my understanding, this pod is being used to monitor API server and make those changes for ingress in Application Gateway. I can see route along with backend ip in AG.

#2. Yes routing rules are expected.

#3. Once it's stops working it doesn't work at all.


Below are steps to reproduce:

1) Deployment using Helm.
2) test application and it works for few request(not sure how many but once it's starts failing it doesn't work at all).
3) TO fix #2 , follow from #1


Thanks
Deepak Sanghi

**Comment by dewanymca** [comment]
THanks Akshay for help. This is resolved.

**Comment by sandy-wang** [comment]
Can you let me know what is the fix? Thanks.
