### ISSUE TITLE
deploy AGIC pod to a tainted node using toleration property

### ISSUE THREAD

**Issue by niteenkole** [Azure/application-gateway-kubernetes-ingress#777]
**Describe the Question**
We setting up AGWIC ,is there option to run this only on nodepool which say labelled as edge and taint dedicated=edge:NoSchedule

We want to run all network and critical components on nodepool where applications will not be schedule.

We don't want any buggy or any apps to take down our ingress down.

**To Reproduce**

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
* Output of `kubectl logs <ingress controller>. 
* Any Azure support tickets associated with this issue.

**Comment by akshaysngupta** [comment]
Try using `.Values.nodeSelector`
 ```yaml
nodeSelector:
  <replace-with-label>: <replace-with-value> # example: kubernetes.io/label: edge
```

**Comment by niteenkole** [comment]
Thanks,Not sure what wrong i am doing here.

Node-Selectors:  dedicated=edge
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  26s (x2 over 26s)  default-scheduler  0/3 nodes are available: 3 node(s) had taints that the pod didn't tolerate.
[xxxxxnp01@xxxxxtstd01 applicationGW]$ kubectl get nodes -L dedicated
NAME                                STATUS   ROLES   AGE   VERSION   DEDICATED
aks-nodepool1-35427162-vmss000000   Ready    agent   46h   v1.14.8   edge
aks-nodepool1-35427162-vmss000001   Ready    agent   46h   v1.14.8   edge
aks-nodepool1-35427162-vmss000002   Ready    agent   46h   v1.14.8   edge

values
nodeSelector:
## <replace-with-label>: <replace-with-value> # example: kubernetes.io/label: edge
 dedicated: edge

**Comment by akshaysngupta** [comment]
Can you check the AGIC pod and look if the node selector looks as expected ?

**Comment by niteenkole** [comment]
kubectl get po
NAME                                                           READY   STATUS    RESTARTS   AGE
cglaksnp01-ingress-controller-ingress-azure-7b45fb7957-8g6cv   0/1     Pending   0          13m

kubectl describe po cglaksnp01-ingress-controller-ingress-azure-7b45fb7957-8g6cv
.....
.....
Node-Selectors:  dedicated=edge
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  53s (x11 over 14m)  default-scheduler  0/3 nodes are available: 3 node(s) had taints that the pod didn't tolerate.

selector looks good.

**Comment by niteenkole** [comment]
same with.
helm install xxxxnp01-ingress-controller -f helm-config-sp-02.yaml application-gateway-kubernetes-ingress/ingress-azure --set nodeSelector.dedicated=edge

**Comment by akshaysngupta** [comment]
@niteenkole https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
Looking at this, seems like pod instead needs a toleration property.

Can you try modifying the AGIC deployment definition appropriately ?

AGIC helm package doesn't take toleration property.

**Comment by niteenkole** [comment]
yup works. in deployment

      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: edge
      - effect: NoExecute
        key: dedicated
        operator: Equal
        value: edge

 kubectl get po
NAME                                                           READY   STATUS    RESTARTS   AGE
cglaksnp01-ingress-controller-ingress-azure-84df98c494-h6wl8   1/1     Running   0          47s

I0327 01:11:26.835571       1 main.go:179] Ingress Controller will observe all namespaces.
I0327 01:11:26.873746       1 context.go:129] k8s context run started
I0327 01:11:26.873775       1 context.go:168] Waiting for initial cache sync
I0327 01:11:26.973928       1 context.go:176] Initial cache sync done
I0327 01:11:26.973947       1 context.go:177] k8s context run finished
I0327 01:11:26.974702       1 worker.go:35] Worker started
I0327 01:11:26.974895       1 httpserver.go:57] Starting API Server on :8123
I0327 01:11:27.231460       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment

thank you :)
