### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference : status CrashLoopbackOff

### ISSUE THREAD

**Issue by billandr** [Azure/application-gateway-kubernetes-ingress#779]
**Describe the bug**
I get the following error constantly; not sure exactly when; feels random but I see it more often when I deploy a new image via kubectl set image; but not sure it's related.

What's odd is that I think everything is working fine; the proper routes and rules do get added to the AGW. (but I notice it takes about 3 minutes - after pods have been updated - for the new PODs ip addresses to show up in the backend pool)  But even after they finally get added; I still have that CrashLoopBackOff error.

I've also had everything running and was seeing that error; then have scaled to 0 and then back to 1 in order to restart the POD; and it would take a little while and never get to ready; then finally show the error.  So I suspect something is going wrong when it's syncing with the AGW.  Does the error give any hints? (e.g. [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x12b6ed7] )

This seems related to #629 but not sure.

`ERROR: logging before flag.Parse: I0328 08:25:19.829930       1 main.go:306] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0328 08:25:19.858639       1 environment.go:168] KUBERNETES_WATCHNAMESPACE is not set. Watching all available namespaces.
I0328 08:25:19.858745       1 main.go:149] App Gateway Details: Subscription: 334721bb-4843-4295-97b5-ea17504c130b, Resource Group: tdp-k8s, Name: agw
I0328 08:25:19.858768       1 auth.go:90] Creating authorizer from Azure Managed Service Identity
I0328 08:25:19.858809       1 httpserver.go:57] Starting API Server on :8123
I0328 08:25:20.224296       1 main.go:191] Ingress Controller will observe all namespaces.
I0328 08:25:20.260472       1 context.go:129] k8s context run started
I0328 08:25:20.260516       1 context.go:168] Waiting for initial cache sync
I0328 08:25:20.360729       1 context.go:176] Initial cache sync done
I0328 08:25:20.360753       1 context.go:177] k8s context run finished
I0328 08:25:20.360871       1 worker.go:35] Worker started
I0328 08:25:20.538911       1 redirects.go:44] Created redirection configuration sslr-fl-9cc0407a3335a7032907821ad24f777d for ([staging.dictionaryproject.org    ],443); not yet linked to a routing rule
I0328 08:25:20.538941       1 redirects.go:44] Created redirection configuration sslr-fl-b07619f8fbb2fcc84d98673621ae065c for ([new.dictionaryproject.org    ],443); not yet linked to a routing rule
I0328 08:25:20.550209       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment
I0328 08:25:41.028321       1 mutate_app_gateway.go:182] Applied App Gateway config in 20.47807913s
I0328 08:25:41.028348       1 mutate_app_gateway.go:198] cache: Updated with latest applied config.
I0328 08:25:41.029624       1 mutate_app_gateway.go:203] END AppGateway deployment
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x12b6ed7]

goroutine 128 [running]:
github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext.(*Context).isServiceReferencedByAnyIngress(0xc00032e750, 0xc0004869d8, 0xc00066ab70)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:508 +0x107
github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext.(*Context).IsPodReferencedByAnyIngress(0xc00032e750, 0xc000143880, 0xc00043dc98)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:255 +0x85
github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.AppGwIngressController.ShouldProcess(0x1860000, 0xc0001be000, 0xc000042096, 0x24, 0xc000048015, 0x7, 0xc00004600b, 0x3, 0xc00045eae0, 0xc00032e750, ...)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/should_process.go:22 +0x384
github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker.(*Worker).Run(0xc00037f080, 0xc000388720, 0xc000393e60)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker/worker.go:39 +0x1fd
created by github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.(*AppGwIngressController).Start
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/controller.go:72 +0x1a8
`
**Ingress Controller details**
Name:           ingress-tdp-ingress-azure-764f76d76-t844r
Namespace:      default
Priority:       0
Node:           aks-agentpool-35064155-vmss000000/15.0.0.4
Start Time:     Fri, 27 Mar 2020 01:28:41 -0700
Labels:         aadpodidbinding=ingress-tdp-ingress-azure
                app=ingress-azure
                pod-template-hash=764f76d76
                release=ingress-tdp
Annotations:    prometheus.io/port: 8123
                prometheus.io/scrape: true
Status:         Running
IP:             15.0.0.28
IPs:            <none>
Controlled By:  ReplicaSet/ingress-tdp-ingress-azure-764f76d76
Containers:
  ingress-azure:
    Container ID:   docker://c888a5a23a5874ba3f04b287c9f2803423d2150f6521bf2ea9936b0cf6850777
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.0.1-rc2
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:1543bf5f9b60534d7702ef199dd573ff2d301f3f3f8df96d99da9db7f2f7965a
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Sat, 28 Mar 2020 01:36:09 -0700
      Finished:     Sat, 28 Mar 2020 01:36:30 -0700
    Ready:          False
    Restart Count:  242
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      ingress-tdp-cm-ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_CONTEXT_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:           ingress-tdp-ingress-azure-764f76d76-t844r (v1:metadata.name)
      AGIC_POD_NAMESPACE:      default (v1:metadata.namespace)
    Mounts:
      /etc/appgw/azure.json from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-tdp-sa-ingress-azure-token-9pwsz (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  ingress-tdp-sa-ingress-azure-token-9pwsz:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-tdp-sa-ingress-azure-token-9pwsz
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                     From                                        Message
  ----     ------   ----                    ----                                        -------
  Normal   Pulling  9m32s (x242 over 24h)   kubelet, aks-agentpool-35064155-vmss000000  Pulling image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.0.1-rc2"
  Warning  BackOff  4m34s (x5522 over 24h)  kubelet, aks-agentpool-35064155-vmss000000  Back-off restarting failed container

**Comment by billandr** [comment]
@3quanfeng still exists in 1.2.0-rc1

**Comment by 3quanfeng** [comment]
Hi @billandr , Thank you so much to report the issue, could you help send me the agic log from the version 1.2.0-rc1, and before you start the pod, would you mind help set the log verbosity to 5:
"--set verbosityLevel=5"

**Comment by srodenhuis** [comment]
Any updates on this issue? Also running into the same issue:

I0519 07:58:18.069131       1 mutate_app_gateway.go:203] END AppGateway deployment
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x12b6b77]

goroutine 110 [running]:
github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext.(*Context).isServiceReferencedByAnyIngress(0xc0002f0750, 0xc0006c63f0, 0xc0008fc030)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:508 +0x107
github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext.(*Context).IsPodReferencedByAnyIngress(0xc0002f0750, 0xc0004daa80, 0xc00073dc98)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:255 +0x85
github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.AppGwIngressController.ShouldProcess(0x1856b00, 0xc00031c800, 0xc000044016, 0x24, 0xc000044055, 0x1f, 0xc00004203b, 0x16, 0xc0004164e0, 0xc0002f0750, ...)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/should_process.go:22 +0x384
github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker.(*Worker).Run(0xc0006030a0, 0xc00034e840, 0xc0000901e0)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker/worker.go:39 +0x1fd
created by github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.(*AppGwIngressController).Start
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/controller.go:72 +0x1a8

**Comment by akshaysngupta** [comment]
@srodenhuis We have addresses this issue in the `1.2.0-rc2`. Please upgrade your AGIC installation and see if you still encounter any issues.

**Comment by billandr** [comment]
@akshaysngupta must have missed that commit; will review.

**Comment by srodenhuis** [comment]
> @srodenhuis We have addresses this issue in the `1.2.0-rc2`. Please upgrade your AGIC installation and see if you still encounter any issues.

using 1.2.0-rc2 resulted in the issue. Removed all ingresses and then deployed new ones. That solved it.
