### ISSUE TITLE
Deployment: Agent Disk Size

### ISSUE THREAD

**Issue by florianrusch** [Azure/application-gateway-kubernetes-ingress#78]
**Describe the bug**
The `aksAgentOsDiskSizeGB.metadata.description` in https://github.com/Azure/application-gateway-kubernetes-ingress/blob/1997096de11119f6ac8a29602d53ad1fe5e3ce7d/deploy/azuredeploy.json#L57 says that 0 would set the disk size to the default size of the agentVMSize. But the minimum size is 30 GB.

**Comment by akshaysngupta** [comment]
@florianrusch yes, the AKS cluster doesn't support VM size under 30 GB. I will update aksAgentOsDiskSizeGB minimum to reflect that. Thanks.

**Comment by vramakrishnan** [comment]
Fixed as part of #86
