### ISSUE TITLE
Question: client source IP preservation 

### ISSUE THREAD

**Issue by niteenkole** [Azure/application-gateway-kubernetes-ingress#780]
**Describe the bug**
Multiple setup we need "client source IP preservation" due to audit or other logic like in finance app allow only this attempt and if more block.

Normal ingress if we create we have option "add --set controller.service.externalTrafficPolicy=Local to the Helm install command" is this valid here ?

https://docs.microsoft.com/en-us/azure/aks/ingress-basic
**To Reproduce**

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
* Output of `kubectl logs <ingress controller>. 
* Any Azure support tickets associated with this issue.

**Comment by 3quanfeng** [comment]
Hi @niteenkole, Thanks for the question.
In terms of "client IP preservation", Azure Application Gateway[ automatically injects "X-FORWARDED-FOR"](https://docs.microsoft.com/en-us/azure/application-gateway/how-application-gateway-works) when it relays the request from client to the backend.
AGIC install doesn't have that configuration now.

**Comment by egorchabala** [comment]
Do you have plans to release this functionality for AGIC?

**Comment by giotab** [comment]
@3quanfeng any feedback about this?

**Comment by ramazankilimci** [comment]
@3quanfeng we really need this feature. Any update on this?
