### ISSUE TITLE
AgentPoolK8sVersionNotSupported - 1.15.5

### ISSUE THREAD

**Issue by ajomathew** [Azure/application-gateway-kubernetes-ingress#781]
**Describe the bug**
kubernetesVersion : 1.15.5 is no longer supported in westus2 regions due to which deployment is failing.
This template  **https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/deploy/azuredeploy.json** requires update

**To Reproduce**
Following deployment guideline at https://azure.github.io/application-gateway-kubernetes-ingress/setup/install-new/
az cli gives below error
`{'additional_properties': {}, 'code': 'InvalidTemplateDeployment', 'message': "The template deployment 'ingress-appgw' is not valid according tothe validation procedure. The tracking id is '8ff50afb-6d59-406f-a564-1ffc6177fee4'. See inner errors for details.", 'target': None, 'details': [<azure.mgmt.resource.resources.v2019_07_01.models._models_py3.ErrorResponse object at 0x7f8b90119e10>], 'additional_info': None}`

**Comment by ajomathew** [comment]
Result of az aks get-versions --location westus2

`{
  "id": "/subscriptions/f015d3ce-35b5-4ff2-87ec-0b9af0fd798a/providers/Microsoft.ContainerService/locations/westus2/orchestrators",
  "name": "default",
  "orchestrators": [
    {
      "default": null,
      "isPreview": null,
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.14.7",
      "upgrades": [
        {
          "isPreview": null,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.14.8"
        },
        {
          "isPreview": null,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.15.7"
        },
        {
          "isPreview": null,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.15.10"
        }
      ]
    },
    {
      "default": null,
      "isPreview": null,
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.14.8",
      "upgrades": [
        {
          "isPreview": null,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.15.7"
        },
        {
          "isPreview": null,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.15.10"
        }
      ]
    },
    {
      "default": null,
      "isPreview": null,
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.15.7",
      "upgrades": [
        {
          "isPreview": null,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.15.10"
        },
        {
          "isPreview": null,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.16.7"
        }
      ]
    },
    {
      "default": true,
      "isPreview": null,
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.15.10",
      "upgrades": [
        {
          "isPreview": null,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.16.7"
        }
      ]
    },
    {
      "default": null,
      "isPreview": null,
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.16.7",
      "upgrades": [
        {
          "isPreview": true,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.17.3"
        }
      ]
    },
    {
      "default": null,
      "isPreview": true,
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.17.3",
      "upgrades": null
    }
  ],
  "type": "Microsoft.ContainerService/locations/orchestrators"
}`

**Comment by ajomathew** [comment]
Accidentally closed the issue

**Comment by sebader** [comment]
I'd suggest to change the referenced ARM template to 15.7 for the time being until the updated version with support for >=1.16 is released

**Comment by akshaysngupta** [comment]
Issues related to 1.16 should be addressed in the next pre-release. https://github.com/Azure/application-gateway-kubernetes-ingress/issues/788#issuecomment-608869568

**Comment by akshaysngupta** [comment]
Closing in favour of #788
