### ISSUE TITLE
Add node selector to deployment

### ISSUE THREAD

**Issue by tonyschollum** [Azure/application-gateway-kubernetes-ingress#79]
**Is your feature request related to a problem? Please describe.**
When deploying to a hybrid cluster the deployment often tries to schedule pods on windows nodes

**Describe the solution you'd like**
Add a nodeselector to the deployments template and values

**Comment by asridharan** [comment]
@tonyschollum is the requirement for adding a nodeselector in the Helm chart template and exposing it as a Helm Variable?

**Comment by tonyschollum** [comment]
@asridharan in theory the node selector could be hard coded to linux

**Comment by techbunny** [comment]
The work around I used recently was to just taint my Windows nodes, but it would be great if this would just deploy on a linux node pool by default.
