### ISSUE TITLE
Authentication Issue - Using Service Principal

### ISSUE THREAD

**Issue by vishal8k** [Azure/application-gateway-kubernetes-ingress#791]
**Describe the bug**
I deployed AGIC in my cluster and it was working fine for quite a while. Suddenly the pod crashed and killing the pod was not helpful as the new pods also failed to start. On seeing the logs I could see there has been an authentication problem.  Below are the error logs:

```
Creating authorizer from file referenced by environment variable: /etc/Azure/Networking-AppGW/auth/armAuth.json
E0403 11:17:18.185561       1 auth.go:41] Unexpected ARM status code on GET existing App Gateway config: 401
E0403 11:17:18.185580       1 auth.go:49] Failed fetching config for App Gateway instance. Will retry in 10s. Error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/mysubscriptionid/resourceGroups/myrgname/providers/Microsoft.Network/applicationGateways/MYAPPGW?api-version=2019-09-01: StatusCode=401 -- Original Error: adal: Refresh request failed. Status Code = '401'. Responsebody: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: 9f364711-117b-4d45-af67-f4198fbb0c00\r\nCorrelationID: af17dd24-5ae4-416b-af2b-3bff7e7c1b76\r\nTimestamp: 2020-04-03 11:17:18Z","error_codes":[7000215],"timestamp":"2020-04-03 11:17:18Z","trace_id":"9f364711-117b-4d45-af67-f4198fbb0c00","correlation_id":"af17dd24-5ae4-416b-af2b-3bff7e7c1b76","error_uri":"https://login.microsoftonline.com/error?code=7000215"}
```
I deployed using the below command: 

`helm install appgateway -f app-gateway-helmvalues.yaml application-gateway-kubernetes-ingress/ingress-azure --set armAuth.type=servicePrincipal --set armAuth.secretJSON=$(az ad sp create-for-rbac --name $spname --role $rolename --scopes $spaccessscope --sdk-auth | base64 -w0) --namespace $namespace`

Rolename = contributor
Accesscope = over the entire subscription

**Ingress Controller details**
* Any Azure support tickets associated with this issue.
120040323001501

**NOTE: I checked the service principal secrets, they are not expired and is valid until next year**

**Comment by akshaysngupta** [comment]
@vishal8k can you make sure that output for `az ad sp create-for-rbac --name $spname --role $rolename --scopes $spaccessscope --sdk-auth | base64 -w0` is valid ?

**Comment by vishal8k** [comment]
@akshaysngupta Valid in the sense? IT has been working fine these many days and even worked right now. After reporting this issue I deleted the existing ingress and deployed a new one with the same command and it went well. No issue this time and it has been days.

**Comment by akshaysngupta** [comment]
@vishal8k I am suspecting if this could be an issue with mounting the secret.

**Comment by vishal8k** [comment]
@akshaysngupta So that means there is nothing wrong or troubleshooting from user's side right? Since mounting secrets all are done by the `helm install` command. I also have one more doubt. Now instead of using the command `az ad create-for-rbac` (which creates a new SP) Can I use the secret of an existing SP here? I will do it in the below way

`helm install appgateway -f app-gateway-helmvalues.yaml application-gateway-kubernetes-ingress/ingress-azure --set armAuth.type=servicePrincipal --set armAuth.secretJSON=$($mysecretvalue| base 64 -w0)`

Will this work?

**Comment by vishal8k** [comment]
@akshaysngupta Any updates on this issue? I just now encountered this issue yet again. Is AGIC even trustable for production?

**Comment by akshaysngupta** [comment]
@vishal8k From the error you mentioned, 
`
Refresh request failed. Status Code = '401'. Responsebody: {'error':'invalid_client','error_description':'AADSTS7000215: Invalid client secret is provided
`
Does this problem continue to happen ever after you restart the pod ?

This error is happening when the pod starts and tries to get the Application Gateway. It uses the credentials provided in the secretJSON.
This is place where the error message is coming from: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/73257c2983cebfcc2120f45ba9a7ffb6c0e83dc7/pkg/azure/client.go#L145

**Comment by vishal8k** [comment]
@akshaysngupta  Yes the problem continued even after I restarted the pod (Deleted the pod and a new one got deployed automatically). Hence I deleted the entire setup using helm delete and then re-provisioned. This time everything went well.

**Comment by akshaysngupta** [comment]
Ok. If this happens again, can you help validate the following:
1. The secret that is created as part of `helm install` is having a value for `armAuth.json`
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/73257c2983cebfcc2120f45ba9a7ffb6c0e83dc7/helm/ingress-azure/templates/secrets.yaml#L9
1. If you bash into the pod, do you see the armAuth.json and it has the expected base64 string.

**Comment by vishal8k** [comment]
@akshaysngupta  Okay I can check when it occurs next time but I can't afford this to happen in my production. If I use managed identity will be able to avoid this error? Also is AGIC trustable for production environments?

**Comment by vishal8k** [comment]
@akshaysngupta Below is the json of the secret for ingress that is currently running and working perfectly. I don't see the field you have mentioned above but the ingress is working.

```
{
  "kind": "Secret",
  "apiVersion": "v1",
  "metadata": {
    "name": "appgateway-sa-ingress-azure-token-7phvw",
    "namespace": "assembly-prod",
    "selfLink": "/api/v1/namespaces/mynamespace/secrets/appgateway-sa-ingress-azure-token-7phvw",
    "uid": "e67eb1c6-8888-4871-b09e-6d2bdf4124fe",
    "resourceVersion": "171003",
    "creationTimestamp": "2020-04-29T14:06:01Z",
    "annotations": {
      "kubernetes.io/service-account.name": "appgateway-sa-ingress-azure",
      "kubernetes.io/service-account.uid": "75007194-360f-4085-af36-d2ad7e5a9ebe"
    }
  },
  "data": {
    "ca.crt": "LS0t.....................................................................................................................................................................................................................................................................SUZJQ0FURS0tLS0tCg==",
    "namespace": "YX..............A==",
    "token": "ZXlKaGJHn..............................................................................................................................................................................................................................................................................GMA=="
  },
  "type": "kubernetes.io/service-account-token"
}
```

**Comment by akshaysngupta** [comment]
Yes, it is trustable in production. This is the first time I am seeing this issue. I would need your help to diagnose the problem.

The name of the secret in the file linked above is `networking-appgw-k8s-azure-service-principal`. This secret will be present in the same namespace where you deployed AGIC.
Also, if you see that the secret looks correct. Can you jump into the pod and check at the location `/etc/Azure/Networking-AppGW/auth` and see if the file has the needed content.

The above is just a step in diagnosing the problem. We might have to dig further. Thanks!

**Comment by vishal8k** [comment]
@akshaysngupta In the current ingress that is working fine, both the secret and the armAuth.json inside the pod looks good. I'll paste the contents below. Since I don't know why the error occurs I'm unable to reproduce it and check.

```
{
  "clientId": "XXXX",
  "clientSecret": "XXX",
  "subscriptionId": "XXXX",
  "tenantId": "XXXX",
  "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
  "resourceManagerEndpointUrl": "https://management.azure.com/",
  "activeDirectoryGraphResourceId": "https://graph.windows.net/",
  "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
  "galleryEndpointUrl": "https://gallery.azure.com/",
  "managementEndpointUrl": "https://management.core.windows.net/"
} 
```

**Comment by akshaysngupta** [comment]
@vishal8k Please reopen this issue if you encounter this problem again.

**Comment by vishal8k** [comment]
@akshaysngupta  Yes I have encountered this same problem multiple times after this. I'll give you one heads up. Is there any possibility for this issue to be related to start/stop of the underlying scalesets of the AKS or the stop/start of the application gateway used for the ingress?

**Comment by akshaysngupta** [comment]
@vishal8k When you use `az ad app show -o yaml --query "passwordCredentials" --id <spClientID>`, what do you see as startDate and endDate ?

**Comment by akshaysngupta** [comment]
@vishal8k I don't think this is related to underlying scale set or application gateway.
AGIC pod is trying to communicate to Azure Active Directory directly. Error has to do something with the identity credentials used while communicating to AAD.

**Comment by vishal8k** [comment]
@akshaysngupta Consider this high priority cause now I'm seeing this issue daily once with different AKS and application gateways. It is occurring so frequently now,

**Comment by akshaysngupta** [comment]
@vishal8k I am trying to repro this on my AKS cluster. I have deployed AGIC in my AKS cluster with service principal. Plan is to observe the cluster for some time along with performing some routine re-deployments to see if I can get 401 from AAD.

Here are logs so far:
```
$> k logs ingress-azure-7d97898549-dctq6
ERROR: logging before flag.Parse: I0528 04:02:28.806722       1 utils.go:111] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0528 04:02:28.843250       1 environment.go:230] KUBERNETES_WATCHNAMESPACE is not set. Watching all available namespaces.
I0528 04:02:28.843357       1 main.go:125] App Gateway Details: Subscription: xxxx, Resource Group: sp-test, Name: applicationgateway9f3c
I0528 04:02:28.843370       1 auth.go:37] Creating authorizer from file referenced by environment variable: /etc/Azure/Networking-AppGW/auth/armAuth.json
I0528 04:02:28.843882       1 httpserver.go:57] Starting API Server on :8123
I0528 04:02:29.292195       1 main.go:168] Ingress Controller will observe all namespaces.
I0528 04:02:29.436105       1 context.go:132] k8s context run started
I0528 04:02:29.436154       1 context.go:176] Waiting for initial cache sync
I0528 04:02:29.536449       1 context.go:189] Initial cache sync done
I0528 04:02:29.536484       1 context.go:190] k8s context run finished
I0528 04:02:29.536665       1 worker.go:39] Worker started
I0528 04:02:29.693567       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0528 04:02:50.505853       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0528 04:02:50.505880       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0528 04:02:50.506521       1 mutate_app_gateway.go:204] END AppGateway deployment
I0528 04:02:50.506541       1 controller.go:151] Completed last event loop run in: 20.969838752s
```

I have deployed a [sample](https://raw.githubusercontent.com/Azure/application-gateway-kubernetes-ingress/master/docs/examples/aspnetapp.yaml) application on the cluster.

The secret is valid until 2021-05-20.
```
$> az ad app show --id xxxx -o yaml --query "passwordCredentials"
- additionalProperties: null
  customKeyIdentifier: rbac
  endDate: '2021-05-20T07:06:15.818831+00:00'
  keyId: xxxx
  startDate: '2020-05-20T07:06:15.818831+00:00'
  value: nul
```

**Comment by vishal8k** [comment]
Try to stop and start the underlying scale-sets and application gateways periodically, since that is the only unusual practice that I'm doing. I don't think anyone else stops the underlying scale-sets. (I'm stopping them for cost reasons.) Meanwhile, I will post here If I see the error again.

**Comment by akshaysngupta** [comment]
@vishal8k are you turning off all VMs manually? Or scaling them down through AKS agent pool settings ?

**Comment by vishal8k** [comment]
@akshaysngupta  Turning them off via an automated script during off-buisness hours. The script will directly de-allocate all the scalesets present in the account. Not via AKS agent pool settings.

**Comment by akshaysngupta** [comment]
@vishal8k I tried the above exercise again but I haven't been able to reproduce the issue. After doing above, the AGIC pod comes back online successfully and is able to handle ingress related events and update Application Gateway.

**Comment by vishal8k** [comment]
@akshaysngupta Well then maybe it is caused by something else I guess. but even for me it did not occur every time when I restarted the nodes/application-gateway. It occurred randomly. Anyway lets not waste time by simply doing the same thing. I guess the issue is caused by something else then. I've not had this issue for the past 3 to 4 days now. (My nodes and application gateway were restarted multiple time during this period)

**Comment by akshaysngupta** [comment]
@vishal8k Then I will close the issue for now. Please let me know if you discover something.
