### ISSUE TITLE
Probes are not configured using the healthcheck settings

### ISSUE THREAD

**Issue by Baklap4** [Azure/application-gateway-kubernetes-ingress#796]
**Describe the bug**

We use healthchecks to check if an application is ready and live.
For a specific component we've set the delay to 750 seconds
```
 Liveness:   http-get http://:8080/auth/realms/datahub/.well-known/openid-configuration delay=750s timeout=15s period=10s #success=1 #failure=3
    Readiness:  http-get http://:8080/auth/realms/datahub/.well-known/openid-configuration delay=750s timeout=10s period=10s #success=1 #failure=3
```

However once we check the settings applied in application gateway the below settings apply.
This could lead to potentional 'bad gateways' since the pod within the backend pool doesn't have the status 'ready' since it'll be probed after 750 by kubernetes itself.

![image](https://user-images.githubusercontent.com/3918517/78575624-e5a5da00-782b-11ea-8738-c7e772382e1c.png)

**To Reproduce**
use a liveness / readiness check and set a high value for the initial delay. Then discover that application gateway already sends traffic to the pod while the initial delay is not done yet.

Using the application gateway 1.0.0 and kubernetes v 1.14.6

**Comment by akshaysngupta** [comment]
@Baklap4 App Gateway doesn't support setting an initial delay in the health check right now. You may try making the health check more aggressive by adjusting the interval(period).
