### ISSUE TITLE
Release Helm Chart

### ISSUE THREAD

**Issue by quantumew** [Azure/application-gateway-kubernetes-ingress#798]
I am running into #116 which appears to be fixed on master but was never released to the helm repo outlined in the instructions. Can we get a new release cut for this helm chart?

**Comment by akshaysngupta** [comment]
@quantumew This is an issue with your cluster not having `AAD Pod Identity` installed.
To install AAD Pod Identity to your cluster:

   - *RBAC enabled* AKS cluster

  ```bash
  kubectl create -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml
  ```

   - *RBAC disabled* AKS cluster

  ```bash
  kubectl create -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment.yaml
  ```

**Comment by quantumew** [comment]
Nice, I was able to install that release candidate. `helm search` was only showing helm chart version 1.0.0, which is missing this change https://github.com/Azure/application-gateway-kubernetes-ingress/issues/116#issuecomment-591103138, which was causing it to fail for me. Thanks!

**Comment by nandha2143** [comment]
@quantumew I am not familiar with helm. Can you include the steps to run the helm install from release candidate 1.2.0 application-gateway-kubernetes-ingress?
