### ISSUE TITLE
Error Applying ARM Template

### ISSUE THREAD

**Issue by ElderMael** [Azure/application-gateway-kubernetes-ingress#802]
**Describe the bug**
While deploying the ARM template, an error appears. Deleted the Resource Group and tried multiple times with the same created Service Principal for RBAC to no use.

This is the error logs:
```

##[error]At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.
##[error]Details:
##[error]Conflict: {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
          {
            "code": "BadRequest",
            "message": "{\r\n  \"error\": {\r\n    \"code\": \"RoleAssignmentUpdateNotPermitted\",\r\n    \"message\": \"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\"\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}
```
**To Reproduce**
Apply the arm template.

**Ingress Controller details**
N/A
* Output of `kubectl logs <ingress controller>. 
N/A

**Comment by akshaysngupta** [comment]
@ElderMael `RoleAssignmentUpdateNotPermitted` means that the role assignment exists already. Which step in the template is failing here ?

**Comment by martin77s** [comment]
I have the same issue. The status is "Conflict" and it fails for both RoleAssignmentDeploymentForUserAssignedIdentity and RoleAssignmentDeploymentForKubenetesSp

**Comment by grlima** [comment]
Any updates on this issue? I'm having the same problem. It seems the ARM operation to create a role assignment is not idempotent.

**Comment by jafreitas90** [comment]
I have the same issue
