### ISSUE TITLE
Pre-Release Helm Repo

### ISSUE THREAD

**Issue by geoarchitect** [Azure/application-gateway-kubernetes-ingress#811]
Is there a helm repo with the pre-release versions deployed? 

We can see that a number of fixes have been pushed in the release candidate builds but don't see them in the main repo. 

Can we have instructions to install them?

**Comment by akshaysngupta** [comment]
@geoarchitect With the exception of `1.0.1-rc3`, you should be able to find all the release candidates in the main helm repo.
Release `1.2.0-rc1` should have all the code related changes that we have made so far!

**Comment by geoarchitect** [comment]
Thanks @akshaysngupta 

We got 1.2.0-rc1 deployed yesterday and its working well. 

For others and future reference, we couldn't see the release due to missing the -devel flag when searching the repo's. 

Searching Example 

```
helm search repo ingress-azure --versions --devel
```

Deploymnt

```
helm install ingress-azure -f helm-config.yaml application-gateway-kubernetes-ingress/ingress-azure --version 1.2.0-rc1
```

Also there is a staging repo but its not needed now: application-gateway-kubernetes-ingress-staging

Thanks for the help!
