### ISSUE TITLE
helm installed failed for appgw-ingress-azure azure aks 1.16.7

### ISSUE THREAD

**Issue by nandha2143** [Azure/application-gateway-kubernetes-ingress#813]
**Describe the bug**

helm upgrade --install appgw-ingress-azure -f helm-config.yaml application-gateway-kubernetes-ingress/ingress-azure
Release "appgw-ingress-azure" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"

**To Reproduce**
run above mentioned command with aks version 1.16.7 (HELM 3)

helm search repo "ingress"
NAME                                                    CHART VERSION   APP VERSION     DESCRIPTION
application-gateway-kubernetes-ingress/ingress-...      1.0.0           1.0.0           Use Azure Application Gateway as the ingress fo...

**Ingress Controller details**
There are many issues reported. But no clear instruction to fix this issue

**Comment by akshaysngupta** [comment]
@nandha2143 This has been addressed in version `1.2.0-rc1`.
You can try that by using helm install with `--version 1.2.0-rc1`.
