### ISSUE TITLE
Helm install - decouple appgw.shared Deployment/CRD config from deploying default AzureIngressProhibitedTarget

### ISSUE THREAD

**Issue by tkubica12** [Azure/application-gateway-kubernetes-ingress#815]
**Is your feature request related to a problem? Please describe.**
During IaaC deployment with shared App Gw 3 things happen:
- CRD AzureIngressProhibitedTarget is deployed
- ENV flag is set on Deployment
- Default deny all AzureIngressProhibitedTarget is configured

This makes declarative deployment of cluster scale more complex as deleting objects is imperative and need to modify Helm charts is not convenient.

Would it be possible to set Chart in a way that this default deny all rule is not deployed so I can setup proper exceptions with different decalarative deployment without need to delete something imperatively?

**Describe the solution you'd like**
appgw.share flag would deploy CRD definition and ENV flag in Deployment
appgw.share-denyall whould be true by default and would deploy deny-all AzureIngressProhibitedTarget when appgw.share is set 

With this administrator can disable creation of deny-all rule and use declarative way to setup cluster state.

What do you think? Make sense?

Thanks, 

Tomas

**Comment by LoicAG** [comment]
If anyone else needs this, be sure to take a look #917 , which allows to set this in `values.yaml` :

```appgw:
  shared: true
  prohibitedTargets:
  - name: protect-myotherapp
    paths:
    - /myotherapp/*
  - name: protect-contoso-prod
    hostname: prod.contoso.com```
