### ISSUE TITLE
Pod fails to start - unable to mount volume

### ISSUE THREAD

**Issue by timcrall** [Azure/application-gateway-kubernetes-ingress#819]
**Describe the bug**
As far as I can tell, I followed all the steps in the brownfield guide exactly.  When I run the helm chart, the pod gets stuck in ContainerCreating, complaining that a volume could not be mounted.  What is it trying to mount, exactly, and what could be causing this error?

**Ingress Controller details**

Name:           ingresss-azure-ingress-azure-678dd4447b-xtt9g
Namespace:      default
Priority:       0
Node:           akswin000001/170.2.153.194
Start Time:     Thu, 23 Apr 2020 18:36:06 +0000
Labels:         aadpodidbinding=ingresss-azure-ingress-azure
                app=ingress-azure
                pod-template-hash=678dd4447b
                release=ingresss-azure
Annotations:    prometheus.io/port: 8123
                prometheus.io/scrape: true
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/ingresss-azure-ingress-azure-678dd4447b
Containers:
  ingress-azure:
    Container ID:
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.0.0
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      ingresss-azure-cm-ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_CONTEXT_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:           ingresss-azure-ingress-azure-678dd4447b-xtt9g (v1:metadata.name)
      AGIC_POD_NAMESPACE:      default (v1:metadata.namespace)
    Mounts:
      /etc/appgw/azure.json from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ingresss-azure-sa-ingress-azure-token-558mm (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  ingresss-azure-sa-ingress-azure-token-558mm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingresss-azure-sa-ingress-azure-token-558mm
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age                      From                   Message
  ----     ------       ----                     ----                   -------
  Warning  FailedMount  8m15s (x114 over 3h43m)  kubelet, akswin000001  MountVolume.SetUp failed for volume "azure" : hostPath type check failed: /etc/kube rnetes/azure.json is not a file
  Warning  FailedMount  2m22s (x98 over 3h41m)   kubelet, akswin000001  Unable to mount volumes for pod "ingresss-azure-ingress-azure-678dd4447b-xtt9g_defa ult(4afd046b-8591-11ea-8cdb-aa7c0db8dc3e)": timeout expired waiting for volumes to attach or mount for pod "default"/"ingresss-azure-ingress-azure-678dd444 7b-xtt9g". list of unmounted volumes=[azure]. list of unattached volumes=[azure ingresss-azure-sa-ingress-azure-token-558mm]

**Comment by 3quanfeng** [comment]
Hi @timcrall, you have a extra space in your pod spec:
volumes.hostPath.path: "/etc/kube rnetes/azure.json"

**Comment by timcrall** [comment]
Nice catch!  Okay, I can manually change that, I guess - but since I'm using helm - that error doesn't appear to be in any file I've created, right?  I don't see it anywhere in the config yaml file that I'm feeding into the helm command, which is the only file I've touched - is this a typo somewhere in the code?

**Comment by akshaysngupta** [comment]
I think this is just pasting/rendering issue.

@timcrall is this happening on an AKS cluster ?

**Comment by timcrall** [comment]
yes

**Comment by timcrall** [comment]
Yeah, the hostpath in the pod's yaml looks correct, I think @akshaysngupta was correct about it being a pasting error

**Comment by timcrall** [comment]
oo, I have a thought, am going to try something

**Comment by akshaysngupta** [comment]
@timcrall yes, was about to point that the node is Windows.
`Node: akswin000001/170.2.153.194`

**Comment by vjavle** [comment]
Facing the same issue. Which yaml file did you change?
