### ISSUE TITLE
Question AGW should be in same VNET as AKS ?

### ISSUE THREAD

**Issue by niteenkole** [Azure/application-gateway-kubernetes-ingress#827]
**Describe the bug**
Question AGW should be in same VNET as AKS ?

**To Reproduce**
We in situation like we have subscription where we will have AKS dev and running in separate vnet.

We cannot have AGW in same subscription as we want this AGW to be behind our firewall which is in separate subscription.

We have peered APGW vnet and aks vnet.

Question is such setup supported ,can AGW be in separate vnet and AKS in separate vnet ?

**Comment by niteenkole** [comment]
raised this because

https://azure.github.io/application-gateway-kubernetes-ingress/troubleshooting/

Get the list of pods with Cloud Shell: kubectl get pods -o wide. We expect for a pod named 'test-agic-app-pod' to have been created. It will have an IP address. **This address must be within the VNET of the App Gateway**, which is used with AKS.

**Comment by akshaysngupta** [comment]
@niteenkole You can have Application Gateway and AKS in separate VNETs.
The two VNETs must be peered for traffic to flow from App Gateway to VNET. Also, if you are using AKS with Kubenet CNI (basic networking), then please associate the route table of the AKS node found in the AKS node resource group (the one that starts with MC_ and is created automatically in the subscription) to the Application Gateway subnet.

I will try to add a documentation around using a different VNET.

**Comment by niteenkole** [comment]
Awesome thank you,We using Azure CNI.

**Comment by niteenkole** [comment]
Hi Akshay,

Subscription “Kubernetes Dev” is where we have AKS living.  It is peered to the Transit VNet in the middle and the Ingress controller (AppGW). We have AKS successfully controlling the App GW when it spins up/down a service(s), but it seems that the traffic for the health probes from the AppGW is not getting correctly returned to the AppGW, therefore the service never becomes “Healthy” on the AppGW.  We see the traffic coming from the AppGW on FW and it is allowed. We see it get dropped back into the VNet and over the peer but then it never comes back.Opened to any ideas or suggestions

**Comment by niteenkole** [comment]
I think it works for us.Only now we struggling to make ssl end to end setup work :). It was our NSG.we had subnet and looks like it doesn't like when we add destination VirtualNetwork looks good.

**Comment by mhsh64** [comment]
Please can you refer to any documents required for configuring AKS and APG in different vNETs.

**Comment by niteenkole** [comment]
@mhsh64  when you say backend unhealthy http or https ?

Confirm your backend are working like example. From inside cluster those backend are reachable ?
example: we test using alpine image then exec to it and tested.

Also if you can fire ubuntu or windows in same vnet as your cluster to make sure your backend are working.

**Comment by mhsh64** [comment]
Hi
Backend is reachable and healthy now from APG perspective.
Now the issue is, if the ApG vNet peered with an ER vNet, and if as per MSFT support, we may need to disable propagation on UDR, how the traffic from on-prem will reach to ApG?
Have you ever configured ApG on a Vnet peered with ER vNet?

**Comment by mcarlsen** [comment]
We have a similar situation, and would like some documentation on how to achieve this before we make the attempt.

FYI, I had a chat with Azure support about this. They seemed to believe some manual configuration was necessary: 

> I checked with the SME, and it is not supported with AKS Ingress Controller, they need to be in the same vnet as per the documentation. 
> In theory, if they were separate, and the VNETs were peered, we believe you can manually add the backend as IP addresses. however, we cannot guarantee it will work as it is not documented.

**Comment by akshaysngupta** [comment]
Added documentation about using AKS and Gateway with various networking options.
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/how-tos/networking.md

Suggestions and improvements are welcome!

**Comment by MarekLani** [comment]
@akshaysngupta please, is this doable: Kubenet + Different VNETs + **Different Subscriptions** for GW and AKS

**Comment by MarekLani** [comment]
I made some more research and based on what is stated in the documentation of [Route Tables](https://docs.microsoft.com/en-us/azure/virtual-network/manage-route-table#associate-a-route-table-to-a-subnet), my over stated scenario is not achievable as "_You can only associate a route table to subnets in virtual networks that exist in the same Azure location and **subscription** as the route table._"
