### ISSUE TITLE
Multiple application Gateways in one k8s cluster

### ISSUE THREAD

**Issue by arunssasidhar** [Azure/application-gateway-kubernetes-ingress#831]
**Describe the bug**
In our non-prod environment, we have one AKS cluster with multiple namespaces for each non-prod environment like DEV, INT, TEST. ACC etc. We would like to deploy a dedicated "application gateway Ingress" per namespace. That means, DEV has one dedicated application Gateways as ingress, INT has another, and so on.

I have used this guide to deploy the Ingress - https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-install-new

The installation worked as expected in the first environment DEV. When I try to deploy the Ingress in the Second environment (INT), I get following error -

`rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: , name: application-gateway-kubernetes-ingress-ingress-azure, existing_kind: rbac.authorization.k8s.io/v1beta1, Kind=ClusterRole, new_kind: rbac.authorization.k8s.io/v1beta1, Kind=ClusterRole`

**To Reproduce**
- Create a AKS cluster
- Create 2 namespaces in it
- Create 2 Application gateways (one for each namespace)
- Deploy "application-gateway-kubernetes-ingress" in the first namespace with one app gw
- Deploy "application-gateway-kubernetes-ingress" in the second namespace with second app gw

**Ingress Controller details**
**application-gateway-kubernetes-ingress version** : 0.10.0 (because I am using "Standard v1 app GW)
**Deployment Method** : Helm
**My config values are given below**
`verbosityLevel: 3
appgw:
    subscriptionId: ${var.subscription_id}
    resourceGroup: ${var.resource_group_name}
    name: ${var.app_gateway_name}
    shared: false
    usePrivateIP: true
armAuth:
    type: aadPodIdentity
    identityResourceID: ${var.azurerm_user_assigned_identity_id}
    identityClientID:  ${var.azurerm_user_assigned_identity_client_id}
rbac:
    enabled: true
aksClusterConfiguration:
    apiServerAddress: ${var.k8s_host}
kubernetes:
    watchNamespace: ${var.k8s_namespace}`

I have created a diagram for my requirement. See

![image](https://user-images.githubusercontent.com/4438811/80631869-07356280-8a74-11ea-8904-cccf051f1907.png)

Running dedicated App GW's per namespaces is supported?

**Comment by BarnumD** [comment]
I was just wondering the same thing.  I'm not sure if I want a single application gateway for my entire a aks cluster.  At least, the way I'm reading it is that the agic can only take a single app gateway as an argument.  So it's a one to one mapping.

So if I have multiple applications in my cluster and I want them each to have separate application gateways, (Perhaps I want them separate for configuration reasons such as WAF rules or just separation of concerns.) how would I go about doing that?

Can I create multiple app-gateway-kub-ingress controllers that each attach to a different app gateway?  

It seems like it might be allowed based on this [page](https://docs.microsoft.com/bs-latn-ba/azure/application-gateway/ingress-controller-multiple-namespace-support), but it's not clearly spelled out.  It does say that caution would be needed to make sure multiple ingresses are not watching the same namespaces.

**Comment by 3quanfeng** [comment]
Hi @arunssasidhar , do you happen to use same [NAME] to install both, i.e. helm install [NAME] ...?

**Comment by arunssasidhar** [comment]
I am using Terraform for installing this using Helm. Here is the detailed installation steps.

**Step 1** -  Install AAD Pod Identity on the default namespace (**_one time in a cluster_**)
`kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml`

**Step 2** -  Install "application gateway Kubernetes ingress" **_per namespace in the cluster_**. For the first namespace, it works without any issues.  When I try to install in the second namespace it throws the reported error.
..........................Terraform Config..............................................
resource "helm_release" "agw_ingress_multiple" {
  name            = "application-gateway-kubernetes-ingress"
  repository    = data.helm_repository.helm_appgw.name
  chart            = "ingress-azure"
  version         =  "0.10.0"
  namespace  = var.k8s_namespace

 values = [
    <<EOF
verbosityLevel: 3
appgw:
    subscriptionId: ${var.subscription_id}
    resourceGroup: ${var.resource_group_name}
    name: ${var.app_gateway_name}
    shared: false
    usePrivateIP: false
armAuth:
    type: aadPodIdentity
    identityResourceID: ${var.azurerm_user_assigned_identity_id}
    identityClientID:  ${var.azurerm_user_assigned_identity_client_id}
rbac:
    enabled: true
aksClusterConfiguration:
    apiServerAddress: ${var.k8s_host}
kubernetes:
    watchNamespace: ${var.k8s_namespace}
EOF
  ]
}
..........................Terraform Config..............................................

**Comment by arunssasidhar** [comment]
AWS alb ingress controller have the opposite problem. https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/329
It creates dedicated ALB for each Ingress, that is I need in my case :)

I have created a diagram for my requirement. I hope it will make easy to understand my requirement.
![image](https://user-images.githubusercontent.com/4438811/80631869-07356280-8a74-11ea-8904-cccf051f1907.png)

**Comment by 3quanfeng** [comment]
Hi @arunssasidhar , can you try with different name other than "name = "application-gateway-kubernetes-ingress"" for your second install? or you could also include the namespace in your naming to make it unique

**Comment by arunssasidhar** [comment]
Thank you @3quanfeng changing the name fixed the issue!

Now I have another issue :(

I am using Application GW "Standard v1" without public IP. And I set "usePrivateIP: true" in the config. But when I look at the pod log, I get the error "**A Public IP must be present in the Application Gateway FrontendIPConfiguration (APPG012)**"

See the full log below

`$ kubectl --namespace nonprod-int logs -f application-gateway-kubernetes-ingress-d69439e8-ingress-az2glxc
ERROR: logging before flag.Parse: I0430 07:58:47.601996       1 main.go:286] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I****30 07:58:47.638812       1 main.go:126] App Gateway Details: Subscription: fa8-a-***-***-cac1892d0083, Resource Group: rg.kked.nonprod, Name: appgw-ingress-nonprod-int-app-gw
I0430 07:58:47.638835       1 auth.go:90] Creating authorizer from Azure Managed Service Identity
I0430 07:58:47.839326       1 main.go:175] Ingress Controller will observe the following namespaces:nonprod-int
F0430 07:58:47.926009       1 main.go:181] Got a fatal validation error on existing Application Gateway config. Please update Application Gateway or the controller's helm config. Error:A Public IP must be present in the Application Gateway FrontendIPConfiguration (APPG012)`

I am using AGIC version "0.10.0"

**Comment by 3quanfeng** [comment]
Hi @arunssasidhar , [0.9.0](https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/0.9.0) is the last release version we support v1.
May I ask is there any specific reason for you to stick to V1?

**Comment by arunssasidhar** [comment]
Hi @3quanfeng,

I choose app gw v1 is mainly due to cost. We are setting up this ingress for our development environments so we don't need any HA. 
But I understand the limited support of v1 app gw, we decided to use app gw v2.

I deployed V2 app gateways in our non-prod AKS and it is working as expected.

Thanks for your support
Arun Sasidharan

**Comment by Rashee04** [comment]
it is possible to attach two application gateway with 2 AGIC to one aks that has only one namespace?
