### ISSUE TITLE
Following greenfield tutorial - ingress-azure pod in CrashLoopBackOff

### ISSUE THREAD

**Issue by howardjones** [Azure/application-gateway-kubernetes-ingress#838]
I'm following the greenfield tutorial: https://azure.github.io/application-gateway-kubernetes-ingress/tutorial/

All components are deployed: kubernetes-ingress:1.0.0, mic:1.6.0, nmi:1.6.0
plus the aspnetapp, all from helm or supplied manifests.

No configuration ever occurs at the app gateway. The ingress-azure pod is in CrashLoopBackOff state.

```
  Normal   Started    33m (x2 over 34m)     kubelet, aks-agentpool-35064155-0  Started container ingress-azure
  Warning  Unhealthy  32m (x5 over 34m)     kubelet, aks-agentpool-35064155-0  Liveness probe failed: Get http://10.0.0.7:8123/health/alive: dial tcp 10.0.0.7:8123: connect: connection refused
  Warning  Unhealthy  9m31s (x64 over 34m)  kubelet, aks-agentpool-35064155-0  Readiness probe failed: Get http://10.0.0.7:8123/health/ready: dial tcp 10.0.0.7:8123: connect: connection refused
  Warning  BackOff    4m23s (x88 over 28m)  kubelet, aks-agentpool-35064155-0  Back-off restarting failed container
```

The logs for the pod itself show an error about flag parsing, but nothing at the end:
```
ERROR: logging before flag.Parse: I0504 12:55:20.229628       1 main.go:302] Using verbosity level 5 from environment variable APPGW_VERBOSITY_LEVEL
I0504 12:55:20.272159       1 environment.go:168] KUBERNETES_WATCHNAMESPACE is not set. Watching all available namespaces.
I0504 12:55:20.272183       1 main.go:132] App Gateway Details: Subscription: 6b179e9f-7603-45fa-a369-83e24c8dccb9, Resource Group: hj-test-ag, Name: applicationgateway78e6
I0504 12:55:20.272191       1 auth.go:90] Creating authorizer from Azure Managed Service Identity
```

One of the MIC pods has lots of this in the logs:

    E0504 12:45:40.593297       1 mic.go:899] Ignoring azure identity default/ingress-azure, error: Invalid resource id: "", must match /subscriptions/<subid>/resourcegroups/<resourcegroup>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<name>

But `kubectl describe azureidentities.aadpodidentity.k8s.io ingress-azure` shows a Resource Id in that format for my identityClientId.

I can see my service and ingress in kubectl. No IP in the ingress though (presumably because nothing has been configured on the gateway)

How can I troubleshoot further?

**Comment by mscatyao** [comment]
We've fixed this issue but it's pending the next rc2 release. In the meantime, please use AAD pod identity version 1.5.5 as per our greenfield deployment instructions: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/setup/install-new.md#install-aad-pod-identity
