### ISSUE TITLE
AGIC with Neuvector

### ISSUE THREAD

**Issue by niteenkole** [Azure/application-gateway-kubernetes-ingress#843]
**Describe the bug**
We not able to make AGIC expose Neuvector portal or API. SSL end to end.Not sure what we doing wrong.

**To Reproduce**
Steps to reproduce the behaviour:

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: neuvector-ingress-portal-webui
  namespace: neuvector
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-protocol: "https"
    appgw.ingress.kubernetes.io/backend-hostname: "nv-xxxxxx.ca"
    appgw.ingress.kubernetes.io/appgw-trusted-root-certificate: "nv-xxxxxx-ca-root-cert1"

spec:
  tls:
  - hosts:
    - nv-xxxxxx.ca
    secretName: neuvector-ingress-portal-tls
  rules:
  - host: nv-xxxxx.ca
    http:
      paths:
      - path:
        backend:
          serviceName: neuvector-cluster-portal-webui
          servicePort: 443

Neuvector pod we see

2020-05-08 23:09:26,301|ERROR|MANAGER|spray.can.server.HttpServerConnection(apply$mcV$sp:65): Aborting encrypted connection to /192.xxx.xxx.xx:49604 due to [SSLHandshakeException:Invalid Padding length: 90] -> [BadPaddingException:Invalid Padding length: 90]
2020-05-08 23:09:53,415|ERROR|MANAGER|spray.can.server.HttpServerConnection(apply$mcV$sp:65): Aborting encrypted connection to /192.xxx.xxx.xx:44186 due to [SSLHandshakeException:Invalid Padding length: 86] -> [BadPaddingException:Invalid Padding length: 86]
2020-05-08 23:09:56,303|ERROR|MANAGER|spray.can.server.HttpServerConnection(apply$mcV$sp:65): Aborting encrypted connection to /192.168.xxx.xxx.xx:49764 due to [SSLHandshakeException:Invalid Padding length: 176] -> [BadPaddingException:Invalid Padding length: 176]

backend health
172.16.xxx.xxx (pool-neuvector-neuvector-cluster-portal-webui-443-bp-8443)

Cannot connect to server. Check whether any NSG/UDR/Firewall is blocking access to server

pod listening to correct port.
/ # telnet 172.16.xxx.xxx 8443
Connected to 172.16.xxx.xxx

![agic-neuvector](https://user-images.githubusercontent.com/44979343/81456802-c9b29280-9161-11ea-8f89-890a5d209851.png)

**Comment by 3quanfeng** [comment]
Hi @niteenkole , was anything going wrong with your AGIC pod? could you please help send the logs(verbosity 5 helps better)? Thanks!

**Comment by niteenkole** [comment]
[agic-log.txt](https://github.com/Azure/application-gateway-kubernetes-ingress/files/4604318/agic-log.txt)

any easy way to switch log level from 3 to 5 ?

**Comment by niteenkole** [comment]
[Health probe shows we good.docx](https://github.com/Azure/application-gateway-kubernetes-ingress/files/4604899/Health.probe.shows.we.good.docx)

I think I had some key and cert mismatch,recreated and now we see.
The root certificate of the server certificate used by the backend does not match

1.Under health prove shows we good.
2.Under backend health shows "root certificate of the server certificate used by the backend does not match"

**Comment by akshaysngupta** [comment]
@niteenkole Can you make sure that hostname used by app gateway matches the subject of the certificate ?

You can use the `backend-hostname` annotation to match the subject name of the certificate. This is needed for the ssl handshake to succeed.
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/annotations.md#backend-hostname

**Comment by niteenkole** [comment]
Yes We do have backend-hostname exactly same as CN= in certificate

**Comment by akshaysngupta** [comment]
@niteenkole is your setup working now ?

**Comment by niteenkole** [comment]
No w.r.t Neuvector.

Looks like back-end application not sending back intermediate and root even when we add all chain of certificates,Working with Neuvector to see why.

Attach test.

[ssl-cert-test.txt](https://github.com/Azure/application-gateway-kubernetes-ingress/files/4657619/ssl-cert-test.txt)

and for other test application basically we get end to end ssl but looks like cookie effinity issue or like that.

https://redmine.postgresql.org/issues/5513
https://redmine.postgresql.org/issues/5512

**Comment by niteenkole** [comment]
Hi,

Neuvector confirmed passing full chain of certificates presently not supported and they working on it.

I will update once they support.

**Comment by akshaysngupta** [comment]
@niteenkole if this is an issue on the Neuvector backend pods, then we will go ahead with closing the issue on the AGIC repo. Please reopen if you need help.
