### ISSUE TITLE
AKS v1.16.7 no matches for kind "Deployment" in version "apps/v1beta2"

### ISSUE THREAD

**Issue by niteenkole** [Azure/application-gateway-kubernetes-ingress#845]
**Describe the bug**
Helm install on AKS 1.16.7 says

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"

**To Reproduce**
 helm install xxxxxp01-ingress-controller -f helm-config-sp-05.yaml application-gateway-kubernetes-ingress/ingress-azure
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"e2d9f8479783020904aba3de7499a49be6c75ebd", GitTreeState:"clean", BuildDate:"2020-04-09T02:31:15Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
* Output of `kubectl logs <ingress controller>. 
* Any Azure support tickets associated with this issue.

**Comment by niteenkole** [comment]
Works fine on v1.15.10

helm install cglaksnp01-ingress-controller -f helm-config-sp-05.yaml application-gateway-kubernetes-ingress/ingress-azure
NAME: cglaksnp01-ingress-controller
LAST DEPLOYED: Sun May 10 16:12:08 2020
NAMESPACE: default

 kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"059c666b8d0cce7219d2958e6ecc3198072de9bc", GitTreeState:"clean", BuildDate:"2020-04-03T15:17:29Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by akshaysngupta** [comment]
@niteenkole Please try version 1.2.0-rc1 which has the fix for this.
https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/1.2.0-rc1

k8s 1.16 has deprecated deployment/v1beta2.

**Comment by niteenkole** [comment]
Looks like I landed up in know issue.
 helm upgrade cglaksnp01-ingress-controller application-gateway-kubernetes-ingress/ingress-azure --version 1.2.0-rc1
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: default, name: cglaksnp01-ingress-controller-ingress-azure, existing_kind: apps/v1, Kind=Deployment, new_kind: apps/v1, Kind=Deployment

**Comment by niteenkole** [comment]
I have uninstall and reinstall again :(.

**Comment by akshaysngupta** [comment]
@niteenkole yes, This is an open issue in helm: https://github.com/helm/helm/issues/7219
