### ISSUE TITLE
Question: under what condition AGIC for new ingress will pick backend pool as defaultaddresspool ?

### ISSUE THREAD

**Issue by niteenkole** [Azure/application-gateway-kubernetes-ingress#846]
Question: under what condition AGIC will pick backend pool as defaultaddresspool ?

**To Reproduce**
If you see below its picking up "backend pool defaultaddresspool" 

I0510 21:10:36.171082       1 health_probes.go:55] Created default HTTP probe defaultprobe-Http
I0510 21:10:36.171088       1 health_probes.go:56] Created default HTTPS probe defaultprobe-Http
I0510 21:10:36.171101       1 ingress_rules.go:112] Found backend:pgadmin/pgadmin-svc
I0510 21:10:36.171394       1 health_probes.go:70] Created probe pb-pgadmin-pgadmin-svc-443-pgadmin-ingress for ingress pgadmin/pgadmin-ingress and service pgadmin/pgadmin-svc
I0510 21:10:36.171446       1 backendhttpsettings.go:185] Created backend http settings bp-pgadmin-pgadmin-svc-443-443-pgadmin-ingress for ingress pgadmin/pgadmin-ingress and service pgadmin/pgadmin-svc
I0510 21:10:36.171479       1 backendaddresspools.go:37] Created default backend pool defaultaddresspool
I0510 21:10:36.171548       1 frontend_listeners.go:117] Processing Rules for Ingress: pgadmin/pgadmin-ingress
I0510 21:10:36.171800       1 requestroutingrules.go:112] Bound basic rule rr-nv-aks-xxxx.ca-443 to listener fl-nv-aks-np.cglcloud.ca-443(nv-aks-xxxx.ca, 443), backend pool defaultaddresspool and backend http settings bp-pgadmin-pgadmin-svc-443-443-pgadmin-ingress
I0510 21:10:36.195396       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment

====
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pgadmin-ingress
  namespace: pgadmin
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-protocol: "https"
    appgw.ingress.kubernetes.io/backend-hostname: "nv-xxxxxx.ca"
    appgw.ingress.kubernetes.io/appgw-trusted-root-certificate: "nv-xxxxxxx-ca-root-cert1"
spec:
  tls:
  - hosts:
    - nv-aks-xxxxxxx.ca
    secretName: pgadmin-ingress-portal-tls
  rules:
  - host: nv-aks-xxxxxx.ca
    http:
      paths:
      - path:
        backend:
          serviceName: pgadmin-svc
          servicePort: 443

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
* Output of `kubectl logs <ingress controller>. 
* Any Azure support tickets associated with this issue.

**Comment by niteenkole** [comment]
I think when backend service is not available or listening to correct port ,it picks up default,may be warning or alert should be generated.

example. I had "app: pgadmin-prod" in my svc but my actual selector is k8s-app: pgadmin-prod

changing to k8s-app: pgadmin-prod fixed it.

apiVersion: v1
kind: Service
metadata:
  name: pgadmin-svc
  namespace: pgadmin
spec:
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
  type: ClusterIP
#  type: NodePort
  selector:
    app: pgadmin-prod ----<<<<

**Comment by akshaysngupta** [comment]
If you using kubernetes version < 1.16, you should see an event created on the ingress object.

https://github.com/Azure/application-gateway-kubernetes-ingress/blob/0bf5fa3c1bdd5f4af38d19c260200a5d35733a2e/pkg/appgw/backendaddresspools.go#L104
