### ISSUE TITLE
Docs: "Azure identity in resource group"?

### ISSUE THREAD

**Issue by howardjones** [Azure/application-gateway-kubernetes-ingress#849]
Reading the Brownfield deployment guide to help create an ARM template+script to deploy AGIC in a consistent manner.

In [that document](https://azure.github.io/application-gateway-kubernetes-ingress/setup/install-existing/) it says 

> "Create an Azure identity in the same resource group as the AKS nodes. **Picking the correct resource group is important**. The resource group required in the command below is not the one referenced on the AKS portal pane. "

However, in an ARM template, there is [no option to specify an associated Resource Group](https://docs.microsoft.com/en-us/azure/templates/microsoft.managedidentity/2018-11-30/userassignedidentities). In fact, in the Greenfield doc's ARM template, it doesn't do this either. It uses the resource group only to find the correct location.

So: is the group important? What does it actually mean to create an identity "in a resource group"?

**Comment by SychevIgor** [comment]
@akshaysngupta any updates? issue created 9 months ago
