### ISSUE TITLE
Integration with AAD for user authentication

### ISSUE THREAD

**Issue by torangel** [Azure/application-gateway-kubernetes-ingress#855]
According to this guide:
https://docs.microsoft.com/en-us/azure/aks/azure-ad-integration-cli

this command can be used to connect a RBAC enabled cluster to Azure Active Directory for outsourcing user authentication/management.
```
az aks create \
    --resource-group myResourceGroup \
    --name $aksname \
    --node-count 1 \
    --generate-ssh-keys \
    --aad-server-app-id $serverApplicationId \
    --aad-server-app-secret $serverApplicationSecret \
    --aad-client-app-id $clientApplicationId \
    --aad-tenant-id $tenantId
```

When using the following command to create AKS/APPGW deployment using the deployment template in this repo
```
az group deployment create -g $rg -n $deploymentName --template-uri "https://raw.githubusercontent.com/Azure/application-gateway-kubernetes-ingress/master/deploy/azuredeploy.json" --parameters aksServicePrincipalAppId="${appId}" aksServicePrincipalClientSecret="${password}" aksServicePrincipalObjectId="${objectId}" aksEnableRBAC=true aksAgentCount=1
```
The AKS cluster is RBAC enabled, and the supplied serviceprincipal works perfectly fine integrating with "the rest of azure" managing the the application gateway. I however cannot find how to establish "the rest" of the AAD integration for enabling user integration.

Available parameters:
![image](https://user-images.githubusercontent.com/1355125/81966163-61f4bf80-9619-11ea-89f4-880be06f8f08.png)

https://docs.microsoft.com/en-us/azure/aks/azure-ad-integration-cli
also states that:

> The following limitations apply:
> Azure AD can only be enabled when you create a new, RBAC-enabled cluster. You can't enable Azure AD on an existing AKS cluster.

Is it possible to enable the Azure AD using the deployment template, or is this only available using the cli with 
```
az aks create...
```
?

If this is not currently possible using the deployment template, is there any chance this can be adjusted?

One approach I haven`t invested time in trying is described here:
https://docs.microsoft.com/en-us/azure/aks/update-credentials
```
az aks update-credentials \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --reset-aad \
    --aad-server-app-id <SERVER APPLICATION ID> \
    --aad-server-app-secret <SERVER APPLICATION SECRET> \
    --aad-client-app-id <CLIENT APPLICATION ID>
```
Maybe this can be used after the initial creation with the template in this repo?

**Comment by 3quanfeng** [comment]
Hi @torangel , AGIC supports to use[ AAD pod identity](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/setup/install-new.md#install-aad-pod-identity) to access Azure resources based on AAD, to use AGIC with AAD pod identity, you will need a user-assigned managed identity, please follow the greenfield deployment of AGIC.

**Comment by 3quanfeng** [comment]
Hi @torangel , to support AKS to authenticate with AAD in tempate, you might try: 
1. use [aadProfile](https://github.com/Azure/azure-rest-api-specs/blob/7eeef3ce97572bf15bbf3865fdfd17e78b1e760b/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2020-03-01/managedClusters.json#L1992) instead of 

> servicePrincipalProfile

in azuredeploy.json
2. set the [required fields](https://github.com/Azure/azure-rest-api-specs/blob/7eeef3ce97572bf15bbf3865fdfd17e78b1e760b/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2020-03-01/managedClusters.json#L2205) for aadProfile

**Comment by torangel** [comment]
Thank you for your reply!
Please confirm if this is how I should undertand your comment:

Instead of using the _servicePrincipalProfile_ which is defined in the template here:
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/deploy/azuredeploy.json#L609

I should instead edit the template to use aadProfile and complete my editing with defining values for the required fields.


The end result will be something like in attached picture (but with values fetched from params of course)

![image](https://user-images.githubusercontent.com/1355125/82379593-7674f580-9a27-11ea-807a-50f73769aef4.png)

**Comment by 3quanfeng** [comment]
> Thank you for your reply!
> Please confirm if this is how I should undertand your comment:
> 
> Instead of using the _servicePrincipalProfile_ which is defined in the template here:
> https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/deploy/azuredeploy.json#L609
> 
> I should instead edit the template to use aadProfile and complete my editing with defining values for the required fields.
> 
> The end result will be something like in attached picture (but with values fetched from params of course)
> 
> ![image](https://user-images.githubusercontent.com/1355125/82379593-7674f580-9a27-11ea-807a-50f73769aef4.png)

Correct, we haven't tried it out in the template, please share here if you have any news :)

**Comment by torangel** [comment]
I have now tried adjusting the template. 
Changes to be found here:

https://github.com/torangel/application-gateway-kubernetes-ingress/commit/958a5d75b2c9aff51f6e8c0af0211cb2bc9f9acf

I am following the tutorial here:
https://docs.microsoft.com/en-us/azure/aks/azure-ad-integration-cli

Only swapping this
```
az aks create \
    --resource-group myResourceGroup \
    --name $aksname \
    --node-count 1 \
    --generate-ssh-keys \
    --aad-server-app-id $serverApplicationId \
    --aad-server-app-secret $serverApplicationSecret \
    --aad-client-app-id $clientApplicationId \
    --aad-tenant-id $tenantId
```

With the script below - which results in an error....

```
torangel@TCAXPS15:~$ az group deployment create -g myResourceGroup -n $aksname \
>     --template-file "/mnt/c/slettmeg/DeploymentTemplateK8/azuredeploy.json" \
>     --parameters aadProfileManaged=true \
>         aadProfileClientAppID="${clientApplicationId}" \
>         aadProfileServerAppID="${serverApplicationId}" \
>         aadProfileServerAppSecret="${serverApplicationSecret}" \
>         aadProfileTenantID="${tenantId}"
Azure Error: InvalidTemplateDeployment
Message: The template deployment 'tcazadcluster' is not valid according to the validation procedure. The tracking id is '181e866f-8ec5-4a9f-9c5c-c9b92298b66e'. See inner errors for details.
Exception Details:
        Error Code: InvalidParameter
        Message: Provisioning of resource(s) for container service aks5466 in resource group myResourceGroup failed. Message: {
  "code": "InvalidParameter",
  "message": "Required parameter servicePrincipalProfile is missing (null).",
  "target": "servicePrincipalProfile"
 }. Details:
```

This makes be wonder if I am doing something wrong when removing the servicePrincipalProfile?
I am also wondering about these lines in the template - which currently does not have any meaningful value for the **aksServicePrincipalObjectId**

- https://github.com/torangel/application-gateway-kubernetes-ingress/blob/958a5d75b2c9aff51f6e8c0af0211cb2bc9f9acf/deploy/azuredeploy.json#L536
- https://github.com/torangel/application-gateway-kubernetes-ingress/blob/958a5d75b2c9aff51f6e8c0af0211cb2bc9f9acf/deploy/azuredeploy.json#L546


Great if you can shed some light on this

**Comment by akshaysngupta** [comment]
@torangel You can find the objectId by using the following command for the server application.
```
az ad sp show --id ${serverApplicationId} -o tsv --query "objectId"
```

Try using the above object for the aksServicePrincipalObjectId.

**Comment by torangel** [comment]
Works with these modifications:
https://github.com/torangel/application-gateway-kubernetes-ingress/commit/0f6c7a332eae030e30584aba931809e4d223d2ee

Thank you for your help @akshaysngupta !
