### ISSUE TITLE
AGIC with VMSS 

### ISSUE THREAD

**Issue by ushabapat** [Azure/application-gateway-kubernetes-ingress#856]
Hi, We have configured the AGIC with VMSS. The setup is done and by default the POD IPs are configured as backendpool in application gateway WAF_V2. Since we are using VMSS, we have updated the app gateway backendpool to point to vmss instead pod IPs.  The backend health is failing with error "unable to connect to the server". The NSGs are configured and app gateway and AKS both are in the same VNET. We are unable to fix the issue as there are no logs specific to health check failure.
Any help would be much appreciated.

**Comment by ushabapat** [comment]
Hi, Any update on this ? Why the POD IP is added under backendpool when VMSS is used in AKS for auto scale. Eventually, the communication should happen via VMSS to POD internally via route tables/ip tables . The similar setup works fine when we use without VMSS. 

It would be great if you can provide more details about the issue.
The issue is explained in stackoverflow.  https://stackoverflow.com/questions/61734606/

**Comment by 3quanfeng** [comment]
Hi @ushabapat , did you mean to set up AppGw to be shared by your VMSS application and AKS services? if yes, please refer to the brownfield deployment
