### ISSUE TITLE
Helm package for this repo has not been updated at repo

### ISSUE THREAD

**Issue by pbalexlear** [Azure/application-gateway-kubernetes-ingress#865]
This helm package appears to have not been pushed to https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/ as when I tried to use this to apply AGIC to my cluster it didn't work, having looked into this it appears to be because there was changes made to AAD Pod Identity to make it case sensitive and the AzureIdentity and AzureIdentityBinding Templates in the version published are not in the correct case. Having looked at the repository here that now appears to have been updated but when I pull the latest from the helm repo it is not updated.

This means when following the guide here: https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-install-new this doesn't work as the pod identity is not correctly picked up and assigned.

Please can the helm charts in the published repo be updated?

**Comment by akshaysngupta** [comment]
Thanks for reporting.

We have just released `1.2.0-rc2` which addresses this issue.

Duplicate https://github.com/Azure/application-gateway-kubernetes-ingress/issues/828
