### ISSUE TITLE
Configuration is lost after re-deploying ARM template

### ISSUE THREAD

**Issue by besteban1989** [Azure/application-gateway-kubernetes-ingress#866]
1. I have installed app gateway, AKS with ARM Template 
2. I have installed the AGIC Helm Chart 
3. I have installed a test app and ingress
4. Https listeners, backend pools, probes have been created. 
5. I did a change in the ARM template and now all rules that AGIC push to the app gateway are lost

Is there a way to tell App Gateway or ARM to avoid reconfigure the app gateway?

**Comment by akshaysngupta** [comment]
@besteban1989 This is expected as the template does a PUT on the Application Gateway resource.
To address these cases, we have solution which can make AGIC reconcile the Application Gateway rules. To enable this feature, you need to update the helm template and provide a reconcile timeout. Here is the documentation.
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/features/agic-reconcile.md

Please feel free to reopen this issue if you encounter any issues in this feature.

**Comment by mhsh64** [comment]
@akshaysngupta Hi
Is this possible to open this issue?
Because this solution you suggested has a downtime, which is not applicable in production
The time appgw does not have any configs till the agic will configure it again
