### ISSUE TITLE
Question: health check says  "GET / HTTP/1.1" 302 237 "-" "-" 

### ISSUE THREAD

**Issue by niteenkole** [Azure/application-gateway-kubernetes-ingress#869]
Question

health check says  "GET / HTTP/1.1" 302 237 "-" "-" 

is this normal ?

**To Reproduce**

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
* Output of `kubectl logs <ingress controller>. 
* Any Azure support tickets associated with this issue.

**Comment by akshaysngupta** [comment]
@niteenkole I assume this log is from the backend. Backend health, if status code is not specified, considers 200-399 as a healthy status code.

**Comment by niteenkole** [comment]
ok thanks 

From backend health check it says "Success. Received 302 status code"
