### ISSUE TITLE
Question : Applications moved under default backend pool with no IP address

### ISSUE THREAD

**Issue by akshetty9** [Azure/application-gateway-kubernetes-ingress#880]
On what circumstances application gateway ingress controller moves the services under default backend pool? If I have two pods running two different applications, I am expecting them to create separate backend pool mapping to IP address of the PODS. But sometimes, it associates both of these pods as rules under the default backend pool with an empty IP address. 

As you can see in the screenshot below, 7 of the 9 applications got created under default backed pool, which return 502 bad gateway due to no mapping to IP address.

![image](https://user-images.githubusercontent.com/17539815/82862622-c549f000-9f3d-11ea-80cf-054a9d2c4ff2.png)

**Comment by 3quanfeng** [comment]
Hi @akshetty9 , if it's for path based rules, the rule will also be associated to the default backend, i.e. if no path matched, the rule will route the request to the default backend.

**Comment by 3quanfeng** [comment]
close
