### ISSUE TITLE
PGADMIN4 end to end SSL behind AGIC is working

### ISSUE THREAD

**Issue by niteenkole** [Azure/application-gateway-kubernetes-ingress#881]
**Describe **
PGADMIN4 end to end SSL behind AGIC is working
This might help anyone else.
We have pgadmin4 running inside AKS and behind AGIC with end to end SSL.

Things to take care.
1.You need to add all chain of certificate in cert file.
   add all server,root and intermediate.
2. used below.
      annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-protocol: "https"
    appgw.ingress.kubernetes.io/backend-hostname: "pgadmin.xxxxxx.ca"
    appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
    appgw.ingress.kubernetes.io/appgw-trusted-root-certificate: "xxxxxxx-root-cert1"
 3.From PGADMIN side make sure add below else donet work.
           - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
          value: "False"
4. Also have used azure file for data persistent.
         volumes:
      - name: pgadmin-var
        persistentVolumeClaim:
          claimName: pvc-azurefile-pgadmin-var
      - name: pgadmin-cert
        secret:
          secretName: pgadmin-ssl-key

**To Reproduce**

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
* Output of `kubectl logs <ingress controller>. 
* Any Azure support tickets associated with this issue.

**Comment by niteenkole** [comment]
create detail document

https://github.com/niteenkole/pgadmin4

**Comment by 3quanfeng** [comment]
Thanks @niteenkole , would you mind to help contribute your writings to agic[ how-tos](https://github.com/Azure/application-gateway-kubernetes-ingress/tree/master/docs/how-tos)?

**Comment by niteenkole** [comment]
Sure

**Comment by akshaysngupta** [comment]
Thanks @niteenkole .Closing the issue.
