### ISSUE TITLE
helm chart ingress-azure - explicitly specify nodeSelector: kubernetes.io/os: linux

### ISSUE THREAD

**Issue by jbinko** [Azure/application-gateway-kubernetes-ingress#888]
helm chart ingress-azure deployment is failing on AKS with windows pool/nodes.
AKS is trying to install it also on windows nodes and it fails.

Maybe workaround is to specify:
--set nodeSelector."kubernetes\.io/os"=linux
(this was not worknig for me)

I modified and deployed local chart with:
nodeSelector:
        kubernetes.io/os: linux

Expected fix:
nodeSelector:
        kubernetes.io/os: linux
should be explicitly specified in the deployment file

**Comment by akshaysngupta** [comment]
@jbinko Can you try using `--set nodeSelector."kubernetes\.io/os"=linux` ?

**Comment by wronda** [comment]
This is still an issue on AKS clusters with Windows and Linux pools. You can easily reproduce this by trying to helm install a nginx ingress. Even with specifying the node selector the pod get's scheduled onto a windows node.

**Comment by chefcook** [comment]
> This is still an issue on AKS clusters with Windows and Linux pools. You can easily reproduce this by trying to helm install a nginx ingress. Even with specifying the node selector the pod get's scheduled onto a windows node.

I can only confirm that this problem still exists.
Could reproduce it with different helm charts

`--set nodeSelector. "kubernetes\.io/os"=linux `

is simply ingorated.

**Comment by katydidknot** [comment]
We're still having this issue, did anyone get this sorted?
