### ISSUE TITLE
We socket support with path

### ISSUE THREAD

**Issue by burn2delete** [Azure/application-gateway-kubernetes-ingress#889]
Websockets are only supported at the root path “/“. Nginx supports nested paths for the ingress. 

Support websockets at non-root ingress paths.

**Comment by akshaysngupta** [comment]
@flyboarder 
Is the backend pod expecting the packet to be rewritten to "/" ?
For example: 
You can solve this my using `appgw.ingress.kubernetes.io/backend-path-prefix: "/"` annotation to the ingress resource.

**Comment by flyboarder** [comment]
@akshaysngupta yes this is how it's currently configured and works for websites which connect to the server via websockets, however this will not work for node client websockets, which will attempt to use the hostname as the server and the `/websocket/` will be interpreted as the namespace (using socket.io).

Im not sure this can be fixed, but it should be documented that when websockets are used outside of a browser the websocket server must be at the root path.
