### ISSUE TITLE
Can't run more than 2 ingress-azure pods

### ISSUE THREAD

**Issue by PandaXass** [Azure/application-gateway-kubernetes-ingress#89]
**Describe the bug**
As long as specifying replicaCount equals or greater than `3` in helm value file, only 2 `ingress-azure` pods will work correctly.

**To Reproduce**
Specify any value bigger than `2` for `replicaCount` in value.yaml during helm installation. And then check logs for each pod.

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
```
$ helm list
agw                      	3       	Mon Jan 21 08:41:59 2019	DEPLOYED	ingress-azure-0.1.5       	1.0        	default

$ kubectl describe pod agw-ingress-azure-56ccd6f4c8-bwlm9
Name:               agw-ingress-azure-56ccd6f4c8-bwlm9
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               aks-agentpool-30504654-1/10.11.0.35
Start Time:         Wed, 09 Jan 2019 13:09:05 +0100
Labels:             aadpodidbinding=agw-ingress-azure
                    app=ingress-azure
                    pod-template-hash=1277829074
                    release=agw
Annotations:        <none>
Status:             Running
IP:                 10.11.0.40
Controlled By:      ReplicaSet/agw-ingress-azure-56ccd6f4c8
Containers:
  ingress-azure:
    Container ID:   docker://51fc60de38b5661dfa229562b607dd9d044d00e3e44fa9335253deb64aa13335
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.1.4
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:b996e8d9812d4d92cf55d2b02fe8f404352b08e137757c4b8d8dabd11fb1901b
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 17 Jan 2019 11:48:08 +0100
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Wed, 09 Jan 2019 13:09:11 +0100
      Finished:     Thu, 17 Jan 2019 10:49:56 +0100
    Ready:          True
    Restart Count:  1
    Environment Variables from:
      agw-cm-ingress-azure  ConfigMap  Optional: false
    Environment:
      KUBERNETES_PORT_443_TCP_ADDR:  XXXXXXXX
      KUBERNETES_PORT:               tcp://XXXXXXXX:443
      KUBERNETES_PORT_443_TCP:       tcp://XXXXXXXX:443
      KUBERNETES_SERVICE_HOST:       XXXXXXXX
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from agw-sa-ingress-azure-token-j49rn (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  agw-sa-ingress-azure-token-j49rn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  agw-sa-ingress-azure-token-j49rn
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

* Output of `kubectl logs <ingress controller>. 
```
$ kubectl logs --tails=7 agw-ingress-azure-56ccd6f4c8-bwlm9
I0121 07:52:07.689500       1 main.go:86] Retrying in 10s
E0121 07:52:17.749200       1 main.go:83] unable to get specified ApplicationGateway [xxxxxxxx-agw], error=[azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/XXXXXXXX/resourceGroups/MC_xxxxxxxx_xxxxxxxx_eastus2/providers/Microsoft.Network/applicationGateways/xxxxxxxx-agw?api-version=2018-06-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}
]
I0121 07:52:17.749232       1 main.go:86] Retrying in 10s
E0121 07:52:27.813296       1 main.go:83] unable to get specified ApplicationGateway [xxxxxxxx-agw], error=[azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/XXXXXXXX/resourceGroups/MC_xxxxxxxx_xxxxxxxx_eastus2/providers/Microsoft.Network/applicationGateways/xxxxxxxx-agw?api-version=2018-06-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}
]
I0121 07:52:27.813374       1 main.go:86] Retrying in 10s
```

**Comment by asridharan** [comment]
Currently the ingress controller is not meant to run as a cluster. If you run multiple replicas of the ingress controller, all the replicas would try writing to the AG at the same time with the ingress resources that were learnt. While the operations would be serialized and they shouldn't technically be overwriting each others config, there would failures in writes that won't be handled. 

What are you trying to achieve by running multiple replicas of the ingress ?

**Comment by PandaXass** [comment]
Hi @asridharan, thank you for your comments.
What I want to achieve is HA of AG ingress controller, since if the controller is failing, then the datapath forwarding configurations will not be propagated to AG. Then the pod becomes the single point of failure.

**Comment by dan-jackson-github** [comment]
@asridharan, based on your explanation, if I have understood correctly, this ingress controller is simply responsible for configuring application gateway to route request/load balance between pods. The ingress controller itself doesn't need to be Highly available because it is only ever needed to upload configuration? Is this correct?

**Comment by asridharan** [comment]
@dan-jackson-github yes your understanding is correct. The ingress controller itself doesn't need to be highly available since its stateless and is used only as a tranformation gateway to translate ingress resources into AG config. Thus making it highly available doesn't serve much purpose because the model is inherently eventually consistent.

**Comment by PandaXass** [comment]
Hi @asridharan,

Well, yes, in the end it might be eventually consistent.
But when the ingress controller is in a bad state or unavailable, at the same time, anything happens to the pod causing IP changes will not be reflected in application gateway will cause downtime until someone or somehow realize there is an issue in ingress controller, which is too optimistic in production environment.
