### ISSUE TITLE
Prohibited Targets based on Path

### ISSUE THREAD

**Issue by DavidJohnsonSN** [Azure/application-gateway-kubernetes-ingress#896]
Hello, we are trying to determine whether we can configure the app gateway kubernetes ingress to match our scenario.

Required Scenario:
Domain: abc.ourdomain.com

Route Path: `/function1/*` to an Azure Cloud Service (Classic) or Azure App Service
Route Path: `/function2/*` to an app in AKS

We have found the documentation about prohibited targets and can see that is based on host i.e. we can prohibit host abc.ourdomain.com but that does not fully help us because we want to allow the App Gateway ingress to configure for path `/function2/*` but ignore the configuration for `/function1/*`

The current behaviour is to wipe out the configuration for `/function1/*`

Is this possible?

Thank you.

**Comment by 3quanfeng** [comment]
Hi @DavidJohnsonSN , thanks for asking, you can specify prohibited target with host and path
here is an example:

apiVersion: appgw.ingress.k8s.io/v1
kind: AzureIngressProhibitedTarget
metadata:
    name: prohibit-backend-ns
spec:
    hostname: brownfield-blacklist-ns.host
    paths:
    - "/blacklist/*"

You can also check the schema [here](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/crds/AzureIngressProhibitedTarget.yaml)

once you enable the blacklist, prohibited-all-target will be applied automatically, you can then apply your customized policy as above.

**Comment by DavidJohnsonSN** [comment]
Thank you for answering. We will try it out and let you know if we are successful.

**Comment by 3quanfeng** [comment]
close
