### ISSUE TITLE
Multi-namespace support missing rule binding

### ISSUE THREAD

**Issue by mbrumpton** [Azure/application-gateway-kubernetes-ingress#897]
**Describe the bug**
I have setup watchNamespace to monitor two namespaces with two SSL applications, both with multiple paths and when it syncs to AGW one of the the applications does not have a rule assigned to it. 

Both applications work when one one namespace is monitored. 

**To Reproduce**

Environment:
AKS 1.17.5
Helm3
--version 1.2.0-rc2

Both applications in different namespaces have a similar ingress config:

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: namespace
  annotations:
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: sslcert
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: example.website.com
  - http:
      paths:
      - path: /services/http/*
        backend: 
          serviceName: service-http
          servicePort: 80
      - path: /
        backend: 
          serviceName: frontend-site
          servicePort: 80

**Ingress Controller details**
ERROR: logging before flag.Parse: I0604 17:52:54.934226       1 utils.go:111] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0604 17:52:54.971178       1 main.go:125] App Gateway Details: Subscription: 185bd685-2d36-430b-bd36-f0c279e033a9, Resource Group: obstage-ne-rg, Name: obstage-ne-appgateway
I0604 17:52:54.971421       1 auth.go:41] Creating authorizer using Cluster Service Principal.
I0604 17:52:54.971244       1 httpserver.go:57] Starting API Server on :8123
I0604 17:52:55.389928       1 main.go:170] Ingress Controller will observe the following namespaces:obstage-comp,obstage-dash
I0604 17:52:55.464844       1 context.go:132] k8s context run started
I0604 17:52:55.464881       1 context.go:176] Waiting for initial cache sync
I0604 17:52:55.665157       1 context.go:189] Initial cache sync done
I0604 17:52:55.665190       1 context.go:190] k8s context run finished
I0604 17:52:55.665270       1 worker.go:39] Worker started
I0604 17:52:55.769760       1 redirects.go:44] Created redirection configuration sslr-fl-c61dda7ff9748ec5f51989767db5afd0 for ([    ],443); not yet linked to a routing rule
I0604 17:52:55.783802       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0604 17:53:16.391713       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0604 17:53:16.391740       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0604 17:53:16.393659       1 mutate_app_gateway.go:204] END AppGateway deployment
I0604 17:53:16.393679       1 controller.go:151] Completed last event loop run in: 20.728357785s

**Comment by akshaysngupta** [comment]
@mbrumpton This scenario is not supported right now. You need to either have **unique paths** for each service or use **different hostnames** on the two ingresses if you want to use the same path. This is an important so that the packets can be routed to the correct service.

**Comment by mbrumpton** [comment]
Hi, just to clarify each appgw ingress has a unique hostname, is there support for a multi-site host header?
