### ISSUE TITLE
How to support Multiple Gateways

### ISSUE THREAD

**Issue by geoarchitect** [Azure/application-gateway-kubernetes-ingress#899]
**Is your feature request related to a problem? Please describe.**
Application Gateways do not support multiple IP's listening on the same port. 

We need to then have two ingress controllers or two different Application Gateways per cluster. One for a Public IP and one for a Private IP both listening to port 443.

**Describe the solution you'd like**
Any instructions or anything we may need to consider to setup one or more AGIC for supporting more than one IP listening to port 443. Is this even possible with how this is setup today? 

Any guidance on this from the team would be greatly appreciated.

**Comment by akshaysngupta** [comment]
@geoarchitect If you want to expose all services over both public IP and private IP at 443, then
You can deploy 2 AGIC -  2 AppGW on the cluster. Both will listen to all the ingresses across the cluster.
Specifically, for AppGW/AGIC which will serve your services over Private IP,
1) Make sure you add a private IP to the App Gateway. You can use portal or CLI to do this.
2) Add `usePrivateIP: "true"` to the helm configuration. This will attach all the ingresses to the private IP configuration.

**Comment by PPreamble** [comment]
If you have an NVA deployed into the environment (such as Azure Firewall) you can utilize port mapping to send private traffic to the single AGW after configuring it to listen on a different port than the public IP uses. AGW config can use the same ports for the backend traffic so no additional http configs or pools are needed.

Still, it would be really nice if this was not a limitation in design in the first place.

**Comment by geoarchitect** [comment]
@akshaysngupta - Is it possible to deploy a second ingress but using the same gateway just on an alternate port? 

The idea being we could have the private ip for backhaul traffic go over port 8443 or something similar?
