### ISSUE TITLE
Trusted root certificate not enabled in HTTP settings

### ISSUE THREAD

**Issue by michaelsiuda** [Azure/application-gateway-kubernetes-ingress#900]
**Describe the bug**
Even though I use the `appgw.ingress.kubernetes.io/appgw-trusted-root-certificate` annotation and define host name override, the corresponding HTTP settings on the app gateway doesn't have these options enabled. As a result, I cannot use HTTPs on the connection between the app gateway and my app running on AKS.

As soon as I manually enable trusted root certificate on the http setting in the app gateway, HTTPs connection between the gateway and backend is established.

**To Reproduce**
See the ingress configuration below.

**Ingress Controller details**
Using version 1.2.0-rc2 of AGIC:
```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
ingress-azure   default         2               2020-06-03 15:42:40.736420152 +0000 UTC deployed        ingress-azure-1.2.0-rc2 1.2.0-rc2
```

And the following ingress configuration:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/appgw-trusted-root-certificate: InternalRootCA
    appgw.ingress.kubernetes.io/backend-protocol: https
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"appgw.ingress.kubernetes.io/appgw-trusted-root-certificate":"InternalRootCA","appgw.ingress.kubernetes.io/backend-protocol":"https","appgw.ingress.kubernetes.io/ssl-redirect":"true","kubernetes.io/ingress.class":"azure/application-gateway"},"name":"myserviceserver-ingress","namespace":"default"},"spec":{"rules":[{"host":"myservicestaging.aks.mydomain.com","http":{"paths":[{"backend":{"serviceName":"myservicestagingaks","servicePort":443}}]}}],"tls":[{"hosts":["myservicestaging.aks.mydomain.com"],"secretName":"internal-ssl-certificates"}]}}
    kubernetes.io/ingress.class: azure/application-gateway
  creationTimestamp: "2020-06-04T08:10:51Z"
  generation: 1
  name: myserviceserver-ingress
  namespace: default
  resourceVersion: "4177360"
  selfLink: /apis/networking.k8s.io/v1beta1/namespaces/default/ingresses/myserviceserver-ingress
  uid: 6ce28113-81d1-433c-ae4d-0d168cf06e64
spec:
  rules:
  - host: myservicestaging.aks.mydomain.com
    http:
      paths:
      - backend:
          serviceName: myservicestagingaks
          servicePort: 443
  tls:
  - hosts:
    - myservicestaging.aks.mydomain.com
    secretName: internal-ssl-certificates
status:
  loadBalancer:
    ingress:
    - ip: XX.XX.XX.XX
```

Note that the ingress believes that the `"appgw.ingress.kubernetes.io/appgw-trusted-root-certificate":"InternalRootCA"` configuration has been applied to the app gw.

Here are the logs from the AGIC pod:
```
ERROR: logging before flag.Parse: I0605 23:07:35.086795       1 main.go:302] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0605 23:07:35.125790       1 main.go:102] Unable to load Azure Context file:
I0605 23:07:35.125818       1 environment.go:168] KUBERNETES_WATCHNAMESPACE is not set. Watching all available namespaces.
I0605 23:07:35.125825       1 main.go:132] App Gateway Details: Subscription: XXXX, Resource Group: staginguk, Name: staginguk-aks-appgateway
I0605 23:07:35.125831       1 auth.go:81] Creating authorizer from file referenced by environment variable: /etc/Azure/Networking-AppGW/auth/armAuth.json
I0605 23:07:35.481205       1 main.go:179] Ingress Controller will observe all namespaces.
I0605 23:07:35.515902       1 context.go:129] k8s context run started
I0605 23:07:35.515944       1 context.go:168] Waiting for initial cache sync
I0605 23:07:35.616091       1 context.go:176] Initial cache sync done
I0605 23:07:35.616112       1 context.go:177] k8s context run finished
I0605 23:07:35.616251       1 worker.go:35] Worker started
I0605 23:07:35.616437       1 httpserver.go:57] Starting API Server on :8123
I0605 23:07:35.756086       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment
I0605 23:07:56.189982       1 mutate_app_gateway.go:182] Applied App Gateway config in 20.433869683s
I0605 23:07:56.190076       1 mutate_app_gateway.go:198] cache: Updated with latest applied config.
I0605 23:07:56.190952       1 mutate_app_gateway.go:203] END AppGateway deployment
```

And here's resulting http settings on the application gateway:
```
{
  "affinityCookieName": null,
  "authenticationCertificates": null,
  "connectionDraining": null,
  "cookieBasedAffinity": "Disabled",
  "etag": "W/\"20773f56-3815-495f-8349-94fe3b798315\"",
  "hostName": null,
  "id": "/subscriptions/XXXX/resourceGroups/staginguk/providers/Microsoft.Network/applicationGateways/staginguk-aks-appgateway/backendHttpSettingsCollection/bp-default-myservicestagingaks-443-443-myserviceserver-ingress",
  "name": "bp-default-myservicestagingaks-443-443-myserviceserver-ingress",
  "path": null,
  "pickHostNameFromBackendAddress": false,
  "port": 443,
  "probe": {
    "id": "/subscriptions/XXXX/resourceGroups/staginguk/providers/Microsoft.Network/applicationGateways/s`taginguk-aks-appgateway/probes/pb-default-myservicestagingaks-443-myserviceserver-ingress",
    "resourceGroup": "staginguk"
  },
  "probeEnabled": null,
  "protocol": "Https",
  "provisioningState": "Succeeded",
  "requestTimeout": 30,
  "resourceGroup": "staginguk",
  "trustedRootCertificates": null,
  "type": "Microsoft.Network/applicationGateways/backendHttpSettingsCollection"
}
```

Note that:
```
  "trustedRootCertificates": null,
```

**Comment by 3quanfeng** [comment]
Hi @michaelsiuda , regarding 
"Note that the ingress believes that the "appgw.ingress.kubernetes.io/appgw-trusted-root-certificate":"InternalRootCA" configuration has been applied to the app gw."
Just want to confirm if you have the root cert "InternalRootCA" imported to appgw or not before you start AGIC?

**Comment by michaelsiuda** [comment]
Hi @3quanfeng, 

I am not sure it's clear what exactly it means to start AGIC, but I have deleted the azure-ingress pod (which I believe is the key component of AGIC) and deleted and re-created the Ingress object after installation of the cert.

Is there any recommended sequence I should run that you'd consider as restart of AGIC, or is deleting the pod sufficient (the pod is then recreated by the AGIC deployment).

**Comment by 3quanfeng** [comment]
Hi @michaelsiuda , sorry for the confusing, for start, I meant you will need to have the cert imported to appgw before you use AGIC, AGIC in this case will simply put the reference of the cert in your appgw config and you will then be able to see your httpsettings have the cert configured from the portal, did you see the cert name in your httpsetting this time?

**Comment by michaelsiuda** [comment]
Hi @3quanfeng ,

Sorry, should have made that clearer in the bug report - I have uploaded the cert to app gw, following the instructions in https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/annotations.md#appgw-trusted-root-certificate. Then I have restarted AGIC.

I have confirmed that the cert is present and installed on the app gw through `az` CLI as well as looking in the portal. Furthermore, if I go to the portal, and find the http settings corresponding to my service (these were created by AGIC), I could change the config to use that trusted cert.

Hopefully that makes it clearer, but let me know if there's any info missing from the report.

**Comment by 3quanfeng** [comment]
Hi @michaelsiuda , thanks, so I guess you issue is resolved? do you have any other issues before I marked it resolved?

**Comment by michaelsiuda** [comment]
Hi @3quanfeng,
 
Unfortunately, I don't believe the issue is resolved. I only got the SSL connection working after manually modifying the settings in the app gw. But as soon as my service on AKS restated, AGIC reset the settings on app gw to ones without the root certificate.

You said that "AGIC in this case will simply put the reference of the cert in your appgw config and you will then be able to see your httpsettings have the cert configured from the portal". What I'm reporting here is that AGIC does not do that in my case. It does not put the reference of the cert in the app gateway config.

**Comment by 3quanfeng** [comment]
Hi @michaelsiuda , could you help set the log level to 5 and see if you can find any log lines like "Found trusted root certificate(s): xxx from ingress: xxx/xxx", and could you please share with me the snippet of the logs? Thanks!

**Comment by michaelsiuda** [comment]
Hi @3quanfeng ,

In order to increase the verbosity level I had to reinstall the entire AGIC helm chart, and after new installation the root certificate was properly installed at the app gw. 

Let's close this issue for now as unreproducible. I will be doing more testing in the next couple of months so if I see this again I will re-open the ticket.

Thanks for the support!
