### ISSUE TITLE
Documentation on Istio setup & support

### ISSUE THREAD

**Issue by darrenk13** [Azure/application-gateway-kubernetes-ingress#907]
**Is your feature request related to a problem? Please describe.**
What support is included with AGIC around Istio?  I see several files with Istio in the name but I don't see any documentation around Istio in the docs folder or on the various Microsoft Docs pages that have information on AGIC.  I am have been trying to get Istio working on AKS with an application gateway with TLS end to end (the end service pod has a valid TLS cert) with the ability to do Istio routing rules and I have not succeeded yet.

**Describe the solution you'd like**
More information how to setup Istio with AKS and application gateways with AGIC.

**Comment by adamcarter81** [comment]
This is a good call - I am battling and have had some success with AGIC and Istio using an Istio ingress gateway:

Successful testing - http from AGIC to Istio ingress works OK

Unsuccessful - TLS End to end - the listener & backend pools work, cert is uploaded OK, but the health check fails (using HTTP to probe the Istio ingress) (https://github.com/Azure/application-gateway-kubernetes-ingress/issues/875) I need to get more time to work on the health probe

But overall I agree, a little more documentation or supported scenarios would be a real help. Still, a good way for me to learn, although it has sucked up a lot of time

**Comment by thomas-riccardi** [comment]
Here is the result of my head banging on the wall, somewhat working, far from perfect: https://github.com/Azure/application-gateway-kubernetes-ingress/issues/875#issuecomment-652464080
