### ISSUE TITLE
Ingress-azure container won't start - AZURE_AUTH_LOCATION error

### ISSUE THREAD

**Issue by dan-jackson-github** [Azure/application-gateway-kubernetes-ingress#91]
**Describe the bug**
When I create the helm templates with the service principal option (not aad-pod-identity) when the container starts up it reports the following error:

I0206 12:30:59.179672       1 main.go:63] Creating authorizer from file referenced by AZURE_AUTH_LOCATION
F0206 12:30:59.179815       1 main.go:68] Error creating Azure client from config: invalid character 'c' looking for beginning of value

One suggest would be to provide clearer instructions on how to setup service principal configuration, you only have it for aad-pod-identity it seems in your docs.

**To Reproduce**
Setup a service principal in Azure and created an associated secret in AKS cluster using the following YAML:

apiVersion: v1
kind: Secret
metadata:
  name: networking-appgw-k8s-azure-service-principal
type: Opaque
data:
  username: _removed_
  password: _removed_

I then use the following helm values configuration for the service principal:
 armAuth:
   type: servicePrincipal
   secretName: networking-appgw-k8s-azure-service-principal
   secretKey: password

**Ingress Controller details**
Pod describe
Name:               *****************
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               **********************
Start Time:         Wed, 06 Feb 2019 12:43:22 +0000
Labels:             app=ingress-azure
                    pod-template-hash=2740828966
                    release=release-name
Annotations:        <none>
Status:             Running
IP:                 10.0.0.11
Controlled By:      ReplicaSet/release-name-ingress-azure-6c84d6dfbb
Containers:
  ingress-azure:
    Container ID:   docker://d78c07da94becbe167e1942cd5c29afb75d2457ea123214a3db4f05e15aa9193
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.1.4
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:b996e8d9812d4d92cf55d2b02fe8f404352b08e137757c4b8d8dabd11fb1901b
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Wed, 06 Feb 2019 13:50:20 +0000
      Finished:     Wed, 06 Feb 2019 13:50:20 +0000
    Ready:          False
    Restart Count:  18
    Environment Variables from:
      release-name-cm-ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_AUTH_LOCATION:           /etc/Azure/Networking-AppGW/auth/password
      KUBERNETES_PORT_443_TCP_ADDR:  <removed>
      KUBERNETES_PORT:               <removed>
      KUBERNETES_PORT_443_TCP:       <removed>
      KUBERNETES_SERVICE_HOST:       <Removed>
    Mounts:
      /etc/Azure/Networking-AppGW/auth from networking-appgw-k8s-azure-service-principal-mount (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from release-name-sa-ingress-azure-token-mmsvd (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  networking-appgw-k8s-azure-service-principal-mount:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  networking-appgw-k8s-azure-service-principal
    Optional:    false
  release-name-sa-ingress-azure-token-mmsvd:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  release-name-sa-ingress-azure-token-mmsvd
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                From                               Message
  ----     ------   ----               ----                               -------
  Warning  BackOff  2m (x296 over 1h)  kubelet, <removed>  Back-off restarting failed container

Pod logs (are posted above in the bug description)

**Comment by asridharan** [comment]
@dan-jackson-github the reason we don't have documentation for using service principal directly, with using the AAD-POD-IDENTITY integration for using MSI, was that the support service principal was introduced primarily to support development activities. Is there a specific reason you need to use the service princiapl and not an MSI to access the AG?

**Comment by dan-jackson-github** [comment]
hi @asridharan thanks for the response. The reason is I would like to keep the k8s configuration as minimal as possible, introducing aad-pod-identity introduces more complexity and another point of failure, it seems the only thing that is going to use it in my AKS implementation is this ingress controller. I prefer to use service principal approach because that keeps my configuration consistent. I also have no experience with aad-pod-identity, have never seen or supported it before!

What is the reason that service principal support is only intended for development? It seems to be a standard approach in AKS for other areas such as load balancer services, storage access and container registry access. Are we saying you don't recommend this approach for productive use? Is it not secure?

**Comment by nezoic** [comment]
Was this ever answered or set as a supported approach? I also do not understand why a service principal would only be used for development. It's pretty common practice to prefer service principals over MSI in Azure.
