### ISSUE TITLE
Deployment takes insane amount of resources (12 vCPUs ?)

### ISSUE THREAD

**Issue by ksanchez15** [Azure/application-gateway-kubernetes-ingress#910]
I have been trying to follow the instructions for the  (Greenfield Deployment)[ https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/setup/install-new.md], but when trying to deploy the template deployment I get the following error:

> Provisioning of resource(s) for container service aks382a in resource group lotusmd_rg failed. Message: Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: eastus, Current Limit: 10, Current Usage: 0, Additional Required: 12, (Minimum) New Limit Required: 12. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%2247ea0af4-3a83-45e1-b98e-996878b9ba04%22,%22pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/regional-quota-requests..

This seems completely overkill, why do I need 12 cores for a simple Kubernetes cluster? When I manually create an AKS cluster and I run multiple containers in it, I only need 2 cores. Is the application gateway that resource hungry? So much so that I need to upgrade my subscription? 

Or am I simply not doing things right ? (hope that's the case)

**Comment by akshaysngupta** [comment]
@ksanchez15 Application Gateway doesn't run on the AKS cluster. It is separate resource and will not add to your CPU quota.
You can customise the VM count and VM SKU as you like.
In Greenfield, You can modify the parameter file to give values for `aksAgentCount` and `aksAgentVMSize` so that you don't exceed your limits.

https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/deploy/azuredeploy.json#L60
```json
        "aksAgentCount": {
            "defaultValue": 3,
            "minValue": 1,
            "maxValue": 50,
            "type": "int",
            "metadata": {
                "description": "The number of agent nodes for the cluster."
            }
        },
        "aksAgentVMSize": {
```

**Comment by ksanchez15** [comment]
Ahhh so If I understand you right @akshaysngupta the agent node max value is used to decide what will be the limit required and it won't actually use the 12 cores? 

But how is the agent node count related to the core quota?

**Comment by akshaysngupta** [comment]
@ksanchez15 Just to be clear, the limits and default values are arbitrary and actually represent the your subscriptions actually capacity. You can edit this file locally to fit your use-case - you can view your limits through Azure Portal `subscriptions` page.

`aksAgentVMSize` determines the type of VM you are using. You can search the internet for Azure VM sizes. This will determine the cpu/mem per VM in your AKS cluster.
`aksAgentCount` determines the number of VMs you want in your AKS cluster.
aksAgentCount * (CPU per VM) is the vCPUs you will use.
