### ISSUE TITLE
502 Bad Gateway Error - Not able to find backend service

### ISSUE THREAD

**Issue by fortanu82** [Azure/application-gateway-kubernetes-ingress#921]
I tried various permutations and combinations to make it work but somehow I keep receiving 502 bad gateway error. Here is the manifest file:-

Service File
> apiVersion: v1
> kind: Service
> metadata:
>   labels:
>     name: resources-ilb-backend
>   name: resources-ilb-backend
>   namespace: resourcesilb
> spec:
>   ports:
>     - name: http
>       protocol: "TCP"
>       port: 80
>       targetPort: 8001
>       #nodePort:
>     - name: https
>       protocol: "TCP"
>       port: 443
>       targetPort: 44345
>   selector:
>     app: resources-ilb-backend
> 	
Deployment File
> 
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: resources-ilb-backend
>   namespace: resourcesilb
> spec:
>   replicas: 2
>   selector:
>     matchLabels:
>       app: resources-ilb-backend
>   template:
>     metadata:
>       labels:
>         app: resources-ilb-backend
>     spec:
>       nodeSelector:
>       imagePullSecrets:
>       - name: regcred
>       containers:
>       - image: staffinguatacr.azurecr.io/resourcesapi:204
>         imagePullPolicy: Always
>         name: resources-ilb-backend
>         ports:
>         - name: http
>           containerPort: 80
>         - name: https
>           containerPort: 443

Ingress File
> apiVersion: extensions/v1beta1
> kind: Ingress
> metadata:
>   name: resources-ilb-backend-ingress
>   namespace: resourcesilb
>   annotations:
>     kubernetes.io/ingress.class: azure/application-gateway
>     appgw.ingress.kubernetes.io/backend-path-prefix: "/"
> spec:
>   rules:
>    - http:
>       paths:
>       - path: /resources/
>         backend:
>           serviceName: resources-ilb-backend
>           servicePort: 80

Description of Manifest files:- 
kubectl describe ingress resources-ilb-backend -n resourcesilb
> Name:             resources-ilb-backend-ingress
> Namespace:        resourcesilb
> Address:          10.193.48.135
> Default backend:  default-http-backend:80 (<none>)
> Rules:
>   Host  Path  Backends
>   ----  ----  --------
>   *
>         /resources/   resources-ilb-backend:80 (10.193.49.42:8001,10.193.49.58:8001)
> Annotations:
>   appgw.ingress.kubernetes.io/backend-path-prefix:  /resources/
>   kubernetes.io/ingress.class:                      azure/application-gateway
> Events:                                             <none>
> 

kubectl describe service resources-ilb-backend -n resourcesilb
> Name:              resources-ilb-backend
> Namespace:         resourcesilb
> Labels:            name=resources-ilb-backend
> Annotations:       <none>
> Selector:          app=resources-ilb-backend
> Type:              ClusterIP
> IP:                10.95.24.35
> Port:              http  80/TCP
> TargetPort:        8001/TCP
> Endpoints:         10.193.49.42:8001,10.193.49.58:8001
> Port:              https  443/TCP
> TargetPort:        44345/TCP
> Endpoints:         10.193.49.42:44345,10.193.49.58:44345
> Session Affinity:  None
> Events:            <none>

**Expected Result**
Below CURL command - should return the result 200 OK but it throws 502 error:-
```
curl -v http://10.193.48.135/resources/swagger/index.html
*   Trying 10.193.48.135...
* TCP_NODELAY set
* Connected to 10.193.48.135 (10.193.48.135) port 80 (#0)
> GET /resources/swagger/index.html HTTP/1.1
> Host: 10.193.48.135
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 502 Bad Gateway
< Server: Microsoft-Azure-Application-Gateway/v2
< Date: Sat, 20 Jun 2020 06:18:57 GMT
< Content-Type: text/html
< Content-Length: 183
< Connection: keep-alive 
```
PS: Services are running fine, if I execute the below CURL command from any of the container , it returns result :-
curl http://resources-ilb-backend/swagger/index.html

Ingress Running
kubectl get ingresses -o wide -n resourcesilb
```
NAME                            HOSTS   ADDRESS         PORTS   AGE
resources-ilb-backend-ingress   *       10.193.48.135   80      19m

```
Services Running
kubectl get services -o wide -n resourcesilb
```
NAME                    TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)          AGE   SELECTOR
resources-ilb-backend   ClusterIP   10.95.24.35   <none>        80/TCP,443/TCP   19m   app=resources-ilb-backend
```
Containers Running
kubectl get pod -o wide -n resourcesilb
```
NAME                                    READY   STATUS    RESTARTS   AGE   IP             NODE              NOMINATED NODE   READINESS GATES
resources-ilb-backend-5574c74dc-pwmc8   1/1     Running   1          19m   10.193.49.42   aksakswin000000   <none>           <none>
resources-ilb-backend-5574c74dc-xxgqb   1/1     Running   1          19m   10.193.49.58   aksakswin000000   <none>           <none>

```
Any help is appreciated.
Thanks

**Comment by fortanu82** [comment]
To test Whether or not application deployed working fine, the URL to test is - 
http;//Cluster-IP/swagger/index.html , which is - http://10.95.24.35/swagger/index.html

In Ingress file, I have defined a path as **path -/resources/** and to test it using application-gateway private ip , I called the URL as **http://app-gateway-private-ip/resources/swagger/index.html** file that is - http://10.193.48.135/resources/swagger/index.html

I hope the way its defined in ingress file is correct as the above URL will be resolved to **http://10.193.48.135/swagger/index.html**

**Comment by 3quanfeng** [comment]
Hi @fortanu82 , it seems like your service target port doesn't refer the container port.

**Comment by fortanu82** [comment]
Thanks for your response. I am curious to know in this case, how the service is able to retrieve the result when directly called from the container.
**Called from Service-Name**
![image](https://user-images.githubusercontent.com/48510516/85259749-31f5d300-b487-11ea-8282-8d2a6d5b3a40.png)
**Called from IP**
![image](https://user-images.githubusercontent.com/48510516/85259483-c7449780-b486-11ea-818b-45f1c2cf9ad6.png)

**Comment by fortanu82** [comment]
Hi @3quanfeng, related to your response, one more thing I noticed, if we describe the ingress manifest, it shows the service is associated with the container ports. 

![image](https://user-images.githubusercontent.com/48510516/85275995-c1f34700-b49e-11ea-8b48-3eaefb0842c4.png)

**Comment by 3quanfeng** [comment]
Hi @fortanu82 , I think that's because you specify 8001 as target port in your service spec.
To fix your problem, there are two ways:
1. update the targetPort to be an integer 80
2. updater the targetPort to be a string "http" which is the port name you defined in your deployment for you container

**Comment by fortanu82** [comment]
Hi @3quanfeng , this is the solution I applied. 

Application URL is – http://hostname(dns)/swagger/index.html. 

After applying the below changes:-
If I hit the URL as - http://hostname(dns)/resources, backend path prefix converts the URL to - http://10.193.48.135/swagger/index.html and returns the result.  Is there any better way of doing this:-

![image](https://user-images.githubusercontent.com/48510516/85374150-f83dce80-b551-11ea-80c9-db98e541a3bc.png)

**Comment by 3quanfeng** [comment]
Hi @fortanu82 , the above is by design, or you could do:
path:/resource/index.html but specify /swagger in backend-path-prefix annotation.
Or what did you mean by better way?

**Comment by rezarms** [comment]
I have still the same issue.
The workaround didn't work either.
I get below error:
Bad Gateway /swagger/v1/swagger.json
but when I hit  http://myipd/swagger/v1/swagger.json it works but UI doesn't work

**Comment by rezarms** [comment]
We found the solution.
In the application we changed swagger url to use relative path so we didn't need to use path-prefix solution.
