### ISSUE TITLE
AGIC cannot add listener for *.domain.com to App Gateway?

### ISSUE THREAD

**Issue by MarcelT-NL** [Azure/application-gateway-kubernetes-ingress#922]
**Describe the bug**
I am trying to use AGIC to provision a wildcard subdomain *.domain.com, but the App Gateway rejects the * in the listener name (created by AGIC).

**To Reproduce**
1. Run an App Gatewaywith WAF_v2, AGIC works fine for sub1.domain1.com
2. Create ingress controller with host: '*.domain2.com'
3. Creation of listener fails: "Invalid listener name. Must start with character word"

It looks like App Gateway does not accept the * as part of the listener name.
I can't find an annotation or any other field that allows me to overwrite the listener name.

What am I missing here?

**Comment by akshaysngupta** [comment]
@MarcelT-NL Can you check if you are using AGIC version `1.2.0-rc3`.
If not, you can find the steps here.
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/CHANGELOG/CHANGELOG-1.2.md#how-to-try

**Comment by akshaysngupta** [comment]
@MarcelT-NL Please install AGIC version `1.2.0` which should be able to support wildcards in listeners.
Please reopen this issue if you need any help.

**Comment by davejhahn** [comment]
@akshaysngupta what I get using a wildcard, e.g. *.mydomain.com, with 1.2.0, is  Error: cannot load values.yaml: error converting YAML to JSON: yaml: line 56: did not find expected alphabetic or numeric character.  

I've tried enclosing the value in double quotes when passed in to my helm chart, e.g.  ingress.hosts[0]="*.mydomain.com" and also in the ingress template, adding double quotes, e.g. - host: "{{ . }}" and each individually, and still get this error.

**Comment by davejhahn** [comment]
Never mind!  I had a default value in my values file, hosts, e.g. - *.mydomain.com,  I added double quotes to that and it works.  Weird since I am replacing that for what I pass in, it must evaluate it before or something.
