### ISSUE TITLE
Unable to install application-gateway-kubernetes-ingress/ingress-azure Using HELM

### ISSUE THREAD

**Issue by Yiyito11** [Azure/application-gateway-kubernetes-ingress#923]
Hey guys I´m having this error while creating ingress controller with helm:

```
helm install -f  helm-dev.yml application-gateway-kubernetes-ingress/ingress-azure --generate-name
Error: apiVersion "apps/v1beta2" in ingress-azure/templates/deployment.yaml is not available
```
This is first time I´m having this issue with Helm 3 Version. Already installed it with no issues some weeks ago. 

k8s Version is: 1.16.8

Helm yml was downloaded from [here](https://azure.github.io/application-gateway-kubernetes-ingress/setup/install-existing/). In step 2 of : **Install Ingress Controller as a Helm Chart**

Is there a new issue? Was reading this [document](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) and it´s suggesting to change yml file,  but no api version is specified in this Helm YML file I just downloaded.-

thanks!

**Comment by rlevchenko** [comment]
You are definitely using wrong/old helm charts. Check the history of the [deployment.yaml ](https://github.com/Azure/application-gateway-kubernetes-ingress/commit/5710a69e0e17947b2ac303664fddfc7188ae2d51#diff-86d90b1e65a78d1a1ba08a0f7051bb91) and you can find out there was a commit that updates v1beta2 to v1 api version. In short, you can use helm charts from the [repo](https://github.com/Azure/application-gateway-kubernetes-ingress/tree/master/helm)

**Comment by akshaysngupta** [comment]
Correct. This issue is resolved in the latest RC - 1.2.0-rc3.

**Comment by Yiyito11** [comment]
thanks guys that was the issue. I though that by default you got the latest version. I tried first with : `helm search -l application-gateway-kubernetes-ingress` to check available versions  but in HELM 3 this is not working anymore .

**Comment by akshaysngupta** [comment]
Helm 3 requires `--devel` flag for listing RC/beta releases.
