### ISSUE TITLE
Issues with installing azureingressprohibitedtarget crd on Azure k8s v1.16.9

### ISSUE THREAD

**Issue by gavinwakeley1** [Azure/application-gateway-kubernetes-ingress#929]
**Describe the bug**
After upgrading our Azure k8s cluster to v1.16.9 (current version) we are unable to use the existing helm crd for AzureIngressProhibitedTargets due to various errors.

1) The graph initially failed to apply due to the api version being set to v1beta1. This was changed back to v1 based on online recommendations

Next the problem appeared to be to do with the fact that a crd_hook was specified in the existing code that was not supported in helm v3. This was removed as a template and added into a /crd folder in the chart.

2) The format of the crd was then reported as incorrect with the following error:

Error: failed to install CRD crds/azureingressprohibitedtarget.yaml: CustomResourceDefinition.apiextnsions.k8s.io "azureingressprohibitedtargets.appgw.ingress.k8s.io" is invalid: [spec.versions: Invald value: []apiextensions.CustomResourceDefinitionVersion(nil): must have exactly one version marked s storage version, status.storedVersions: Invalid value: []string(nil): must have at least one store version, metadata.annotations[api-approved.kubernetes.io]: Required value: protected groups must hae approval

3) After following an online example (https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/) all the errors were cleared up except

'protected groups must have approval annotation "api-approved.kubernetes.io", see https://github.com/kubernetes/enhancements/pull/1111'

This appears to be a problem due to the use of the ingress.k8s.io namespace. This is preventing us deploying AzureIngressProhibitedTargets to our cluster. Can you advise if there is a workaround or if we will need to wait until the next release?

- Cluster k8s version: v1.16.9
- Api version: v1
- AGIC version: v1.2.0 (also tried v1.2.0-rc3)
- Helm version: v3.2.3

To Reproduce:
Attempt to install crd for AzureIngressProhibitedTargets on versions above

**Comment by 3quanfeng** [comment]
Hi @gavinwakeley1 , may I ask the AGIC version you used? we have a fix to install CRD via helm3 in 1.2.0-rc2

**Comment by gavinwakeley1** [comment]
Hi @3quanfeng , yes indeed it is 1.2.0-rc3 so that would be brilliant - thank you!
Typo on my 'versions' list at the end of my post - corrected now.

**Comment by gavinwakeley1** [comment]
Hello, please can anyone help with this issue? It is causing us issues with using this in our production environment.
Thank you for any assistance you can give.
Kind Regards,
Gavin
