### ISSUE TITLE
Add Release.Namespace to chart templates

### ISSUE THREAD

**Issue by dan-jackson-github** [Azure/application-gateway-kubernetes-ingress#93]
I am deploying this chart using helm template and kubectl apply (we do not use Tiller). I'd like to be able to deploy this controller into a namespace other than default. But without the {{ Release.Namespace }} in the helm charts I cannot see a way of doing this cleanly. Therefore, would it be possible to add this functionality into the template, then running Helm template --namespace <namespace_name> would give me what I need. Unless there is another way to achieve this, for now I have forked the repo.

**Comment by asridharan** [comment]
@dan-jackson-github do you want to create a PR against this repo? Would be helpful.

**Comment by dan-jackson-github** [comment]
hi @asridharan will take a look at submitting something, I can't fully test though as I am not using Tiller which is reason for forking.

**Comment by pallxk** [comment]
What about

```
helm template $chart | kubectl apply --namespace $ns -f-
```

**Comment by dan-jackson-github** [comment]
Thanks @pallxk I hadn't thought about doing it that way!
