### ISSUE TITLE
504 - Gateway Timeout Error on every deployment

### ISSUE THREAD

**Issue by nreddipalle** [Azure/application-gateway-kubernetes-ingress#933]
**Describe the bug**
Performing a rolling update via AKS deployment causing 504 Gateway Timeout Error(s). Backend Pool seems to be updated with latest Pod IP's instantly but the endpoint throws 504.. The app is coming up only after 3-4 min. Any other Config I am missing.. I configured the preStop lifecycle hook along with terminationGracePeriodSeconds

lifecycle:
            preStop:
              exec:
                command: ["timeout","90"]

terminationGracePeriodSeconds: 101

Configured Ingress annotations:
   ```
    kubernetes.io/ingress.class: "azure/application-gateway"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "120"
    appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
    appgw.ingress.kubernetes.io/request-timeout: "120"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "appservcert"
```

**To Reproduce**

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
* Output of `kubectl logs <ingress controller>. 
* Any Azure support tickets associated with this issue.

**Comment by 3quanfeng** [comment]
Hi @nreddipalle , sorry for late response, are you still running into the same issue when you do rolling update?
could you help try it with cookie-based-affinity disabled to see if you have the same issue?

**Comment by nreddipalle** [comment]
This is good now after following the steps stated here..  https://azure.github.io/application-gateway-kubernetes-ingress/how-tos/minimize-downtime-during-deployments/
