### ISSUE TITLE
AppGw configs lost after redeploying with ARM

### ISSUE THREAD

**Issue by mhsh64** [Azure/application-gateway-kubernetes-ingress#937]
**Describe the bug**
As per https://github.com/Azure/application-gateway-kubernetes-ingress/issues/866 the appGW configurations lost after redeploying the appGW through ARM. In that issue, it has been suggested to use the following in agic configs:

reconcilePeriodSeconds=30

However, even using the above field cause an outage for ingress resources, since it takes time to agic to reconfigure listeners, rules , etc on redeployed appGW. 

Also I observed sth worse:

Even by using reconcilePeriodSeconds , I saw the appGW redeployment fails because the running agic tries to connect to appgw and cancel any operations on it. Not even this, agic is also failing, because appgw started to redeploy and it lost all its settings, even the managed identity assigned to it.

 
I tried to use an empty properties for ARM during deployment, although this document https://docs.microsoft.com/en-us/azure/templates/microsoft.network/applicationgateways#applicationgatewaypropertiesformat-object

 says  the properties are not mandatory, however, it fails and in arm validation it says the backendpools, listedners etc are required. So this trick does not work at all.

Please help on this since it is a blocker in our environment 
**To Reproduce**

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
* Output of `kubectl logs <ingress controller>. 
* Any Azure support tickets associated with this issue.

**Comment by wyp84** [comment]
We have the same issue here, would be nice to have a production ready solution for this.

**Comment by fadamsen** [comment]
Same issue here, this prevents us from using Azure Application Gateway.
