### ISSUE TITLE
AGIC Issue : "Authentication failed. The 'Authorization' header is missing."

### ISSUE THREAD

**Issue by shubhammicrosoft1** [Azure/application-gateway-kubernetes-ingress#938]
**Describe the bug**
We have configured the Application gateway ingress controller as per supported docs. However when we are using ServicePrincipal , the Ingress controller pod is not getting started & is reporting below error
We have the Service Principal already configured & has Contributor rights on the subscription

E0702 17:36:18.353628       1 client.go:170] Code="ErrorApplicationGatewayUnexpectedStatusCode" Message="Unexpected status code '401' while performing a GET on Application Gateway." InnerError="network.ApplicationGatewaysClient#Get: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="AuthenticationFailed" Message="Authentication failed. The 'Authorization' header is missing.""
I0702 17:36:18.353661       1 retry.go:33] Retrying in 10s
E0702 17:36:28.441377       1 client.go:170] Code="ErrorApplicationGatewayUnexpectedStatusCode" Message="Unexpected status code '401' while performing a GET on Application Gateway." InnerError="network.ApplicationGatewaysClient#Get: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="AuthenticationFailed" Message="Authentication failed. The 'Authorization' header is missing.""
I0702 17:36:28.441414       1 retry.go:33] Retrying in 10s
E0702 17:36:38.497708       1 client.go:170] Code="ErrorApplicationGatewayUnexpectedStatusCode" Message="Unexpected status code '401' while performing a GET on Application Gateway." InnerError="network.ApplicationGatewaysClient#Get: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="AuthenticationFailed" Message="Authentication failed. The 'Authorization' header is missing.""
I0702 17:36:38.497746       1 retry.go:33] Retrying in 10s
E0702 17:36:48.551356       1 client.go:170] Code="ErrorApplicationGatewayUnexpectedStatusCode" Message="Unexpected status code '401' while performing a GET on Application Gateway." InnerError="network.ApplicationGatewaysClient#Get: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="AuthenticationFailed" Message="Authentication failed. The 'Authorization' header is missing.""
I0702 17:36:48.551387       1 retry.go:33] Retrying in 10s
E0702 17:36:58.608318       1 client.go:170] Code="ErrorApplicationGatewayUnexpectedStatusCode" Message="Unexpected status code '401' while performing a GET on Application Gateway." InnerError="network.ApplicationGatewaysClient#Get: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="AuthenticationFailed" Message="Authentication failed. The 'Authorization' header is missing.""
I0702 17:36:58.608350       1 retry.go:33] Retrying in 10s

**To Reproduce**

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 

* Output of `kubectl logs <ingress controller>. 

E0702 17:36:18.353628       1 client.go:170] Code="ErrorApplicationGatewayUnexpectedStatusCode" Message="Unexpected status code '401' while performing a GET on Application Gateway." InnerError="network.ApplicationGatewaysClient#Get: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="AuthenticationFailed" Message="Authentication failed. The 'Authorization' header is missing.""
I0702 17:36:18.353661       1 retry.go:33] Retrying in 10s
E0702 17:36:28.441377       1 client.go:170] Code="ErrorApplicationGatewayUnexpectedStatusCode" Message="Unexpected status code '401' while performing a GET on Application Gateway." InnerError="network.ApplicationGatewaysClient#Get: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="AuthenticationFailed" Message="Authentication failed. The 'Authorization' header is missing.""
I0702 17:36:28.441414       1 retry.go:33] Retrying in 10s
E0702 17:36:38.497708       1 client.go:170] Code="ErrorApplicationGatewayUnexpectedStatusCode" Message="Unexpected status code '401' while performing a GET on Application Gateway." InnerError="network.ApplicationGatewaysClient#Get: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="AuthenticationFailed" Message="Authentication failed. The 'Authorization' header is missing.""
I0702 17:36:38.497746       1 retry.go:33] Retrying in 10s
E0702 17:36:48.551356       1 client.go:170] Code="ErrorApplicationGatewayUnexpectedStatusCode" Message="Unexpected status code '401' while performing a GET on Application Gateway." InnerError="network.ApplicationGatewaysClient#Get: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="AuthenticationFailed" Message="Authentication failed. The 'Authorization' header is missing.""
I0702 17:36:48.551387       1 retry.go:33] Retrying in 10s
E0702 17:36:58.608318       1 client.go:170] Code="ErrorApplicationGatewayUnexpectedStatusCode" Message="Unexpected status code '401' while performing a GET on Application Gateway." InnerError="network.ApplicationGatewaysClient#Get: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="AuthenticationFailed" Message="Authentication failed. The 'Authorization' header is missing.""
I0702 17:36:58.608350       1 retry.go:33] Retrying in 10s

* Any Azure support tickets associated with this issue.

**Comment by akshaysngupta** [comment]
@shubhammicrosoft1 Thanks for reporting.

When using service principal method, a secret in the k8s cluster which stores the information about the service principal: clientID/cientSecret/tenantId etc. This secret is then mounted as a file on to the AGIC pod and used to communicating with Azure.
As a sanity check, can you check that the secret is having the information I mentioned above. Also, can you check that the AGIC pod is having this secret properly mounted ?

**Comment by shubhammicrosoft1** [comment]
Hi @akshaysngupta : Sure , so right now we are using helm configuration file to pass base64 secret to AGIC pod.
Please let us know if you need some logs which can help you in isolating the issue

**Comment by akshaysngupta** [comment]
@shubhammicrosoft1 
1. can you check that the secret is having the information I mentioned above.
1. can you check that the AGIC pod is having this secret properly mounted ?
1. Did you try deleting the AGIC pod and seeing if the issue persist ?

**Comment by akshaysngupta** [comment]
@shubhammicrosoft1 are you still facing this issue ?

**Comment by shubhammicrosoft1** [comment]
Hi @akshaysngupta , one question is that when i upgraded the cluster to a newer version, it seems to be working.
Is there a dependency on version as well ?

**Comment by akshaysngupta** [comment]
There shouldn't be any dependency issue with 1.16 and AGIC version 1.2.0 at least in terms of authentication.

**Comment by shubhammicrosoft1** [comment]
Ok , i am closing the same now. Thankss again
