### ISSUE TITLE
Integration with Azure DNS Zone

### ISSUE THREAD

**Issue by Mahesh-MSFT** [Azure/application-gateway-kubernetes-ingress#949]
There is [guidance](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/how-tos/dns.md) available to automate DNS updates. However, from that guidance it is not clear if the domain delegation is a pre-requisite for it to work.

[HTTP Application routing for AKS](https://docs.microsoft.com/en-us/azure/aks/http-application-routing) currently supports configuring Azure DNS Zone out of the box including domain delegation configuration.

Is AGIC going to implement out-of-the-box configuration for Azure DNS Zone just like HTTP Application routing?
Or is it already supported and I am missing a trick?

**Comment by flyboarder** [comment]
use external-dns for dns updates

**Comment by akshaysngupta** [comment]
Duplicate https://github.com/Azure/application-gateway-kubernetes-ingress/issues/615
