### ISSUE TITLE
Annotation for Backend Hostname NOT WORKING

### ISSUE THREAD

**Issue by edervaldonetoMS** [Azure/application-gateway-kubernetes-ingress#952]
**Describe the bug**
We have tried to add the annotation **appgw.ingress.kubernetes.io/backend-hostname: "internal.example.com"** and seems to be not working.

![image](https://user-images.githubusercontent.com/56553626/88173116-f2eba680-cc19-11ea-95c0-705ecbda4946.png)

**To Reproduce**

apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"app":"aspnetapp"},"name":"aspnetapp","namespace":"default"},"spec":{"containers":[{"image":"mcr.microsoft.com/dotnet/core/samples:aspnetapp","name":"aspnetapp-image","ports":[{"containerPort":80,"protocol":"TCP"}]}]}}
  creationTimestamp: "2020-07-22T09:30:16Z"
  labels:
    app: aspnetapp
  name: aspnetapp
  namespace: default
  resourceVersion: "1428"
  selfLink: /api/v1/namespaces/default/pods/aspnetapp
  uid: 2482b047-7506-486e-87ed-46c4f6cd75d9
spec:
  containers:
  - image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
    imagePullPolicy: IfNotPresent
    name: aspnetapp-image
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-7nrp4
      readOnly: true
    readinessProbe:
      httpGet:
        port: 80
        path: /
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 2
      successThreshold: 1
      failureThreshold: 3
    livenessProbe:
      httpGet:
        port: 80
        path: /
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 2
      successThreshold: 1
      failureThreshold: 3
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-agentpool-35064155-2
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-7nrp4
    secret:
      defaultMode: 420
      secretName: default-token-7nrp4
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-07-22T09:30:16Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-07-22T09:30:26Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-07-22T09:30:26Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-07-22T09:30:16Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://f78055599bc7d1e198f8f05d385e61802479d67d55bf567835fe343210b88e3b
    image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
    imageID: docker-pullable://mcr.microsoft.com/dotnet/core/samples@sha256:2ff90b7484a2f1a5bcadab5c5720ea0e231ed1a1ec82a6014ff4f792d7b76cac
    lastState: {}
    name: aspnetapp-image
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2020-07-22T09:30:25Z"
  hostIP: 10.0.0.35
  phase: Running
  podIP: 10.0.0.61
  qosClass: BestEffort
  startTime: "2020-07-22T09:30:16Z"

**Ingress Controller details**

Name:           ingress-azure-db7567987-998hd
Namespace:      default
Priority:       0
Node:           aks-agentpool-35064155-0/10.0.0.4
Start Time:     Wed, 22 Jul 2020 10:29:29 +0100
Labels:         aadpodidbinding=ingress-azure
                app=ingress-azure
                pod-template-hash=db7567987
                release=ingress-azure
Annotations:    prometheus.io/port: 8123
                prometheus.io/scrape: true
Status:         Running
IP:             10.0.0.14
IPs:            <none>
Controlled By:  ReplicaSet/ingress-azure-db7567987
Containers:
  ingress-azure:
    Container ID:   docker://1aa3234decb4a0ea2c45e94f8390927e432fb3efa1e6b041e3da69575c7fb734
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.0.0
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:c295f99ae66443c5a392fd894620fcd1fc313b9efdec96d13f166fefb29780a9
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 22 Jul 2020 10:29:40 +0100
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_CONTEXT_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:           ingress-azure-db7567987-998hd (v1:metadata.name)
      AGIC_POD_NAMESPACE:      default (v1:metadata.namespace)
    Mounts:
      /etc/appgw/azure.json from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-azure-token-t8lsd (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  ingress-azure-token-t8lsd:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-azure-token-t8lsd
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

**YAML of Ingress **

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/backend-hostname: www.edervaldo2.com
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"azure/application-gateway"},"name":"aspnetapp","namespace":"default"},"spec":{"rules":[{"http":{"paths":[{"backend":{"serviceName":"aspnetapp","servicePort":80},"path":"/"}]}}]}}
    kubernetes.io/ingress.class: azure/application-gateway
  creationTimestamp: "2020-07-22T09:30:16Z"
  generation: 5
  name: aspnetapp
  namespace: default
  resourceVersion: "15697"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/aspnetapp
  uid: eac6f094-4c42-4734-8416-6f44936a6289
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: aspnetapp
          servicePort: 80
        path: /
status:
  loadBalancer:
    ingress:
    - ip: 52.149.109.92

** LOGS**

ERROR: logging before flag.Parse: I0722 09:29:40.555555       1 main.go:302] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0722 09:29:40.597669       1 environment.go:168] KUBERNETES_WATCHNAMESPACE is not set. Watching all available namespaces.
I0722 09:29:40.597715       1 main.go:132] App Gateway Details: Subscription: e54f260a-1a3a-4d8f-ba4a-06f008ac2f62, Resource Group: MyResourceGroup, Name: applicationgateway71d3
I0722 09:29:40.597726       1 auth.go:90] Creating authorizer from Azure Managed Service Identity
I0722 09:29:46.568023       1 main.go:179] Ingress Controller will observe all namespaces.
I0722 09:29:46.604860       1 context.go:129] k8s context run started
I0722 09:29:46.604930       1 context.go:168] Waiting for initial cache sync
I0722 09:29:46.705299       1 context.go:176] Initial cache sync done
I0722 09:29:46.705333       1 context.go:177] k8s context run finished
I0722 09:29:46.705542       1 worker.go:35] Worker started
I0722 09:29:46.705636       1 httpserver.go:57] Starting API Server on :8123
I0722 09:29:46.913044       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment
I0722 09:30:07.412228       1 mutate_app_gateway.go:182] Applied App Gateway config in 20.499145568s
I0722 09:30:07.412273       1 mutate_app_gateway.go:198] cache: Updated with latest applied config.
I0722 09:30:07.413013       1 mutate_app_gateway.go:203] END AppGateway deployment
I0722 09:30:16.422551       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment
I0722 09:30:37.105487       1 mutate_app_gateway.go:182] Applied App Gateway config in 20.682879615s
I0722 09:30:37.105529       1 mutate_app_gateway.go:198] cache: Updated with latest applied config.
I0722 09:30:37.106226       1 mutate_app_gateway.go:203] END AppGateway deployment
I0722 09:30:38.192922       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment
I0722 09:30:58.729120       1 mutate_app_gateway.go:182] Applied App Gateway config in 20.536165765s
I0722 09:30:58.729153       1 mutate_app_gateway.go:198] cache: Updated with latest applied config.
I0722 09:30:58.730069       1 mutate_app_gateway.go:203] END AppGateway deployment
I0722 09:57:19.708106       1 mutate_app_gateway.go:150] cache: Config has NOT changed! No need to connect to ARM.
I0722 09:59:08.855132       1 mutate_app_gateway.go:150] cache: Config has NOT changed! No need to connect to ARM.
I0722 10:55:25.185859       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment
I0722 10:56:05.922381       1 mutate_app_gateway.go:182] Applied App Gateway config in 40.73647568s
I0722 10:56:05.922425       1 mutate_app_gateway.go:198] cache: Updated with latest applied config.
I0722 10:56:05.924044       1 mutate_app_gateway.go:203] END AppGateway deployment
I0722 11:06:02.479452       1 mutate_app_gateway.go:150] cache: Config has NOT changed! No need to connect to ARM.
I0722 11:06:52.382955       1 mutate_app_gateway.go:150] cache: Config has NOT changed! No need to connect to ARM.
I0722 11:09:28.940301       1 mutate_app_gateway.go:150] cache: Config has NOT changed! No need to connect to ARM.
I0722 11:11:23.281205       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment
I0722 11:12:03.969789       1 mutate_app_gateway.go:182] Applied App Gateway config in 40.688532874s
I0722 11:12:03.969830       1 mutate_app_gateway.go:198] cache: Updated with latest applied config.
I0722 11:12:03.970570       1 mutate_app_gateway.go:203] END AppGateway deployment
I0722 11:25:22.019056       1 mutate_app_gateway.go:150] cache: Config has NOT changed! No need to connect to ARM.
I0722 11:26:03.213703       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment
I0722 11:26:23.759430       1 mutate_app_gateway.go:182] Applied App Gateway config in 20.545693037s
I0722 11:26:23.759465       1 mutate_app_gateway.go:198] cache: Updated with latest applied config.
I0722 11:26:23.759989       1 mutate_app_gateway.go:203] END AppGateway deployment
I0722 11:35:59.863944       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment
I0722 11:36:20.718805       1 mutate_app_gateway.go:182] Applied App Gateway config in 20.854821799s
I0722 11:36:20.718851       1 mutate_app_gateway.go:198] cache: Updated with latest applied config.
I0722 11:36:20.719564       1 mutate_app_gateway.go:203] END AppGateway deployment
I0722 11:36:21.835334       1 mutate_app_gateway.go:150] cache: Config has NOT changed! No need to connect to ARM.
I0722 11:36:48.084717       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment
I0722 11:37:08.592690       1 mutate_app_gateway.go:182] Applied App Gateway config in 20.507941477s
I0722 11:37:08.592722       1 mutate_app_gateway.go:198] cache: Updated with latest applied config.
I0722 11:37:08.593208       1 mutate_app_gateway.go:203] END AppGateway deployment
I0722 11:37:09.690251       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment
I0722 11:37:30.282458       1 mutate_app_gateway.go:182] Applied App Gateway config in 20.592172692s
I0722 11:37:30.282493       1 mutate_app_gateway.go:198] cache: Updated with latest applied config.
I0722 11:37:30.283022       1 mutate_app_gateway.go:203] END AppGateway deployment
I0722 11:38:41.673807       1 mutate_app_gateway.go:150] cache: Config has NOT changed! No need to connect to ARM.
I0722 11:41:26.630335       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment
I0722 11:41:47.288660       1 mutate_app_gateway.go:182] Applied App Gateway config in 20.658286674s
I0722 11:41:47.288692       1 mutate_app_gateway.go:198] cache: Updated with latest applied config.
I0722 11:41:47.289219       1 mutate_app_gateway.go:203] END AppGateway deployment
I0722 11:44:41.639763       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment
I0722 11:45:02.337835       1 mutate_app_gateway.go:182] Applied App Gateway config in 20.69803462s
I0722 11:45:02.337879       1 mutate_app_gateway.go:198] cache: Updated with latest applied config.
I0722 11:45:02.338569       1 mutate_app_gateway.go:203] END AppGateway deployment
I0722 11:45:03.443262       1 mutate_app_gateway.go:154] BEGIN AppGateway deployment
I0722 11:46:14.240657       1 mutate_app_gateway.go:182] Applied App Gateway config in 1m10.797349552s
I0722 11:46:14.240696       1 mutate_app_gateway.go:198] cache: Updated with latest applied config.
I0722 11:46:14.241447       1 mutate_app_gateway.go:203] END AppGateway deployment
I0722 11:46:15.354236       1 mutate_app_gateway.go:150] cache: Config has NOT changed! No need to connect to ARM.

**Comment by akshaysngupta** [comment]
@edervaldonetoMS This annotation was added in version `1.2.0`. Please upgrade your AGIC installation.
