### ISSUE TITLE
New Annotation to pick the host name from Backend

### ISSUE THREAD

**Issue by edervaldonetoMS** [Azure/application-gateway-kubernetes-ingress#953]
Could you please add the feature new "annotations"  so the customer can choose to use the hostname from backend.

https://docs.microsoft.com/en-us/azure/application-gateway/configuration-overview#pick

The customer want to use the hostname in the rule of ingress but he also want to use the POD IP as backend health probe.

**Comment by akshaysngupta** [comment]
@edervaldonetoMS can you elaborate more on the use-case ?

**Comment by edervaldonetoMS** [comment]
@akshaysngupta 
resolved using version **1.2.0** agic. thanks. You can close it.
