### ISSUE TITLE
Syncing with AppGateway Configured Through Terraform

### ISSUE THREAD

**Issue by davejhahn** [Azure/application-gateway-kubernetes-ingress#959]
I create App Gateway with Terraform.  Initially, it has default rules, because it requires at least one rule for most of the resource types.  The subsequent rules, backends, etc... that are added to App Gateway come from AGIC as applications are deployed. 

What I found, which is expected, when I redeploy my Terraform project, it wipes out all of the AGIC controlled rules.   It also never syncs them back, unless, which is the only way I found to make it sync, is to delete a release (e.g. helm delete), where they almost instantly get added back, minus the one of course that I've deleted.  So my workaround if I need to redeploy the Terraform project is to delete an app release and redeploy.

I'm sure others have run into this.  I guess I would like to see Terraform handle these differently, not sure how, I know I've seen at least one request asking to be able to separate them out of the main azurerm_application_gateway resource block.  But this isn't the Terraform project, so I can't ask for that!

Has anyone run into this and come up with an elegant way of handling it?  Really the only thing that I can think of is somehow having AGIC update my Terraform project, which is not elegant, and likely more destructive.  I am also looking at pulling out the App Gateway from my core Terraform project so I can re-run the Terraform project without worrying about AppGateway, but there are some dependencies between Vnet, Roles, AKS, that I'd have to get right and then sequence running them on any initial create, which I suppose isn't terrible, but in the end it doesn't solve the problem, just separates it.

What I'd like to see, at least, is re-syncing the AGIC rules back into App Gateway if they don't exist, without forcing it by deleting a release.  This is still destructive.   Outside of this, it's more of a Terraform thing, which I will throw some comments in the repo also.

**Comment by akshaysngupta** [comment]
@davejhahn we added the ability to [reconcile](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/features/agic-reconcile.md) (beta) in the last release. Can you give that shot and provide feedback ?

**Comment by davejhahn** [comment]
@akshaysngupta Absolutely!  Will give it a try and let you know.

**Comment by davejhahn** [comment]
@akshaysngupta I was able to test--blew away an application gateway, added back, no rules, then it refreshed everything.  So, that is a great capability.  

I would add though, it is great for non-production, when it comes to production, it's still a huge problem but I think that is something that the Terraform resource will need to handle though (and don't blame it on the AGIC at all).  

I did create an issue on this https://github.com/terraform-providers/terraform-provider-azurerm/issues/7935 for reference if anyone else would care to upvote it.  

Thanks!

**Comment by JorTurFer** [comment]
Hi @davejhahn ,
This is documented in terraform docs but is not explicit... The problem is that the real state of the agw doesn't match with the desired state in the terraform files so terraform will "fix" the differences.
When you deploy agw with terraform, you have to add some ignores in the terraform files in order to skip the lifecycle manage. You should add this in you _azurerm_application_gateway_:
```terraform
resource "azurerm_application_gateway" "agw" {
  name                = ...
  ...

  lifecycle {
    ignore_changes = [
      tags,
      ssl_certificate,
      trusted_root_certificate,
      frontend_port,
      backend_address_pool,
      backend_http_settings,
      http_listener,
      url_path_map,
      request_routing_rule,
      probe,
      redirect_configuration,
      ssl_policy,
    ]
  }
}
```

With this ignores, terraform will skip consolidation of the differences in subresources during the terraform apply

**Comment by davejhahn** [comment]
@JorTurFer I will try it out, I think I misunderstood how the ignore_changes works...based on what you are presenting, all blocks listed will be ignored for updates entirely, which is exactly what I want.

**Comment by JorTurFer** [comment]
@davejhahn 
When you add a ignore to any item, all changes over that item will be ignored after creation. I use the ignores that I pasted in my deployments with agic. In the same way for example, if your cluster has autoscale for the nodes, you should add the properly ignore to the node count

**Comment by davejhahn** [comment]
@JorTurFer I was able to get it working wonderfully, thanks for your help, appreciate it.
