### ISSUE TITLE
Let's Encrypt Ingtegration

### ISSUE THREAD

**Issue by dan-jackson-github** [Azure/application-gateway-kubernetes-ingress#96]
Hi, is there any plans to provide let's encrypt integration with this ingress controller? I.e. when you setup the ingress, rather than storing the certificate details as a manual step, the ingress integrates with the let's encrypt service for certificate creation and renewal. I think there is already a cert manager pod that does that the nginx ingress controller works well with

**Comment by asridharan** [comment]
Thanks @dan-jackson-github will take a look.

**Comment by ct-appcenter** [comment]
hey @asridharan,

As far as I could configure the appgw-ingress integrates with cert-manager. 
But It gets an error to configure applicationn gateway rules. With that the certificate generation fails.

Application gateway logs
```
ERROR: logging before flag.Parse: I0417 00:04:41.462075       1 controller.go:98] ~~~~~~~~ ↓ ApplicationGateway deployment ↓ ~~~~~~~~
ERROR: logging before flag.Parse: W0417 00:04:41.617271       1 controller.go:105] unable to send CreateOrUpdate request, error [network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidResourceName" Message="Resource name k8s-ag-ingress-ktn-cm-acme-http-solver-j7sxh-8089-bp-8089-cm-acme-http-solver-t8rnf is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'." Details=[]]
ERROR: logging before flag.Parse: I0417 00:04:41.617341       1 controller.go:106] ~~~~~~~~ ↑ ApplicationGateway deployment ↑ ~~~~~~~~
```

Is it possible to trim the value to ensure the 80 characters limit ?

**Comment by marceldiass** [comment]
hey @asridharan,

As far as I could configure the appgw-ingress integrates with cert-manager. 
But It gets an error to configure applicationn gateway rules. With that the certificate generation fails.

Application gateway logs
```
ERROR: logging before flag.Parse: I0417 00:04:41.462075       1 controller.go:98] ~~~~~~~~ ↓ ApplicationGateway deployment ↓ ~~~~~~~~
ERROR: logging before flag.Parse: W0417 00:04:41.617271       1 controller.go:105] unable to send CreateOrUpdate request, error [network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidResourceName" Message="Resource name k8s-ag-ingress-ktn-cm-acme-http-solver-j7sxh-8089-bp-8089-cm-acme-http-solver-t8rnf is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'." Details=[]]
ERROR: logging before flag.Parse: I0417 00:04:41.617341       1 controller.go:106] ~~~~~~~~ ↑ ApplicationGateway deployment ↑ ~~~~~~~~
```

Is it possible to trim the value to ensure the 80 characters limit ?

**Comment by draychev** [comment]
Ingress Controller works well with Let's Encrypt - this is [documented here](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/9e07d57746f29f1d69d9c0f0e28e5d2eca7170a7/docs/how-tos/lets-encrypt.md#certificate-issuance-with-letsencryptorg)
