### ISSUE TITLE
getting 413 Request Entity Too Large

### ISSUE THREAD

**Issue by niteenkole** [Azure/application-gateway-kubernetes-ingress#968]
**Describe the bug**
We hosted artifactory on AKS and using AGIC.

**To Reproduce**
when we try to push image we getting.
docker push artifactory.xxxxxxx.ca/docker-local/alpine:latest
The push refers to repository [artifactory.xxxxxxx.ca/docker-local/alpine]
50644c29ef5a: Pushing
50644c29ef5a: Pushing [==================================================>]  5.845MB
error parsing HTTP 413 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body>\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>Microsoft-Azure-Application-Gateway/v2</center>\r\n</body>\r\n</html>\r\n"

 
Anything we need to do on AGW?

**Comment by akshaysngupta** [comment]
@niteenkole Please create support ticket on Application Gateway.

**Comment by akshaysngupta** [comment]
Closing this issue on AGIC.
