### ISSUE TITLE
Any plan when the project will be GA?

### ISSUE THREAD

**Issue by swoop-alex** [Azure/application-gateway-kubernetes-ingress#97]
I searched and did not find any roadmap or plan when this project will be GA. The last release was in Oct 2018.

Could any of the maintainers share any info on this?

Thank you!

**Comment by wesselkranenborg** [comment]
We are also interested in this.

**Comment by asridharan** [comment]
@swoop-alex  @wesselkranenborg  sorry for the delay in responding to this question. We are still looking at resource allocation to get a better estimate of the time line to GA the ingress controller. A guess would Q2 (April-June) or (June-Sep) time frame. 

We want to have better integration with aks to make the installation and debugging a bit more seamless and also be able to expose all AG features on the ingress resource before we go GA.

**Comment by TallOrderDev** [comment]
@asridharan Thanks for your response. 

Do the devs still feel this is an accurate timeline. We are doing our prod release here in the next month or so, and are curious if we should abandon hope for MVP, or if waiting a couple days/weeks will allow for this.

We are all very excited and appreciative of all the hard work that's been put in and by no means want to rush anyone! Thank you all!

**Comment by asridharan** [comment]
@TallOrderDev we are on-track for going GA in the Aug-Sep time frame. Our main aim is to get better test coverage and support for our code as well as ensuring feature coverage for all the major features exposed by AG. 

Meanwhile, as we churn releases out on our way to a 1.0 GA release, please help us improve the project by creating Github issues for any bugs/gaps that you see as a user. Please be assured that we are very much invested in making this project a success, and the developers would be responding to Github issues with the utmost urgency.

**Comment by SychevIgor** [comment]
Really interesting question. 
Looks like before the GA we should consider ModSecurity as an option?

**Comment by Benjiiim** [comment]
@asridharan, would you mind to give an update regarding the time frame for GA? Thanks a lot.

**Comment by Benjiiim** [comment]
GA today ! :-)
http://aka.ms/appgwaks
