### ISSUE TITLE
Upgrade from 1.2.0-rc3

### ISSUE THREAD

**Issue by rlevchenko** [Azure/application-gateway-kubernetes-ingress#970]
1.2.0 is a new stable version which, according to the release notes, includes all new features/fixes introduced by the release candidates. In our environment we're using the 1.2.0-rc3 version. Is it worth doing an upgrade to 1.2.0 given the fact there haven't any major updates released since the 1.2.0-rc3 (correct me If I'm wrong)?

Plus, I've noticed that the upgrade page hasn't been updated since 2019. Do we need always the same upgrade steps regardless the aad-pod version (there are some breaking changes starting from 1.6.0)? Preferred order? (ingress -> aad-pod I guess)

**Comment by rlevchenko** [comment]
Anyone?

**Comment by 3quanfeng** [comment]
Hi @rlevchenko , I would recommend to upgrade to 1.2.0 even if it's equivalent to rc3. 
```
helm repo update
helm upgrade \
  <release-name> \
  application-gateway-kubernetes-ingress/ingress-azure
```
AKS recommends to use AAD Pod Identity with version >= 1.6.0, to support the recommended version, you will need to upgrade your AGIC to at least 1.2.0-rc2 or the release 1.2.0.

We have doc updated in a PR, should available soon.

**Comment by rlevchenko** [comment]
@3quanfeng thanks. In short, 1.2.0 rc3 and 1.2.0 are indistinguishable.  In that case, I don't see any reasons to upgrade) 

`We have doc updated in a PR, should be available soon.`

Thanks!
