### ISSUE TITLE
Breaking Changes when used with Azure Active Directory (Azure AD) pod identity >=v1.6.0 

### ISSUE THREAD

**Issue by Brandon-FS** [Azure/application-gateway-kubernetes-ingress#976]
When using version 1.6 or higher of the Azure AD POD Identity breaking changes were introduced whereby the following case sensitive fields were changed

![image](https://user-images.githubusercontent.com/69585924/90015553-ac311f80-dca0-11ea-8c49-2ca65a34da2f.png)

https://github.com/Azure/aad-pod-identity/blob/master/README.md#v160-breaking-change

This causes the resourceID and other values to not be passed through.

**To Reproduce**
Install Version 1.6.0 of the Azure AD Pod Identity
With application-gateway-kubernetes-ingress then review the nmi pods to see the error

mic.go:899] Ignoring azure identity default/loping-crab-azid-ingress-azure, error: Invalid resource id: "", must match /subscriptions/<subid>/resourcegroups/<resourcegroup>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<name>

**Comment by 3quanfeng** [comment]
Hi @Brandon-FS , we have addressed the issue in [1.2.0-rc2](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/CHANGELOG/CHANGELOG-1.2.md#v120-rc2)
You will need to upgrade your AGIC to release 1.2.0 to use AAD Pod Identity >= 1.6.0
