### ISSUE TITLE
Ingress.yaml Helm chart no longer creates MultiSite HTTPS listener

### ISSUE THREAD

**Issue by AKSNewbie** [Azure/application-gateway-kubernetes-ingress#996]
Hi All,
I have noticed that since deploying either AGIC 1.2.0 rc2 or rc3 my previously functioning ingress chart no longer creates a multisite listener, yet if i use rc1 it does.

Here is my ingress.yaml (which has always worked)

![image](https://user-images.githubusercontent.com/70979792/92603569-5c497680-f2a7-11ea-9053-8cacbd98d745.png)

The working environment i have is the following:

K8s - 1.15.11
Helm 2.14.1 (i know, i will upgrade)
AGIC 1.2.0-rc1

If i move versions of kubernetes then i am forced to upgrade AGIC which is when everything stops working. I am surprised i have not found anything else about this, so i assume i am doing something wrong.
Thanks
John

**Comment by thisispaulsmith** [comment]
Did you make any progress on this?
I'm having a potential issue with wildcard certs and noticed the lack of hostname/hostnames.

I think you're going to have to update k8 as you're out/almost out of support.

**Comment by vishal8k** [comment]
@AKSNewbie  Can you provide the ingress yaml you used here for better insight because there is an existing known issue where you won't able to see the host names of the multi-site listeners via portal but however there won't be any problems in request serving. Need to know more details on how you concluded that multi-site listeners are not being created. The bug I stated above is only for portal and you will still be able to see listeners with hostnames via AZ cli or Powershell.

**Comment by AKSNewbie** [comment]
I have decided to do a full upgrade of all aforementioned versions and from what i can see all is good. The issue was odd though and i am aware of the bug but my ingress was creating basic listeners instead of multi site. Anyway...closing. Thanks anyway

**Comment by AKSNewbie** [comment]
Closing issue

**Comment by AKSNewbie** [comment]
@vishal8k @thisispaulsmith - Unfortunately i need to reopen this, the issue still seems to be there after my upgrade to Helm3

So, versions now are:
Helm 3.3
AGIC 1.2.0-rc3
K8s 1.16.13
The ingress.yaml is still as above, and i repeat that this works perfectly on the aforementioned version of each component.
I have a wildcard cert installed on my gateway *.mydomain.com so my ingress creates a listener https://clientname.mydomain.com but on the newer version it does not create the listener as multisite, so as soon as i try to create a second listener for say https://client2.mydomain.com i get failures as cannot have 2 basic listeners on same port 443.
Example:
![image](https://user-images.githubusercontent.com/70979792/94779023-2129f700-03be-11eb-90a5-40078742b480.png)
And here from a working gateway/agic(old versions)
![image](https://user-images.githubusercontent.com/70979792/94779175-6bab7380-03be-11eb-8da8-e1eaa16735ee.png)

I understand that from the portal you can no longer see the hostnames field etc, but that is not what i am saying. This is about the type of listener that is being created. So, do we have to somewhere now specifiy in the ingress.yaml the type of listener we want to create, some annotation or something? I cannot find this anywhere.

**Comment by akshaysngupta** [comment]
@AKSNewbie You are seeing basic listener as Portal evaluates whether a listener is basic or multi-site by using the "hostname" property which is not used by AGIC in the latest version.

Another way to check your appgw config by running AGIC with `verbosityLevel: 5`. That will print the AppGW config in the AGIC pod logs.

```bash
helm upgrade \
    <helm-release-name> \
    application-gateway-kubernetes-ingress/ingress-azure \
    --reuse-values \
    --verbosityLevel=5
```

**Comment by AKSNewbie** [comment]
@akshaysngupta Hey, thanks for your reply. I mean, i don't even need to do that, just through CLI i can query the listener and yes i can see the hostname is configured:
![image](https://user-images.githubusercontent.com/70979792/94912824-2495af00-04a0-11eb-8e8d-542c3eebee1c.png)

But that doesn't take away from the fact that if i go to the portal and look at my listeners i see them all as basic and if i click on one of them i get an error that they are all on the same port:
![image](https://user-images.githubusercontent.com/70979792/94912981-5b6bc500-04a0-11eb-9c96-688ae3b413a9.png)

Oh, and....yes, the listeners do actually work. My applications sitting behind said listeners are accessible, but just from a troubleshooting perspective if someone was to come along and look at those listeners they would instantly assume "oh, there is the problem".

So, is this accepted behaviour now? Doesn't seem right to me.
Thanks again.

**Comment by vishal8k** [comment]
@AKSNewbie Yes. That is also a part of the bug that I have mentioned above. As a temporary fix, you can run the below powershell script to see the listeners in the portal user friendly. 
```
$rgName="myrgname"
$appgwName="myappgwname"
$gw=Get-AzApplicationGateway -Name $appgwName -ResourceGroupName $rgName
Foreach ($listeners IN $gw.HttpListeners)
 {
 if($listeners.HostNames.length -gt 0)
 {
   $listeners.HostName=$listeners.HostNames[0]
   $listeners.HostNames=$null
   }
 }
Set-AzApplicationGateway -ApplicationGateway $gw
```
**NOTE:** This is just a temporary fix. After running this script, if you add/edit ingress rules then they will again be back to buggy-names.

**Comment by AKSNewbie** [comment]
@vishal8k @akshaysngupta 
Thanks very much to you both, i guess the positive here is that it works and also its not me doing something wrong. Maybe a chat with Microsoft might help.

**Comment by aelmanaa** [comment]
@akshaysngupta  is it planned to solve the "small bug" in the portal?

**Comment by Guru-Sky** [comment]
Can someone help me ?
I'm trying to create the listener like this:

az network application-gateway http-listener update -g RG_NAME --gateway APPGW_NAME -n ListenerDefault --host-names test2.example.com test1.example.com


And I get the error below.


ListenerDefault must specify a non-empty value for either HostName and HostNames, but not both

**Comment by Vishal2696** [comment]
@Guru-Sky your issue seems related to AZ CLI and nothing related to AGIC. Guess you would get better help by raising this issue on the az cli github page.

**Comment by Guru-Sky** [comment]
Hello Vishal, yes the problem is the same via CLI tbm the multiple sites doesn't works.
I can't create multiple sites by dashboard or by CLI :/

Tks

**Comment by aelmanaa** [comment]
> @AKSNewbie There is an existing known issue where you won't able to see the host names of the multi-site listeners via portal but however there won't be any problems in request serving. Need to know more details on how you concluded that multi-site listeners are not being created. The bug I stated above is only for portal and you will still be able to see listeners with hostnames via AZ cli or Powershell.

Hello @Vishal2696,

you say that there is "an existing known issue".  Do you know if a bug has been reported and if a fix is ongoing?

**Comment by LoicAG** [comment]
Related issue: https://github.com/Azure/application-gateway-kubernetes-ingress/issues/1151
